### ISSUE TITLE
Remove crafting of mese crystals into mese block

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1171]
(and possibly remove crafting of obsidian shards into obsidian too).

The purpose is to make mese block meaningful instead of being able to craft it from the very easy to access mese crystals at y = -64. So if a recipe requires a mese block you would need to mine to y = -1000 which is not an unreasonable depth. For example the batteries of my 'mesecars' require a mese block and owning such a vehicle should come at a higher price than mining to y = -64, which can be done simply by walking down a tunnel.

To consider this i'm asking to see how common mese block is in recipes to see if this is a problem.

Although we are not too concerned with strict reality, mese is apparently a crystal so not allowing reverse crafting makes sense.

**Comment by DonBatman** [comment]
I like the idea. I am not sure if I have recipes that use mese blocks but will change them if needed.

**Comment by C1ffisme** [comment]
Finding Mese is already hard enough for some people who don't want to spend the entirety of the game mining in a rather boring and lifeless underground.

> For example the batteries of my 'mesecars' require a mese block and owning such a vehicle should come at a higher price than mining to y = -64

Shouldn't you just adjust your mod to be balanced correctly? You could make the batteries require uranium or some other metal that is generated far below the ground...

> ...which can be done simply by walking down a tunnel.

Maybe in V7, but if you were still playing in V6, it probably wouldn't be this easy.

Besides that, the Mese Block is **very** useful in mesecon circuitry when you don't want to use finicky vertical mesecons.

**Comment by paramat** [comment]
Hm, -1024 may be too deep, we could perhaps raise mese block to -512 or even higher.
Depends how many recipies use it and how difficult to mine it is intended to be.

**Comment by paramat** [comment]
The underground isn't boring, that's your problem, there are always mods to add features.
When i first mined to y = -1000 it was a real adventure and gave a sense of achievement.

Many mods, as well as my own, will want to have a recipe depending on something rare that is included as default, there is nyancat but the problem is the distribution means it can be unfindable for months, and then you only get a few rainbows.

We need a default material that is a challenge to reach but is quickly findable in reasonable amounts once you get there, currently we don't have anything like this, it might as well be mese block in it's current location. It is also ideal since it is the 'mysterious, magickal material' that has a very wide variety of uses.

I expect most recipes needing mese will be requiring mese crystal, so hopefully there will not be too much disruption. I feel it's worth it even if a few mods have to change their recipies.

**Comment by yyt16384** [comment]
If you remove reverse recipes for mese, it makes sense to do it for diamond as well.

**Comment by paramat** [comment]
I forgot about diamond block, i consider that different as crafting diamonds into diamnd block is necessary to acquire the block, and th eblock doesn't occur naturally.

**Comment by sofar** [comment]
I'm in support of this, it adds some badly needed progression for certain harder to get items.

**Comment by tenplus1** [comment]
I like having recipes to turn shards into full blocks again for storage.  Maybe the addition of a compressor type machine mod to fill the gap if recipe's are removed.

**Comment by everamzah** [comment]
Since Mese is special, and you can mine it in block form, I think it makes sense to treat it differently.  However, as tenplus1 mentioned, it'd be a real pain to collect the stuff if we can't compress it.

And it's not shards into full blocks, either, @tenplus1.  It's Mese Crystal into full blocks, or Mese Crystal Fragments into Whole Crystals.

**Comment by Thomas--S** [comment]
I prefer the current behaviour. Many players don't like mining, so I think the harder version shouldn't be the default. I think that merging minetest/minetest#4034 would be more helpful, so that mods can delete the recipes.

**Comment by Fixer-007** [comment]
MESE block is very rare right now. If you want to remove reverse crafting of it, you should increase its probability of finding somewhat.

**Comment by paramat** [comment]
> MESE block is very rare right now. If you want to remove reverse crafting of it, you should increase its probability of finding somewhat.

The idea here is to have something rare.

>  Just Test and ESM server use MESE block as central piece in recipe for protector. Some other mods like basic_machines, technic, mesecons, bitchange, travelnet, pipeworks, moreblocks, hook, firearms, minetest-money, moremesecons, teleport potion

Yeah this is the dilemma, is it worth the disruption? These recipies should perhaps be using mese crystal instead though if they want an ingredient that's not too difficult to find, requiring a mese block is, in a way, asking for travel to -1024.

**Comment by Rogier-5** [comment]
>> Just Test and ESM server use MESE block as central piece in recipe for protector. Some other mods like basic_machines, technic, mesecons, bitchange, travelnet, pipeworks, moreblocks, hook, firearms, minetest-money, moremesecons, teleport potion

> Yeah this is the dilemma, is it worth the disruption? These recipes should perhaps be using mese crystal instead though if they want an ingredient that's not too difficult to find, requiring a mese block is, in a way, asking for travel to -1024.

The question is not what they *should* do, but what they *do*. If this change went through, then all those mods would have to be patched ('re-balanced') as well. And I'm sure not all mod developers are still very active... The way I see it, this breaks backward compatibility, as it breaks the balance that many mod writers have put into their recipes.

I do agree with @sofar though, that some progression is a good idea. However, that is also a very personal preference. Some people prefer progression in fighting mobs, where others prefer progression in mining, and others prefer to build (but without enabling creative mode). Or people like a combination.

So if you do this, then please make it subject to a configuration setting, which is off by default (for compatibility reasons). And then of course, do make mese blocks more abundant at greater depths, e.g. at 2048 and more 4096.

> We need a default material that is a challenge to reach but is quickly findable in reasonable amounts once you get there

IMO, a different underground ore distribution would also help. With the current uniform distribution, there really is no challenge in finding ores. If instead ores were relatively abundant in some underground areas, but scarcer elsewhere, then there'd be the challenge of finding such an area. One found, the amount of ores present should be larger (i.e. more concentrated), so that there is a reward for finding them, and so that they don't require an excessive amount of stone to be dug away to obtain them.

For people who hate digging, above a certain depth, it should not be harder than it is now to find all types of ores. People who are fine with digging should reap the benefits if they are prepared to dig deeper. At great depths (I'd say 10000 at least!), they could be rewarded with occasional highly-concentrated pockets of ores.

For added challenge, the underground ore areas could become more concentrated (and maybe a bit larger as well) with depth, but farther between. Even if the average concentration of ore does not change, that still makes them harder to find...

**Comment by paramat** [comment]
Nah i'd rather not do this than add another setting.
Mods always need maintenance so that can't stop really good ideas.
However this idea is disruptive and quite likely to not go ahead, for now this issue can sit and gain opinions.

**Comment by Rogier-5** [comment]
> Mods always need maintenance so that can't stop really good ideas.

If good ideas cause mods to be lost because they break, or become unplayable, then minetest loses. Not everybody is as active as they used to be, or they sometimes simply lose interest in an mod in favor of other minetest activities.

So, please *do* implement good ideas, as many as possible, but as an addition, so that existing mods keep functioning as much as possible. Removing old interfaces or old behavior is a significant maintenance burden for mod writers, server operators, etc. Please do so only if really necessary. and after a significant deprecation time.

> Nah i'd rather not do this than add another setting

You're right. Too many settings *are* bad.

Anyway, I suspect that people would soon create a mese crystals <--> mese block crafting mod anyway.

Can't there be a new type of ore or crystal, or other material, that can only be found below -1024 ? Active mod writers will start using it, and balance their recipes accordingly. Maintenance-mode mods will keep working as they did.

**Comment by C1ffisme** [comment]
> The underground isn't boring, that's your problem, there are always mods to add features.
When i first mined to y = -1000 it was a real adventure and gave a sense of achievement.

To you, maybe. You find it interesting to explore a mapgen you've created and perfected for a long time, but not all of us find a grey cave interesting. I far prefer building in Minetest or Minecraft, since in both games the underground is still just lifeless stone.

Two screenshots of underground, one at -100, and one at -1000:

![screenshot_20160703_094428](https://cloud.githubusercontent.com/assets/9893266/16546042/1918c8a2-4103-11e6-8e7e-d1ef4e42870e.png)
![screenshot_20160703_094540](https://cloud.githubusercontent.com/assets/9893266/16546043/1def22cc-4103-11e6-8583-d08125aee687.png)

The only real difference is in lava, and in the concentration and types of ores that spawn here. Other than that, it's all the same. Past -1024, the world will always be the exact same.

Adding more ores won't help. Adding more variation will.

For some reason in Minecraft, though, mining is at least slightly more interesting. Notice the different types of stone and the smooth lava lake.
![2015-12-28_13 35 01](https://cloud.githubusercontent.com/assets/9893266/16546057/f87e21ae-4103-11e6-83b4-e65f17e80930.png)
While those stone types (Granite, Diorite and Andesite) are notorious for clogging up inventory space, they make the underground world look a lot less monotonous.

(Sorry for getting a bit offtopic, the point is, underground in Minetest isn't very exciting.)

**Comment by Rogier-5** [comment]
> The only real difference is in lava, and in the concentration and types of ores that spawn here. Other than that, it's all the same. Past -1024, the world will always be the exact same.
>
>Adding more ores won't help. Adding more variation will.

The default game is indeed rather uniform and monotonous underground. Iwould also welcome some more variation. However, let's be fair: there also exist sufficient mods that make the underground much more varied, if not more exciting. Vanessae's dreambuilder subgame contains a good selection that I know of. It doesn't *have* to be as dull and grey as in your screenshots...

**Comment by C1ffisme** [comment]
@Rogier-5 Could you link me to some examples, just for reference?

I still wish, though, that MTG didn't require mods to be fun. Minecraft comes in one package, but to have any real fun with Minetest you have to pick and choose which features you like best, or code your own mods.

**Comment by Rogier-5** [comment]
@C1ffisme The forum thread is [here](https://forum.minetest.net/viewtopic.php?f=15&t=9196), it has a screenshot of a [caverealms](https://forum.minetest.net/viewtopic.php?f=11&t=9522) cave, but the caverealms page has better screenshots. Dreambuilder also has lots of different ore mods. You could go and see for yourself on one of Vanessae's servers. Links to the servers' forum threads are in the dreambuilder thread. The dreambuilder thread also contains a list of mods that are included.

> I still wish, though, that MTG didn't require mods to be fun. Minecraft comes in one package, but to have any real fun with Minetest you have to pick and choose which features you like best, or code your own mods.

OTOH, the simpler the default game stays, the more diverse the mod ecosystem will be, the more the creativity of mod writers will be stimulated, and the bigger the chance that among the many mods, a player will find those that suit his taste.

For those that don't like assembling a collection of mods, and prefer ready-made selections, the [subgame releases forum thread](https://forum.minetest.net/viewforum.php?f=15) shows the work of other people who did like to select and tune their own mod combinations, and shared their work.

**Comment by DonBatman** [comment]
If mtg has lots of mods then modding would become harder. There would be many more items that would have to be overriden. Better to keep the game simple and let players/servers set the game up the way they like it. Imho

**Comment by everamzah** [comment]
I think Minimal should be a base for other sub-games, and Minetest Game should be as full featured as possible.

**Comment by paramat** [comment]
Minimal is hopelessly out of date and is just a dev tool.
MTGame is intended to be the base for modding but we have been adding lots of new features recently, as long as th enew features are of a fairly basic simple nature.
For something more exciting new subgames have been requested by celeron55 but he has not been impressed enough to add one, so it's down to you.

**Comment by Rogier-5** [comment]
> I think Minimal should be a base for other sub-games, and Minetest Game should be as full featured as possible.

Your phone also doesn't come fully featured, with all possible apps installed. Instead, you choose your pick based on your needs. You may very well want some apps *not* installed (they consume memory, bandwidth, screen real-estate, processing power, ...), or you may prefer a different app for a specific task than your brother, or sister, wife, kids, etc. With a *fully featured* phone, that woudn't be an option...

The minetest engine is more like a phone than a game. And the minetest game is the basic set of apps that (almost) everybody needs. From that basis, everyabody can, and should, add their own pick of apps/mods to suit their personal taste.

**Comment by everamzah** [comment]
Minetest Game comes with no protection.  minetest.is_protected() exists, and the stock Minetest game doesn't even use it.

**Comment by Rogier-5** [comment]
> Minetest Game comes with no protection. minetest.is_protected() exists, and the stock Minetest game doesn't even use it.

I don't understand the relevance of this comment in this context.

This discussion is going off-topic anyway. If you think minetest_game has a bug, then please submit it. Or fix it yourself and submit a pull request if you prefer, or you want to increase the chance that it gets fixed.

**Comment by everamzah** [comment]
It was in response to your smart phone analogy.  It'd be like buying a smart phone and having to download an App to access a screen locker.  I assume that's a standard feature.

As for the issue, Mese Crystal Fragments used to craft back into Mese Crystals, then that was removed, then it was added again, and now we're talking about whether to remove it again, and possibly remove Obsidian Shards into Obsidian?  I think we should leave it alone and move on.

Mese and Obsidian are specially generated and both have shard/fragment reverse crafts.  I think that's reasonable.

**Comment by C1ffisme** [comment]
@everamzah Minimal is more of a place where devs can experiment with engine code, and not have to load the entire MTG to test something.

I don't want Minetest Game to become any less of a place to add on mods, I just want it to be fun on it's own. A game suggests fun, otherwise we should have renamed it to Minetest Foundation or Minetest Engine a while back.

Sure, a phone doesn't come with all the apps it needs to be used for anything big, but at least it has the apps it needs to run. (The Operating System, etc.) **And** it also includes apps for some of the most basic functions. (A Web Browser, for example.)

But, this discussion is getting far offtopic.

**Comment by paramat** [comment]
TIme to close this i feel.

**Comment by paramat** [comment]
Re-opening. Although this will cause some updating to be done i feel it's possibly worth it.
Mese block is something found at y = -1024, so a mod using this in a recipe but as something crafted from mese crystals is strange, just use mese crystal in the recipe instead.

Waiting for input from other mtgame devs @Ekdohibs @sfan5 @PilzAdam @ShadowNinja

**Comment by C1ffisme** [comment]
@paramat If we do remove the recipe, there needs to be some way to turn mese crystals back into a mese block through some other means, such as a high-temperature crucible.

Also, people are going to lose the ability to store mese crystals as blocks. 4 stacks of mese crystals is a lot easier to carry as 1 stack of mese crystals and 1 stack of blocks.

**Comment by everamzah** [comment]
Maybe just remove the recipe.

**Comment by paramat** [comment]
> If we do remove the recipe, there needs to be some way to turn mese crystals back into a mese block

That would defeat the purpose of doing this.

Anyway, closing again, PR is closed too.

**Comment by C1ffisme** [comment]
That would defeat the purpose of doing this.

I was thinking that the machine used to make mese blocks from mese crystals would require at least one mese block as a schematic or power source or something.
