### ISSUE TITLE
Furnaces keeps burning fuel if src and dst inventories are full

### ISSUE THREAD

**Issue by volkj** [minetest/minetest_game#1221]
When the destination inventory of a furnace is full and there are fuel and a smeltable node in the src inventory the furnace keeps burning fuel without increasing dst inventory or decreasing src inventory.

The on-screen label over the furnace (the one you get pointing the pointer over a furnace node) has a "Furnace active: Item %" percent that grows well over 100%.  

Minetest 0.4.14 vanilla

**Comment by sofar** [comment]
It may be a bug, but you left the stove on. The fuel isn't accidentally destroyed: there's stuff to cook.

Maybe fix the tooltip number but leave the fuel consumption part?

**Comment by volkj** [comment]
With a full dst inventory and at least one node in src inventory the fuel keeps being consumed without consuming the src inventory's node.

If a player doesn't check the destination inventory then the furnace could waste all the fuel.

**Comment by sofar** [comment]
I think it's perfectly reasonable to punish a player for mistakes. Players should check their furnaces can hold all the items they want to cook when they put something in.

I strongly suggest leaving this code as-is.

**Comment by volkj** [comment]
As an example, homedecor's furnace code [manages the dst full inventories](https://github.com/minetest-mods/homedecor_modpack/blob/master/homedecor/handlers/furnaces.lua#L265)

First line of that file says `
-- This code supplies an oven/stove. Basically it's just a copy of the default furnace with different textures.`, the way it manages the full dst inventories could work even on normal furnaces.

**Comment by everamzah** [comment]
If the furnace is full, and there's cookable items that remain as fuel, then pop the cookable items out onto the floor around air.

**Comment by sofar** [comment]
I'm not debating that the code can't be changed. 

I'm stating that I don't *want* it changed.

The only time that a furnace by itself overflows (sans pipeworks et al) is because a player *forgot* to empty `dst`. This isn't some bad coincedence or misleading stuff. You left the stove on, the stove does what you told it to.

So, logically, an overflowing furnace is a *player caused problem*, and I don't see anything wrong with *punishing* the player for making a mistake.

And no, popping items out seems like an even worse solution (creating possibly hundreds of entities that are just going to get deleted by the engine anyway).

So, I first think this isn't a bug to begin with. It's "a game mechanic you happen to dislike". But the game has hundreds of mechanisms you don't like, like falling damage, or having to punch trees to get wood.

Celeron55 has stated long before that he wants (like many of us) to make minetest_game more challenging. We should have more of these mechanisms (e.g. proper tool wear) and not less.

**Comment by everamzah** [comment]
Items are disappearing into a void, and a full furnace should smolder and stop burning, I'm thinking.

**Comment by volkj** [comment]
This is clearly a bug, not a game mechanic as i see a furnace with a 8000% item label.

@everamzah worse is that `src` items aren't even cooked but it's just fuel that is being burned.
A behavior compatible with the `game mechanics` would be burning all the `src` items when furnace is full, then making furnace stop when `src` inventory becomes empty.

**Comment by sofar** [comment]
We can fix the label being incorrect, that is a bug for sure.

I think your proposal to burn all the `src` items goes a little over the top, that would really, really suck if it was a stack of gold lumps. Burning the fuel off is punishment enough, I think. We don't want to that cruel to players who make a mistake (a stack of coal takes maybe 10-20 minutes of mining, a stack of gold lump could well take 2 hours of mining, if not more).

**Comment by sofar** [comment]
#1269 - indicate when `dst` is full.

**Comment by Fixer-007** [comment]
dst?

**Comment by Ferk** [comment]
This could even be considered a feature.

This way you can keep a fireplace at your home where you only need to refill the fuel when you want to turn on the fire for a while, without having to add items to src every time.

**Comment by paramat** [comment]
#1269 is merged.

**Comment by paramat** [comment]
> When the destination inventory of a furnace is full and there are fuel and a smeltable node in the src inventory the furnace keeps burning fuel without increasing dst inventory or decreasing src inventory.

I agree with sofar that fuel should burn if the furnace is misused.
The % readout is fixed.
