### ISSUE TITLE
Sinking in water goes really slow

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1228]
If you jump in water and let yourself fall down you go really slow terribly slow in fact, I think this should go a little bit faster, maybe a new swimming system would be nice as well just hold the forward button and look in the direction you want to go ( you should move in that direction)

**Comment by paramat** [comment]
There was a lot of discussion over this, sinking was made faster for a while but many didn't like the 'tied to a astone' feeling and we reverted to the original. Note people are naturally almost buoyant in water so a slow sink is sutable. It also avoids the need to press 'up', we have the 'descend' key for swimming downwards.
See discussion #293 #399

**Comment by everamzah** [comment]
There's also [movement_liquid_sink](https://github.com/minetest/minetest/blob/master/minetest.conf.example#L962), and I believe _climb and _descend also affect player speed in water.

**Comment by paramat** [comment]
So, we are using the original value used for years, few players are complaining about it.
@rubenwardy any opinion?

**Comment by tobyplowy** [comment]
@paramat sorry I'm just trying to help, i report everything that doesn't seem right and needs to improve. ( I think I just need to keep moving to other projects,

sorry that I have to say this but becuse the way minetest is developt now doesn't seem like it's going anywhere it's quite sad because minetest seemd to have a bright future but you dont Focus on Actual gameplay the thing people want in a game and I know you guys call it an engine but it's a game

I downt think i'm coming back anytime soon sorry that I was such a disturbance :/

**Comment by rubenwardy** [comment]
I think it's fine as it is now, and whilst it would be nice to have emersion based floating, it's not necessarily and should be low priority

**Comment by C1ffisme** [comment]
@paramat I'm trying not to do it as badly. Although you can't expect that at the rate we are going, someone is going to get impatient.

As you say, we _are_ understaffed and you all work on _your free time_.

Back on topic, I feel as though going through water could at least be slightly faster, because right now it feels more like floating through sludge. And if someone asks for sinking in water to be faster again, we can just say "Well, it's not as bad as it was before".

**Comment by paramat** [comment]
The forum is the place for casual chatter and discussion of initial ideas, i hope you're both members, if not sign up, it's cool you like to discuss dev so much but you need to do most of this on the forum. This way you'll then develop something worth bringing to gihub discussion.

Here any comments have to be focussed and well thought through. Any comments here notify devs and means we have to spend time reading and considering what you say, i'm spending too much time reading excessive and unnecessary comments from you two. Often your comments are about things explained earlier in the thread. Kilbith felt this way too which is why he correctly complained about your 'useless noise'. I don't want to start ignoring both of you so please think more, code more, comment less.

**Comment by everamzah** [comment]
#minetest on freenode irc is good for casual chatter, also.

**Comment by C1ffisme** [comment]
@paramat It might be a good idea putting something about this in ```CONTRIBUTING.md```, along with other good rules to stop developers from verbally abusing each other, flamewars, excessive profanity, etc.

**Comment by paramat** [comment]
@sofar any opinion on sink speed?

**Comment by sofar** [comment]
It would be a whole lot better if the sink speed would apply only when you're almost fully submerged, not when your toes are touching the water only. I'm not sure a speed adjustment is needed, I think the speed transition can be better, though.

e.g. the speed isn't instantly lowered to the max water speed, but is lowered bit by bit every server step until it is below the water speed.

**Comment by tobyplowy** [comment]
@sofar that actually Sounds like a good system

**Comment by paramat** [comment]
Or, continue to have just 2 speeds but switch when half-submerged, simple. I feel it's too minor an issue to use a complex simulation.

**Comment by everamzah** [comment]
I think it's actually slower in Quake, that you descend in water while not moving.  I could be wrong.

**Comment by Megaf** [comment]
We could just increase sink speed and decrease acceleration accordingly to give the same initial feeling. Best of both worlds.
But, IMHO, it is fine the way it is right now, everybody is used the the current speeds. Changing that would affect the gameplay, possibly negatively.

**Comment by tobyplowy** [comment]
Seriously sinking in water goes too slow it feels like you're stuck in tar

Also there's not much "gameplay" in minetest unless you install a ton of mods

**Comment by NathanSalapat** [comment]
rant
@tobyplowy I'm a nobody, as in not a Minetest core dev, so take this with a grain of salt, and don't let it represent any official minetest feelings. That said, if you want to discuss things please use the forums, github is for discussing actual bugs, things that are creating errors when playing, or to review code. If you are seeing so many problems, why don't you start coding solutions, rather than just complaining about things.
rant over.

**Comment by everamzah** [comment]
>everamzah commented on Jul 31
There's also movement_liquid_sink, and I believe _climb and _descend also affect player speed in water.

I agree that this can be closed.

**Comment by paramat** [comment]
Ok, since this issue is about sink speed, and that is configurable and accepted by most players, and was changed to be faster a while ago and was lateer changed back to slow with much support, closing.

**Comment by paramat** [comment]
This is a valid thing to open an issue for though Nathan :]
