### ISSUE TITLE
Better plant hit boxes

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1256]
The jungle grass hit box is ridiculously small I suggest that the hit box is like 2 blocks on top of each other similar to a door but just a full block

**Comment by paramat** [comment]
Plant hitboxes are smaller than nodes because it's often useful to aim past them, but i'll check this.

**Comment by paramat** [comment]
It's the same as any other grass, seems ok to me.

**Comment by paramat** [comment]
It has the same box as grasses and dry shrubs, which is a low box shaped for grass1, we could perhaps have a taller thinner box, like flowers, that better represents the primary mass of the grass.

**Comment by paramat** [comment]
Adjusting these boxes is very easy, do you not want to suggest new dimensions? I understand you may not be able to submit the PR.

**Comment by tobyplowy** [comment]
@paramat yes ( but who will make the PR?)

**Comment by tobyplowy** [comment]
@paramat can you make the pr?

**Comment by paramat** [comment]
Don't worrry about who will make it, if it's good work someone will, possibly me.

**Comment by paramat** [comment]
Anyway i support this being done, something consistent with flower selection boxes.

**Comment by tobyplowy** [comment]
@paramat Can this be fixd?

**Comment by sofar** [comment]
something almost 1x1x1 would be fine, 1 high and maybe 14px x 14px at the base?

**Comment by tobyplowy** [comment]
@sofar @paramat I think the hitbox should be one full block wide one full block thik and two full blocks tall

**Comment by paramat** [comment]
It should be roughly consistent with other plants. For a nice fraction i would say 8 pixels wide and around 1 node tall. For plants it's nice to be able to point at the node below.
2 nodes tall is taller than the grass itself, not acceptable.

**Comment by paramat** [comment]
![screenshot_20161101_171440](https://cloud.githubusercontent.com/assets/3686677/19899137/d56a90c8-a056-11e6-833e-3bb1a180a0d9.png)

This is {-0.4, -0.5, -0.4, 0.4, 1.18, 0.4}
For most of our plants the box snugly fits around the dimensions of the plant, but here i made it thinner than 1 node although the grass is wider.

![screenshot_20161101_170959](https://cloud.githubusercontent.com/assets/3686677/19899202/185da5c8-a057-11e6-9a45-c3819592da43.png)

Noticed that dry shrub is also bad, will attend to both.

**Comment by paramat** [comment]
![screenshot_20161101_172147](https://cloud.githubusercontent.com/assets/3686677/19899355/ba51f1cc-a057-11e6-945f-9a5a04f30d71.png)

{-0.3, -0.5, -0.3, 0.3, 0.25, 0.3}

**Comment by tobyplowy** [comment]
@paramat de hitbox in the top image Looks really good :D (Every Flower and Grass have that weird Selection box that the dead shrub has)

**Comment by paramat** [comment]
Maybe i'll make a PR to tune selectionboxes for several plants, including some of the flowers which have boxes a node wide. What i'm thinking is, to distinguish the box from the node below always limit it's width to roughly 14 pixels, otherwise fit it to the plant maximum dimensions.

**Comment by tobyplowy** [comment]
@paramat i like the new dead shrub selectionbox

**Comment by sofar** [comment]
14x14 as a default box (x,z) seems good - having a consistent hitbox for plantlike like that will be useful. I would try and keep the junglegrass hitbox 1 high myself, though.

I wouldn't do (-0.4,0.4) but (-7/8,7/8) instead where possible, and align to 16px.

**Comment by paramat** [comment]
Yeah aligned. I tried a 1 node high box but it wasn't very visible within the large junglegrass structure. But maybe that can be the vertical limit for boxes, i'll try it.

**Comment by paramat** [comment]
![screenshot_20161102_184926](https://cloud.githubusercontent.com/assets/3686677/19943778/dd4862ae-a130-11e6-8936-51aa8ee783fd.png)

![screenshot_20161102_184908](https://cloud.githubusercontent.com/assets/3686677/19943781/e090b06a-a130-11e6-8d26-f77d60732484.png)

![screenshot_20161102_184945](https://cloud.githubusercontent.com/assets/3686677/19943794/e5adf80a-a130-11e6-9914-114b0af9f956.png)

![screenshot_20161102_185016](https://cloud.githubusercontent.com/assets/3686677/19943802/eb835310-a130-11e6-83fb-8d8ea9256ed5.png)

![screenshot_20161102_185033](https://cloud.githubusercontent.com/assets/3686677/19943806/ef0a10be-a130-11e6-83db-5f60ef2246f1.png)

![screenshot_20161102_185053](https://cloud.githubusercontent.com/assets/3686677/19943810/f25a12dc-a130-11e6-86ce-1e9701437e5f.png)

![screenshot_20161102_185127](https://cloud.githubusercontent.com/assets/3686677/19943815/f586169a-a130-11e6-844c-3641d9baf297.png)

![screenshot_20161102_185146](https://cloud.githubusercontent.com/assets/3686677/19943819/f8f870f2-a130-11e6-9412-9d19f70ba768.png)

![screenshot_20161102_185222](https://cloud.githubusercontent.com/assets/3686677/19943823/fc9fd614-a130-11e6-834f-4f16b7fa6f1c.png)

![screenshot_20161102_185249](https://cloud.githubusercontent.com/assets/3686677/19943825/ff6cb286-a130-11e6-8547-d76eebbeaef4.png)

Thought i'd redo all flowers too. The approach here is to match the boxes to the pixel grid. The box is fitted to the maximum dimensions of the plant, except horizontally the box is limited to 14 pixels wide, so that a plant in a 1 node wide space has a box that does not disappear into the surrounding nodes.

**Comment by paramat** [comment]
![screenshot_20161102_193659](https://cloud.githubusercontent.com/assets/3686677/19944644/a840b3e6-a134-11e6-86d5-4bd743e7f2a6.png)

![screenshot_20161102_193737](https://cloud.githubusercontent.com/assets/3686677/19944652/ab8234c6-a134-11e6-9d51-57e76042e47a.png)

![screenshot_20161102_193800](https://cloud.githubusercontent.com/assets/3686677/19944653/ae1db228-a134-11e6-9ab7-bbd61aec1cd8.png)

![screenshot_20161102_193901](https://cloud.githubusercontent.com/assets/3686677/19944659/b14c5fe4-a134-11e6-80aa-a5d0ad934348.png)

![screenshot_20161102_194249](https://cloud.githubusercontent.com/assets/3686677/19944667/b547807e-a134-11e6-8053-40ea2d091810.png)

**Comment by tobyplowy** [comment]
@paramat Looks amazing nice work paramat as Always

**Comment by paramat** [comment]
I'll do saplings as well and eventually make a big PR.

**Comment by tobyplowy** [comment]
@paramat Maybe The Grass Selection boxes chuld Be More like the dead Bush Selection Boxes

**Comment by paramat** [comment]
I'll also change these dimensions to fractions for clarity.

**Comment by paramat** [comment]
![screenshot_20161105_034129](https://cloud.githubusercontent.com/assets/3686677/20027355/f6ae1e20-a309-11e6-9248-21ae19b425f1.png)

![screenshot_20161105_034157](https://cloud.githubusercontent.com/assets/3686677/20027356/fac4c39c-a309-11e6-8a93-9f28c43555b4.png)

^ Width limited to 14 pixels

![screenshot_20161105_033610](https://cloud.githubusercontent.com/assets/3686677/20027358/077c206c-a30a-11e6-853f-e18611e78f71.png)

![screenshot_20161105_033704](https://cloud.githubusercontent.com/assets/3686677/20027359/0b4818a4-a30a-11e6-9bef-d09d924b675f.png)

![screenshot_20161105_033718](https://cloud.githubusercontent.com/assets/3686677/20027362/100c62be-a30a-11e6-9295-5b7ea4da0b4e.png)

![screenshot_20161105_033725](https://cloud.githubusercontent.com/assets/3686677/20027363/146ccfce-a30a-11e6-8c31-8b10bc40d259.png)

![screenshot_20161105_033732](https://cloud.githubusercontent.com/assets/3686677/20027364/1783b664-a30a-11e6-9d23-21b4a3f1e892.png)

**Comment by paramat** [comment]
Will make a PR.

**Comment by sofar** [comment]
:+1:

**Comment by paramat** [comment]
#1367 merged.

**Comment by tobyplowy** [comment]
@paramat 👍
