### ISSUE TITLE
Digging stone with picaxe in creative mode is slower than with bare hand

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1267]
I noticed that in creative mode digging stone with the picaxe is slower than digging stone with any other item or bar hand

Digging wood with an axe is also slower with other items. Same with shovel and dirt. But you need a stone shovel to see a difference.

A diamond shovel is much faster than normal creative speed, but a diamond picaxe is not fast

**Comment by asl97** [comment]
Imo, this is a engine problem.
maybe it can check for creative (privs) when it figuring out how long it should be digging.

https://github.com/minetest/minetest/blob/d767f025cb0d5cca29c1f2147d2a0931a088b717/src/game.cpp#L3985

**Comment by paramat** [comment]
i've noticed weird dig times in creative too, should all be one optimised time.

**Comment by MarkuBu** [comment]
Then I will reopen my first issue in minetest

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/creative/init.lua#L223
I see that the hand is given a quick dig time, looks like the intent is for players to use the hand for everything, this would explain why it's faster than many tools.
This effect of creative does seem to be defined only in the creatve mod, so perhaps this is a game issue only. The mod would have to redefine dig times for all tools to change their behaviour, this is perhaps not a good idea due to the complexity.

**Comment by paramat** [comment]
See discussion in https://github.com/minetest/minetest/issues/4462

**Comment by paramat** [comment]
See #1268

**Comment by paramat** [comment]
#1268 merged.

**Comment by paramat** [comment]
Closing for above reasons.
