### ISSUE TITLE
No bones when died on a rope

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#1280]
Hi there,

i just fighted with someone and he died on a rope.
There were no bones dropped.

I also had no log about the bones (i added notes to the mod).

In our case, it was a xdecor:rope.

**Comment by everamzah** [comment]
Bones node checks for air above, if not found then +1 Y above that.  If neither spot is `air` then bones node fails to place.

Perhaps bones should find air *near* where player died, instead of *above*.

**Comment by ExeterDad** [comment]
If he had nothing in his inventory there would not be bones either.

**Comment by tchncs** [comment]
> If he had nothing in his inventory there would not be bones either.

but he had.

**Comment by everamzah** [comment]
Yes, if you lack items, no bones node is placed.  In this case it appears that the player had inventory and there were no air nodes above him by two.

This can be fixed by finding air around the player.  If they die inside an unprotected stone node, that should be replaced.  Currently, the only thing a bones node will replace is a node that is `buildable_to`.  (?)

I think that a bones node should be placed regardless of whether a player holds items.

**Comment by tenplus1** [comment]
If a player dies and no space is found for bones at player position or +1 above then all items inside their inventory/crafting drop as items instead.

**Comment by paramat** [comment]
'find node near' looking for air in a 1-node radius would be better, can anyone make the PR?

**Comment by tenplus1** [comment]
Fixed: https://github.com/minetest/minetest_game/pull/1282

**Comment by paramat** [comment]
#1282 merged.
