### ISSUE TITLE
Disable destroying default:river_water_source by empty bucket

### ISSUE THREAD

**Issue by amadin** [minetest/minetest_game#1319]
Please disable to destroying default:river_water_source by the empty bucket, because on public servers players can easy destroy a part of river(s) and disable other players to float the rivers on a boats because a rivers in some places will be without water. For example default:water_source are can not be destroy by the emty bucket. Also i hope you disable different textures color for rivers and seas.

**Comment by paramat** [comment]
Good point, i was thinking about this recently, river water is not renewable, so bucketing it creates ugly holes. It's also not very useful because when you pour it out it only has range 2.
I think we need code that when river water is bucketed it leaves the source node remaining, this is no different to how normal water is infinitely renewable.

**Comment by paramat** [comment]
See #1320

**Comment by paramat** [comment]
#1320 merged.
