### ISSUE TITLE
Adding a default automation MLGame

### ISSUE THREAD

**Issue by alexeysvrv** [minetest/minetest_game#1326]
I propose to add to the standard game, and the possibility to automate the creation of various mechanisms. I propose to integrate into MTGame Mesecons modes. Thank you very much for your work.
P.S. With the mod mesecons have a very big problem of productivity. FPS sags to 10-20 when creating breakers (wires periodically light up and faded out). Perhaps this is a problem or fashion game engine
P.S.S I russian. Sorry for grammatic :)

**Comment by sofar** [comment]
Mesecons is LGPL-3.0, and therefore can't be merged into minetest_game, as is.

**Comment by alexeysvrv** [comment]
@sofar So GPL version 2 is compatible with the LGPL. There are no licensing issues

**Comment by alexeysvrv** [comment]
@Jeija

**Comment by everamzah** [comment]
You can put minetest_game into mesecons, but you cannot put mesecons into minetest_game.

**Comment by alexeysvrv** [comment]
@everamzah What copyleft license is needed to be able to combine them?

**Comment by everamzah** [comment]
They cannot be combined without changing either minetest_game to lgpl-3.0, or changing mesecons to lgpl-2.0.

**Comment by sofar** [comment]
In the current state of mesecons, I don't see it getting merged as-is. There needs to be a wider discussion as to whether this is wanted, needed and if everyone (both mtg and mesecons teams) is willing to make this work.

Currently, both those teams are fairly happy with the current situation, as it allows them to focus on their own project while not being too bothered by changes in either project. If we merge those, we'd also merge communities, and a *lot* of code would need to be touched.

One thing to consider, for instance, is that we might not want to merge *all* of mesecons' features all at once. Mesecons is very rich and large, and it would make sense to merge only a limited set of bits at first. This would make things harder for both the mesecons teams and the minetest_game team, since in such a scenario we'd not only have to decide where to cut, but we'd have dozens of unproductive discussions online in threads like this with people interjecting ("I want the note block") and with little actual benefit (it probably will break stuff).

So yeah, this isn't a good idea.

**Comment by alexeysvrv** [comment]
@sofar There is an alternative? We can create an independent implementation, which subsequently will be included in the main branch? Or will gradually integrate objects and functions? I propose to discuss

**Comment by paramat** [comment]
I'd rather not add Mesecons.

**Comment by C1ffisme** [comment]
In the future, if the Minetest Engine is built so that things like mobs or technology work on most computers, I'd like to see Mesecons get added at some point. But currently the engine trying to support older, slower computers. (At least, that seems to be the case.)

I feel like noting, though, that Minecraft isn't exactly "lag-proof", you can do things like making huge amounts of sand fall, blowing up insane amounts of TNT, etc. So maybe we don't need to be too concerned about making sure that Minetest cannot wreak havoc on people's computers?

**Comment by stujones11** [comment]
Mesecons is a fantastic mod but does not fit well with the 'olde worlde' theme of this game. IMO it is best left as a mod or be part of a different sub-game.

**Comment by alexeysvrv** [comment]
We can create an independent implementation, which subsequently will be included in the main branch?

**Comment by sofar** [comment]
@alexeysvrv that would avoid the license issues, but you'd still have to also avoid all the other problems noted, as well as have a high quality implementation that is worth maintaining.

**Comment by Wuzzy2** [comment]
I have to agree with the developers here. Adding Mesecons to Minetest Game would have several problems.
It also has the danger that it might “kill” any innovation in Mesecons since Minetest Game developers seem to be very conservative in development.
Implementing our own “automation mod” in Minetest Game, independent of Mesecons will have the danger that it “kills” Mesecons itself because Minetest Game's version might be incompatible.

**Comment by C1ffisme** [comment]
@stujones11 
> Mesecons is a fantastic mod but does not fit well with the 'olde worlde' theme of this game. IMO it is best left as a mod or be part of a different sub-game.

Minetest doesn't really have any theme right now. While people will shame someone who wants to add guns or cars to vanilla Mine**craft**, Minetest seems to be a bit themeless.

**Comment by sofar** [comment]
I'd like to close this issue, before the discussion goes into a tangent on "alternative" mesecons implementations and "oh this would be good" type of discussion.

Question was: should we merge mesecons
Answer: no because (1) not possible license wise (2) too complex to merge as-is. Both (1) and (2) are unlikely to get fixed.

**Comment by paramat** [comment]
I'd prefer any alternative to mesecons stay a seperate mod.
So :-1: for this request.

**Comment by nerzhul** [comment]
if something is needed to automation maybe we should expose coreside logics into lua to unify mods but else, the licensing problem doesn't permit to add it

**Comment by paramat** [comment]
sfan5 disapproves http://irc.minetest.net/minetest-dev/2016-10-29#i_4733096
I think we can close.
