### ISSUE TITLE
Fly and fast on by defult if in Creative mode

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1373]
Fly and fast on by defult if in Creative mode It's rediculus to have to type a command everytime i go into a new Creative mode world in a (singleplayer world)

Even if People don't want you to fly Around in Creative mode on a server for some Reason they can Just remove The privilege

This is just my 2 cents on this I don't know the reason why this isn't like this, so there's probably a reason for it.

**Comment by C1ffisme** [comment]
This is possible, it just means more changes to the privileges system, such as making another list of privileges turned on by default in creative mode.

Although, personally, I don't see why it's so much effort to type a single command, or change a config setting once.

**Comment by tobyplowy** [comment]
@C1ffisme flying is a gameplay function of creative mode without flying creative mode sucks
Also I make a lot of the worlds and so i have to type command alot and it's annoying because it should be on by default

**Comment by paramat** [comment]
:-1: Even in creative players are more likely to want normal movement to begin with.

**Comment by tobyplowy** [comment]
@paramat If You Just Don't Turn on Fly (Whatever button It is on your keyboard) there is no problem you can Just Walk Around unless you have the setting on for Double Tap spacebar but Still have to Double Tap The spacebar and you Just Turn It Back off If you don't want it

It's just a hassle to have to do it everything I make a new world
And its really un user Friendly  (They don't know that command so they have to ask for it)

**Comment by tobyplowy** [comment]
@paramat Maybe It can be a setting On The World select screen the same way you Select Survival or Creative

**Comment by Fixer-007** [comment]
>Even in creative players are more likely to want normal movement to begin with.

not always

**Comment by C1ffisme** [comment]
> Even in creative players are more likely to want normal movement to begin with.

Eh, no.

Don't get me wrong, tobyplowy. I wouldn't mind this, and would probably prefer it, it just seems like a bit more work for someone to do, when it would be much easier if everybody just changed a config if they really needed too.

I can't really see a reason why not to, though. It just depends on how much work someone wants to put into such a little feature. Of course, maybe I only think this is a lot of work because I'm too lazy to fiddle with Github for more than half an hour.

**Comment by paramat** [comment]
No not a setting, not remotely justified.
Even if it's 50+% of players using fly and fast from the start of a new world (i usually do due to testing commits) it is obvious correct practice to start the player in the normal state. It's only '/grantme all' at the start of a new world, which is not that often.

**Comment by rubenwardy** [comment]
It would be rather hacky to grant fly and fast by default when in creative, especially when in multiplayer

**Comment by tobyplowy** [comment]
@rubenwardy like this we're never going to get anywhere seriously!

Is there any chance it can only be enabled when in single player ( you know where you made the world and you are the Only One on it!)

**Comment by paramat** [comment]
:-1:

**Comment by C1ffisme** [comment]
@rubenwardy What if creative mode and invincibility were privileges themselves? We would need to modify most mods that depend on the setting for creative mode, but it would be a lot better for servers that need per-player gamemode!

**Comment by paramat** [comment]
Please star a new issue for that request.
