### ISSUE TITLE
Add ambience mod for fire and water sounds

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1385]
https://github.com/paramat/parambience
Here is a mod for testing. Use 'permanent flame' nodes to test, not normal fire nodes, to avoid triggering the sound code in the fire mod.
Water sounds are gentle and triggered by flowing water.
I suggest removing the sound code from the fire mod (see #1112 for why the current code cannot be used any longer) and adding this ambience mod (under a new name and with CC BY water samples) for fire and water ambience.

See further details and discussion in #1112 
This mod is not perfect but is perhaps good enough until client-side modding or dedicated ambience sound code in the engine provides a better alternative.
This code started as alternative sound code for the fire mod, but since the node search is being carried out it is not much extra load to add water ambience.

**Comment by paramat** [comment]
Hang on, i'm going to change this back to positional sounds, still has issues but is a little less weird.

**Comment by paramat** [comment]
The fire-sound only version of this mod had positional sounds at one point, i just realised this cannot now have positional sounds because this is searching for fire and water nodes, the list of positions will be a mix of the two so we can't tell if a position is fire or water.

**Comment by Fixer-007** [comment]
Yeah, after those fixes it sounds much better... Would you like to add lava standing and flowing sounds?

**Comment by tobyplowy** [comment]
lava standing and flowing sounds oh man that wuld be Amazing in Caves.

**Comment by Rui-Minetest** [comment]
As @sofar have suggested, it shouldn't be implemented until client-side modding API is implemented.

**Comment by paramat** [comment]
As an alternative, this version of the mod https://github.com/paramat/parambience/archive/048c874f9c9492b020af93aad5963f1f7ddd12b6.zip is just fire sounds, but makes them positional, this has some issues described in #1112

**Comment by BluebirdGreycoat** [comment]
Here is the code I'm using currently, if anyone is interested in it. Fire sounds only. It updates sound whenever the player moves more than a certain distance from their last position, and also updates sound instantly, if flame nodes are created or destroyed (requires a modification to the `fire` mod, see comments in the code). Seems to work well for me although I have not stress-tested it.

Advantages over the code already posted: 1) it does not rescan the area around a player if the player has not moved and no flame nodes were created or destroyed (reduces load for players that are AFK or not moving for whatever reason). 2) Sounds are started/stopped instantly when flame nodes are created or destroyed (but this requires callbacks in the flame nodes, see comments).

If you decide to take a look, DO read the code carefully, I wrote it to be easy to read and you WILL need to change it slightly before it will work for you.

The reason this mod is not standalone is because it is designed to run cooperatively with other mods on my server which need to modify the behavior of fire, so it can't just override the flame node definitions.

[init.lua.txt](https://github.com/minetest/minetest_game/files/620402/init.lua.txt)

**Comment by paramat** [comment]
Thanks will look.

**Comment by paramat** [comment]
This is useful for considering how my code can be improved.
Note that looped sounds must be attached to an object https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L464 the current fire sounds loop without attaching to objects and sound bugs reported may be due to this. Perhaps you could attach the sounds to the player object?

**Comment by BluebirdGreycoat** [comment]
Do you mean this bug?

> Fire sounds are reported to be heard 1000s of nodes away.

I am not knowledgeable about it, but I believe this could possibly be caused by the `fire` mod attaching sounds to actual map locations. Once those locations are unloaded, who knows what funny stuff happens. 

However, I have not encountered this bug yet with my own code, and my code does not attach sound to map locations but instead to player's clients with `to_player = name`; this may be getting around the bug.

I _can_ change the code to attach sounds to the player object, but that feels like a hack to me. It would also cause the sound to be sent to other players if two or more players stand close together enough: imagine if 2 people stand next to a fire, both will hear the fire sound twice, once for themselves, and once for the other person.

Addendum: I have carefully looked at the sound code in the `fire` mod, and I believe the reason for hearing fire at huge distances can be explained quite simply.

Imagine the following scenario: 1) A player starts a fire. 2) The fire nodes spread and sounds are updated and attached to map locations. 3) The player leaves the area. 4) The mapblocks with fire are unloaded. 5) The `fire` code requires the mapblocks to be loaded in order to update sounds, but since the map is unloaded, no sound updates can happen; thus the sound continues to loop, but at ever-decreasing gains as the player gets farther away. However the sound gain never reaches 0.

If this explanation is correct (and I want to stress the "if") then my code will not suffer from this problem. It explicitly stops sound when the player moves far enough from fire, and does not care whether mapblocks are loaded or not. It even works when the player teleports.

Obviously it would be great if others could confirm that this code does not have this bug.

**Comment by paramat** [comment]
Yeah that bug, thanks.

I tested attaching a sound to a player object, as well as having 'to_player = player_name,', the result was very weird, the sound was very loud due to exponential volume with distance from source, and every time you move the sound rises and falls in volume because the source of the sound has a position lagging behind client player movement.

I then tried looping a sound without attaching it to an object, but using 'to_player = player_name,', but the gain seemed to be fixed in this case.

**Comment by paramat** [comment]
So looping a sound using 'to_player = player_name,' seems to work, maybe i have misunderstoof the documentation, it seems that using 'to_player = player_name,' counts as attaching to an object.

**Comment by BluebirdGreycoat** [comment]
If the code works reliably, I'd hope to see the documentation updated to reflect that.

**Comment by paramat** [comment]
Working on a mix of your code and mine.

**Comment by paramat** [comment]
The current sound code loops sounds without either attaching to an object or playing direct to one player.

**Comment by paramat** [comment]
@BluebirdGreycoat 
Documentation updated.
Please see #1436 i don't think fire sounds can be done acceptably in Lua.

**Comment by paramat** [comment]
#1436 merged.

**Comment by sorcerykid** [comment]
Just FYI: Don't trust the documentation, it is misleading. Sounds can be looped regardless of their association with an object. Moreover, sounds are not "attached" to an object internally. When minetest.sound_play( ) is invoked with an object, it does not maintain any reference to the object. It is only used for positioning purposes at the time of invocatioin. Regardless of whether the object is moved or removed afterward, the looped sound will continue to play from that same position until stopped (hence the bug with fire sounds).

**Comment by paramat** [comment]
Thanks.
