### ISSUE TITLE
Add farming_plus to minetest_game

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest_game#1394]
I think it would be really cool to at least add parts of @tenplus1 's farming_plus mod to the default minetest_game.

**Comment by paramat** [comment]
Yeah could consider after release.

**Comment by sofar** [comment]
No disrespect for tenplus1's efforts, but farming redo (it's not named farming plus?) is huge.

I can make a list of things that I find (subjective, yes) incompatible with minetest_game - the size, many of the textures, a lot of the mechanics, the amount of coding it would take to merge it, etc..

This is one of the reasons I wrote `crops` myself from scratch - I feel we just need 3-4 more farming crops with a simple twist and originality, not 17 (honestly though, I'm flattered some of `crops` are in here :))

My intent for `crops` has always been to make it mergable, and perhaps this is a better starting point, although I know some people don't like the unconventional interaction style it imposes. The watering part should likely also be removed, but that is fairly trivial as it's already optional.

**Comment by tenplus1** [comment]
gary: Farming Redo is meant as a farming replacement mod since it uses a different api to grow crops in the background while the player is off exploring elsewhere...

sofar: the different texture sizes are meant to make crops look 2 blocks high when it's only a single node.

**Comment by SpaghettiDeveloper** [comment]
Hi guys! I follow the project every day. Sofar, you have developed a new farming system to Minetest vanilla? I knew you'd also worked on this. I noticed a lot of new things in the latest nightly build (I brutal testing in every detail), I am very happy for the new farming in the works, Minetest vanilla needs new crops, thus the next release will be excellent bases finally complete. You did a great job, Sofar, TenPlus1, Paramat, and everyone else, you are great!

With affection and admiration, an Italy-standing fan (1977)

**Comment by sofar** [comment]
There is not enough time to do this or anything before the next release.

**Comment by C1ffisme** [comment]
I'm okay with adding new crops, but they need to have special uses in crafting, or some other reason to use them besides food. Example with Minecraft:

- Wheat (Used in two foods, hay and animal breeding.)
- Carrots (Used in golden carrots and pig/rabbit breeding.)
- Potatoes (Pig breeding and baked potatoes.)
- Beetroot (Used to breed pigs, and make red dye. A bit redundant, but it was added in a very small update, so maybe it will get a better use later?)
- Pumpkins (Used in golems, Jack o'Lanterns and funny headwear.)
- Melons (Used in glistering melons.)

(Glistering melons and golden carrots are used in brewing, and baked potatoes make a pretty decent food source, just to clarify.)

Just don't start adding items that have uses only as a food, because Minetest's hunger system is non-existent right now, and it stops people from only growing one or two crops. In fact, right now you might as well just grow cotton, because it actually gives something worth the long wait.

**Comment by sofar** [comment]
Good points by @C1ffisme  - even `crops` has zero additional uses for the grown crop other than food.

**Comment by C1ffisme** [comment]
@sofar Thanks.

I will say, though, Beetroot is a pretty useless crop, after I found out it only heals a shank, and the only food item you can craft with it is un-stackable. (For some reason, Minecraft updates are going to be smallish until 1.14.X, according to Mojang-crosoft, so we can find things in Minecraft to actually complain about.)

I suppose the problem with adding food in Minetest is that there aren't a lot of sensible things that we can use it for as an alternative. One day, I would hope brewing or chemistry would pop up in Minetest to make something worth diving into. (Imagine if you could ferment extra food into ethanol, and use that to fuel your furnace!)

The only other thing food can be used for at the moment is making blocks, but crops are so hard to grow at the moment that you might as well just use cobblestone, or make a stained clay mod. (Or dyeable planks, cobble, etc.)

**Comment by rubenwardy** [comment]
Polish means that items need to make sense in the context of the game. New food chains need to either:

* Give more health but at the cost of longer production times (eg: bread)
* Be biome specific (ie: make bread grow only in temperate biomes, add food for other biomes)
* Have degradable benefits (not currently a MTG feature)
* Have debuff benefits

Adding a lot of new plants and foods to MTG doesn't make sense to me without those. It's more of a mod thing

**Comment by C1ffisme** [comment]
@rubenwardy It makes more sense when hunger/stamina actually exists in the game. Otherwise, it's just a bit pointless to have food at all.

In the meantime, what about making food regenerate health over time instead of instantly healing it? (As well as being able to change the speed that food regenerates.) Then there is actual value in having certain foods in certain scenarios. (e.g. Get food that heals faster, but not as much for when in a battle-type situation, get food that heals slower, but much more for when you need to heal up in a safe place.)

Another thing that could be useful is if certain foods gave certain temporary effects, such as more hearts or better walking speed.

**Comment by sofar** [comment]
the `stamina` mod does this. Unfortunately, the core doesn't support player metadata and the HUD API support is horrible at the moment, and those preclude merging mechanisms like that.

**Comment by rubenwardy** [comment]
While we may be adding more crops in the future, we won't be adding farming_plus

**Comment by paramat** [comment]
I agree to the close.
