### ISSUE TITLE
Keys: add ability to label them

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1421]
Right now after assigning the skeleton key, it becomes "key", that's it, you end up with key1, key2, key3, key10, you give them to friends... they make some more, and ... they are indistinguishable.

My proposal: right mouse clicking with key opens up formspec similar to sign: you name your key as you want, save - it gets labeled which can be observed by hovering mouse over it or selecting it in inventory (if possible), or just show text on screen as for sign.

Or maybe some kind of key with label node, with some similarities to books.

What do you think? Do not ignore this, it will be a major pain in one place if not thinked over.

**Comment by sofar** [comment]
Already discussed at length, you can't change the tooltip of an ItemStack until the engine supports this.

The popup form is an interesting thought, but I doubt it would help much since it requires the player to interact with each key, which is just as trial-and-error as trying a key on a door.

It's not being ignored either, we've spent a lot of time coming up with solutions already :/

**Comment by matt8fr** [comment]
as for the door/chest/...     : owned by/for (playername) door's.

**Comment by sofar** [comment]
>as for the door/chest/...     : owned by/for (playername) door's.

This is blocked by an engine bug/feature.

**Comment by matt8fr** [comment]
This engine poses a lot of worries. 
Good luck with this key

**Comment by Fixer-007** [comment]
Can be done now, closing
