### ISSUE TITLE
New cactus texture?

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1465]
Currently the texture for the cactus looks a bit strange it doesn't resemble a cactus in my opinion

**Comment by SpaghettiDeveloper** [comment]
I would change the textures of jungletree because it is bad lol! I like the texture of cactus, Minetest needs an update of the textures of trees woods! without the side edges in the tree texture pine, acacia tree, and tree. Combine the wooden blocks returns a bad effect without continuity of textures.

Obviously it is my opinion as a passionate builder, and careful observer.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper the jungle tree has a strange Texture and its really hard to build with but please we're here for the cactus stay on topic :)

**Comment by sofar** [comment]
I'm getting a bit annoyed with these type of requests. There is no bug. The texture is not broken. And until someone makes an actual new texture, there is little to no discussion possible that has a positive outcome. 

These type of requests belong on the forums under a big "texture requests" thread, but not here. 

Please close this.

**Comment by tobyplowy** [comment]
@sofar textures are really important to make a game Look Good but that doesn't seem to matter for minetest, what ever I will close it :/

**Comment by sofar** [comment]
@tobyplowy I don't disagree with you at all. Textures are critical, even. 

The problem isn't that we don't know which textures are ugly or don't fit. We know which ones are found ugly or inconsistent by players. 

The problem is that this type of issue report is just pointless. We always end up with a frantic discussion that goes on for ages and nobody comes up with an actually better texture. 

And when someone actually makes a better texture, WE HAVE THE SAME DISCUSSION AGAIN. All over. Including all the off topic comments. 

So what I'd like to see instead, and this has worked really well (look at how the gravel texture was redone, for instance), is that someone who has a little bit of artistic sense, just submits a concept texture in a PR. If the discussion starts on topic, it leads almost always to a positive and aesthetic improvement.

**Comment by tobyplowy** [comment]
> So what I'd like to see instead, and this has worked really well (look at how the gravel texture was redone, for instance), is that someone who has a little bit of artistic sense, just submits a concept texture in a PR. If the discussion starts on topic, it leads almost always to a positive and aesthetic improvement.

But That can Take Forever to get the correct situation
I'm doing my best to make the minetest Community bigger and better im really Almost Breaking Under the work and it's almost useless If this stuff Keeps Happening (sorry if this last comment was off-topic I just needed to get it out)

Also Again offtopic for example with the [Cobblestone Texture made by d00med](https://github.com/D00Med/LegendofMinetest/commit/fa77724a33152453dea9a0b0e40111969fbe992e)
it's a lot Better And everyone can say it is but It Will Never Be added even though you would probably be allowed by d00med to use it (also please consider using tis texture if your allowed by d00med) I guess this is the end of this conversation unless you want to say something

**Comment by tobyplowy** [comment]
@sofar 

> So what I'd like to see instead, and this has worked really well (look at how the gravel texture was redone, for instance), is that someone who has a little bit of artistic sense, just submits a concept texture in a PR. If the discussion starts on topic, it leads almost always to a positive and aesthetic improvement.

But That can Take Forever to get the correct situation
I'm doing my best to make the minetest Community bigger and better im really Almost Breaking Under the work and it's almost useless If this stuff Keeps Happening (sorry if this last comment was off-topic I just needed to get it out)

Also Again offtopic for example with the [Cobblestone Texture made by d00med](https://github.com/D00Med/LegendofMinetest/commit/fa77724a33152453dea9a0b0e40111969fbe992e)
it's a lot Better And everyone can say it is but It Will Never Be added even though you would probably be allowed by d00med to use it (also please consider using tis texture if your allowed by d00med) I guess this is the end of this conversation unless you want to say something

**Comment by sofar** [comment]
>I'm doing my best to make the minetest Community bigger and better im
>really Almost Breaking Under the work and it's almost useless If this
>stuff Keeps Happening

So instead, don't submit feature requests like this that can't go anywhere, but take one thing, one thing you know you can make a difference with, and put all your time in it. 

That's what I do. I pick one thing that I understand, know what needs improvement, study the problem, read the history, and then do the work. Even if it means I don't get it merged, it's totally worth the time: because I've made something before I submit it, and even if it's not merged I can post it as a nice mod for people to use.

>Also Again offtopic for example with the [Cobblestone Texture made by
>d00med](https://github.com/D00Med/LegendofMinetest/commit/fa77724a33152453dea9a0b0e40111969fbe992e)
>it's a lot Better And everyone can say it is but It Will Never Be added

It can only be added if it's submitted as a PR! It's a chicken and egg problem. The chicken can't merge the egg if there is no egg, and it's silly to have a discussion about the egg until it's laid.


>I guess
>this is the end of this conversation unless you want to say something

I guess I'm not getting through to you. I want your time spent on Minetest to be more effective. For that to happen you need to spend more time on things where you *can* make a difference. Asking us to change the cactus texture is not effective. Making a cactus texture or finding a usable texture is effective. 

I suggest you make a forum post like some of the devs have done where you list your items where you'd like to see improvement. That could be a way to focus and get traction.

**Comment by tobyplowy** [comment]
@sofar 

> I suggest you make a forum post like some of the devs have done where you list your items where you'd like to see improvement. That could be a way to focus and get traction.

Did it this morning https://forum.minetest.net/viewtopic.php?f=5&t=16077

**Comment by tobyplowy** [comment]
@sofar also I will ask D00med if he wants to submit his textures as pull request
