### ISSUE TITLE
Add different  sandstones?

### ISSUE THREAD

**Issue by cx384** [minetest/minetest_game#1477]
Why do we have three different sands and only one sandstone?
It would be great to have different sandstones, because minetest needs more building blocks.
The [Sandplus Mod](https://forum.minetest.net/viewtopic.php?f=9&t=16281&p=244637#p244637) already got those nodes.

**Comment by tenplus1** [comment]
I like it :) this would bring more decorative builds with sand/sandstone into play :)

**Comment by MarkuBu** [comment]
Mt had two types of Sandstone. Sandstone and Desert sandstone. What happend? Add one sand and remove one sandstone?

**Comment by SmallJoker** [comment]
@MarkuBu, there are normal and desert ~sand~_stones_. 

Having more materials to build is a good idea. But like always when adding more materials to a mapgen, it will cause ugly borders in older worlds and make it almost impossible to find it when large parts of the map already were generated.

**Comment by Napiophelios** [comment]
I like the silver sandstone idea, a bleached sandstone would be nice choice when building stuff.
I always assumed desert stone was the compliment to desert sand;
I think adding "desert sandstone" would be kind of redundant.

**Comment by MarkuBu** [comment]
@SmallJoker you're right. My fault

But not adding/changing something just because of some issues with old maps? Then you can never change a mapgen

**Comment by octacian** [comment]
I agree, Minetest should have silver sandstone and such. Personally, I think this should have been done before Minetest 0.4.15 was released. Oh well. Though it could mess mapgen up a bit, it's still worth doing. Somebody should open a PR with this, could probably directly use the textures and possibly much of the code from Sandplus. heh, if people agree this should be done, and nobody else opens a PR, I'll do it next week.

**Comment by DS-Minetest** [comment]
the stones of desert sand and silver sand are desert stone and normal stone
but i am not sure
you could see normal stone and desert stone as even more compressed sandstone `sand=>sandstone=>stone`
or as stone that becomes sand if enough wind blows `stone=>sand=>sandstone`

**Comment by GreenXenith** [comment]
Glad to see my mod turned out nicely!
I noticed dungeons in Cold Deserts look a bit out of place, so maybe Cold Desert Dungeons have Silver Sandstone Brick and maybe Desert Dungeons have 50/50 chance of either Desert Stone or Desert Sandstone Brick. Just a thought.

**Comment by paramat** [comment]
Desert stone is the companion (sand)stone to desert sand, stone is the companion stone to silver sand.
More sandstone types is a fine idea of course but perhaps for optional mods? we try to keep default nodes minimised, every stone type adds a bunch of blocks, slabs, stairs etc.

**Comment by sofar** [comment]
Geologically speaking, sand can come from sandstone, and stone. We have 2 types of sandstone and one stone, so 3 sands would be fine.

**Comment by DS-Minetest** [comment]
@sofar arent there only one sandstone and 2 stone types? desert stone is no sandstone since you cant craft it to desert sand or reversed

**Comment by paramat** [comment]
I consider desert stone a sandstone, we could add crafting recipies to link it to desert sand.

**Comment by cx384** [comment]
I always thought desert stone was a stone type.

**Comment by DS-Minetest** [comment]
but desert stone drops desert cobble, sandstone doesnt drop cobble, stone does
and the texture of desert stone is more similar to stone than to sandstone
and you can dig sandstone with shovel and pickaxe, desert stone only with pickaxe

=> altogether there are 4 reasons to count desert stone to stones and not to sandstone

by involving non mtg mods there would be the 5th reason that eg. `technic` or `basic_machines` grinder grinds desert stone to desert sand and stone to sand

**Comment by paramat** [comment]
Indeed desert stone has not been considered a sandstone in the past, but maybe it should and we can make the necessary changes? Sofar is the geologist.

**Comment by octacian** [comment]
I would suggest that we put the nodes introduced by Sandplus into MTG, as though it may or may not be fully realistic, it would make things seem more consistent and offer more variety. A full list of the nodes I'd suggest should be added (the nodes in Sandplus) is below.

* Desert Sandstone
* Silver Sandstone
* Blocks/Bricks/Stairs/Slabs for both of the above

I personally believe that though MTG shouldn't be overly complex, it should still offer a interesting and playable experience. Unless otherwise advised, I will start on a PR in a few hours.

**Comment by sofar** [comment]
Geologically speaking `sand` is a grain size denomination and says nothing about the chemical components that make up the material. You can have sand originate from granite all the way to mudstone, as long as the material grain size is > 63um and < 2mm, and more than 70% (or so) of that grain size, it's called sand.

This is why it doesn't matter too much to me that there is no direct relation between desert stone, sandstone and stone and the derivatives `gravel`, `sand` and `clay`, since geologically speaking, there is no relation.

So I don't think we should change minetest_game at all. There are already so many inconsistencies in it, and this one isn't worth changing. Adding another node type in between these is just a kludge if you ask me. So let's stop adding kludges.

**Comment by Fixer-007** [comment]
Only problem with this is that you need to change mapgen settings to accommodate those new sandstones...

**Comment by paramat** [comment]
I agree with sofar, i don't think we need new sandstones.

**Comment by GreenXenith** [comment]
I still don't get how this affects mapgen...new sandstone biomes don't have to be added. The only mapgen thing that I see might be affected would be dungeons (refer to my last comment), which should be a minor thing to deal with, is it not?

**Comment by paramat** [comment]
Correct it's not a problem. but we need a good reason to add new sandstones, and new natural stone types are usually only added when needed in mapgen, otherwise how would you find them? There would be no resource.

**Comment by C1ffisme** [comment]
@sofar To my knowledge, most of the yellow/white, powdery stuff we call "sand" is normally Silicon Dioxide...

**Comment by paramat** [comment]
We could change the 'texture' of the desert stone texture to make it a sandstone, it should be really, then have crafting to/from desert sand. However to avoid disruption we couldn't change the name of desert stone.

**Comment by GreenXenith** [comment]
@paramat You don't need to find sandstone naturally (because you rarely can). All you have to find naturally is the sand and then craft the sandstone from the sand. The reason for more sandstone is to give the other sands a purpose and have more decoration/building blocks.

**Comment by sofar** [comment]
@C1ffisme while that's what most people think, it's entirely incorrect.

https://en.wikipedia.org/wiki/Sand

Quote: `Sand is a naturally occurring granular material composed of finely divided rock and mineral particles. It is defined by size, being finer than gravel and coarser than silt.` (...more stuff about grain sizes)

Nothing in here says it needs to be SiO2. If you have granite-derivative sand, a lot of the sand will be feldspar (SiAlO). And in Basalt rich areas you'll get a basalt derivative sand(no SiO2). Even limestone sand is extremely common: Every tropical beach island in the world is covered with sand from Coral debris, and therefore is limestone sand (which is why it's so bright white).

/end geology recap

**Comment by kaeza** [comment]
#1596

**Comment by 0-afflatus** [comment]
I'm not going to get too heavily involved in this particular debate.

The mapgen watershed is about breaking worlds. If a change actually breaks mapgen then existing servers cannot upgrade. Introducing new types of things doesn't necessarily break mapgen, but it often means that the server admin needs to figure out some way of introducing the new element into the world.

**Comment by paramat** [comment]
#1596 merged.
