### ISSUE TITLE
Minetest Game Values and Direction Document

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1488]
I wrote a document stating how I see MTG:

http://dev.minetest.net/User:Rubenwardy/Minetest_Game_Development

I'd be grateful if links could be posted to celeron55 stating his vision
Please don't edit that document if you're not a MTG dev (unless you're fixing typos etc), instead post below

**Comment by C1ffisme** [comment]
I don't think that Minetest Game is exactly 'Medieval'. With Minecraft it makes sense, because many of it's items (redstone, potions, enchantments) seem to be magical, which is normally connected with a medieval setting. In fact, I'd actually rather see Minetest Game become more about semi-realistic/sci-fi machinery/industry, to contrast Minecraft.

**Comment by sofar** [comment]
I think the technology level is medieval, so the term is appropriate.

Mods can take it to the alien/sci-fi/industrial age, I'd prefer to keep it out.

**Comment by paramat** [comment]
Yeah i don't like the definition of the time period, MTG is more like semi-fantasy anime steampunk.

**Comment by rubenwardy** [comment]
How about:

> Late Medieval - but with steam punk / semi-fantasy elements (eg: steel, glow nodes, etc)

**Comment by C1ffisme** [comment]
> I think the technology level is medieval, so the term is appropriate.

Not necessarily, since there is very little technology to speak of, anyway. (Sure, the game only has primitive metal-smithing and tool crafting equipment, but we don't have anything beyond that to suggest any other time period.)

What if Minetest went for an early Industrial Revolution time period? (Early 1800s?)

**Comment by 0-afflatus** [comment]
It's about the form of words. Better to say:
"The base technology level of Minetest Game is late-medieval"
Having run a medieval-style server I can confidently assert that most players don't build in a medieval style. We could add:
"... with a few sci-fi / fantasy elements." 
because that's true. We could also say that other technology can be added through mods.

When I first started playing MT I would have put the date somewhere around 1850 and placed the action in America - default farming features fruit and veg not found in Europe before Columban colonisation. I felt (and still do) that the game requires significant modification to support a Medieval European theme.

One of the things I think appeals to players is that you are not bound by a theme - you can build what you want. Too many players build glass skyscrapers to describe the game as medieval beyond the default tech level.

**Comment by MarkuBu** [comment]
> Exploration - interesting mapgen/biomes

I think, this is a difficult part for MTG. This would need much much more biomes, tons of plants and a lot of building structures. With 8 biomes and 5 trees you can't win a match

> Immersion - adding feedback such as sounds, mobs, and interactivity to make the world feel alive

I think, mobs are also difficult. Minetest doesn't has pleasing mobs yet. And good sounds will be rejected by server hoster because of their download size. But short sounds...

> Semi-minimalism - No additions that are decided to be too much

But some basic decoration items like chairs, tables, flower post, frames and stuff would be nice

**Comment by C1ffisme** [comment]
@MarkuBu 
> I think, this is a difficult part for MTG. This would need much much more biomes, tons of plants and a lot of building structures. With 8 biomes and 5 trees you can't win a match

Agreed. Biomes are great, but most of them are a bit too... normal. There's nothing that really catches anyone by surprise. Wow, look! The grass in this biome is a different color! Ooh! In this biome, there is sandstone under the dirt! Even worse is that there is even less to explore under the ground.

> I think, mobs are also difficult. Minetest doesn't has pleasing mobs yet. And good sounds will be rejected by server hoster because of their download size. But short sounds...

Heck, Minetest doesn't have mobs... at all. Mods don't count, because they are not included with the default download. And saying that Minetest has sounds is a bit misleading because all we have are basic digging and placing sounds. There is no ambience, no music, not even a button feedback sound.

> But some basic decoration items like chairs, tables, flower post, frames and stuff would be nice

Chairs and tables? Debatable, to say the least. I feel that when mods give you too much furniture, there is very little incline to use creative thinking. But other, more interactive things, like flower pots, item frames, pedestals and maybe dynamic shelves (That show what you put on them) would be really good. (I don't get the demand for chairs the player can sit on. Do you just want to roleplay that badly?)

**Comment by rubenwardy** [comment]
This isn't saying what we currently have, it's what we're aiming for

**Comment by C1ffisme** [comment]
@rubenwardy But you can bet it's going to be taken the wrong way. This document is basically the cover to our book of a game. (Depending on wherever we post it.) At least saying something like "This is what we strive for" in the document would be a little bit less misleading, and look a little bit less like an advertisement.

Also, unrelated but:

> Alien - Mese is an alien crystal / meteorite 

I feel like this should be rewritten a bit, not mentioning the name of our only alien object. That's a bit like saying:

> Alien - Minetest has this stuff called mese, and it's _kinda_ alien. At least, that's the only real lore the devs put behind it. That's really it in the way of alien, though. Mese is pretty much it. Yep. The rest of the game is just medieval.

**Comment by rubenwardy** [comment]
This is on the dev wiki, it's not meant to be read by players
