### ISSUE TITLE
Make keys a separate mod

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1490]
It could use override_node to add on_key_use to doors and chests
It seems that key logic is not actually need in default.can_use_locked_node #1486 as for chests it's done in on_key_use. For doors you'd need to add a callback etc

A few server operators have complained about this

Keys are relatively new. I don't know of any mods that rely on it being default:key

Please vote using :+1: :-1: on this post. Comment any comments :)

@sofar

**Comment by sofar** [comment]
Instead of waving around threats, I'd like to understand the problem that you state.

> A few server operators have complained about this

what is the actual complaint? there are likely many ways to solve this, but making `keys` a mod would force `doors` to depend on it, and it would be a giant kludge to disable keys while retaining `doors`.

I think `minetest.override_item` should be banned from minetest_game, btw. Nothing good can come from registering items, allowing mods to see them in their `init` phase, and then removing them or changing them later.

**Comment by sofar** [comment]
Well, I agree with the idea that this should have been a mod early on, but I didn't see any clean path to doing so when I wrote the code.

I'm not sure I find the criticism listed above reasonable - we have very few items in `minetest_game` that are easily removable - only the ones that are subject to grief abuse. Keys aren't easily grief abusable as is at all. A settings thing for keys is possible, though, even without making it a mod (disable the items, leave the API active).

**Comment by sofar** [comment]
Making this a separate mod would require a new API callback in `has_locked_chest_privilege` to make sure the auth data can be verified.

**Comment by sofar** [comment]
Same for doors.

It seems you want this order to change:

player uses key -> doorchecks including keycheck -> open/close door

to

player uses key -> keycheck -> doors API -> open/close door

the problem with that is that the doors api already does the permission checks for the door. Having permissions checked in 2 layers isn't a good design, but that forces us to make an `permission` hook in there if we want to move keys to a mod. This is the crux of why it is implemented this way. The locked chests use the same design model.

FWIW if we do take this out, we can't just override doors:door_metal since mods may just create all sorts of new metal doors that we want keys to also work on (especially since they've been registered with the doors API to begin with). In other words: making the keys check key privileges before calling the doors API requires mod owners to pass in their own `on_key_use` for every door, even though the template one from the `doors` mod already works.

**Comment by sofar** [comment]
long and short I think it's a bad idea to go ahead with this - I'd much rather prefer a setting to just disable the two key items instead, and leave the entire API and code as is.

**Comment by Ezhh** [comment]
sofar, I'm sorry if you find the criticism harsh or unfair, but others have voiced it as well. I have one server where I'd like to handle locked doors and keys differently, and another where I simply don't want keys at all. If keys were a separate mod, this would be easy. Keys were not present in minetest_game when I made the choice to use it on my server and their inclusion now is one of the things putting me off updating minetest_game any further. 

If there is any way to make them be a separate mod, that would solve some bother. Otherwise an option to simply disable them would be appreciated instead.

**Comment by sofar** [comment]
A setting to disable the items but maintain the API would be 2 lines of code.

**Comment by rubenwardy** [comment]
It's possible to disable the permissions check for doors by passing clicker=nil
so the on_key_use for doors would call doors:toggle() with clicker=nil to force a door open without protection/owner checks

However, a setting may be good enough (although a little ugly in my opinion - but it works and solves the issues)

**Comment by tenplus1** [comment]
If it helps any here is an easy way to disable keys entirely:
```
-- unregister keys
minetest.unregister_item("default:skeleton_key")
minetest.unregister_item("default:key")

**Comment by Fixer-007** [comment]
Keys will get labels in future IMO, after someone adds that ability in engine...

**Comment by paramat** [comment]
@rubenwardy although i don't understand the issues, if this can be done i feel it should, more than one server owner is complaining about it.

**Comment by paramat** [comment]
@rubenwardy this is much requested, is a separation possible?
We could add a setting as suggested in the meantime.

**Comment by jastevenson303** [comment]
What's the complaint?

**Comment by tenplus1** [comment]
Doors already use the default.can_interact_with() function to work and the key is registered inside default/tools.lua and can be easily removed or overwritten.

**Comment by paramat** [comment]
This has the support of 4 devs now.

**Comment by paramat** [comment]
PR #2715
