### ISSUE TITLE
Poll: Growing crops and/or saplings underground?

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1493]
If we make any changes to minetest how plants/trees grow with respect to light levels, we have several choices.

Irregardless of what was previously possible or not in minetest_game, we want to make sure that in the future, it does what we expect it to do in the future, and is consistent.

To state your preference, please use the emoticons to indicate your preference, like or dislike to the options below. The top 8 comments are reserved for the options. If you suggest new options, I can move them up, so please use the word: SUGGESTION at the start of your comment.

Use :smile: for your top pick, :+1: for options you like, and :-1: for options you dislike. You may attach one emoticon per option.

**Poll will close 2017-01-10. Results will be summarized in this entry.**

**Comment by sofar** [comment]
1

**Comment by sofar** [comment]
2

**Comment by sofar** [comment]
3

**Comment by sofar** [comment]
4

**Comment by sofar** [comment]
5

**Comment by sofar** [comment]
6

**Comment by sofar** [comment]
7

**Comment by sofar** [comment]
8

**Comment by sofar** [comment]
Comments go below this one.

**Comment by stujones11** [comment]
2 - Was a bug and would be inconsistent.

3 - Could have wider consequences like things growing where they wouldn't have before.

**Comment by sofar** [comment]
I really dislike (2) as well. I think it will be a kludge to implement properly, since it requires us to check that there is a torch adjacent, and this forces us to do node checks, as well as figure out how to handle non-minetest_game torches.

**Comment by rubenwardy** [comment]
> since it requires us to check that there is a torch adjacent, and this forces us to do node checks

You'd just change default.can_grow, it's only used by saplings in MTG (not sure about external mods)

**Comment by sofar** [comment]
Updated option 2 to reflect we'd just use torch light level adjacent to saplings, not do a node check.

**Comment by Ekdohibs** [comment]
SUGGESTION: allow both saplings and crops to grow when adjacent to torches (i.e. reduce the light level they need to grow by 1)

**Comment by tenplus1** [comment]
Why not add a global flag 'default.grow_light_level' that can be changed if needed via mod, but allows you a minimum light level to grow saplings/crops.

**Comment by rubenwardy** [comment]
> Why not add a global flag 'default.grow_light_level' that can be changed if needed via mod, but allows you a minimum light level to grow saplings/crops.

That's option 1). Changing the light level is possible by mods, at least for saplings

**Comment by sofar** [comment]
@tenplus1 API changes can be made irregardless. This poll is about the game behavior, not about how it's tunable.

**Comment by tenplus1** [comment]
@rubenwardy - exactly, keep current behaviour but have light levels easily configured by mods by using the global variable.

**Comment by sofar** [comment]
@Ekdohibs Added (5). But I note that that's the same as (4) except stuff doesn't grow slower.

**Comment by Ekdohibs** [comment]
@sofar I know that; it is a compromise between (2) and (4), since it doesn't have the inconsistencies between crops & saplings (2) has.

**Comment by C1ffisme** [comment]
I've said it a few times, but since it's difficult to find comments spread across multiple issues, I'll say it again: if farming requires going back to the surface to grow things, then that means that mobile inventories and fast transport become more valuable, and less of a simple luxury.

Going underground needs to be less of a chore, and more of an adventure that requires preparation. The game gets fun when mining is less about finding resources on a checklist, and more of a planned expedition.

**Comment by Zeno-** [comment]
Please note that option number 1 is a bit confusing. The "current" behavior is new to 0.4.15 and not the behavior of previous releases.

**Comment by stujones11** [comment]
I don't think it was ever intentional for for saplings to grow in the dark so any recent changes were in fact bug-fixes, you are complaining that you are no longer able to cheat?

Option 1, whatever it ends up looking like, is the most obvious and least disruptive solution.

**Comment by paramat** [comment]
Please can another option be added? Which is my preferred compromise solution:

6 - Add a setting to MTGame 'plant_growth_required_light' set to the current 13 (light source brighter than torch required) as default. Those who want the old bug behaviour can set it to 12 (growable by torch) and it would be applied to all plants, flowers, grass, crops.

**Comment by sofar** [comment]
I don't think that option needs to be added: The discussion is about the functional working of minetest. If we do 4 or 5 or even 2, we will likely add a configurable option that would allow a light level to be set, effectively allowing people to slide their own servers back to option 1 if they set it to 13.

**Comment by paramat** [comment]
> If we do 4 or 5 or even 2, we will likely add a configurable option that would allow a light level to be set,

This hasn't been made clear, people are more likely to choose a non-1 option if they don't know that a setting may also be added. With a setting option 1 then accomodates those wanting the old behaviour.

**Comment by paramat** [comment]
If you have an election, everyone who wants to stand should be allowed to stand, no one person can decide who is allowed to stand.
As one of the primary people involved in this discussion i obviously should be allowed to have an option of my choosing as part of this.
Mostly though i suggest a poll isn't necessary, the result tends to depend on who saw the thread and who bothered to vote.

**Comment by rubenwardy** [comment]
I feel like this is covered by

> Existing servers can use a mod such as the torches_grow_saplings mod to change this (and keep backwards compat)

**Comment by paramat** [comment]
Hm :) what is covered?

**Comment by paramat** [comment]
Note that you can change your emotivote by selecting your previous emoticon a second time, it will be removed.

**Comment by rubenwardy** [comment]
Allowing server owners to choice whether saplings can grow under torch light levels

**Comment by paramat** [comment]
Ok i see, but that is different to a setting and more trouble because a mod must be used, this will alter how people vote.

**Comment by paramat** [comment]
Please add to 1 that a setting for the required light level will be added, then that counts as my choice of option.
Then please ask people to re-assess their vote, the problem being some may have voted and may not now return to see the new information. So this poll is still of not much significance and is still somewhat invalid.

**Comment by paramat** [comment]
My requests are still being refused, making this poll inherently biased and even less significant.

**Comment by sfan5** [comment]
@paramat 
IMO having a setting is an implementation detail that will be decided later when it comes to implement the chosen solution. Things like <i>this would change the sapling to grow at the light level that torches produce.</i> in option 2 are also unnecessary since they are an implementation detail.

**Comment by fermionic** [comment]
why not just mention the option possibility for number 1? it doesn't take many words and it lets people know the whole situation...what's the big deal?

**Comment by sofar** [comment]
Because adding the config options doesn't clearly show what behavior people would prefer as the `default`. They'd chose `the lesser evil`, and look how the election in the US turned out.

**Comment by paramat** [comment]
@sfan5 refusing to mention settings alters the vote, the use of a setting cannot be ignored at this stage because it is an integral part of the solution. This is a ridiculous technical argument justifying a biased poll.

**Comment by paramat** [comment]
> Irregardless of what was previously possible or not in minetest_game

We cannot disregard how MTG has behaved in the past, it's extremely relevant.

**Comment by paramat** [comment]
> 3 - Allow saplings to grow irregardless of light. Restores something which was possible much earlier (0.4.13 and before).

To be clear, saplings, cactus and papyrus were all missing light checks before a year ago, this has now been fixed.
Throughout the history of MTGame all other plants have required light level 14 (more than a torch) to grow, and if the plants missing light checks had been given light checks in the past they would have been given the requirement of 14 to be consistent with other plants.

Essentially the chosen past behaviour was that plants required level 14 (more than a torch) to grow, as is reasonable.

**Comment by paramat** [comment]
All options in this poll are unsuitable as a solution.

Those (in the minority) who want the old sapling behaviour want to grow saplings, cactus and papyrus by torchlight and have them grow at normal speed.
For consistency all other plants should have the same light requirement.
The current behaviour, which has been the behaviour or intended behaviour throughout MTG's history should be preserved as the default.
None of the options do all of this.
My suggested compromise (which is being refused inclusion in this poll, making the poll invalid) is to have a simple setting 'plant_growth_light_level' set to 13 (current behaviour) by default, which applies to all plants. This keeps everyone happy while also being very simple.

**Comment by Ekdohibs** [comment]
@paramat if you don't want to change anything, I think you should select option 1.
>>> 1 - No Change

**Comment by rubenwardy** [comment]
The reason I support 1) primarily is because I prefer that behaviour for new servers, especially when we add mobs, and older servers can change the behaviour (using a mod) to keep backwards compatibility. Sun lamps being ugly or expensive is another issue

**Comment by Zeno-** [comment]
I'm confused. How is this poll biased?

**Comment by Zeno-** [comment]
@paramat 

> Throughout the history of MTGame all other plants have required light level 14 (more than a torch)

Stop perpetuating this lie. Please.

**Comment by rubenwardy** [comment]
> Stop perpetuating this lie. Please.

This statement is true:

> All plants have always required light level 14 unless they don't/didn't have any light checks at all (such as saplings, cactus, and papyrus)

It's worth noting that the original plants except grass - saplings, cactus, and papyrus - have/had no light checks. It was only made the expectation with farming.

Any changes should be consistent, imo. Requiring different light checks should only be done if logical - say the plant requires less sun in real life

**Comment by Zeno-** [comment]
Saplings did not require light level 14.

**Comment by rubenwardy** [comment]
> unless they don't/didn't have any light checks at all

**Comment by paramat** [comment]
> It's time you recognised that throughout minetest history trees could be grown without the super lamp.

That's exactly what i have been saying. They were missing light checks. Re-read:

> To be clear, saplings, cactus and papyrus were all missing light checks before a year ago, this has now been fixed.
Throughout the history of MTGame all other plants have required light level 14 (more than a torch) to grow,

Your consistent misunderstanding after many many explanatons is bizarre.

**Comment by Ekdohibs** [comment]
@paramat so you think the difference between a mod and a setting is significant, then? If that is so, maybe we could change option 1 so that it would be a setting instead, this it would be very close. @sofar, could you do that please?

**Comment by sofar** [comment]
I removed the mention of `mods` since it's fairly clear that none of the devs would allow an implementation that does not allow that (all the options listed assume mods can override the behavior, in essence)

**Comment by rubenwardy** [comment]
> I removed the mention of mods since it's fairly clear that none of the devs would allow an implementation that does not allow that (all the options listed assume mods can override the behavior, in essence)

I think it is important to note that it will be easy to change with mods

**Comment by sofar** [comment]
```
Irregardless of what was previously possible or not in minetest_game, we want to make sure that in the future, it does what we expect it to do in the future, and is consistent.
```

The intent of this poll, IS, HAS BEEN, and ALWAYS WAS, to determine which game mechanic players prefer, IRREGARDLESS OF MODS AND/OR OPTIONS.

This is why the poll isn't listing all the variations and options. I never assumed, and nobody is assuming, including @paramat, that we will end up with something that provides NO OPTIONS or NO MODDABILITY. In fact, the opposite is entirely certain.

There are more complaints about "this poll is biased" than on slashdot. Of course it's biased, it's a poll. All polls are biased. What we do with the results however can be simple, unbiased and honest, though.

The question was: what behavior do people want?
The answer depends on whether we want to please half the players, the other half, or the odd one hero that wants nothing to grow outside of sunlight (go @wuzzy2!). Or *gasp* please everyone.

I'm not the person who is going to be a dick and write some implementation that pisses off half the devs and half the players. In fact, I'm not inclined to write any PR for this at all. But I've long made up my mind about the implementation I'd like to see, and that is one that allows 99% or even 100% of the players and devs to feel like their option is trivially (without mods) supported, and with minimal settings if it deviates from the default.

And what this poll tells me is that is the right way forward.

And the other most important thing the poll results tells me is that (almost) everyone wants some sort of underground growing to be possible. So that should be likely in the default behavior.

Now, if everyone calms down I might actually work on a PR for this, and then we can discuss the merits of that in the relevant PR thread, using the results of this poll as **one** of the data points in the discussion.

**Comment by paramat** [comment]
Ok i fel a bit better now.

**Comment by paramat** [comment]
This issue started due to those who liked the behaviour before a year ago where saplings had no light check and grew at normal speed at any light level. Although option 4 is popular in this poll (and the one on Github) it does not satisfy those people because saplings will grow much slower in torchlight.
In both polls option 1 is also popular.

If as i suggest we have a simple 'required light' setting for all plants this keeps option 1 voters happy plus those who like the old behaviour, it may also be popular to those who like option 4, it's also simpler.

Sorry for my previous frustration, i'm feeling calmer now and will of course take notice of the poll results.
I still feel my suggestion should have been included, and was refused inclusion for questionable reasons. So all i can do is ask those who like my suggestion to mention their support here in the comments, as some of you have already done.

Although MTGame is only loosely based on reality the requirements for plant growth are fairly realistic, you need fertile (or damp) soil, nearby water in some cases (papyrus), and light. Allowing plants to grow by torchlight is very unrealistic, plants require a special kind of light to grow and if they don't get it they don't grow at all. This has also been the intentional design of the game (apart from the missing light checks) for the last 4 years.

I ask that the MTGame devs realise these points and use their own good judgement to avoid option 4 as the default. The default should continue to be what MTGame has done for 4 years, option 1, then add a setting or parameters for alternative behaviour.

Option 4 is a compromise that doesn't really satisfy either viewpoints in the argument, it's only being seen as good because it's halfway between, it would be a big mistake to make it the default. Better to have options to switch between the popular current behaviour and the requested old behaviour, with current behaviour as default.

**Comment by Zeno-** [comment]
> The default should continue to be what MTGame has done for 4 years, option 1

Option 1 is *not* how the game has worked for the last 4 years. You continue to say I'm confused, paramat, but I think it's you who seem to be confused. Have you actually played the game at some point during the last 4 years?

**Comment by Ezhh** [comment]
paramat... Personally I voted for option 4 because it's what I'd like, not because it's halfway between anything else. 

No one has voted for things to grow with no regard to light, yet by the rules of the poll you can thumb up more than one option. So if people wanted option 3, they'd at least be giving it a thumb up even if not making it their first choice... This means that yes, there are people who want option 4 without wanting either of the extremes.

**Comment by paramat** [comment]
> Option 1 is not how the game has worked for the last 4 years

As i have written elsewhere a few times, i mean that some were missing light checks, but would have required 14 if they had light checks, to be consistent.
Also see a few lines above, i made it clear how i meant this:

>  This has also been the intentional design of the game (apart from the missing light checks) for the last 4 years.

Ezhh you are correct. It's strange that 3 is so unpopular as that was the original request.
I know 4 popular with the voters, when i wrote 'it is being seen as good because it is halfway between' i mean to those who created the poll and the options.

**Comment by Zeno-** [comment]
I don't recall 3 ever being the original request. I remember the original request as being "allow torches to grow saplings and farms"

**Comment by paramat** [comment]
Hm i guess the original request is more 2 or 5 then.

**Comment by Zeno-** [comment]
No, it wasn't 4. I guess it was more like "we want our underground forests and farms back without resorting to mese lamps" :)

**Comment by paramat** [comment]
We can only go by the polls, and 4 is popular witih voters and some MTGame devs.
When options are added on request we tend to keep the current behaviour as default. My preference is that current behaviour is kept as default, then we have options or parameters for whatever else, which will probably include option 4 plus maybe other possibilites too.

**Comment by C1ffisme** [comment]
> This issue started due to those who liked the behaviour before a year ago where saplings had no light check and grew at normal speed at any light level. Although option 4 is popular in this poll (and the one on forum) it does not satisfy those people because saplings will grow much slower in torchlight.

1. The first thing I'd like to point out, in the README file, shown when viewing the Github page for minetest/minetest, it says:

> **This game is not finished**

We warned them. The game is going to change, and **should** change, regardless of what people in the Alpha/Early Release stages of this game have created or done. Progress can't be stopped just because we [broke someone's workflow](http://xkcd.com/1172/).

2. It's game balance. The player shouldn't be able to just make or reproduce required materials everywhere. At the very least, the player should be _suggested_ to set up a base with meselamps rather than throwing dirt, torches and a sapling on the ground. And before anyone has meselamps, it suggests making stairs or minecart tracks up to the surface.

**Comment by Ferk** [comment]
@C1ffisme you supported requiring meselamps and yet you voted as your top pick the 4th option in here, which allows growth by torch. Was that a mistake?

It's already 2017-01-11 anyway, poll was to be closed.
It's not clear whether it's [the forum poll](https://forum.minetest.net/viewtopic.php?f=3&t=16332&start=50&hilit=Growing+crops) or this one the determinant one.. but both seem to point out option 4 as the winner.

At least I hope the growth time is high enough that it's impractical to use normal torches for tree farming underground, to prevent making the game too easy. Option 5 wasn't very popular after all, so I guess most people would rather have it be a lot slower (just like the option indicated).

**Comment by stujones11** [comment]
The forum poll, 53% of all those who voted do not want option 4 but it ultimately for the game developers to decide what happens. @Ferk as I read option 4, plants can grow by ordinary torch light (slowly) instead of requiring a mese-lamp as it is now.

**Comment by Ekdohibs** [comment]
@stujones11 yes, but option 4 is still more popular than option 1.
As a side note, I think addi makes a point in the forum topic: [https://forum.minetest.net/viewtopic.php?f=3&t=16332&start=25#p245885](https://forum.minetest.net/viewtopic.php?f=3&t=16332&start=25#p245885) small constructions that cast a shadow can prevent crops from growing, in cases where one would expect the crops to grow.

**Comment by stujones11** [comment]
True, though think Punk's reply was absolutely spot-on

> It makes more sense to use mods for these unrealistic options.

Or a simple config for that matter, that's all it takes to keep everyone happy without changing a thing.

**Comment by Ferk** [comment]
@stujones11 that's how I read option 4 too, that's why I was discussing the parameters. It would allow plants to grow with ordinary torch light slowly. But how slowly is not really determined yet, nor is the actual value for the minimum lighting (we know it would be lower than 13 but not by how much...).

I assume the minimum lighting value will end up being configurable (maybe even the slowdown curve too?) but I guess there has to be a default value. And I assume the point of the poll was to get an idea on what value range and behavior would people prefer as default.

The democratic choice might not always be the best choice, but at least there will be nobody else to blame than the voters.

**Comment by stujones11** [comment]
I agree that some changes need to be made enable some plants to grow at lower levels, however, I am still strongly opposed to the idea that the light of a flame should should be enough. It de-values mese, making the game totally unrealistic and even less challenging.

**Comment by paramat** [comment]
Devs will make the final decision, but we are taking account of the polls. In both options 1 and 4 are near-equal and far ahead of the others. We're not going to ignore option 1 just because 4 is very slightly more popular. 

The idea was to see which behaviours were most popular, then add options to keep most players happy, so 1 and 4 will probably be the main options and there may be even more configurability for Zeno, VanessaE, hmmmm etc. who liked growing saplings with torches with a normal grow time.

To reduce disruption, when we add new gameplay options, the current behaviour tends to remain as the default, so i insist that 'no change' remains the default, especially since it is near-equal to 4.

**Comment by C1ffisme** [comment]
@Ferk It's a compromise, but it still means that for farming underground to be worth the effort, you still need to work for meselamps. Later on, we could change it so that torches cannot grow trees at all, but for now, it seems pretty balanced.

**Comment by sofar** [comment]
I think we have enough data and feedback in this thread, so I'm inclined to lock and close it.

**Comment by C1ffisme** [comment]
@sofar The results suggest that people are more inclined to either No Change or torches growing trees at a slow (very _very_ slow, depending on balance choices) pace, compared to meselamps. (4 has more likes and top picks than 1, so that might be the winner.)
