### ISSUE TITLE
Include git version and date info somewhere

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1494]
People often use some obscure dev versions of minetest_game (not aligned with engine version) and when it comes bug time, they don't remember exact version or timing.

Any ideas?

**Comment by rubenwardy** [comment]
This is difficult unless you have the git repo to hand, at which point there's no point - they can just do git status

Minetest is different as it's compiled

**Comment by Zeno-** [comment]
You could write a function that creates a hash based on the files in minetest_game. You'd have to try and track down which commit corresponds with which hash (unless someone maintains a list), though.

**Comment by rubenwardy** [comment]
the problem with that is that tiniest of modifications changes the hash. You wouldn't be able to say "this is commit ABCDE with small changes"

**Comment by Zeno-** [comment]
No you'd have to find the commit with the exact same hash.

**Comment by kaeza** [comment]
Couldn't a `pre-commit` hook be used to modify a `version.txt` file or such and add it to the commit?

See [this SO answer](http://stackoverflow.com/a/16832764).

**Comment by rubenwardy** [comment]
that could work

**Comment by paramat** [comment]
Folding #1809 into this.

**Comment by Wuzzy2** [comment]
Evil solution: Delete all bug reports without the exact version or commit number attached. :smiling_imp:

**Comment by paramat** [comment]
Seems a good idea if implementation is simple.

**Comment by paramat** [comment]
Any core dev support?

**Comment by An0n3m0us** [comment]
Hmm, this will be pretty easy, other than the problem of compatibility for Windows and Mac. I did some experimenting and here's what I got:

Firstly, it's _quite_ simple for a user on Linux. Simply add a folder in the repository called `.githooks` or something, then run this command:
`git config core.hooksPath '.githooks/'`
That will set the hooks path locally (which is what we want); not globally.

I followed the code from the SO post above and created this out of it (I stored the file as `.githooks/pre-commit`). (One has to also `chmod +x` the file so that it can be run):
```
#!/bin/sh

version=$(git rev-parse HEAD)
echo $version > version.txt
git add version.txt
echo "Updated version to $version"
exit 0
```

What that does is gets the current commits hash and outputs it into version.txt, either overwriting the previous version that was in there, or creating a new file if required.
It, of course, runs when one uses the `git commit` command.

Here's what happens now when one commits:
```
git add totallynotavirus.sh
git commit -m "Added a script that fixes stuff and doesn't delete your worlds"

Updated version to 3606607d976f2732867f76af826208b0e36b3c19
[githooks 0a2bfc7] Added a script that fixes stuff and doesn't delete your worlds
 2 files changed, 2 insertions(+)
 create mode 100644 totallynotavirus.sh
 create mode 100644 version.txt
```

And here's what `version.txt` looks like now:
`0a2bfc79533ab996a630e965833d0d6b4159735a`

---

Now, there are only two problems with this; one, it seems like each contributer has to set `git config core.hooksPath '.githooks/' so that Git knows where the hooks are. Yes, we could store the hook in `.git/hooks/` but how would we then distribute the file (it's ignored by Git if it's in the `.git` folder)? One would have to download it, set it as an executable and place it in the correct directory.

And two, the compatibility with Windows and Mac; I'm sure there must be an answer to this; especially with such a simple script.

**Comment by An0n3m0us** [comment]
There is a manual way that will work for pretty much anyone; checking the last modified date in a file manager. It will show the date and time of the last modifications and that will (if the person hasn't edited all of the files) correspond to a commit date. (I've collapsed my writing as it got a little large for something so small : ) )

<details><summary>(Click to uncollapse)</summary>

On Linux one can simply open the directory in the terminal and write `ls -altr` to get the last modified date (it will correspond to the date of the commit), or just open the directory in a file manager.
Now, this will only work if one doesn't edit all of the files in that directory as I don't think that it's possible to find the creation date of a file on Linux.

For example, here's an output. `ls -altr` sorts it descending by last date modified:
```
2020-01-25 15:55 game_api.txt
2020-01-25 15:55 game.conf
2020-01-25 15:55 .gitignore
2020-01-25 15:55 LICENSE.txt
2020-01-25 15:55 .luacheckrc
2020-01-25 15:55 menu
2020-01-25 15:55 minetest.conf
2020-01-25 15:55 minetest.conf.example
2020-01-25 15:55 mods
2020-01-25 15:55 schematic_tables.txt
2020-01-25 15:55 screenshot.png
2020-01-25 15:55 settingtypes.txt
2020-01-25 15:55 .travis.yml
2020-01-26 09:18 README.md
```

I'm sure that can be done on Windows and Mac without too much difficulty; even by just using a file manager.

Now one can simply find the commit that corresponds with that date; or, if they clone the mtg repository they can run *`git log --after="2020-01-25 15:55:00" --before="2020-01-25 15:56:00"` to get the commits within that timeframe.

I'm not saying that this is a fix; but it usually works OK ; )

* https://stackoverflow.com/a/19987337

</details>
