### ISSUE TITLE
Documentation and improvements for killme mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1506]
See #1483 
This chat command should be documented somewhere in MTGame, how about a chat_commands.txt document?
It may be good to have /killme work when damage is disabled, for this the engine's 'findspawnpoint' function needs to be accessible through a new API.

**Comment by C1ffisme** [comment]
@paramat I wouldn't really say this chat command warrants a documentation file all on it's own. I would be fine with a `chat_commands.txt` or ingame help, though.

**Comment by paramat** [comment]
The chat commands for sethome etc, could be included in the file, a single file of chat commands would be useful reference.

**Comment by sorcerykid** [comment]
Dare I ask, is there some reason that a single chat command needs to be an entirely independent mod? Why not just include it in default along with a related "spawn" command as well? The functionality for both killme and spawn could be enabled or disabled via a setting in minetest.conf.

**Comment by C1ffisme** [comment]
@sorcerykid @paramat  What about a `servercommands` mod that adds current commands and can contain any future commands? I think that would be better than eight mods devoted to single commands.

**Comment by octacian** [comment]
Well, for one, why don't we move the killme command to default in a file such as `chatcommands.lua`? I'd think it could then be documented in the README.

Personally, I think it should be in builting anyways now since chatcommands can be unregistered with `minetest.unregister_chatcommand`. Maybe not the best though, as it would require existing mods/modpacks that didn't need it to make changes (small, but still).

**Comment by paramat** [comment]
@rubenwardy made it a separate mod because we have been trying to split default into smaller mods, apparently having individual mods makes modding and subgame creation easier. So anything that can reasonably be made a separate mod is added as one.

**Comment by rubenwardy** [comment]
Chat commands don't matter that much, it's mostly nodes and craft chains

**Comment by Wuzzy2** [comment]
Why bother?
Isn't `/help killme` enough documentation? Especially since `/killme` is a super simple command anyways?

In-game help is better than obscure text files which are randomly scattered around various direcories anyways.

:-1: as redundant.

**Comment by paramat** [comment]
Certainly the documentation part of this is low priority, but it bothers me that chat commands are not documented anywhere within the repos of engine and game. The wiki is out of date and separate from the repos.

**Comment by Wuzzy2** [comment]
Well, I might be fine with writing text documents for the more difficult commands which can hardly be explained in a single sentence. I think of the rollback stuff, or `/auth_reload`. I have no idea how these work, and `/help` is not helping.
But I still think the text you see in `/help` is very important and must be of high quality as this text is very important (otherwise, the user can't understand how this command works!). I think this is much more important than external text documents, it is MUCH less convenient to look these up then to simply type in `/help`.

But well, in general I am very much in favor of adding documentation where it actually belongs to. In the game or at least in the repo, and away from the wiki. This is something where Minetest (not just Minetest Game) is still *massively* lacking. But commands are actually one thing where Minetest at least offers *some* help, even in-game. IMO there are much more important things which aren't documented in the repo: Weapons, tools, blocks, gameplay, etc.

**Comment by paramat** [comment]
Certainly /help killme is good, but to do that you need to know of the command iin the first place, it's existence should be documented somewhere in the repo (same goes for engine commands, where other than the wiki do players learn of a commands existence?). Perhaps we can add it to game_api.txt?

**Comment by Wuzzy2** [comment]
:+1: Good point!
But not in `game_api.txt`, this is probably the last file a normal player would look into. I think it should go straight into the readme file, as I think the needed text is very short anyway.

Besides, the current readme is very poor, it does not tell anything about Minetest Game itself which is interesting for the player (esp. gameplay). Currently it's just a bunch of legal and technical yadda-yadda. It's not wrong to have this info, but it should be at the end.

**Comment by paramat** [comment]
Minor issue.
