### ISSUE TITLE
Dyes: Add flowers to enable direct crafting of all basic colours

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1509]
Currently we have 6 flowers providing 'red orange yellow blue violet white' and coal providing 'black'.

I am often aware of how the sequence 'red orange yellow blue violet' is the basic rainbow spectrum colours and is awkwardly missing the fundamental colour 'green' which must be crafted from dye mixing.

I am also aware of how 'black' awkwardly comes from coal instead of a flower.

I suggest that our basic colours are 'red orange yellow green blue violet' plus 'black white' and that all of these should be directly craftable from flowers. So we need flowers for black and green.

Black rose immediately comes to mind, although is extremely rare growing naturally. Black roses have a very strong, dark, mysterious symbolism associated with death, the occult and romance, and are wonderfully gothic and perfect for spooky or sinister uses.

For green a bright lime green would be good, as a normal green would be too dull against all the other greenery around. On a quick search Green Chrysanthemum has a good strong lime green colour.

**Comment by sofar** [comment]
Well, I'm fine with the colors as is.

A green from a plant or cactus would be too convenient, since they're abundant or grow upwards (e.g. papyrus) and I think we should limit the supply at least somewhat, especially for the bright colors.

Incidentally, copper would make a base for green, since copper arsenic is one of the older green pigments used by painters. Might give us a novel use for copper, finally?

**Comment by paramat** [comment]
i agree that my previous idea of green from grass was a mistake becaus grasses are far too common. However arguing that getting a dye from a flower is too easy is strange as that's how we get all other basic colours, and mixing blue and yellow for green is not much of a challenge. Thus will hardly ruin the game by making it too easy.
You seem to have an obsession with avoiding good ideas even if they make the game only insignificantly easier.
The missing green is just down to mod neglect, not having a green flower at the time the dye recipes were created.
More flowers means richer biomes, the colours will be welcome on the landscape.

**Comment by paramat** [comment]
Coal is actually easier to find than a particular colour flower.

**Comment by C1ffisme** [comment]
> Black rose immediately comes to mind, although is extremely rare growing naturally.

What about some kind of withered or evil looking flower? I think people would prefer a magic or alien flower, rather than an obscure, little known flower. (Although we don't have any dark or evil looking biomes, and I think such a flower wouldn't quite fit in a bright green meadow.)

**Comment by sofar** [comment]
Cave roots might be a good idea - relatively simple to add, and we can make them poisonous unless cooked. If you craft them you get the dye? The dungeon generator could place them as a decoration as well on cobblestone, or in caves on stone.

**Comment by JurajVajda** [comment]
Inspiration:
There is a lot of black flowers even a black grass: http://balconygardenweb.com/20-black-flowers-and-plants-to-add-drama-to-your-garden/
..almost for every biome

**Comment by Fixer-007** [comment]
I'm fine with dark from coal and green from cactus. Simple enough.

**Comment by paramat** [comment]
The decoration API cannot place in caves yet.
A black flower will be less easy to find, a particular flower in mgv7 can be 1000+ nodes away, caves are everywhere. Since we have white from a flower i would like black from a flower too. Black roses are much more interesting than cave roots.

**Comment by sofar** [comment]
I wouldn't add a node that provides black dye. We already have coal, and black is only an ingredient to a few other colors (gray/dark green/dark gray/orange?), limiting its usefulness.

The cave root idea was to provide green dye.

**Comment by paramat** [comment]
Coal is hacky, and possibly too common. Black dye is essential for reaching several of the dyes so is as important as any other dye.

**Comment by sofar** [comment]
Well, coal as dye has been around for a while now? Removing things players may have already discovered by themselves, and then replacing it with an item that -on their map may not exist, unless they go far beyond the explored world to get that new flower- is a big problem.

I'd say that's a showstopper: People who have explored their entire map surface won't be able to get your new black flower. Yes, that's unlikely, but it's highly likely that players have explored large areas already, and are unlikely to know that new exploration is required in order to yield something they previously had reasonable access to.

**Comment by paramat** [comment]
I agree, i wouldn't remove dye from coal.

**Comment by tenplus1** [comment]
Definitely add a flower for cyan and we'll have all primary colours for proper mixing.

**Comment by DS-Minetest** [comment]
I think, it's not good to limit the source for a dye to one.
And dye shouldn't be that rare, it's not realistic that people have to search for flowers to eg. color their bed red because they couldn't sleep on uncolored beds.
Flowers don't give that much color, it would be nice to make it out of different rocks, like chalk or brick. Mix the rock (pulverized?) with water and obtain dye. Maybe make the stone drop by chance some extra stuff for dye?
Also, white dye could be craftable from bones?
(And water is blue, right, so, extract the blue dye?)

**Comment by Sokomine** [comment]
Dyes used to be too limited in mtg already. With https://github.com/minetest/minetest_game/commit/df19b4eab0aa1a03e5f70fdeec5097f3387e7e9b it is even no longer possible to craft dyes from coal/cactus by using catalysators - i.e. crafting source dye + target dye into two target dyes. This is bad as it makes dyes far too expensive.
Flowers are a source for dyes - yes. But their main purpose in the game is to decorate the landscape. Players digging ores underground like crazy do not destroy the landscape (there is none) - players digging all plants above do. The surface looks less good with fewer to none flowers.
The "make dyes rare" approach does not take the requirements of people who want to build nice structures into account. If you want rare - go for a big box made out of mese blocks, diamond blocks or rainbow blocks - and be "surprised" that it'll be equally bad as the same box made out of cobble. These rare blocks have textures that only look well in small quanitites.
Dyes, on the other hand, are the basis for many colored blocks. When used well, they can lead to many extremly impressive buildings. Even "simple" colored wool can be used for impressive creations.
But in order to create such impressive buildings, people need dye. *Without* having to destroy the entire landscape around.
If you want absolute hardcore, please choose an appropriate game for that or go to a server that focusses on survival and less on building (e.g. AdventureTest - works very well there; or worlds with many mobs and pvp enabled for those who want to play a shooter).
The purpose mtg has here - on itshelf and as a basis for other games - is to provide dyes as a crafting material. That goal cannot be achieved if dye is too expensive.
I'll open a new issue for a dye catalysator.
More and diffrent flowers are certainly welcome.

**Comment by paramat** [comment]
A problem is that flowers spread very slowly and only up to a low density. They also cannot be farmed using seeds.

**Comment by Wuzzy2** [comment]
If you think coal is too common but don't want to remove coal crafting, you can simply reduce the output from 4 to 1, 2 or 3.

I really like the black rose idea. Maybe the dye yield can be a bit higher than usual (5 or 6) to undo its relative rarity. I don't think the black rose and the coal crafting are mutually exclusive.

I think making green (or dark green) from cactus is fine, either by crafting or cooking, and with a low yield. Or you just invent a fantasy flower or plant which yields green dye. :-)

I would not oppose flowers for the other colors as well, just not as common as the current six. Also, adding some flower variants for dyes which are already craftable might add to the overall game atmosphere. Maybe with higher/lower yields and rarity, or limited to one biome only, etc.

**Comment by AntumDeluge** [comment]
Isn't there also a flower called the black orchid?

**Comment by paramat** [comment]
I've decided to use a black tulip.

**Comment by paramat** [comment]
#1950 merged.

**Comment by JosiHewes** [comment]
lol there is so many variants of flowers here: [bonsaimery.com ](https://bonsaimery.com/) and try focus on [Peacy Lily](https://bonsaimery.com/peace-lily/) its amazing !!
