### ISSUE TITLE
Make burning TNT an entity

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest_game#1514]
Burning TNT should be an entity like a falling node.
This is so tnt cannons could be made. I made a tnt cannon, but I had to repair it every use.

**Comment by paramat** [comment]
Ignited TNT is a falling node and auto-updates to make it fall as an entity when ignited.

**Comment by bigfoot547** [comment]
But then it changes back to a block when it lands. I think it would be cool to have it like in *the other game* Minceraft.

**Comment by DS-Minetest** [comment]
@bigfoot547  The `nuke` mod does with its explosives exactly what you want, right?

**Comment by bigfoot547** [comment]
@DS-Minetest Yes, that is exactly what I want.

**Comment by tobyplowy** [comment]
@bigfoot547 +1

**Comment by sofar** [comment]
It's possible to do this, and the thought had crossed my mind when I added the falling node stuff. Maybe in a future release.

**Comment by octacian** [comment]
A check would also have to be added to TNT nodes so that they wouldn't blow up other nodes if surrounded by water. I don't think it'd be too hard to do, just one of the things that would need to be considered.

**Comment by sofar** [comment]
TNT explodes normally in water, so we should just ignore water sources and explode nodes as normal.

**Comment by paramat** [comment]
Yes i prefer that TNT destroys water just like any other node.

**Comment by DS-Minetest** [comment]
It would be nice if explosions wouldn't destroy nodes with a specific group and furthermore would destroy nothing if the explosion is inside such a node.
Then a mod could easily add a liquid with this group for players that want to build a cannon using explosives. Also some mods have nodes that aren't wanted to be destroyed by an explosion, eg. cloud, the barrier nodes from ctf or every else node that should be indestructible.

**Comment by sofar** [comment]
@DS-Minetest There is already a way to prevent blocks from explosions, and it is documented.

**Comment by jhcole** [comment]
You can already build a reusable cannon based on two existing features. First, take advantage of a falling node colliding with an over-sized collision_box and make the falling node get stuck. This falling node will be the ammo. I like to drop sand on the out stretched edge of a castle:tapestry_top. Second, use a protection mod like [landrush](https://github.com/FozLand/landrush) to protect the cannon and drop a TNT behind the ammo from above.

On a side note, the reason I have the TNT drop is to wipe its owner metadata. This is necessary because I'm using #1070 to allow an owner to blast their own area.  However, due to minetest/minetest#4087 once the TNT falls, the owner meta is wiped and the TNT can no longer damage any protected area.

[VIDEO](https://webmshare.com/KEMQq)

![cannon](https://cloud.githubusercontent.com/assets/1099507/22582445/012eddac-e9b5-11e6-97bf-759a01414371.png)

Also note that another TNT can be used as the ammo in place of the sand for even more interesting results!

**Comment by paramat** [comment]
That's cool, so by using a collisionbox you can keep TNT an entity.
Can this issue be closed then?

**Comment by bigfoot547** [comment]
Wake up and smell the potatoes!
*Sorry, I just had to say that. :laughing:*
My point is that you remove `tnt:tnt_burning` and replace it with an entity, making it so that the tnt will explode in entity form.

**Comment by sofar** [comment]
It can all be done, but it will require modifications to the builtin falling entity (not really that difficult). It's just code that someone needs to write. Just not on my radar now, so someone else should look into it.

**Comment by beyondlimits** [comment]
Chances is it done already? My TNT's are falling!

**Comment by paramat** [comment]
No, the request is for ignited TNT to stay an entity even after it has landed.

**Comment by paramat** [comment]
Any core dev support?

**Comment by sfan5** [comment]
I don't even know why minetest_game needs TNT so I'm very much fine with having it be simple (not an entity) and leaving "complex" things up to mods.

**Comment by paramat** [comment]
^ Closing, see thumbs up.
