### ISSUE TITLE
Include saveschems mod in MTGame repo or in Minetest organisation?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1553]
I mean to store it in a non-running form.
Since it is so essential to the game and shows how to create and edit schematics.

**Comment by MarkuBu** [comment]
How about a txt file in minetest/doc? Or just a link to the repo in lua_api.txt

And you should add an example how to convert a binary schematic to lua

**Comment by sofar** [comment]
not opposed, but I'd prefer it if it somehow ships as 'disabled' so we don't incur the startup penalty of writing 10+ schematic files out.

**Comment by paramat** [comment]
Yes of course.
As a text file example might be ok too, not sure yet what form is best.

**Comment by sofar** [comment]
Maybe this:

- saveschems mod folder
- all the actual code sits in schems.lua
- init.lua has a setting, reads schems.lua if setting enabled

Alternatively:

- we don't ship it with minetest_game
- we ask packagers to include it in their distribution in the `mods` folder instead

**Comment by Wuzzy2** [comment]
No. This is a developer tool. Why should be included in the subgame? The problem is that it will only work with Minetest Game, but not with other subgames (unless they ship it, too).
I understand the importance of this mod and the desire to consolidate developer tools. But not like this.

Idea: Ship `saveschems` as *mod* in Minetest. Meaning, when you install Minetest, you also get this mod in the `mods` directory of Minetest (NOT Minetest Game!). This will be the first standalone mod shipped by default. So it can be activated and deactivated at will and thus works for ALL subgames. :-)

**Comment by C1ffisme** [comment]
`saveschems`, like `minimal`, is a developer tool that shouldn't be packaged by default, except maybe in development versions or in github downloads.

I would like to see this game look a little bit more like a game, which seems to be our goal, and less like a development project.

I would be fine with it shipping with Minetest in the form of a deactivated mod, though.

**Comment by paramat** [comment]
Good point, it's not a subgame thing.
