### ISSUE TITLE
Add 'superuser' privilege

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest_game#1571]
The 'superuser' privilege would finally allow for consolidation of all administrator-specific privileges, essentially forming a middle ground between the 'server' privilege which is operator-scope and 'basic_privs' which is moderator-scope.

Users granted the 'superuser' privilege would have access to administrative commands including /kick and /ban and /unban and /setpassword and /clearpassword, to circumvent protection and ownership checks, to bypass access controls on locked chests and locked doors, and to place tnt and lava and water without restriction anywhere in world. Mods could make use of this privilege to limit functionality to administrators as well (an admin pickaxe for example could check for 'superuser' in its on_use callback).

I addressed this subject to some degree previously: https://github.com/minetest/minetest/issues/4927#issuecomment-271355679

I think adding a new privilege for administrator-only tasks, that is not too descriptive or restrictive (such as the case with 'kick', 'ban', and 'protection bypass'), will improve extensibility and flexibility of the existing role-based security model of Minetest.

**Comment by paramat** [comment]
Maybe "supermod" is more suitable, as it describes someone above moderator but below server admin?

**Comment by rubenwardy** [comment]
I don't like this. Privileges should describe abilities not status

**Comment by DS-Minetest** [comment]
One priv for many different things is not nice. Server owners want to grant only specific abilities.

**Comment by Wuzzy2** [comment]
Yeah, let's just nuke the privilege system altogether! Only 1 privilege: Either you're admin or nothing! xD
So much simpler! It's because Minecraft does itt!!!1!11 xD

OK, for real this time:
Unacceptable is a privilege which basically does the same as a group existing privileges, this creates much redundancy and messes up things. Just one example: If you grant `superuser`, but then revoke `kick`, will the user still have `superuser`?
With the exepction of placing water/lava the privileges you ask for already exist, you just have to grant them one by one:

* `kick`
* `ban`
* `protection_bypass`
* `password`

For water and lava placement, this could be done in a mod by adding a priv for that.

It appears to me that what you really want is a shorthand for a certain set of privs like `kick`, `ban`, etc. This would be acceptable.

PS: Yes, possible close indeed (also because this belongs to Minetest, not Minetest Game).

**Comment by rubenwardy** [comment]
Adding a short hand for granting a set of privs is OK, but not destroying the entire system

**Comment by octacian** [comment]
Yes, IK this has been closed, but I'll throw my opinion in.

Privileges like this which are essentially the same as multiple other privileges are not worth implementing as it would complicate the code so much trying to retain support for both privileges and wouldn't make sense anyways because all the other privileges are typically for specific things.

Now, the solution for this is some type of ranks system like in my servertools mod and bigfoot547's ranks mod.

**Comment by paramat** [comment]
:-1: For this suggestion.
