### ISSUE TITLE
Unable to place signs in some parts of bed

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1578]
Some people may need this for design sakes, here I can't put the signs on the sides of bed, https://i.imgur.com/KG8GUGt.png

18/02/2017 minetest_game

**Comment by rubenwardy** [comment]
Does shift+rightclick not work?

**Comment by Fixer-007** [comment]
nope

**Comment by sofar** [comment]
two-node problem. place the sign against the ground and then rotate it.

**Comment by Wuzzy2** [comment]
A very similar problem applies to doors, too. Sneak-clicking on the side of a door only places the node at the bottom.

This issue wouldn't exist if both nodes could be pointed seperately, instead of only the whole bed at once.
Maybe it wasn't the smartest idea to introduce selection boxes larger than a node.
They look prettier, but they also cause trouble like this.

**Comment by DS-Minetest** [comment]
(The same sort of problem also happens if you want to push the upper side of a door with a mesecons movestone.)

**Comment by paramat** [comment]
Very minor issues, both bed and doors are carefully coded double-nodes, it's not surprising that they don't respond like 2 separate normal nodes. I would not agree with adding code to enable normal placing behaviour against these.
I think this could be closed.

**Comment by sofar** [comment]
I don't know if my minetest_game is special, but I can place signs against the top parts of doors just fine somehow. `mtg` signs,

**Comment by sofar** [comment]
#1584

**Comment by Fixer-007** [comment]
Funny enough 1584 is not helped %)

**Comment by Fixer-007** [comment]
>two-node problem. place the sign against the ground and then rotate it.

Can confirm it helped as of today.
