### ISSUE TITLE
new wood plank textures

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1702]
some new wood textures i made 
(in my opinion these look better than the original)

default_wood
![default_wood](https://cloud.githubusercontent.com/assets/16853304/25071847/b3a03266-22c1-11e7-9e3b-5294a92a6e86.png)
default_aspen_wood
![default_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/25071848/b3a054f8-22c1-11e7-8f5b-a38e8c3b363c.png)
default_pine_wood
![default_pine_wood](https://cloud.githubusercontent.com/assets/16853304/25071850/b3a148f4-22c1-11e7-8091-6d809c5abbf8.png)
default_acacia_wood
![default_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/25071849/b3a155ba-22c1-11e7-863b-55390565b0f2.png)
default_junglewood
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/25071844/a3dac918-22c1-11e7-8c2c-b6e91abde122.png)
![planks](https://cloud.githubusercontent.com/assets/16853304/25071851/ba7d8368-22c1-11e7-94d3-98ba3718fbc3.png)

**Comment by tobyplowy** [comment]
also i wanted to make a pr but i don't have permission to do so :/

**Comment by C1ffisme** [comment]
I actually really like it. Good job! I do feel like the junglewood planks could be just a tad darker, though.

**Comment by tobyplowy** [comment]
@C1ffisme thanks :D

you mean like this
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/25073276/87af6f9c-22e3-11e7-8b8f-81f9de2af238.png)
![wood](https://cloud.githubusercontent.com/assets/16853304/25073277/8bc539e0-22e3-11e7-82f9-4804c77e0c9a.png)

**Comment by sofar** [comment]
artistic commentary: Different wood types have different grains, knots and structure. These are just colored versions of the same structure.

**Comment by tobyplowy** [comment]
@sofar that's a interesting idea I may so that later

**Comment by C1ffisme** [comment]
@sofar The current textures already do this, though...

**Comment by paramat** [comment]
> These are just colored versions of the same structure.

You know this but, current ones are too, so it would not be a problem for me.

In the first post you have pine and aspen labels swapped.

**Comment by tobyplowy** [comment]
> In the first post you have pine and aspen labels swapped.

Fixed Thanks for letting me know!
How did i even over look that :/

**Comment by paramat** [comment]
Will compare carefully, but as they are :-1: due to junglewood being too light. The jungletree trunk was designed to be rosewood, the planks need to be of similar darkness to the trunk core and need to be as dark as rosewood, similar darkness to current textures. The acacia planks seem to be lacking the deep richness of the current texture.

**Comment by tobyplowy** [comment]
@paramat if those things get fixed does this have chance to be added?

**Comment by tobyplowy** [comment]
@paramat is this better?
![rrrr](https://cloud.githubusercontent.com/assets/16853304/25137412/f2a98a06-2457-11e7-831a-215765751c1a.png)

default_wood
![default_wood](https://cloud.githubusercontent.com/assets/16853304/25137448/128e540a-2458-11e7-9a20-a44757ae1549.png)
default_aspen_wood
![default_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/25137447/128a1f02-2458-11e7-8fb3-1ef0f6cb648d.png)
default_pine_wood
![default_pine_wood](https://cloud.githubusercontent.com/assets/16853304/25137445/128505da-2458-11e7-8e4d-b1e15d3a9836.png)
default_acacia_wood
![default_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/25137446/12874b2e-2458-11e7-8c42-cdd6865b8ab0.png)
default_junglewood
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/25137458/19c25c08-2458-11e7-9ed7-60c23dcbc3aa.png)

**Comment by DS-Minetest** [comment]
IMO these wood textures don't fit to the other textures of MTG.

**Comment by tobyplowy** [comment]
@DS-Minetest yeh maybe but the wood textures in the game now Don't Look very good ither

**Comment by DS-Minetest** [comment]
@tobyplowy But better than those IMHO. And they fit to the rest.

**Comment by tobyplowy** [comment]
@DS-Minetest why do they not fit give me some feedback

**Comment by DS-Minetest** [comment]
@tobyplowy Idk, eg. they are a bit soft, they just have another style I think.

**Comment by paramat** [comment]
Above: PR.
Below: current.

![128a1f02-2458-11e7-8fb3-1ef0f6cb648d_128](https://cloud.githubusercontent.com/assets/3686677/25210719/2e4326ea-2579-11e7-9925-6f84afd84896.png)

![default_aspen_wood128](https://cloud.githubusercontent.com/assets/3686677/25210726/338f0de4-2579-11e7-91a5-1352e62d10d3.png)

Aspen. I've noticed aspen wood builds are stunning, the PR texture is lacking the pure whiteness.

![128505da-2458-11e7-8e4d-b1e15d3a9836_128](https://cloud.githubusercontent.com/assets/3686677/25210732/3c396f7a-2579-11e7-936e-2394f47ca7ce.png)

![default_pine_wood128](https://cloud.githubusercontent.com/assets/3686677/25210738/3fe83caa-2579-11e7-96a1-f0b0b246f9a7.png)

Pine. PR texture is slightly brownish and rough / 'dirty' looking.

![128e540a-2458-11e7-9a20-a44757ae1549_128](https://cloud.githubusercontent.com/assets/3686677/25210746/4a105488-2579-11e7-87d8-821c28430072.png)

![default_wood128](https://cloud.githubusercontent.com/assets/3686677/25210750/4d60c46a-2579-11e7-92b0-1ce55e3c9c18.png)

Wood. A change in colour.

![12874b2e-2458-11e7-8c42-cdd6865b8ab0_128](https://cloud.githubusercontent.com/assets/3686677/25210755/50f52e90-2579-11e7-8b69-7db9c804e4eb.png)

![default_acacia_wood128](https://cloud.githubusercontent.com/assets/3686677/25210763/5a35d5f4-2579-11e7-8322-0d9b58688621.png)

Acacia.

![19c25c08-2458-11e7-9ed7-60c23dcbc3aa_128](https://cloud.githubusercontent.com/assets/3686677/25210767/5e01a23a-2579-11e7-9397-3ecfe545f895.png)

![default_junglewood128](https://cloud.githubusercontent.com/assets/3686677/25210771/61e353b2-2579-11e7-8945-2164d7abf70b.png)

Junglewood. Not dark enough.

Generally i find the PR textures lack contrast and have a dry, rough, dirty, curved look, 'soft' is correct.
Our current textures have a flatter, glossy, higher contrast look of smooth treated wood.
A problem with the PR is that our current textures are really good and it would take a lot to better them.
The textures are derived from the wood texture which has had this exact look for 5 years, from since 3 days into the history of MTG, so these are classic textures that have survived because they are so good, and players are used to them.
:-1:

**Comment by tobyplowy** [comment]
@paramat can I try to improve the current textures?

**Comment by paramat** [comment]
Of course, you don't need to ask me for that. What could be improved?

**Comment by tobyplowy** [comment]
@paramat I think some noise wuld look good

**Comment by paramat** [comment]
I don't. The noise of your textures is part of what i don't like: 'rough, dirty'.
When you make textures, please could you enlarge them to 128x128 and post them alongside the current textutres at 128x128?

**Comment by tobyplowy** [comment]
@paramat is this better it has less noise
left is new riht is old
![default_wood](https://cloud.githubusercontent.com/assets/16853304/25238144/e363979e-25ec-11e7-93cc-4ce0451b1463.png)
![default_wood](https://cloud.githubusercontent.com/assets/16853304/25238012/803eaeba-25ec-11e7-93cc-462cc51453ed.png)

**Comment by paramat** [comment]
Ignoring the colour, that still has many of the issues i mentioned: lacks contrast and has a dry, curved look. Why have you now twice suggested exactly what i described as problems? This is just a waste of our time, please stop.

**Comment by tobyplowy** [comment]
@paramat ok sorry

**Comment by C1ffisme** [comment]
> This is just a waste of our time, please stop.

What?

We've had these same, ugly, high contrast textures since 0.4.1, and possibly even further back, and you don't want to try and improve on them?

I'm going to try and address your arguments one at a time:

> Aspen. I've noticed aspen wood builds are stunning, the PR texture is lacking the pure whiteness and looks pinelike.

While you may not think so, decorative blocks like pure white blocks should be expensive, or at least semi-expensive, in order to encourage the player to try and find them, rather than easily farm them and not work for their luxuries.

(Okay, I don't like breaking compatibility either, but this seems pretty minor.)

> Pine. PR texture is slightly brownish and rough / 'dirty' looking.

And... shouldn't it look dirty? You just crafted those boards using your hands. Besides, I bet it would fit a 'makeshift cabin in the cold snowy woods' look.

> Wood. A change in colour, not too different from the pine.

Meh, I can agree with you on this one. It could be just a tad closer to the original color.

> Junglewood. Not dark enough and wrong colour for rosewood.

Does it need to be the same color? Nobody is even going to know, considering it's named 'Jungle Wood'. For the sake of making textures that don't look like an eyesore, I think a little differentiation from realism is okay. (Gameplay>Realism, and Good Graphics>Realism)


> Generally i find the PR textures lack contrast and have a dry, rough, dirty, curved look, 'soft' is correct. Our current textures have a flatter, glossy, higher contrast look of smooth treated wood.

Like I mentioned before, these planks have been crafted with your bare hands. It's a wonder they aren't filled with splinters.

> A problem with the PR is that our current textures are really good and it would take a lot to better them.

That's subjective. I think these textures look much better, and fit the artstyle of most of the other blocks.

> The textures are derived from the wood texture which has had this exact look for 5 years, from since 3 days into the history of MTG, so these are classic textures that have survived because they are so good.

Have they survived because they are so good, or because we're too afraid to look for alternatives? The whole Minetest community, me included (though less about Minetest, and more about other things) is infected by some nostalgia bug, that won't let us drop the old to try on the new. (Or at the very least, it must be over-nostalgic personalities that are attracted to voxel sandbox games? Just a theory.)

> The shading of the panels gives them a curved look that suggests light coming from above, so these will not look so good when rotated upside down as part of slabs and stairs.

This argument is invalid, since lots of blocks with stairs and slabs are shaded this way.
![This is the only image I've used in this entire rant?](https://cloud.githubusercontent.com/assets/9893266/25301519/044354ba-26ef-11e7-8030-71ef70c2859e.png)

Wow... Okay... I'm sorry for this whole, long, rant, but I'm getting sick of arguments like this, that seem to be purely spun from nostalgia or personal taste. And please understand that this:

> This is just a waste of our time, please stop.

Translates to this, over the internet:

> You are wasting our time, get lost.

(And the brain adds in the 'go and commit suicide', 'we hate you', etc.)
