### ISSUE TITLE
new crack anylength

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1705]
a new crack anylength i made
![fe870ad6-25ee-11e7-8bd1-026a8398f666](https://cloud.githubusercontent.com/assets/16853304/25294753/0d271eb2-26e1-11e7-96c7-e6a2bd8cb9cf.png)
![59e03698-25ed-11e7-9685-743b663cf732](https://cloud.githubusercontent.com/assets/16853304/25294754/0d2afe42-26e1-11e7-9699-680668ee2523.png)

5 frames
![waw](https://cloud.githubusercontent.com/assets/16853304/25238960/fe870ad6-25ee-11e7-8bd1-026a8398f666.png)
![crack_anylength](https://cloud.githubusercontent.com/assets/16853304/25238303/59e03698-25ed-11e7-9685-743b663cf732.png)

**Comment by Calinou** [comment]
I don't think the crack animation needs to look different right now, but it definitely needs more frames – it's not smooth enough on slow-to-dig nodes. Minecraft has 10 frames for the crack animation, but we could have even more (Minetest will automatically detect the number of frames based on the texture height).

**Comment by tobyplowy** [comment]
> but it definitely needs more frames

I agree with that!

**Comment by paramat** [comment]
However remember each frame of the crack animation causes a mesh update, with the amount of digging players do this is critical. If anything there should be fewer frames.

**Comment by tobyplowy** [comment]
> However remember each frame of the crack animation causes a mesh update

Is there a way to make this client side instead of server side?

**Comment by paramat** [comment]
So in the first post your texture is the left column and current is the right column?
Could you explain what makes it better?
I think the first frame is a waste because 1-2 pixels is not really noticeable.


![flat](https://cloud.githubusercontent.com/assets/3686677/25291854/9b4f722c-26cb-11e7-85db-b1adae52c236.png)

Note there are no bright pixels so it will not be seen on a dark node.
Otherwise i quite like it, maybe the lower contrast will be less intense.

**Comment by tobyplowy** [comment]
@paramat yes it's the left one 

Why do I think it's better 

The cracks connect into each other that makes it feel more natural (just imagine yourself hitting something over and over until it breaks it won't break from the centre and go into straight lines it will crack and go all over the place and the cracks will connect to each other)

Second it feels like you're doing more damage and that makes it more satisfying :)

> But will it still be visible on all nodes? 

Yes it is visible on all nodes (as far as I know)

> 4 frames would help with mesh updates so i suggest just removing the first frame.

I'm not sure about that but I guess if it improves performance I'm all for it

That's really it

**Comment by tobyplowy** [comment]
> there are no bright pixels as in the current so it will not be seen on a dark node.

Yes I did that on purpose darker textures are mostly shade based so it doesn't need a lot of the detail so your attention gos to highlights
(This is mostly personal taste) 
do you whant me to add a highlight?

**Comment by paramat** [comment]
Actually i realised bright pixels are probably not needed because the grey will be seen. So it's probably ok as it is (with preferably 4 frames).

**Comment by tobyplowy** [comment]
@paramat so do I just resze the image that's it nothing more?

**Comment by paramat** [comment]
All i ask is to remove the first frame, but keep the original too in case other devs insist on all 5 frames.

**Comment by tobyplowy** [comment]
@paramat i updated the first post

**Comment by sofar** [comment]
The amount of frames needed should be dictated by the longest dig time. Some things, especially in mods, can take 3 - 5 seconds to dig. I'd think it's weird to go to 5 frames, I know the mesh is updated every frame, but having no frame updates for 1.0 second isn't a way to make the game more performing, it's just not the same scale performance wise as emerging 500 blocks when walking around a bit.

So, for me it can stay at 8+ frames easily. I wouldn't mind seeing 12 or even 16 frames.

**Comment by paramat** [comment]
Yes it's rate of crack changes that matters with the mesh update issue.
The current crack texture has 5 frames.
The mesh update issue is significant, an issue was opened for it showing CPU load spikes during digging, obviously if a tool is powerful those 5 frames are occuring in rapid succession constantly during the mining of many nodes and the 5 frames are running too fast to be useful.
RBA was very concerned about this too and made a PR to make the crack optional.
So if we can make crack frame rate more constant we can then have more frames, but not until then.

**Comment by paramat** [comment]
I find the current crack ugly, it's too high contrast, i'll try this one in-game.

**Comment by tobyplowy** [comment]
@paramat I agree 

That's why I made this issue :)

**Comment by VanessaE** [comment]
:-1:  fewer frames is bad, and it does not address the underlying issue of mesh updates.

**Comment by kahrl** [comment]
Changing the crack animation frame does NOT cause a mesh update (at least not in the sense of creating a whole mesh for a mapblock, which is what I believe everyone here is referring to). Only the first frame (starting to dig) and removing the crack (stopping to dig) does, as well as switching to a different node. The relevant function is Client::setCrack().

To change the crack animation frame, only the material of the existing mapblock mesh is updated. This takes pretty much no time at all. See the first part of MapBlockMesh::animate().

If anyone does not believe me and wants to test this in-game, here's how:
1. In games/minimal/default/init.lua, in register_item(":"), change line 1837 to
``crumbly = {times={[2]=60.00, [3]=60.00}, uses=0, maxlevel=1},``
Dirt will now take 60 seconds to dig with the hand, which makes it possible to use the in-game profiler to verify that no mesh updates happen when the crack frame changes. (the profiler only updates every 5 seconds)
2. Start up a new minimal world.
3. Set the viewing distance really small (e.g. 20) so that no far-away mesh updates will mess with the measurements.
4. Look around you to make sure all the meshes in the viewing range have been generated.
5. Open the profiler with F6 and wait until "Client: Mesh making" settles at 0.
6. Start digging a dirt node with your hand. You'll see that starting to dig causes a mesh update ("Client: Mesh making" goes up a little), but further updates to the crack animation will not -- "Client: Mesh making" will remain at 0.

**Comment by paramat** [comment]
Thanks for the clarification, i'm happy i was wrong. Perhaps RBA meant that starting and finishing the crack animation caused mesh updates, and i misunderstood.

**Comment by paramat** [comment]
So, we could perhaps go up to 8 frames? Since most nodes are dug very quickly 16 seems too much, it would be excessively rapid.

**Comment by tobyplowy** [comment]
@paramat yes i also think 8 frames will do the job just fine
![crack big](https://cloud.githubusercontent.com/assets/16853304/26068231/230e736e-399d-11e7-8e80-345a9d64fa87.png)
![crack](https://cloud.githubusercontent.com/assets/16853304/26068230/230ace44-399d-11e7-97af-f9092ae976df.png)

**Comment by paramat** [comment]
Nice.

**Comment by paramat** [comment]
![screenshot_20170518_112627](https://cloud.githubusercontent.com/assets/3686677/26198151/e91f44ea-3bbc-11e7-897c-c394c08e21e4.png)

It's not visible on coalblock and not very visible on stone, because it is so grey, if it had more contrast it would be good. The pattern of cracks and how they grow is good but there is a reversal of 'crackiness' in one area from frame 4 to 5.

**Comment by tobyplowy** [comment]
@paramat is this better? it fixes the frames and also the black is darker
![crack big](https://cloud.githubusercontent.com/assets/16853304/26204255/7c536f40-3bde-11e7-8910-2162cd8fd1c5.png)
![crack](https://cloud.githubusercontent.com/assets/16853304/26204256/7c57d364-3bde-11e7-9cc0-df9632e48a96.png)

**Comment by tobyplowy** [comment]
@paramat i added some white to this one and id say this gives the best resolts
![crack](https://cloud.githubusercontent.com/assets/16853304/26204653/a9d03fc4-3bdf-11e7-9ba2-4598976429bc.png)

clay
![crack big](https://cloud.githubusercontent.com/assets/16853304/26204603/893b073a-3bdf-11e7-8153-6689d4688fe8.png)
stone
![crack big - kopie](https://cloud.githubusercontent.com/assets/16853304/26204604/893af024-3bdf-11e7-8f5d-ff692a9f3fd1.png)
obsidian
![crack big - kopie 2](https://cloud.githubusercontent.com/assets/16853304/26204602/893a4386-3bdf-11e7-865f-3fac874340c8.png)

**Comment by tobyplowy** [comment]
@paramat is the above texture good or does it need to be Changed More?

**Comment by paramat** [comment]
I tried it but the cracks seem too wide now, as you can see on the obsidian above, it's a big mess of grey. It's also too grey and the more outward cracks are not visible on stone.

**Comment by tobyplowy** [comment]
@paramat ok I will see what I can do (NOTE I can't make it look good on light and dark textures at the same time)

**Comment by tobyplowy** [comment]
@paramat im not sure if this is better

![893b073a-3bdf-11e7-8153-6689d4688fe8](https://cloud.githubusercontent.com/assets/16853304/26730846/8fd5e8e2-47b2-11e7-9307-1a9f06cadea4.png)
![893af024-3bdf-11e7-8f5d-ff692a9f3fd1](https://cloud.githubusercontent.com/assets/16853304/26730845/8fd2ed2c-47b2-11e7-9e2a-39382cfd0eb2.png)
![893a4386-3bdf-11e7-865f-3fac874340c8](https://cloud.githubusercontent.com/assets/16853304/26730847/8fd8be96-47b2-11e7-8af5-a9fa2382b452.png)
![a9d03fc4-3bdf-11e7-9ba2-4598976429bc](https://cloud.githubusercontent.com/assets/16853304/26730866/9d2f4e84-47b2-11e7-8f56-cd122a299b1a.png)

**Comment by tobyplowy** [comment]
@paramat i finally did it i made a PR https://github.com/minetest/minetest_game/pull/1796
