### ISSUE TITLE
Axes and Hoes have two recipes

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest_game#1752]
I recently noticed that axes and hoes have recipes in mirrored directions,
XXO   XXO
XIO    IXO
OIO    IOO

where X is the material, O is blank and I is a stick. Should we consider removing one of the recipes.

**Comment by SmallJoker** [comment]
I believe this was added because the other tools (sword, shovel and pickaxe) all have symmetrical craft recipes. Perhaps it's sometimes helpful that it doesn't matter in which way you put the materials. Our 3x3 grid allows many various combinations, thus a few more or less taken by the subgame doesn't hurt.

**Comment by paramat** [comment]
I support removing one recipe. In MT generally there will be many non-symmetrical recipes, doubling the recipes for all of these would is excessive. Doubled recipes add lines to code and cause very slight performance loss.

**Comment by paramat** [comment]
#1777 merged.
