### ISSUE TITLE
Gun powder trails burn diagonally

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1754]
The burning rules of gunpowder doesn't match the appearance of the gunpowder trails. That means, the “burning” of the gunpowder does not exactly follow the trail.

Specifically, burning gunpowder ignites stuff diagonally, although there is no visible connection between diagonally-aligned gunpowder nodes.

Example, viewed from above:

    x.
    .X

* `X` = burning gunpowder
* `x` = non-burning gunpowder
* `.` = air

X ignites x although there is no visual connection. X should only burn up but not ignite anything.

Another example:

    x..
    x..
    xxX

Expected behaviour here would be that the burning follows the trail exactly. But at the second node, it gets messy (just try it out).

I think gunpowder rules should be changed in order to match visuals. This means, a burning gunpowder node is only allowed to ignite immediate neighbors excluding diagonals.

Tested in 0.4.15.

**Comment by paramat** [comment]
:+1: good idea.

**Comment by Ferk** [comment]
The connected visuals are probably calculated client-side though, I don't think the orientation is stored in param2 or anything like that, so if you really want to trigger the ``tnt.burn`` only for the connected nodes you still have to check the nodes around the gunpowder anyway to see if they are connectable.

It's probably simpler to just skip the diagonals in the XZ plane but keep the current logic that doesn't check if the node is really connected.

Diagonals in the XY and ZY planes (side views) should still be used so that gunpowder propagates on slopes both uphill and downhill, though.

Still this would reduce the number of calls from 24 to 12

**Comment by paramat** [comment]
^ I agree.

**Comment by paramat** [comment]
@Wuzzy2 simple to code this, could you make a PR?

**Comment by Wuzzy2** [comment]
Nope.

**Comment by paramat** [comment]
#1857 merged.
