### ISSUE TITLE
Quartz ore

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#1756]
I think that since there's silver sand now, quartz ore should probably be added as well. Silver sand contains quartz:
> Silver sand is a fine white sand used in gardening. It consists largely of quartz particles that are not coated with iron oxides.

**Comment by paramat** [comment]
Silver sand is intended to be a breakdown of silver sandstone or grey stone or gravel, so there is no strong link to quartz.
However, once we have underground decorations we could possibly have giant quartz crystals in caves to be a little different to MC.

**Comment by Yzelast** [comment]
There will be underground decorations? Maybe some kind of underground biome could be easily created with it. 
Furthermore i wanna ask if wold be difficult to implement some underground modifiers to the biome register function like: 
- a layer(with custom depth) of nodes around underground water and lava, 
- nodes around the biome stone

**Comment by paramat** [comment]
Nodes around cave liquids is difficult because immediately after mapgen only the source nodes exist, they flow out after mapgen, so the effect would not be what you want., Seems low priority too.
However the decoration API might be able to place decorations on the liquid surface.

The underground decrations i plan will be able to place decorations either above or below the specified 'place on' node, together this allows covering a large amount of cave surface.

**Comment by paramat** [comment]
Quartz crystals in caves yes, i will add an underground decoration API.
Quartz ore, no.

**Comment by C1ffisme** [comment]
Please no. Not after we've already added one useless metal to the game. (And don't even point out that tin can be used for decoration or a higher tier material, because you could say that about almost everything in the game at this point.)

**Comment by tacotexmex** [comment]
Underground decoration API, please yes.

**Comment by paramat** [comment]
Well, quartz crystals in caves is a maybe, we'll decide on underground decorations later.
Quartz ore is a definate no, becuase it is best in crystal form and because it is too much of an MC copy.
