### ISSUE TITLE
Redo MTG for 0.5

### ISSUE THREAD

**Issue by XtremeHacker** [minetest/minetest_game#1798]
Minetest Game needs help, the default mod is quite bloated, there are backwards compatibility measures that are most likely not need, a fresh, more community driven sub game would be nice.
Please share your opinions. :)

**Comment by C1ffisme** [comment]
There is discussion about seperating MTG into two parts (a modding base and a game) and I think 0.5.0 might be the time to do this.

Considering that we've done this with 0.3.X, I think we should remove minimal and replace it with a toned down version of MTG for 0.4.X. (Possibly looking something like Minetest Game from 0.4.1?)

I also think lots of texture overhauls might be nice, although we've done a lot of that in 0.4.10. (Maybe save it for 0.5.1?)

\</daydreams\>

**Comment by paramat** [comment]
Too much depends on MTG to make big changes, what is needed is new subgames, there are many discussions about this already, a fresh start new mod base would be good plus new more exciting, more complete subgames that impress without needing mods.
MTG will likely just be maintained from now on with some minor additions.
Some core devs might be writing new subgames, but overall we are extremely understaffed. However, subgames written by non-core-devs are welcome as long as the quality is as high as MTG.

Since this is another duplicate, closing, please discuss in the other threads about the future of MTG.

**Comment by Iniquitatis** [comment]
@paramat, isn't it normal to break backwards compatibility at the alpha stage of software development process?
