### ISSUE TITLE
Add tree species to descriptions for appletree and jungletree

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1817]
No change to node technical names though.

Normal wood is obviously an appletree (which is a fairly specific species or tree family), and i carefully made jungletree log top textures to appear like Rosewood trees, so i suggest using 'Apple' and 'Rosewood' for trees and all wood-related descriptions such as planks, fences, doors etc.

@Ezhh may be interested.

**Comment by Ezhh** [comment]
I'd be against "Rosewood", because I  worry people won't know what rosewood is, and it could be confusing. Keeping to simple and very well known tree/wood types is likely best.

For adjusting the generic tree description to "Apple Tree", the only issue is that not all generic trees have apples, but I think that's fine. It also seems odd for a world to have so many apple trees, but maybe that's an excuse to convince you to add more types of tree to MTG anyway. :)

(Hint: I really would love to see more types of trees/grass/plants in MTG and would gladly help with that)

**Comment by paramat** [comment]
Apple tree is a fairly specific species, since all other trees are fairly specific species i feel all should be.
Rosewood is a well known wood, as any gutarist knows fretboards are made from this. It's no less obscure than aspen.
Here i am not concerned with keeping our current 'wood' a generic node, or 'jungletree' a generic rainforest tree. Mods will have to start registering their own nodes, which is a good thing to do anyway.

**Comment by Ezhh** [comment]
But why is rosewood needed? Jungle tree / jungle wood, Aspen / aspen wood,  Acacia / acacia wood.
...Apple tree / rosewood? This doesn't follow on from all the others.

To be consistent, it would either be Apple tree / apple wood or rosewood tree / rosewood (or rosewood wood?? the inclusion of wood in the name doesn't help).

**Comment by paramat** [comment]
Yes sorry, rosewood is the jungletree.

**Comment by Ezhh** [comment]
Okay, sorry for the confusion. 

Would there be any alternatives for jungle trees which don't have wood in the name?

**Comment by paramat** [comment]
The log also looks like Wenge but our jungletree doesn't have the shape of a Wenge tree, so not really.
I don't think that's a problem, we can use 'Rosewood Tree' and then 'Rosewood Planks', 'Rosewood Fence' etc. Obviously we need to avoid 'Rosewood Wood ..'.

**Comment by paramat** [comment]
When i redesigned the jungletree top texture (which took a huge amount of time and several attempts), i decided to work out what the species was from the wood colour and the tree shape (non-mgv6 tree shape). As a perfectionist i spent maybe 8 hours over several days researching rainforest trees and Rosewood was the one, so it's certainly Rosewood whether we describe that or not.

I'm not concerned with the suggestd confusion between the 'jungletree' nodename and the 'Rosewood' description, as this is just like 'tree' and 'Appletree' in being a very unspecific nodename plus a species in the description:
"it's a tree, specifically an appletree"
"it's a jungle tree, specifically a Rosewood tree"

**Comment by Ezhh** [comment]
You can also say "it's a tree, specifically a jungle tree".  Unless you decide to subdivide this further by actually adding more types of jungle tree to MT so that they need specific names, it's really a non-issue.

Node name will also still include jungle, so there's another layer of potential confusion there. Letting the name include something the description does not have is a different (potentially confusing) issue than having descriptions which are more specific than the name.

Just my opinion though. I'll let you decide what you want to do, but my goal with working on descriptions was to remove, not increase, possible confusion.

**Comment by paramat** [comment]
We could do appletree / applewood first in a separate PR, if devs consider Rosewood controversial.

**Comment by Ezhh** [comment]
I don't have any issues with apple tree. and would support that PR (or make it if you prefer). 

I doubt a description is going to be judged controversial either way (there are so many more important things to worry about), but I really hope you don't change jungle trees to rosewood.

**Comment by paramat** [comment]
Yes please a PR for Apple Tree / Wood would be welcome.

**Comment by DS-Minetest** [comment]
IMO renaming junglewood to rosewood is more personable than changing tree to appletree. I don't know any mod that adds another rosewood tree but eg. moretrees adds an apple tree.

**Comment by paramat** [comment]
The wooden door can be crafted from any wood so i guess should remain generic.

**Comment by Ezhh** [comment]
I mentioned (outside the comments here) that mods add apple tress as well, but I don't think MTG should make decisions based on what mods add.

**Comment by paramat** [comment]
I agree, what mods do is irrelevant, and our trees are obviously apple trees :].

**Comment by DS-Minetest** [comment]
I just wanted to give reasons to change junglewood to rosewood.
Also the jungletree is as much a rosewood tree as the tree is an apple tree.

**Comment by TumeniNodes** [comment]
Sorry to butt in,
would there be an issue to moving apple tree into the farming mod?
and replace the generic tree with something such as Maple? (and make it as high as the Aspens?)
I like the idea of Rosewood trees.

**Comment by paramat** [comment]
We can't do that.

**Comment by paramat** [comment]
Mostly done by #1834
