### ISSUE TITLE
player model sink to the floor

### ISSUE THREAD

**Issue by JurajVajda** [minetest/minetest_game#1837]
`Minetest 0.4.16-dev (Linux)`
`Using Irrlicht 1.8.4`
`build: 201707210702-0~49920cf~ubuntu17.04.1`

After recent update of the player model, visually from outside the model sink to the floor. Is this a known issue or is there something to fix this ?

![screenshot_20170722_002811-min](https://user-images.githubusercontent.com/5089392/28484996-71bfef66-6e76-11e7-846b-725fe56e0547.jpg)
![screenshot_20170722_002846-min](https://user-images.githubusercontent.com/5089392/28484995-71beb484-6e76-11e7-9bf1-b42ff9f6903c.jpg)

**Comment by octacian** [comment]
This is a feature, caused by a recent commit to Minetest (https://github.com/minetest/minetest/pull/6007). It is one of the several new upcoming features that will be considered breaking features. The only way to "fix" this (I say "fix" as it's not really a bug) is to update MTG. If you're playing on a server that can't safely run on a development version of Minetest game, then your best solution is to downgrade your client.

**Comment by JurajVajda** [comment]
@octacian awesome,thanks for the info.
CLOSING this issue due to: Not a bug

**Comment by lhofhansl** [comment]
Note that this will require certain mods to be adjusted as well.
One example in playeranim, the other is MineClone2 (which provides its own player model, which is now offset by one)

**Comment by JurajVajda** [comment]
good to know, also good that im following minetest default game with very little mods ;)

**Comment by verymilan** [comment]
Just in case someone finds their way to this issue these day's, don't forget to update 3d_armor as well. :)
