### ISSUE TITLE
[Idea] ore/fluid/item dictionary

### ISSUE THREAD

**Issue by MisterXtreme** [minetest/minetest_game#1887]
The idea is that for all ores, fluids, the like, and recipes using them, use a group, instead of the item name.

I.e. group for iron would be ore_iron, and that group would be used in all recipes using it, thus allowing mods to have inter-game recipes, and avoid conficts with two mods registering the same thing.

I would be willing to make a PR for it if that is OK, so it would be no workload on core devs.

**Comment by DS-Minetest** [comment]
>I.e. group for iron would be oreIron

[Lua code style guidelines](http://dev.minetest.net/Lua_code_style_guidelines#Naming) want lowercase_underscore_style.

**Comment by MisterXtreme** [comment]
OK, I'll change that, what about the idea, are there any issues that I missed?

**Comment by tenplus1** [comment]
Please give more examples of this please ? am trying to understand the change.

**Comment by paramat** [comment]
This would result in too many groups, hundreds, and groups are there to be groups not individual items.
There's also not much need :-1:

**Comment by tenplus1** [comment]
Good point paramat.

**Comment by MisterXtreme** [comment]
I was going to ask if we could add a system for this, but thought that is what groups are for?

**Comment by MisterXtreme** [comment]
So, the idea was to help with recipe conflicts, and that can happen as we get more mods, the fact that this hasn't happened yet is not a good excuse

I didn't know that using groups this way was "hackish".

"The thread title is mis-leading, it has nothing to do with a dictionary"

Definition of dictionary
plural dictionaries
1
:  a reference source in print or electronic form containing words usually alphabetically arranged along with information about their forms, pronunciations, functions, etymologies, meanings, and syntactic and idiomatic uses
2
:  a reference book listing alphabetically terms or names important to a particular subject or activity along with discussion of their meanings and applications
3
:  a reference book listing alphabetically the words of one language and showing their meanings or translations in another language
**4
:  a computerized list (as of items of data or words) used for reference (as for information retrieval or word processing)**

"There's also not much need. Interesting idea but is a hacky abuse of groups, _we_ simply cannot do this :-1:"

From the original post:
"I would be willing to make a PR for it if that is OK, so it would be no workload on core devs."

**Comment by C1ffisme** [comment]
Clearly people are misinformed.

Minecraft Forge, the most common mod API for Minecraft, uses an ore dictionary. This is because multiple mods register the same Copper, Tin, Aluminum, Uranium ores so that they don't have to depend on an "ores" mod that could stop being updated at some point.

The Ore Dictionary allows items with the same tags to be used the same way in certain crafting recipes. For example, two Copper Ingots from two different mods that are both tagged "copperIngot" can both be used in a recipe that requires a "copperIngot".

This is useful in Minetest, because it means a mod like Technic can register it's own ores without having to depend on a mod like moreores, but if moreores is installed, the ingots and such will still work in moreores recipes and moreores items will work in Technic recipes.

This could also be useful if you are making a mod for multiple subgames, because you can register certain ores that one subgame already has that another subgame doesn't, but the all the recipes will be compatible.

Item groups actually seem to be _exactly_ the right place to do this kind of thing, because we already do the same thing with recipes that require wood, stone or other items that have multiple variants.

**Comment by rubenwardy** [comment]
The food mod does this by overriding items: https://github.com/rubenwardy/food/blob/master/food_basic/support.lua#L15

**Comment by paramat** [comment]
> Minecraft Forge, the most common mod API for Minecraft, uses an ore dictionary

Ok that must be the source of using the term 'dictionary', but not everyone has a deep knowledge of MC.
'Dictionary' is a very vague term for this feature, a more descriptive thread title would be 'Add a group for every item'. 'Dictionary' has nothing to do with making a group for every item, it only makes sense if you have a deep knowledge of MC.

> we simply cannot do this

By 'we cannot do this' i mean this can't be allowed, we cannot merge this, it doesn't matter who codes it.

**Comment by MisterXtreme** [comment]
OK, I will admit, the title is a bit vague, and has been changed
As for adding a group for every item, that was not the idea, it would only be for ores, fluids, and _perhaps_ other items on a case-by-case basis.
Is that still hacky abuse, and if so, then how _exactly_ is it abuse, as there would not be tons of groups, and is the similar to how we have all the wood in a wood group, their only difference is cosmetic, but they have a group for recipe reasons.

I'm not trying to start a flame war, just wanting to see opinions on the idea, and what is wrong with it, and what is right.

**Comment by C1ffisme** [comment]
I should also note that a fluid dictionary is only really necessary when we have pipes and tanks, otherwise bucket items can receive dictionary entries.

**Comment by MisterXtreme** [comment]
That is true, fluids probably isn't much of a big deal with how we only have 3 fluids, that would all not be duplicated for any good reason.
