### ISSUE TITLE
(discussion) Texture inconsistencies and improvements

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1913]
First i would like to tell that i know The minetest game textures are made by Different People and yes they do it for free ok now that that's out of the way let's begin

So minetest game has a lot of Different textures for a lot of different things that are made by different poeple so Naturally there's gonna be some inconsistencies

SO you may ask what are these ''inconsistencies'' 
Well take for example the tree top textures you have default tree, aspen, and pine ok everything looks consistent and than you add jungle and Acacia and those are not consistent why? 

Next is color minetest has very high contrast (painfully high) this needs to be addressed becouse it turns people off (please don't say anything about texturepacks if I don't like the default) 
How can this be fixed well you can make the textures brighter and turn down the contrast a bit

Next is the menu loading bar why does it look so cartoony?
Don't get me wrong it looks really good but in my opinion it looks a bit out of place maybe making it less bright and making it have less Contrast will help

My next problem is the wood plank textures they are too simple there just some dark lines some bright lines and a bace color 
How can it be inproved maybe adding a bit of noise wuld help

And last I think some textures have meh colors 
Like stone (too dark) and dirt (again too dark)

This issue will probably be closed in acopple of days becouse it's ''unproductive'' but if everyone wuld consider this that would help out the minetest community by making mt more appealing I only whant the best for Mt so thanks for reading and have a good day :)

Give me your opinions
PLEASE BE OPEN MINDED!!!

**Comment by tobyplowy** [comment]
Also I'm willing to help with whatever gets told here

**Comment by paramat** [comment]
The consistency discussion has been had before, it's not practical to have one person or a small team making all MT textures because in PRs the author needs to be able to provide their own texture, waiting on one person or a small team for every texture will slow down dev and make it more complex. Also, the PR author may want to create the texture themselves, we already judge submitted textures for their consistency. 

> Well take for example the tree top textures you have default tree, aspen, and pine ok everything looks consistent and than you add jungle and Acacia and those are not consistent why?

Because a jungle tree is not tree, aspen or pine. Acacia is consistent, it's just a recolour of the others (i made the texture).

> Next is color minetest has very high contrast (painfully high) this needs to be addressed becouse it turns people off

Contrast is not colour. MT textures do not have painfully high contrast, it's your eyes, some find the textures to be washed out.

> please don't say anything about texturepacks if I don't like the default

Use a texture pack, that's what they're for, different people have different tastes and you're trying to enforce them on everyone.

> Next is the menu loading bar why does it look so cartoony?

It's lofi because MT is, it's not out of place, besides, you like it.

> My next problem is the wood plank textures they are too simple 

MT textures are often simple with a small palette, if you can improve them submit textures, discussing them won't change them.

> And last I think some textures have meh colors
Like stone (too dark) and dirt (again too dark)

These are just your personal tastes, why not submit textures? Stone is a fundamental classic texture that many are used to, it would take a lot to change it.

> This issue will probably be closed in acopple of days becouse it's ''unproductive''

It's not a good sign that you consider your own issue possibly unreasonable, and some of it is. Most of this is you stating your own tastes, those are irrelevant, everyone has different tastes.

I edited your shouting font size.

///////////////

Essentially, concerning consistency, we all know the default pack is a little inconsistent, however such a pack made by the individual PR authors or those asked and willing at the time is very useful for dev. So it's not great but it's necessary.
Consistent texture packs of higher quality, made by 1 person or a small group are what texture packs are for.
We could even release MTGame with a special consistent pack set as the default and just use the current 'default' pack during dev.

For this topic, please try to avoid endless bikeshedding and personal tastes with no-one actually doing anything.

**Comment by tobyplowy** [comment]
> it's not practical to have one person or a small team making all MT textures

I never said anything about 1 person making textures I just sayd that there is more than 1 person that makes textures for mt in fact I think it's better this way (working together is good)

> So have you started work on a complete consistent texturepack?

No but if you think it would be a good idea than I would yeh 
(is there a chance the edits can end up in bace minetest game?)

> We could even release MTGame with a special consistent pack set as the default and just use the current 'default' pack during dev.

I think your making a joke but I do think it's a interesting if not good idea

> with no-one actually doing anything. 

I think I was pretty clear when I sayd Also im willing to help with whatever gets told here

**Comment by paramat** [comment]
No not joking =)
Sorry for being grumpy, we had a texture consistency discussion before that irritated me.

I think i misunderstood the issue a little, sorry, you're not really suggesting a new consistent pack, but pointing out what you feel is particularly inconsistent or needs improving in the default textures.
Problem is this is very subjective and down to personal taste, each person would have a different opinion of which textures seem wrong.
Pointing out certain textures won't make anyone start work on them, people will work on what they want to work on, which are likely to be different textures because they have different tastes.
Discussion is pointless, all you can do is create and submit textures.

**Comment by tobyplowy** [comment]
> Sorry for being grumpy, 

Nah don't worry it happens to us all

> all you can do is create and submit textures.

Yup will do

Also how can I help minetest becouse I really want to but it's extremely hard I have tried alot (keep in mind that I can't program)

Also feel free to use @tobyplowy if you need any textures I'm more than happy to help :)
