### ISSUE TITLE
Eating food causes punching of pointed block

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1938]
This was known for ages, is there any reasons for that or it is plain gameplay bug?

**Comment by TekhnaeRaav** [comment]
Forgive me for my ignorance, but what is a pointed block?

**Comment by kingoscargames** [comment]
> Forgive me for my ignorance, but what is a pointed block?

The block that is pointed at.

**Comment by DS-Minetest** [comment]
You can't point a whole block. Probably node is meant with block.

**Comment by paramat** [comment]
Possibly an engine/builtin issue.

**Comment by Ferk** [comment]
Eating (or left clicking with any usable item, like the how) does not trigger any punches. I've verified it just now.

What I have observed is that if you eat the food until it disappears, the hand quickly appears and you are almost guaranteed to punch the block in front of you, since there's no input delay when you switch from having food to using your hand.

**Comment by paramat** [comment]
Ok non-issue then, move delay discussion to engine.
