### ISSUE TITLE
More underground variety

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1944]
- [ ] Underground decorations: glow-worms, crystal formations, stalactites, stalagmites ...
- [ ] Varying stone types underground
- [ ] Underground biomes to vary those decorations and stone types
- [ ] Reconsider which stones will contain which ores, some ores could have solid-ore textures and appear in multiple stone types.

**Comment by paramat** [comment]
I'll might add some of these myself, i think crystals (giant quartz) and stalactites / stalagmites (made from a new node) are the obvious ones. I'm not inspired to add plants or more fantastical things though, others can do that and will be much better at that than me.

**Comment by Wuzzy2** [comment]
The most obvious thing to do would be to add more stone types of varying hardness, adding some challange and *greatly* improving variety. Just using stone for >99% of the underground gets boring really quick, and desert stone is … well … reserved for deserts.

Even in its simplest form (implmented as blob ores) it would be an improvement. But even better would be to generate the other stones in *large* quantities in the underground (but this will also be the hardest part, to generate the stone in a way which doesn't look too artificial).

**Comment by paramat** [comment]
Good idea and easily done, just set the biome 'node_stone' to a different stone.
I often think about a variety of stone types underground with varying colours / textures.
A bigger issue is that ores use stone as the base texture, we would need another set of ores for each new stone type (no ores in deser stone or sandstone due to this).

**Comment by GreenXenith** [comment]
Aren't ores already overlay textures on top of another texture (stone)? Why bother with a new texture? Just register all the mapgen ores using the same method. They will all turn into the same lump (or crystal) when mined anyway.

**Comment by paramat** [comment]
Well with overlays you would still need a new node for each stone type, if the ore filled the texture you only need 1 node per ore. There may be many stone types, adding a bunch of new nodes for each slows down mapgen and complicates MTG.

**Comment by Ezhh** [comment]
Ever considered ores which are unique to specific stone types? That would give other stone types something worth mining for (assuming you make them useful ores) and prevent lots of duplicated ore nodes.

**Comment by NewbProgrammer101** [comment]
I think this shouldn't be in minetest_game since there's already the caverealms mod and I think that is enough.

It even has a counterpart: caverealms_lite.

**Comment by rubenwardy** [comment]
@NewbProgrammer101 I think this is something that MTG is lacking most - a motive to actually mine deeper. MTG should be playable and fun without mods

**Comment by paramat** [comment]
Yes it's high priority.

**Comment by tobyplowy** [comment]
> a motive to actually mine deeper. MTG should be playable and fun without mods

You know adding More content to the caves isent gonna make the game more fun you're gonna have to do More Than that but its a good beginning!

I just really hope we can see stalagmites and stalactites 
(ones that are made with plantlike and not nodeboxes so they can be edited with texturepacks)

**Comment by paramat** [comment]
> adding More content to the caves isent gonna make the game more fun

Wow thanks =/

**Comment by GreenXenith** [comment]
> > adding More content to the caves isent gonna make the game more fun
>
> Wow thanks =/
Since you're so disappointed in MTG maybe you should stop bothering us and being negative and just write your own game?

Dunno what he is talking about, I would sure enjoy more content in caves. Especially cool formations.

On-topic; how about underground rivers? They exist. Rare. But they exist. Underground pools too?

**Comment by tobyplowy** [comment]
> You know adding More content to the caves isent gonna make the game more fun

Sorry I meant "You know adding More content to the caves isent gonna make the game fun 
(it's nice to have tho) 
But i know my opinion doesn't matter 

> Since you're so disappointed in MTG maybe you should stop bothering us and being negative

Yeh I may be negative but I only whant the best for minetest (you guys just can't take feedback)

> and just write your own game?

Well I have its called farlands

@paramat Im really not your enemie please read this 
https://forum.minetest.net/viewtopic.php?f=56&t=18922
I really want to help I really do!
But you will have to let me help!

**Comment by paramat** [comment]
Sorry, i was annoyed by the negativity. Your involvement is welcome, but please restrain unconstructive negativity.

**Comment by dsohler** [comment]
>>adding More content to the caves isent gonna make the game more fun
>>
>Wow thanks =/

Well, actually it would make the game more fun because there are more materials to use for buildings. But just adding some blobs of different stones isn't exactly "more content". 

There should be more variation below -1000. The caves are cool and all, but there simply isn't much to do. Below -500 I barely find lava (or i'm just unlucky) or water, or anything besides some ores and some wide, open, caves.

What about poisonous liquids? What about fungi? Where are bioluminescent algae? Where are stalactites and stalacmites? And so on. Caves just don't feel much like caves. The generation is great, but the assets are missing completely 😢

**Comment by InfiniteOtter** [comment]
I have been in caves. I have taken ropes and flashlights into caves to explore them. The caves feel a lot like caves, with a few exceptions. 

While I think a few additions in the materials department are nice and logical, there is a point where managing all the various materials just clogs up inventory and makes for tedious play. I advise caution on adding things. Stalactites, Stalagmites and pools are all good things to add. Dripping water from some nodes would be a fun detail since stalactites and stalagmites are formed by dripping water. Stalactites should drip. Stalagmites should be beneath drips. Flares to light up large areas for a short time would also be a nice addition.
It may be the cave I have been in, but still water is more common than running and falling water. A lot more common.

**Comment by TekhnaeRaav** [comment]
I would love some more natural light in caves to. Minecraft did this fine with its higher amount of lava, but I don't know if thats what we'd want.

**Comment by paramat** [comment]
Caves are for lighting up. However we may well add bioluminescent decorations which will be dim but pretty.

**Comment by paramat** [comment]
Added varying stone types to the first post, travelling underground will be much more interesting with varying stone colours.
We have grey, red, orange stones, we could add white (limestone), greenish, blueish ones. Crafted into 'blocks' they will add colour variation for builds.

'desert sandstone' and 'silver sandstone' need adding to the world, i might add strata of these above sea level in desert biomes but to provide more resources of these they could be underground too in larger volumes.

Stalactites and stalagmites are calcium carbonate and require limestone as a source of material.
Remember that if you register a single stacked decoration with both "all floors" and "all ceilings" flags the floor and ceiling decorations will be vertically aligned and will sometimes meet, as is realistic.

**Comment by jastevenson303** [comment]
>Ores need to be considered, they are all in grey stone currently

This is the real issue, I find.

**Comment by Ezhh** [comment]
I would love to see white, or very pale, stone of some kind added.

**Comment by InfiniteOtter** [comment]
Paramat, I love your idea of classes of stone and ore going together. An underground biome or really a geome maybe, would make sense. The best refractory clay (What kilns, fireplaces and furnaces are really made of) is found just under coal. Clay deposits are often huge. A few years ago there was a bit of fear that the source for greenstripe fireclay was exausted. Now it is back to being one of the cheapest refractory materials you can get. (at least in America)

**Comment by Ezhh** [comment]
I've long been in favour of ores specific to stone types (I've gone with a unique stone type and ores linked to it in subgame experiments.) I'm not hugely keen on the idea of solid ore textures, but it might depend how they look in practice.

**Comment by paramat** [comment]
Ores specific to stone types was Ezhh's idea. Before that i was concerned that every ore would have to be in every stone type, but that's not necessary and less interesting.
Solid ores would be unsuitable for most ores, and are unnecessary anyway if ores are specific to stone types.

**Comment by Ezhh** [comment]
I'd be very keen on seeing pale limestone caverns underground, since the colour contrast would still be a quite natural one against grey, but nonetheless noticeable and distinct. I'm not sure how that would best be implemented yet though, since part of the pleasure of finding unusual underground biomes would be not necessarily knowing where you will find them (the technique I've been playing with so far won't help much to just add in a single underground biome like this, and only helps if you are specifically linking up surface and underground biomes as a progression).

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/pull/2109#issuecomment-381427121
The profining shows that using stratum oregen to add undulating layers of stone underground is not unacceptably intensive (with 1 2D noise per stratum).

**Comment by paramat** [comment]
Closing due to #2710
