### ISSUE TITLE
Burntimes make no sense

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1946]
The burntimes are confusing me. Leaves have a burntime of 1, grass_1 has a burntime of 2, apples have 3 and saplings have 10 (12 for a jungle sapling). They burn even longer than 1qm of wooden planks. 

Apples don't burn at all, and leaves have a much much higher volume plus branches than e.g. grass. Saplings are tini tiny plants. What should burn for 12 seconds?

The order of burntime, that makes sense to me is, from shortest to longest:

grass (1), dry grass (2), saplings (2-3), leaves (5-7), planks (10), trunks (30-40)

Is it because leaves are more common than e.g. saplings and almost useless, except to use them as deco?

**Comment by paramat** [comment]
Hehe apples 3. In some cases perhaps some unburnable things are made 'burnable' just to allow detroying them in a furnace, however i don't see why you wouldn't just eat an apple, probably best make them unburnable.

I'm not sure there is much logoc behind some of these.
If someone makes a PR, leave trunks, wood planks, fences unchanged as i chose those carefully.
Saplings being less is fine but keep thei relative burntime ratios (currently 6, 7, 8, 9, 10, 11, 12) because the burntime is related to wood properties, maybe divide all the numbers by 3?

Leaves > grass makes good sense.

**Comment by paramat** [comment]
#1955 merged.
