### ISSUE TITLE
Add Hidden Lore/Backstory For Added Gameplay Depth

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest_game#1949]
Minetest Game lacks depth, in the sence that things have no reason to exist or behave the way they do. While we have MESE (our resident voodoo plot material) we don't have any official origin for it. Dungeons  have some low-tier loot in them now, but no reason to A) Exist in the first place and B) For the loot to be there.

My suggestion is to give reason for these things, in a way that enhances gameplay without getting in the way.

>@celeron55 has stated that MESE is of alien origin, and Dungeon Masters & Orrkis are the only official mobs to be included in Minetest.
>
> Orkkis are those aliens, and MESE is the material that powered (it glows, powers Mese Lamps, is used in Mesecons, etc) their once great civilization (Dungeons are what is left of this, and their contents could imply most of this story).
> 
> Dungeon Masters were created by the Orrkis to both guard dungeons, and to mine MESE in the hope that their civilization might one day rise again.

The story/lore would be implied by various things hidden around the world (things scattered in dungeons, caves, deep underground caverns) and would help drive exploration as well as spruce up the underground. The story would not necessarily drive gameplay, but could inspire the player to find more artifacts/ruins.

If dungeons were made rarer, and the decorations in them controlled based on parameters (has this type of ruin already been generated, coords) they could be made much more interesting to find and explore.

**Comment by NewbProgrammer101** [comment]
I don't think that would fit the purpose of minetest_game.*

There are other subgames such as Dungeontest and Lord of the Test that has lore and quests in development.

*(yet)

**Comment by benrob0329** [comment]
Minetest Game is a game, no? The point of a game is to be fun, but its hard to make something fun when *everything* is generalized.

Why should I explore? There are no hidden vats of rare materials, no story of those before me, nothing to drive my curiosity. Everything is generalized, and bland.

We're just going to leave things like Mese unexplained? How are we going to use it properly without knowing what it is? What mobs will exist, and why?

A story does not need to be big, or even be the main element of the game. The story can be a guide to development, to exploration, and to creativity. The idea is that this tells what happened before, but its up to the player what happens after.

**Comment by tenplus1** [comment]
I do like celeron's back story :) and for default game it would be nice to have something to play towards with each separate game hosting it's own storyline maybe :)

**Comment by C1ffisme** [comment]
> Why should I explore? There are no hidden vats of rare materials, no story of those before me, nothing to drive my curiosity. Everything is generalized, and bland.

Agreed. A story and lore that the player has to discover at least gives the player incentive to hunt for dungeons and other structures that can reveal this information to him. Especially if pieces of the story are gated behind getting a certain tier of pickaxe, or the high tier of pickaxe can help the player to find structures faster.

Of course, don't just stop at story. Maybe dungeons should also have some technological rewards based on Mese? (Like [Teleportation](https://github.com/minetest/minetest_game/issues/1945)) Of course, it would be helpful if we had a way to lock certain recipes behind certain achievements or goals, such as finding a "schematic" item.

**Comment by Fixer-007** [comment]
It needs features, not a story :}

**Comment by C1ffisme** [comment]
> It needs features, not a story :}

Better close the issue because of this incredibly well constructed argument that completely debunks the idea that we need a story.

**Comment by benrob0329** [comment]
These are from a long time ago on the forums:

![79d5239590597beaf4565568fafb0d00-d6li8k1](https://user-images.githubusercontent.com/19180682/33039870-78c0b962-ce07-11e7-8c98-768ae81ffcb9.jpg)
![qwe_by_kinghearts97-d6ltk16](https://user-images.githubusercontent.com/19180682/33039881-817c0714-ce07-11e7-827c-d0ef9ca82d2e.jpg)

They are by far my favorite depiction of the mysterious beast and his master. Looming, strong, something that would make an inexperienced player run for his/her life. The current simple_mobs model seems cute, almost like a teddy bear. However they are added into the game, I would love if the feeling these creatures gave was not laggy and stiff, but terrifying and awe striking.

**Comment by paramat** [comment]
> While we have MESE (our resident voodoo plot material) we don't have any official origin for it.

It has an official mystery, which is fine and leaves it up to mods to interpret different ways.

> Dungeons have some low-tier loot in them now, but no reason to A) Exist in the first place and B) For the loot to be there.

Nothing wrong with mysterious structures with traces of past activity. Mysteries are fascinating and are a base for imaginative interpretations.

A subtle deveolopment of the mysteries seems ok but your example lore suggests you want to make it too specific. As a mod base MTG has to be somewhat neutral and unversal.
Your 2nd post is excessive negativity. MTG is not necessarily a complete, exciting or fun game, it is a mod base that is slowly improving and moving closer to being a very simple game.

> Back on topic, does anyone have models or concept art of what orrekis and dungeon masters can look like in such a way that they better fit the style of the game?

Better than what? Any specific mod you have in mind? What's wrong with the style of the MT 0.3 mobs? Those can be interpreted into 3D.

**Comment by Ezhh** [comment]
My only request: if anything like this gets added, please make it easy to turn off.

**Comment by paramat** [comment]
Don't worry, i'm :-1: for this level of detail.

**Comment by benrob0329** [comment]
>It has an official mystery, which is fine and leaves it up to mods to interpret different ways.

There is more to a game than its mods :-)

>A subtle deveolopment of the mysteries seems ok but your example lore suggests you want to make it too specific.

It was 3 sentences, how is that too specific?

>As a mod base

(Hyperbolic trigger point, take with salt) Minetest **Game**, its a game. It can also be a mod base, but its a game nonetheless.

>As a mod base MTG has to be somewhat neutral and unversal.

Thus the point is to have everything be implied, completely. Things in the dungeons, hidden in caves, nothing too specific but giving the player a general idea of what might have happened before.

>MTG is not necessarily a complete, exciting or **fun** game

A game that is not fun, is not a game at all.

>Better than what? Any specific mod you have in mind? What's wrong with the style of the MT 0.3 mobs? Those can be interpreted into 3D.

I believe he was referring to Simple_Mobs.

>My only request: if anything like this gets added, please make it easy to turn off.

If done correctly, MTG should be easily modifiable so that if a server wishes, a custom backstory could be implied. Of course, if the server has the same materials and mobs, I don't see why changing the contents of dungeons would make that much of a difference.

>Don't worry, i'm 👎 for this level of detail.

Again, what detail? I'm just trying to explain the things we already have to make them slightly less generic, no detailed story was intended. Addding some explination (even internally to the development) would help people know how to go about adding the details that make the world feel alive, if everything is supposed to be as generic as it can possibly be, then perhaps "Minetest Base" or "Sandbox" is a better name for it :-)

**Comment by C1ffisme** [comment]
> Better than what? Any specific mod you have in mind? What's wrong with the style of the MT 0.3 mobs? Those can be interpreted into 3D.

Actually I was thinking of mob framework, but the models from simplemobs aren't the greatest either. They just don't fit Minetest in my opinion.

**Comment by rubenwardy** [comment]
I don't think MTG should be a mod base. I do think it should be modable and customisable. This achieves exactly the same effect without alienating new players

**Comment by paramat** [comment]
The 3 sentences are too specific.
'Game' is a technical term, MTG is not ncessarily a 'complete game' yet.
I'm ok with very subtle developing of the backstory, but that's not the impression you give here or on IRC.
'Fun' is subjective, at first i found MTG fun on it's own even at 0.4.3, later i then added a very few mods.

I agree most mob mods have unsuitable models, even 'simple mobs' models are too detailed, and the Oerkkis's don't match the 0.3 appearence of a dark pillar. The 'simple mobs' DM is a fairly good match though and less ugly than the 0.3 version.

**Comment by Ezhh** [comment]
Adding a few small bits of lore just doesn't seem like enough for it to matter, and if you add enough for it to matter (so that it might actually change how you play the game) feels like too much for MTG. It would be better to do something like this outside MTG, simply so that it could be done with sufficient depth and detail to make an actually really good experience.

This isn't about not adding content to MTG, because I do feel quite strongly that MTG needs more content. I just don't think something like this can work as well as it should in MTG without changing what MTG is too greatly.

**Comment by dsohler** [comment]
> Minetest Game is a game, no? 

In the current state it isn’t. It lacks anything that would make it an actual game (there is neither a reason to do anything nor a goal to get to). *Minetest Game* is more like a limited sandbox or a base for mods and own games.

**Comment by benrob0329** [comment]
>The 3 sentences are too specific.

Mese make power. Orkki make mese and Dungeon Master, used to thrive. Dungeon Master mine and protect dungeon.

>'Game' is a technical term, MTG is not ncessarily a 'complete game' yet.

Yet is the keyword, we're trying to help it get there :-)

>I'm ok with very subtle developing of the backstory, but that's not the impression you give here or on IRC.

I would have thought that "implied by various things **hidden** around" would have said that it was supposed to be subtle, but perhaps not. It **is** supposed to be subtle.

>Adding a few small bits of lore just doesn't seem like enough for it to matter

Anything to help define the gameplay and reasoning matters :-)

>(so that it might actually change how you play the game)

The point is not to change how you play, but rather to enhance the gameplay that MTG already has. Exploring dungeons and caves could be more fun if there was more in them, and what could be better than a hidden backstory that gives you hints at why things are, and perhaps at how you can do better with those things. (perhaps, that would require some actual story integration that might be too much depending on how complicated it would have to be).

>I just don't think something like this can work as well as it should in MTG without changing what MTG is too greatly

So MTG should be a completely generic, bland, explanation-less base that more or less requires mods to be fun for more than an hour? MTG **has** to change, if it is going to move forward. This is true of any project, and some things may not be the same. To say that we shoudln't change would be to say we shouldn't improve.

That is not to say that MTG can't be fun, or that it hasn't become much more than it used to be. I just want it to continue with that trend of improving, albeit with a little more depth than it used to have.

**Comment by Ezhh** [comment]
> The point is not to change how you play, but rather to enhance the gameplay that MTG already has. 

Your suggestion does nothing to enhance gameplay for me. We don't all find random hints of a very basic plot that never lead anywhere to be fun or interesting. For this to be worthwhile I'd want it to actually do something. I'd want the clues to lead somewhere and to be meaningful.

Then how would you implement this so that it doesn't get repetitive? Would it just add some signs and books in dungeons and nothing else? If that's all it would do and there is no loss in missing the clues you place, then it's massively basic and (to me) boring. However, if I find the same clue ten times, it's then annoying instead of boring. Going the other way, if the clues are rare enough to never find them, it's frustrating if you want to find them but can't. How do you balance this?

> So MTG should be a completely generic, bland, explanation-less base that more or less requires mods to be fun for more than an hour? 

Where did I imply that? I seem to have said the opposite, what with me feeling "strongly" that MTG needs more content. :D 

> To say that we shoudln't change would be to say we shouldn't improve.

Didn't suggest this either. I simply think this is the wrong change (because it's not really adding anything much at all as you describe it).

**Comment by benrob0329** [comment]
>Your suggestion does nothing to enhance gameplay for me.

Adding more to dungeons, caves, giving purpose to materials...I don't see how that doesn't add to the game.

>Would it just add some signs and books in dungeons and nothing else?

"Implied by things hidden around the world" aka never say it, don't spell it out but use the things hidden away to tell of things past.

>Then how would you implement this so that it doesn't get repetitive?

Because it can't be any more repetitive than things already are. I don't see how adding depth makes things **more** repetitive when it would be added in a way to make the environment more interesting.

>if I find the same clue ten times, it's then annoying instead of boring

Again, this all comes to adding it correctly.

>Where did I imply that?

It was an exaggerated comment to show a point.

>Didn't suggest this either. I simply think this is the wrong change (because it's not really adding anything much at all as you describe it).

I'm not really saying how exectly to tie this into the game. I'm giving hints at ideas but this is meant more as a development guide than a hard and set story. Have things in the environment hint at a civilisation past, because that will make it more interesting.

Perhaps ruins above or half buried could be added, with some odd pieces of technology and long-dead Orkkis. Maybe these pieces of technology don't work, but help the player build other things that are similar.

Maybe dungeons could be rarer, and the contents be spawned smartly. Maybe they could be placed close to spawn, rather than on the other side of the world (or maybe the point would be to travel).

Maybe you find hints at the position of a dungeon in the ruins, through the materials in it.

I don't know what mechanics this could lead to, but I think it would help guide the development of exploration a bit.

**Comment by Ezhh** [comment]
> Again, this all comes to adding it correctly.

Yes, but how? That's why I am flagging the issues, so someone can say how. 

> It was an exaggerated comment to show a point.

So not needed and doesn't help us get anywhere. :)

> I don't know what mechanics this could lead to, but I think it would help guide the development of exploration a bit.

Problem is we need mechanics, or we still don't have new gameplay as a result.

**Comment by NewbProgrammer101** [comment]
> Problem is we need mechanics, or we still don't have new gameplay as a result.

Are you pointing at something like a booby trap in dungeons?

**Comment by Ezhh** [comment]
I'm not pointing at anything. I don't think this can work for MTG without changing MTG too much, but I'm hoping I can be convinced otherwise.

**Comment by benrob0329** [comment]
Biggest question is, will MTG stay completely generic? If not we can plan features (I have some stuff in mind) but if it will, then I'll close up the issue.

**Comment by paramat** [comment]
benron0329 i actually agree with you when you suggest subtle development of the mysteries, however the way you're writing about it on IRC and wanting to 'plan it all out' 'with a team' (maybe a new team) strongly suggests the wrong approach.

It's something that was going to happen anyway and will happen as new features are added, it will be done 'in the moment', improvised, as we go along, it doesn't need planning out and agreeing beforehand. The MTG dev's opinions and intentions are ever-shifting anyway so planning or agreeing on something for the future like this is pointless. No one has to worry about it or plan it, it will simply happen. Ideas and discussions about the lore of MTG are fine, planning and organisation is not.

A specific lore is best left to other new games.

I disagree with Oerkki's being the aliens who are the creators of mese, that doesn't make sense with MT0.3 since mese was 'of mysterious origin' then too. Mese should always be fairly mysterious, it's not certain it is of alien origin, that's the lore we already have. We may not have DMs in future so there's no point planning lore based on those. Although i want to bring back Oerkkis we may not have those either, who knows.

The lore of MTG needs to stay very subtle to not get in the way of what is based on MTG.

**Comment by paramat** [comment]
> MTG has to change, if it is going to move forward [...] To say that we shoudln't change would be to say we shouldn't improve.

It is changing and moving, no-one is suggesting it shouldn't. It just may not change in the way you personally want it to. Not developing a specific lore doesn't make a game stop changing or stop developing.

**Comment by benrob0329** [comment]
Very well, good luck to the future then :-)

**Comment by paramat** [comment]
However, whichever approach we took, it would be necessary to first collect all existing backstory into one place, to take inspiration from and avoid inconsistencies.
I'll open an issue for this 'one place' for copy/pastes from whereever. Then i might chat with c55 and ask about any backstory we've missed.
I agree with working with the backstory we already have, but don't think we need more, hopefully we will get a little more from c55, but he should be the source if anyone is.

**Comment by C1ffisme** [comment]
I just feel like noting, just for the sake of bringing it to the table, that a good story or lore is a great way to attract Gamers, Fans and Youtubers and a good way to brand our content and separate it from the competition. 

(Especially when "Minecraft Rip-offs" have a tendency of being poorly made. It's easy to find one or two of these bad sandbox games made for Mobile devices, some of them are even copies of Minetest.)

**Comment by paramat** [comment]
Concerning MC, the 2nd most popular game in the world, which many compliment as being a complete, fun and exciting game, it has almost zero backstory. It's not necessary, and if a game is intended to be moddable, as MTG is, it restricts what mods can do.

**Comment by C1ffisme** [comment]
> Concerning MC, the 2nd most popular game in the world, which many compliment as being a complete, fun and exciting game, it has almost zero backstory

Yes, but MC has something going for it: It managed to be the first game of its kind. (Yes, Infiniminer existed before Minecraft, but Minecraft was the first to become incredibly popular and make the voxel sandbox style of gameplay popular.)

If we want a good reason to download our game other than "Free Minecraft" or "Open Source Voxel Engine", then a story is a good way to attract people to the game. (And to get our name out into the world.)

**Comment by benrob0329** [comment]
MC has quite a bit of story, actually. Sure, its all hidden and implied by mechanics but it is an RPG, with a plot and goal.

**Comment by paramat** [comment]
C1ffisme that's no argument, it's still the case that backstory is unecessary.

What's the backstory? I'm obsessed with watching MC 'let's play' videos, and have done almost every day since 2011, in that time i would think i would have noticed some backstory.

**Comment by C1ffisme** [comment]
@paramat Minecraft doesn't need a backstory to be popular, because it's already popular.

If we want to be popular, there are two routes that we can take: 

1. Perfect the game to the point where it can be appraised for being very original and very creative, which is very difficult because we already look like a much more popular game.

It's not possible anymore to be the very first voxel sandbox centered around building and mining, because Minecraft already did that. We would need to come up with a new kind of gameplay type built around our engine, which would deviate us from the course of building a good Minecraft clone.

Games like World of Goo, Portal and Kerbal Space Program don't need to be popular because of their story or characters, even if they have them. They're popular because they have original gameplay that no other game before it managed to have, or managed to do correctly.

Minetest's gameplay is exactly like Minecraft in every aspect except for the exact types of blocks and items that exist in the game, and a lot of the graphical quality. Unless we want to push Minetest's gameplay in another direction, possibly even dropping a voxel sandbox altogether, there is another option:


2. Create an engaging story/characters/universe that people would like to play the games of, make fan art or fan fiction about, or buy merchandise of.

Franchises like Sonic the Hedgehog, Fnaf, Undertale, and more can gain an audience of fans, even if casual gamers and Youtubers think that the games or characters are very similar to other franchises.

Characters that can have fan art drawn of them turn fans into advertisements, and grows a community of fan artists around the game. Once characters draw in an audience, a story or story universe can keep them in the fan community by letting them write additional stories that add onto the main story.


> What's the backstory? I'm obsessed with watching MC 'let's play' videos, and have done almost every day since 2011, in that time i would think i would have noticed some backstory.

I wouldn't say it has a backstory, Minecraft lets you choose your own story, but it still places in elements that help make this story, like crazy places to adventure to and mysterious things to find.

We don't have a lot of these elements, besides the dungeons, which are all exactly the same besides different room sizes and shapes and loot.

**Comment by paramat** [comment]
> Minecraft doesn't need a backstory to be popular, because it's already popular.

What sort of weird logic is this?
It became popular, so it didn't need a backstory to become popular, which is what i said.

> If we want to be popular

We already are popular, MT is near or at the top of open source voxel game popularity.

>  there are two routes that we can take:
Perfect the game to the point where it can be appraised for being very original and very creative,

A game doesn't have to be original to be popular, for example, MC.
You then use the false logic of '2 choices' to insist that a backstory is needed, it's nonsense.
As i suspected, MC doesn't have backstory.

**Comment by C1ffisme** [comment]
> We already are popular, MT is near or at the top of open source voxel game popularity.

Key words: **open, source**

We're popular among people that already play open source games, but we can expand that, both to bring people into the Minetest community and to bring people into open source programming in general.

> A game doesn't have to be original to be popular, for example, MC.

MC is original, or at the very least, it took a badly or mediocrely done idea and did it better than anyone before it, and gave people the example of what a voxel sandbox should be, like the Mario 64 of voxel sandbox games. If you want to top Minecraft, rather than copy it, you need to add something.

> You then use the false logic of '2 choices' to insist that a backstory is needed, it's nonsense.

The other choice is "be called a Minecraft rip-off by anyone that doesn't understand open source."

**Comment by Fixer-007** [comment]
MC story is kinda meh, some guy in adventure land with some creepy stuff, ???, fight dragon, ???, profit (kinda)

**Comment by paramat** [comment]
I'm more interested in making MT better than more popular. Focussing, obsessing and worrying about popularity (as some here do excessively) is the wrong approach.
For example people know the MC community is fairly unpleasant, that inevitably comes from it's size and being mainstream. Much better to be less popular, more 'niche', with a better community, which is the case with MT.
More popularity means more annoying people, arguing, more requests and Github issues for the same small amount of devs to cope with, more mobile clients using nasty apps. Popularity is not all good. I'd be happy to see all users of bad apps disappear, as many server owners would, that could be 75% of players.

> The other choice is "be called a Minecraft rip-off by anyone that doesn't understand open source."

As before, you create a false situation of "if you don't do what i want 'A', then something bad 'B' will happen".

**Comment by C1ffisme** [comment]
> More popularity means more annoying people, arguing, more requests and Github issues for the same small amount of devs to cope with, more mobile clients using nasty apps. Popularity is not all good.

Alright, so popularity itself is bad, and I can't convince you otherwise. How about adding a backstory or lore for the sake of a clearer direction when choosing to add things to the game? (Or just making the game a bit more interesting in general.)

**Comment by NewbProgrammer101** [comment]
`More popularity means more annoying people, arguing, more requests and Github issues for the same small amount of devs to cope with, more mobile clients using nasty apps. Popularity is not all good.`

👍 

@paramat , to help you, I will not recommend or discuss Minetest to anybody until the game is to the community's standard of a finished game.

**Comment by paramat** [comment]
> Alright, so popularity itself is bad

No i didn't say that.

Story will be developed when stuff is added, by the stuff that is added, it won't come before that like some sort of .txt essay. Like i said, no planning needed. Direction isn't a solid planned decided thing that comes before additions, it is a fluid, ever-changing organic thing created by additions, in the moment.

**Comment by dsohler** [comment]
> I will not recommend or discuss Minetest to anybody until the game is to the community's standard of a finished game.

Do you really want to wait a couple of years before promoting Minetest?

**Comment by starninjas** [comment]
Man, this would make a cool mod honestly..
