### ISSUE TITLE
Hanging snow blocks after tree decay

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1962]
After tree decay in snow forest, latest minetest_game.
![zizzdmc](https://user-images.githubusercontent.com/16494741/33519869-977e1f88-d7b8-11e7-8a0c-0d0421a83605.png)

**Comment by paramat** [comment]
IRC:

21:37 paramat    it was requested snowblocks don't fall to not break snowblock builds
21:37 paramat    giant snowmen etc.
21:37 sfan5      just make player-placed snow blocks not fall?
21:38 paramat    trees very rarely have snowblocks on them anyway, that only happens when pine branches extend 1 or 2 nodes into icesheet or tundra biomes
21:39 paramat    minor issue
21:39 paramat    taiga doesn't have snowblocks as dust

**Comment by TumeniNodes** [comment]
Is there a way to make them a falling node, only if checked for leaves under?

**Comment by paramat** [comment]
No, groups are fixed.

**Comment by paramat** [comment]
Closing for reasons above.
