### ISSUE TITLE
Node drag

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1963]
In minetest_game travel speed is pretty much the same everywhere, except on liquids, but what about solid nodes, say sand, snow blocks, gravel, ice, they can be configured to decrease player speed (unless on rails), depending on level of survival/realism you want.

**Comment by paramat** [comment]
Unnecessary and too specialised. Every node walked over would need to be checked for speed value.
Once we have 'on walk over' API, which is useful for many things, this can be done by a mod using custom player physics.
:-1:

**Comment by Fixer-007** [comment]
>Every node walked over would need to be checked for speed value

It is not like modern CPU will not handle just one simple check...

**Comment by paramat** [comment]
Yes, i mean it's not worth doing just for node drag, better to add 'on walk over' API and use that in a mod.

**Comment by paramat** [comment]
Oops no need to close, this can be considered once we have 'on walk over' able to trigger a physics override.
However i am :-1: for the concept as it seems too specialised and realistic for MTG, best done in an optional mod or another bundled game.

**Comment by C1ffisme** [comment]
Minecraft has Soul Sand which slows down the player, and I'd be interested in seeing this functionality make it into Minetest.

I'm not fond of the idea that blocks like Normal Sand and Normal Gravel will have this effect, though, because it might just get annoying after a while. (Although if you could make the player go faster on blocks like cobble, it might encourage the player to build roads rather than walking in the dirt all the time.)

**Comment by rubenwardy** [comment]
> Every node walked over would need to be checked for speed value.

We already do this for slippery. It's the exact same thing, it would just make you slow down faster instead of slower

**Comment by paramat** [comment]
Yes that sentence was a mistake, edited. Forgot about slippery.
I think any slowdown on common nodes would be annoying, even if realistic, so best left to optional mods that add special 'slow' nodes.
The engine issue is whether to do this as an extension of slippery code or do it using 'on walk over' plus physics override.

**Comment by paramat** [comment]
I'm opposed to any engine work to extend slippery to do this, because it would be work and code dedicated to a low priority feature, it can be done by an 'on walk over' API instead.
Nevermind what MC has that's irrelevant.

**Comment by Ekdohibs** [comment]
It's a simple feature that shouldn't be too hard to integrate in the movement code. Having on_walk_over + physics override would be a huge load on the server and would be very laggy (movement is something that needs to be done client-side because it needs to be very responsive) unless it is done in CSM (but some people will object having physics overrides in CSM anyway, so...)

**Comment by paramat** [comment]
Good point, 'on walk over' would trigger on every node, which is bad.
However i don't think this is worth the effort and code, especially considering the lack of dev time.

**Comment by paramat** [comment]
Engine issue.
