### ISSUE TITLE
Double Chests

### ISSUE THREAD

**Issue by Gerold55** [minetest/minetest_game#1973]
Can we have double chests?

**Comment by MarkuBu** [comment]
There are several mods that add double chests

**Comment by Gerold55** [comment]
Yes I know but I am wanting it added in game :)

**Comment by MarkuBu** [comment]
It's a nice to have, but I don't think it is necessary and there are more important things to implement. 

Just my 2 cent

**Comment by Gerold55** [comment]
Yeah it's just a feature that would be nice the aesthetic of it would be nice. And more storage in on inventory :)

**Comment by paramat** [comment]
Yes it is low priority. MTG tends to do everything simply, and the opening single chests were a lot of work which would need to be duplicated, for something that is only of visual value :-1:

**Comment by Gerold55** [comment]
Other than visual you would have extra chest space.

**Comment by dsohler** [comment]
> only of visual value

Except having chests with twice as much slots than a single chest.

**Comment by paramat** [comment]
Hm good point, i was thinking 2 chests side by side is equivalent, but of course not as convenient to use.

**Comment by paramat** [comment]
This requires making a model which i can't do (and i am not interested in this task). It seems no other dev has time for MTG so you may have to find someone willing to code this and make the model.

**Comment by benrob0329** [comment]
The model could remain the same, but have the texture change accordingly. (Two chest models next to each other, rightclicking on one opens the other)

**Comment by Gerold55** [comment]
That's what I was thinking also :)

**Comment by paramat** [comment]
Nooo that would look bad, and working with 2 separate nodes will make things more complex.

**Comment by MarkuBu** [comment]
That would be like doors earlier. Looked ugly because both halves doesn't open at the same time

**Comment by Ferk** [comment]
Would a chest formspec with double inventory fit in a small mobile screen?

Minecraft might have double chests, but the normal ones have half the storage space than Minetest.

**Comment by GreenXenith** [comment]
If you go by large chest behavior in Minecraft (which IMO makes sense), if you dig one side of the large chest, it turns into a small chest (obviously on the opposite side of the chest you dug) and drops items that don't fit. If this behavior were wanted for chests in Minetest, we would have to detect which part of the chest the player is pointing at (because it's a 2-block model with a 2-block sized collision box), which I don't think is possible, but I could be wrong.

**Comment by dsohler** [comment]
> Would a chest formspec with double inventory fit in a small mobile screen?

Works flawlessly with [this mod](https://github.com/HybridDog/connected_chests).




* [Computer (Arch Linux, Minetest 0.4.16)](https://user-images.githubusercontent.com/1668792/33955471-f451fafa-e03b-11e7-9a05-d5fcd6dd181c.png)
* [Mobile (Android 7.1, most recent app)](https://user-images.githubusercontent.com/1668792/33955472-f46bf52c-e03b-11e7-9569-be83ae9b6e87.png)

**Comment by TumeniNodes** [comment]
> The model could remain the same, but have the texture change accordingly. (Two chest models next to each other, rightclicking on one opens the other)

@benrob0329  the model cannot remain the same since the recent changes to chest.
a second model of a double (open) chest is required, and would have to be set up so that there is a way for a player to be able to decide if a chest set next to another is to remain a single or turn it into a double.

And I also feel this should be a mod, rather than built into the game.

**Comment by TekhnaeRaav** [comment]
I don't agree with this being a mod, but this is low priority so I'm afraid this will have probably have to wait.

**Comment by TumeniNodes** [comment]
It's actually not _that_ difficult (I think)
Just a matter of a second model added, for double chest open.
and fine tuning HybridDog's connected chests https://github.com/HybridDog/connected_chests ,and then integrate it into default
(easy peasy) ha

Though, I honestly feel that chests should be split into their own (like doors are)

**Comment by benrob0329** [comment]
What if you right-clicked on the side of a chest to combine it with the one you're holding? Then we don't add an extra thing to craft, and have the opportunity to have more than a double chest. Also, no extra model needed if we swap both/all nodes at the same time (vmanip anyone?).

**Comment by paramat** [comment]
New models (and probably textures) per size are still needed. Although i like the crazy idea of a triple chest, double is probably enough.

**Comment by TumeniNodes** [comment]
The formspec covers the chest when opened but, the 2d model w/ UVmap would be because, if you're going to do something..., do it right.
Other than that, HybridDog's mod works well, and has a nice formspec layout, etc.

Though I would like to see using the left shift key to using the right shift key (or something)
Would actually also love to see the formspec background transparent enough to see the open chest through it, but not enough to be a distraction.

I'm actually beginning to change my mind, in regards to this not being added, rather than as a mod.
Especially if chests would be split into it's own default/mod, which just makes sense.

This would probably be something users are very happy with.
(a lil' su-en new to distract from "when is the 0.5.0 release date?")  (big smile emoticon)

**Comment by TumeniNodes** [comment]
[double chest obj.zip](https://github.com/minetest/minetest_game/files/1625255/double.chest.obj.zip)

in case anyone wants to have a go at it.
I might work on the UVs tomorrow or over the weekend

**Comment by cx384** [comment]
This is minetest not minecraft.
Why do we take so much features from minecraft?
A few more or less recent examples: walls, carts, trapdoors, boats, iron bars, glass pains, fence gates, opening chests, flint and steel, dungeon loot, beds, tnt ...

**Comment by Gerold55** [comment]
Well the things that we add are also in real life. I thought it would be good to add to MT

**Comment by MarkuBu** [comment]
> Why do we even take so much features from minecraft?

Well, tell us what we can use that is not already used in Minecraft? Make a game that does not contain any Minecraft content and is still fun. I think if you find 10 things that make sense and aren't used in Minecraft or a mod, then you're a genius. 

But even then you don't have enough for a game

**Comment by Ferk** [comment]
@MarkuBu there are a lot of videogames that have nothing to do with Minecraft and are fun.
Honestly I would have preferred if MTG (and Minetest before it) had been more distanced from Minecraft from the very beginning. It could had been set in an alien planet, or a fantasy land or city landscapes or underground post-apocaliptic worlds (Ultima underworld or Arx Fatalix style). It would have been great if there were more gameplay elements that clearly made a big and lasting distinction that made players realize from the get-go that the game does not try to be just like a Minecraft sandbox game.

A lot of Minetest works like Minecraft, even arbitrary things unrelated to the "fun" that might have actually been more interesting had they been different, or that are inconsistent just for the sake of being like Minecraft.

I was making a list of several arbitrary things from MC that got into MT and could be changed but I realized the post was getting too big for an offtopic so I'd rather leave that for another time and place.

**Comment by TekhnaeRaav** [comment]
Just my opinion on double chests if it matters, I think double chests should be a thing you craft.:)

>Why do we even take so much features from minecraft?

Well, minecraft isn't a bad game, and a lot of these features are just good features for the game. Whether or not it's from minecraft doesn't matter as long as it makes the game better.

**Comment by Ferk** [comment]
> Well, minecraft isn't a bad game, and a lot of these features are just good features for the game

Yes, but there are a lot of great games to draw inspiration from, it doesn't have to be always Minecraft.
I'm not particularly talking about this suggestion, but even features that are not so good or make little sense are copied.

**Comment by paramat** [comment]
Forgetting about other games, a double chest makes sense by providing a larger inventory in one formspec, useful for sorting and organisation. In MTG, as you know, i try to make sure we never do something just because it is in another game.

**Comment by rubenwardy** [comment]
I've never felt the need for double chests, but it's a very popular request and is obviously useful for other people so I'm in favour.

**Comment by TumeniNodes** [comment]
@rubenwardy  that's more label switching than at a black friday sale haha.

I honestly don't see the big fuss over adding/adopting this feature. Regardless of it existing in MC it: 
A: adds a nice visual
B: can be very useful to players
C: aw c'mon..., it's pretty cool
D: because

My points above are, for the most part, meaningless, and not very strong arguments, I admit.
However..., a poll, whether here, or on the forum, etc..., proves absolutely nothing in terms of end users.
When I think about features like this, in-game..., I think "will kids be glad to see it added?", in this case, I think yes.

I also think, there are enough unique aspects related to Minetest Game, to justify similarities.
Unless they have some patent, or copyright on double wide chests..., I don't see the problem.

Either way, they will be available to end users, whether as a HybridDog's mod, or from the game itself.
it would also create more sense of splitting chests into their own mod within MTG (so that is the biggest reason I have changed my mind to, being for it to be added)

**Comment by paramat** [comment]
@rubenwardy I'm neutral, there are mods after all. I certainly won't do the work of adding these.

**Comment by Wuzzy2** [comment]
TBH there's no need for double chests. It's just a ton of work, needs tons of testing and adds a truckload of new possible bugs just for eye candy.
Double chests don't even really add anything to gameplay.

My advice: Don't waste your time on this and reject this suggestion.

**Comment by paramat** [comment]
@Ezhh your opinion?

**Comment by Ezhh** [comment]
I'm leaning toward :-1:  and happy with closing.

Wuzzy summed it up quite well in my opinion.
