### ISSUE TITLE
KISS in Minetest: unnecessary burn times

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1974]
It is just a thought I want to mention. KISS is an important part of Minetest development, and that is ok. 

But why are some things so complicated? For example: why have different wood types different burn times? They don't add real gameplay elements, but blow up the code for no reason

Can we use KISS where it makes sense and !KISS where some more code is needed, please? (C coders should understand this line I hope)

I posted this issue in MTG because it points to node definition, but is also valid for MT core

My first suggestion to this topic is to clean up the node definition and remove unnecessary burn times and other bloating stuff

**Comment by paramat** [comment]
=) oddly enough the different burn times for different woods are a recent addition i helped with, so i'm not sure if we're happy to remove them again so soon. They are for some variation due to different woods, which seems ok.
Any other unnecessary burn definitions?

**Comment by ThomasMonroe314** [comment]
while KISS is a part of MT and MTG,  there is also the factor of making things realistic.
as for the wood burning times, different woods have very different burning times, pine vs jungle wood for example, pine "wood" (sorry for the pun I couldn't help it) burn much faster due the the massive amounts of flammable oils in the wood compared to jungle wood which is very dense and burns much slower.

**Comment by paramat** [comment]
I think our idea was that denser woods have more mass so produce more energy, 'burn time' isn't speed of burn but amount of energy produced.

**Comment by MarkuBu** [comment]
We are talking about a game where the player can chop a tree by hand and can carry tons and cubic meters of material. I think this little amount of realism can be ignored. 

Even if they are realistic in some way, they don't really add much to the gameplay. If you think further ahead then wood should have different times to dig, you have to make sticks for each material and so on. 

I'm sure that no one will use this feature in the story of a subgame, but a lot of people may think "Why can I smelt 26 iron lumps to ingots with two jungle wood, but only 23 with acacia?"

And you always waste some energy because burn time and cooking time don't match. For example you can smelt ~10.5 iron lumps with 1 apple wood log. If you want to smelt a full stack you would need 10 logs and waste most of the last log. With a slightly longer burn time you can smelt 99 items with 9 logs and if this is the same for all logs it is more predictable for the player

**Comment by paramat** [comment]
I'm neutral. Perhaps it was done because it was variety and a little realism at no performance cost and very little code complexity. It was fairly popular with devs. I don't see a justification for removing the feature.

**Comment by C1ffisme** [comment]
I can see where different burn times might be useful in adding value to each type of wood, but when coal is so easy to find underground, I don't really think this is necessary.

I for one think that this should just be simplified, because we don't have any kind of documentation for this kind of thing and it doesn't really improve gameplay.

**Comment by JurajVajda** [comment]
Its nice to have variety in wood burning times but it would improve the game play more if the players would actually know about it, maybe a bit out of topic but adding the info about burning times variety in item/node description/tooltip would be great addition and im sure people would think twice what tree to farm/harvest. Don't like the idea of removing the variety and making game 'simple'.

**Comment by MarkuBu** [comment]
Well, If you want more realism, than you have to add sticks for each type of wood and wooden tools with different burn times and different durability. Also all other tools need a version for each wood stick with different durability ;-)

Fun aside, that's what I mean with "think further ahead"

**Comment by Ezhh** [comment]
There is nothing not simply about this and the last thing MTG needs is less varied content.

**Comment by rubenwardy** [comment]
:-1:

**Comment by C1ffisme** [comment]
Why is this being closed?

This is neither documented in game, nor does this add a reasonable amount of gameplay. The most good that this will do for players is that the players that spawn in certain biomes will be able to cook things in furnaces a bit faster before finding coal after about two full minutes of gameplay.

Not only that, but there are few times you would need the furnace before you get coal. All of the smelting recipes you can preform before you can get coal will only reward you with building materials, and considering there are no mobs to hide from, I could probably just get coal before I even bother with a house even if it took me a full fifteen minutes to find coal.

> Perhaps it was done because it was variety and a little realism at no performance cost and very little code complexity.

Gameplay > Realism
Gameplay > Realism
Gameplay > Realism

Realism isn't a positive factor, it's a neutral one. Even in an educational game, the most important part is that it's still a _playable and enjoyable_ game.

The wood types don't need variety in this aspect. They're supposed to be different because they add different color schemes into players' builds. Adding the ability for one log type to smelt more stuff without ever giving this information to the player just means that the few people that _do_ use wood for fuel will never learn that they have better options with wood.

(The only time I might actually use wood as a fuel source is when I've somehow run out of coal or if I'm lost on an adventure and I only have to smelt one or two items and I don't want to feel like I'm wasting fuel.)

If you wanted to add more variety to the wood textures, maybe you could add something the general playerbase might actually use and want, like doors made out of the different types of wood, or textures for each type of wood that look much more different from each other than the current ones do.

**Comment by MarkuBu** [comment]
Instead of wasting time and code for this, a new tree or something would make more sense.

Different burn times for wood belong to the category "useless", just like the diamond hoe

**Comment by paramat** [comment]
It's normal for different nodes to have different properties and it's simple to do so. Many or most nodes have individual burn times. Grouping a number of nodes together and giving them a single burn time for all is the more unusual behaviour.
Group burn times have no performance benefit because the individual node time is checked before the group one.
Following the approach of this issue would mean increasingly grouping nodes together and removing their individual properties.

**Comment by C1ffisme** [comment]
> It's normal for different nodes to have different properties and it's simple to do so.

They don't need different properties if nobody cares about those different properties.

> Many or most nodes have individual burn times.

Many or most burnable nodes and items that aren't wood-based don't fit in a category like wood items do. 

> Group burn times have no performance benefit because the individual node time is checked before the group one.

I care less about performance benefits right now, and more about simple, expected gameplay that needs little documentation.

> Following the approach of this issue would mean increasingly grouping nodes together and removing their individual properties, not a good idea.

No, it means nodes that are only supposed to be different cosmetically are only different cosmetically. Jungle Wood doesn't need a benefit over normal wood because it's a different color that works with different building materials. Being able to burn it is a side-benefit of collecting it.
