### ISSUE TITLE
Re-assessing MTG core devs

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1987]
Current MTG core devs are:

PilzAdam
sfan5
Ekdohibs
ShadowNinja
paramat
sofar
rubenwardy
SmallJoker

I think we can assume @PilzAdam is no longer a core dev due to lack of communication..
@ShadowNinja @Ekdohibs do you still want to be core devs?
@sofar how about you? you said you were not interested in MTG recently.

**Comment by sofar** [comment]
I'm not very interested in adding new features to this project anymore, but I do have a strong desire and the commitment to assure new commits meet the standards I think they need to have, and I do have the desire to also make sure mtg stays secure and doesn't bitrot. If that's not enough to remain having a vote, so be it.

**Comment by Ekdohibs** [comment]
@paramat I'm currently not very interested in adding new features either (but that might change in the future, as my involvement in mt comes and goes). I will in any case still watch for problems and fix any important bug that might come. I however don't know if you consider that enough for me to remain a core dev, or not.

**Comment by paramat** [comment]
Good to hear this, i want you both to stay devs, you're both talented and have knowledge and experience of MTG, and we need all the help we can get.

Remaining a dev is your own decision only, so i feel bad about your final comments where you may have misunderstood my intent. sofar your good intent is of course enough, it's not down to anyone else to judge. Ekdohibs i'm not remotely judging whether you can remain a dev.

After writing this i became concerned it could be misunderstood, i should have explained. I think it's good to occasionally check if devs still consider themselves devs, so i asked the more absent devs or those who had expressed disinterest.

sofar part of the reason i asked is because on a certain issue you said something like: 'i'm not interested in MTG anymore so don't listen to my opinions', it somewhat sounded like you were suggesting you shouldn't have a say in MTG anymore.

**Comment by paramat** [comment]
This issue was a bit pointless =) closing.

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-hub/2018-02-28#i_5241603 onwards.

@sofar i don't mean this unpleasantly, i think it's best you resign as a core dev from MTG as Ezhh and rubenwardy suggested. Your experience and knowledge of it is, and will still, be highly valued, you can still make PRs for it, and other devs could even add an approval to something through trust of your knowledge, so this comes at no harm to MTG. But there are other MTG dev powers i don't think you should have, like disapproving PRs or influencing the direction of MTG.

**Comment by sofar** [comment]
@paramat, you are literally the best, and the worst thing that has happened to MT at the same time.

The amount of time and dedication you contribute is unmatchable. The amount of friction you introduce in the team is also unmatchable.

I'm not going to resign. Either the team decides to remove me if they wish, as a team, and/or this thread becomes a record for what is happening with the `minetest_game` team and how the discussion is buried in negativity from your side.

I bear no grudges, but I've expressed before in less formal settings that I'm fed up with your attitude of negativity, even if it's an unfair assessment, this is how I feel about your communication style and this last reply is exemplary to your communication style.

Reading IRC threads offline afterwards is an entirely different way of skewing the narrative to your liking. In no way does the informal setting of IRC discussions determine important things like policy, governance and how to manage PRs, nor does it in any way reflect how people actually behave in PRs and technical discussions.

> But there are other MTG dev powers i don't think you should have, like disapproving PRs or influencing the direction of MTG.

Well, now that we're open about this, In an IRC setting I will gladly admit that I don't think you should have these privileges either. However, in an actual PR setting I wouldn't ever put this on the table, since it unfairly skews the discussion and completely breaks apart the trust model that the team should be able to rely on, such as being able to have open and honest discussions on an informal level and not having things misrepresented on different platforms in order to bias the narrative and the onlooking crowd, which is likely grabbing popcorn to follow what is coming next.

For this type of discussion, we should really have 1:1 discussions in IRC first to talk to people who are around, listening, talking, and thinking about how to make mtg better and how to take care of it. This is exactly what I was doing in the discussion. You were not there, and you are now using the fact that I am engaged and motivated, and most importantly, energized about fixing important issues that the community, in a completely honest and open fashion, as purported evidence against me?

I'm explicitly stating that any level of trust you had is completely distroyed in my perspective. This is not how a team should function. You are correct that something should probably change, it is only logical that the thing that should might be something else than me. Maybe you should reflect a little bit, too.

**Comment by paramat** [comment]
I just state my opinions as everyone is free to do. If i think an idea is bad i'll say so and i can be quite forthright about it (just like you or many other devs), this is not an attack on the contributor. Recently you seem to be unable to cope with me having opinions and disagreeing with something, that is your problem. The 'negativity' and  'friction' you think you see is due to some problem you have with me. MTG dev has been going very well recently, although slowly, but you're not around and not involved so maybe can't see this.

Disapproving an idea is not 'negativity' that will drive away contributors, and you only seem to have a problem with disapproval if i do it. Your recent aggressive, censorial and intolerant behaviour towards me has been quite concerning.
Consider that you are one of the most forthright devs with your opinions, which is ok, but recently you can't seem to cope with me being that way. Some of our best devs are quite forthright, like hmmmm and nerzhul, it's something we accept through tolerance.

> You were not there, and you are now using the fact that I am engaged and motivated, and most importantly, energized about fixing important issues that the community, in a completely honest and open fashion, as purported evidence against me?

I'm happy about your engagement, and i actually agree with you on some things you expressed in IRC., but this quote is ridiculous, people can read the logs to see, you have quite an extreme negative view about MTG and want it scrapped as an official MTG repo. You are also long inactive and have stated you no interest in adding anything to it. I can't see how you could keep certain dev powers in this situation.

See the logs, 2 other MTG devs suggested you resign just as i have, but your reaction to us is completely different. I was suggesting you consider it, just like the others did, not telling you to. In my post above i was also very positive about your knowledge and experience, and i value that highly. Your concern was the effect on MTG, you didn't want to walk away from it, i was trying to show that no harm would come.
Very recently i supported you remaining a MTG dev when another dev wondered why you still were, so i have a fairly balanced and reasonable attitude to this, but i didn't realise how extreme your views on MTG were.

I have a huge number of PRs in MTG and have been keeping it going, have many plans and intentions to improve it, have helped bring Ezhh in and am working with her a lot on improving MTG. Now read the linked logs, it seems you are the negative person concerning MTG, not me.

**Comment by sofar** [comment]
I consider this thread a grave attack on my opinions, but with zero evidence that I will somehow harm MTG. You solely take the IRC thread and position my statements as damning, without bothering to take any time to figure out whether I'm trying to make a point, or am actively subverting the minetest_game team.

I am, for the record, not attempting to subvert the mtg team. I am however outspoken about where I think people should be putting in their volunteer time, and explain, if you read the discussion, exactly why I think that, what my personal motivation for this reason is, and why it's worth at least considering to make sure that if people do decide to put time in MTG, that they understand what the ups and downs of it are.

I am 100% entitled to my opinions on where time is better spent. And it's entirely just to do this in #minetest-hub in the way that I did. Note the thread wasn't discussed in #minetest-dev, since I would have significantly altered it if I would have even made an argument in that channel. 

But I am certainly not vindictive or stupid enough to convert that into malicious actions towards the mtg team. Clearly, you think I'm capable of something bad or are concerned about it. And you have the audacity to publically state this, without as much a personal attempt to discuss this with the team or with me.

I'd have no issue leaving if other devs think or have concerns that I will act maliciously or abuse my privileges otherwise. In fact, if there is some required standard for developers that I don't meet, please point it out.

I've been clear I think that I do move around from problem space to problem space to resolve larger scope issues where I see them, but I've never abandoned an open source project unless there really was nothing left to maintain (like my Bukkit plugins) and I've always kept them around to make sure that either they were taken care of by capable people, or put in the time myself to help out those who use the code. If that isn't enough to warrant some trust in me, you may want to ask yourself what kind of commitment and loyalty you demand from developers, and put it in writing, so everyone knows what kind of absurd standards you maintain.

**Comment by paramat** [comment]
sofar, i'm sorry about my wording, " i think it's best you resign as a core dev from MTG" comes over as unpleasant, i was concerned about this so wrote before i didn't mean it unpleasantly, but that completely failed.

I still believe MTG devs should stay even if they have no interest in it and don't want to add anything to it, as you have previously stated, and i supported you staying very recently when others questioned it. However what you wrote yesterday is quite extreme, maybe i misunderstood some things trying to divide deliberate half-serious outrageousness from more reasoned thoughts, but you seemed serious and their were no clues to whether or where you were joking.
if you retract the more extreme and negative statements then i'm fine with you continuing as a MTG dev.

On IRC you actually suggested all MTG devs (including yourself) resign and i manage it on my own (which i completely disagree with by the way) http://irc.minetest.net/minetest-hub/2018-02-28#i_5241725
"which is fine (and somewhat the current status quo)
but then everyone except paramat should resign from mtg"
And 2 other MTG devs asked you (more pleasantly than i did) to consider your position.

I'm not attacking your opinions, you're entitled to them, you were outspoken, forthright and disapproving of something as i often am, which is exactly what you can't cope with when i do it.
I actually agree with much of what you wrote.
I'm not really expecting you to harm or subvert MTG, it's more a case of 'this doesn't make sense' in terms of your position, and i'm just a little concerned your extreme opinions will influence your authority, even if subconciously.
I do actually trust you, despite your recent concerning behaviour.

A little while ago you wrote about an issue something like '.. but don't listen to my opinion in this, i'm uninterested in MTG', you were asking us to disregard you. Now you say everyone except me should resign, so it's not a big surprise if someone questions why you are a dev, as 2 other MTG devs have.
I think you are overreacting because you are fed up with me. It's ok, we all get fed up with other devs at some point.

Sorry i wasn't in channel, i was asleep.

**Comment by jastevenson303** [comment]
Lol paramat
