### ISSUE TITLE
Tiered progression

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#2010]
A system I've seen for structuring progression in MC mods involves tiers, where entry to the each tier is gated so that some milestone needs to be reached in order to progress to the next tier. This doesn't necessarily mean tiers are explicitly tracked and locked out: the most common form of tiering is that crafting items on a certain tier requires a crafting ingredient that can only be obtained after the player has accomplished something.

Whether entry to the tier comes in the form of an item, "character knowledge", or something else, the most important part is probably what the "gate" is to obtaining entry. This could be almost anything, but theses are some examples:
* Combat: The player has to kill something to progress. Example: I don't remember too well, but I think GregTech requires a nether star to start fusing elements together, which produces heavy elements needed for some machines. A nether star can only be obtained by killing a certain (renewable) boss mob.
* Exploration: Progression requires exploring and finding something in the world. Example: One version of Thaumcraft required finding and looting dark tower structures in the world to initially obtain void materials and knowledge. With the knowledge and materials, you could create more void materials, and with those, you could in turn produce new devices and goodies and continue your progression through the mod.
* Engineering: The player has to understand the game mechanics and design a system to certain specifications to progress. Example: RotaryCraft, a tech mod with mechanical energy, has an extractor machine that is required to obtain tungsten, required for late game machines. The machine has a pipeline with four stages, where two of the stages require high torque, and the other two stages require high speed. Before getting to the next tier, the player does not have the ability to deliver both high torque and high speed simultaneously, so they have to design a system that will alternate between providing high torque and high speed.
* Resources: The player needs a lot of a material before producing it efficiently. Hypothetical example: you need 10 nyan cats to build a nyan cat generator, and then you just need to feed it wheat to produce more nyan cats.
* Social: Progression requires having multiple players coordinating. Hypothetical example: a religion's deity can obtain power from its followers (players) by prayer or by offerings. Offerings can produce much more power, but they require the deity to light the shrine's braziers, which cannot be powered by prayer alone with less than five followers.

Within each tier, in addition to actions necessary to progress to the next tier, you usually also get other benefits, such as ore multiplication, magic powers, etc., increasing in power as you go up different tiers.

I don't think there is much of this kind of progression in any current Minetest mods. Technic could be considered to have two tiers: before and after getting LV machines. With a full set of LV machines you gain access to every technic machine and then the only activity players are left with is optimize their resource processing. This isn't that interesting of a tier structure

Do people want MTG to have some kind of tiered progression (not necessarily science-themed)?

Someone will probably say that tier-based progression is a skinner box technique to produce a false sense of accomplishment, and everything in a mod should just be available early on, or that this essentially creates a goal (gain access to all tiers), which doesn't belong in a sandbox game like MTG. The point of tiering doesn't need to be the goals or accomplishment itself, though. The milestones that tiering directs players to can be chosen so that they develop the expertise needed to enjoy the game fully, like in RotaryCraft.

**Comment by Ezhh** [comment]
Lack of meaningful progression has been my biggest long term issue with MTG. 
- You can skip most tiers of tool. 
- There is not much reason to explore and find other biomes beyond different nodes to build with and just looking at them. 
- Nothing about your abilities (how much damage you can take / how fast you can move / crafting you have access to and so on) ever really changes.

The problem is - what type of progression would both fix this and fit in MTG? Combat won't work (no mobs), social is probably a bad idea (must support singleplayer), and the resource approach would be a massive shift in how things work. 

Finding items via exploration is likely the best way, but the items need to contribute to things you will actually make and that will give that sense of progression (unlike whole levels of tool which do require you to dig deeper and deeper for the right ores, but that you can currently skip without missing).

**Comment by Ferk** [comment]
Some time ago, when tin was introduced, I suggested requiring an upgrade for the oven in order to be able to smelt steel, so that there's a technological progression, a sort of "bronce age", during which you use bronce items until you are able to smelt steel.

In nature, iron is easier to find than copper+tin but it's not as easy to smelt as bronce, for several millenia bronce was the chosen material for weapons and tools, because iron has a higher melting point. You need a bellows or blower to be pumping in order to make the coal burn with more oxygen so it reaches higher temperature.

Maybe some sort of blowing device could be placed next to the Minetest oven as a requirement for efficient production of steel. Maybe have the device require bronze and paper/cloth as crafting ingredients.

**Comment by tenplus1** [comment]
That sounds a good idea Ferk...  We could have basic iron which is weak but can be used to make bronze and if the bellows are used beside a furnace eventually hard steel :)

**Comment by Ferk** [comment]
> We could have basic iron which is weak but can be used to make bronze 

Bronze is made with copper and tin, you don't need iron. Previous MTG versions did use iron+copper for bronze, it's a good thing that it got changed, it's misleading.

**Comment by raymoo** [comment]
I brought up tiering in general, but I didn't mean to look for ways to apply it to the current content. This is because getting better tools doesn't open up that many more features, it's just an incremental improvement in digging speed / punch damage. There isn't really anything to gate behind tiers.

**Comment by Ferk** [comment]
Steel is used in more things than just better tools (minecarts, flint and steel, screwdriver, locked chest, fire-resistant doors/signs...), and even if it was only used for better tools, it could easily be made so only higher tier tools can be used to obtain higher tier materials.

**Comment by paramat** [comment]
Yes progression is potentially good, but whether to apply it to a feature, and how to apply it, will depend on each specific feature, a theoretical discussion of whether it is generally desirable is perhaps a little vague. Any specific ideas?

Some exploration progression occurs in survival mode due to finding specific biomes, ores and nodes to craft certain items:
1. Find rainforest for junglegrass for cotton seeds for wool for bed.
2. Find Copper and tin ores to create bronze, and obsidian for obsidian glass, to craft binoculars to enable zoom and loading of distant world.
3. Find savanna for papyrus for paper for a mapping kit to enable the minimap.

**Comment by tacotexmex** [comment]
> Maybe some sort of blowing device could be placed next to the Minetest oven as a requirement for efficient production of steel.

Check out the WIP [workshops](https://github.com/FaceDeer/workshops) mod. It introduces carpentry, dyer, forge, kitchen, loom, masonry, mechanic, smelter and although that may not suite MTG, inspiration could be drawn from some of it.

**Comment by paramat** [comment]
This is vague, even if we agree it's a good idea, there is no submission of an actual feature, and each progression feature will be decided upon individually. Better to approach this by submitting an actual feature when there is one.
