### ISSUE TITLE
Enable showing and hiding of player names

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest_game#2011]
Minetest should allow to hide and show the player names that are above their head.
I would suggest merging [this mod](https://github.com/Ezhh/name_hider).

**Comment by paramat** [comment]
That mod is for server admin only not for players, do you want this choice for players too?

There is an issue in engine https://github.com/minetest/minetest/issues/4193 to enable clients to choose whether to display nametags in some other way other than F1, because players will often want to have HUD enabled, i think this is better done in the engine.

**Comment by paramat** [comment]
Apparently there is a serverside way to hide or show nametags to all clients:

> You can hide nametags by using player:set_nametage_attributes({text = " "}) and show/restore them to their default text by player:set_nametage_attributes({text = ""})

Also each client can remove nametags clientside by using F1.
So what specific functionality do you want?

**Comment by 4w** [comment]
> Also each client can remove nametags clientside by using F1.  
> So what specific functionality do you want?

You mean except hiding nametags without hiding the whole GUI?

**Comment by paramat** [comment]
Yeah we do need the ability to hide nametags clientside independent of F1.

**Comment by TekhnaeRaav** [comment]
>I wanted this on the server side as a universal player setting

but looks like you already got it covered. 😄
