### ISSUE TITLE
Let player crawl

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest_game#2013]
This is a copy from https://github.com/minetest/minetest/issues/6893 and I'm not sure that this should be added to minetest_game.
> I think this could be a mode which player can enter and quit. In this mode player's height is 1 block, his/her velocity is lower and many other limitations.
> Purpose of crawling is for example dodging an incoming arrow or bullet or passing a small hole.

**Comment by rubenwardy** [comment]
please do not open duplicate issues, instead comment on the closed one

**Comment by paramat** [comment]
I think this issue belongs here not in the engine, the engine side of things is controls only which seems covered by existing key binding issues.
MTGame would provide a 'crawling' player model and reset the collisionbox and eyeheight to be low.

**Comment by stujones11** [comment]
I could probably do the animation if the concept were to be approved, though it would require its own key-binding. I have often thought that 'sneak' should have this effect but that would be controversial, to say the least :)

**Comment by paramat** [comment]
Let's wait for controls to make it possible first.

**Comment by 4w** [comment]
> Let's wait for controls

For how many years fully customizable controls are requested now?

**Comment by sorcerykid** [comment]
As both a game designer and player, I would find crouch more useful than crawl in a variety of scenarios. It would probably be easier to create a half-way decent animation for the player model as well. (I can't even imagine what a player crawling would look like in Minetest).

**Comment by CBugDCoder** [comment]
If we wanted to use the current controls we could make double-tapping sneak toggle crawl/crouch

**Comment by paramat** [comment]
Any core dev support for this (once the engine makes it possible)?

**Comment by Ezhh** [comment]
It would be good if it was possible in the engine, but it would be without a specific use in MTG. MTG would first need a reason for players to use it (I don't consider digging one block high tunnels a good reason).

**Comment by paramat** [comment]
Yes that's my opinion too.

**Comment by jastevenson303** [comment]
perhaps not digging one node high tunnels in particular, ezhh, but
certainly useful for traversing one node high tunnels.

**Comment by paramat** [comment]
The player will almost always be able to dig the tunnel to be 2 nodes high, as this is a mining game.

**Comment by jastevenson303** [comment]
Don't sell yourself short.

Now that player's collision box can be changed, this is an all around good
idea and important feature to have.

**Comment by Ezhh** [comment]
@jastevenson303 If you want it, instead of applying pointless downvotes to my comments, give us a useful reason to include it. 

Being able to adjust collision box could indeed be combined with this, but by my thinking that would work better in a game where you actually change the player's size for some reason. MTG doesn't have anything that calls for this, and one node high tunnels is lazy and enabling that would be a huge change to the game for no good reason.

So :-1: unless someone can justify it. Otherwise, go make a mod that includes it, then you can still use it any time you like.

**Comment by jastevenson303** [comment]
The use case is crouching.

**Comment by Ezhh** [comment]
And the use case for crouching is....?

**Comment by jastevenson303** [comment]
Crouching.  It's the same for opening a chest: The use case is opening a chest.  Minetest Game is a base game, meant for expansion.  It lacks a lot already, why not open it up?

**Comment by LoneWolfHT** [comment]
I don't see the point in having crouching in Minetest Game. But it would be nice if it was possible for mods to add it

**Comment by jastevenson303** [comment]
Well, I do.

**Comment by DS-Minetest** [comment]
Currently gaps that are only half as high as the player are barriers. Giving the possibility to crouch to get through such gaps would make sam less robotic. Of course crouching would have to be very slow.

**Comment by benrob0329** [comment]
I think that making the player 1.5m tall when sneaking could be a good compromise (and would allow passing though some spots eg from under a pine tree where the snow tends to trap you).

**Comment by sofar** [comment]
I'd love to see a mod/implementation of this. This is not simple as it will need to account for a lot of things. Once there is some working code, then it's a good idea to discuss inclusion. The other way around isn't very productive, as the discussion turns sour quickly.

Maybe this ends up as something great. Maybe this will cause massive amounts of grief because now everyone can crawl into 1x1 holes left for decoration.

**Comment by jastevenson303** [comment]
Thank you for being the voice of reason, sofar.  I can now better understand Ezhh's point.  Anyone can "go and mod it [themselves]" and should probably do so, so that it may stand a chance of being included.  I also liked benrob0329's compromise.

**Comment by Ezhh** [comment]
> It's the same for opening a chest: The use case is opening a chest.

You open a chest to be able to place and remove content into and from storage, which is a useful game feature. Crouching on the other hand would just add itself based on the current discussion, which isn't good enough. It would need a purpose.

I'd also love to see a mod do this and may well change my mind about it being added to MTG if a good and useful implementation is demonstrated through a mod.

**Comment by jastevenson303** [comment]
Well you crouch to get through tight spots, which is also arguably a useful game feature.  It doesn't matter though, this is a feature I like, and you don't seem to, and I'm all right with that.  Have a nice day.

**Comment by paramat** [comment]
Remember:
> The player will almost always be able to dig the tunnel to be 2 nodes high, as this is a mining game.

If this was a game engine with a world you couldn't mine then this might be useful for small gaps.
The only 1-high gaps in MTG are under low branches, but leaves can be mined by hand, and you can almost always easily walk around the tree.

Some arguments here are for adding crawling for the sake of adding crawling because people like the idea of crawling even though there's no justification, there's no benefit or need but a lot of modelling work.
I support the engine making this possible, but this is unnecessary and specialised so belongs in a mod.
> I think that making the player 1.5m tall when sneaking could be a good compromise (and would allow passing though some spots eg from under a pine tree where the snow tends to trap you).

1/4-node slabs like snow no longer trap the player as the new player model is shorter.
The same arguments apply to semi-crouching, no benefit or need.

Once this is possible and someone has written a mod, and if some usefulness somehow arises we can discuss this again.
