### ISSUE TITLE
Improve 'killme' mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2033]
~~No idea why we added this, should be in builtin if it is that useful, it is not game-specific.~~
~~EDIT: It seems this might be a universally useful feature for all games so is perhaps best in builtin?~~
See https://github.com/minetest/minetest_game/issues/2033#issuecomment-414838401

**Comment by rubenwardy** [comment]
It's game play specific, which is why it's here

**Comment by Ezhh** [comment]
I've always felt it shouldn't be included. With that said, people will not be used to it and may moan if it's removed.

With that said, in the absolute least it should be a more generically named "commands" mod instead with the potential for expansion, rather than a whole mod devoted to one specific command.

**Comment by paramat** [comment]
Sorry rubenwardy that's a good point. I now see i supported this, approved it and merged it, duh.
Is there a case for a certain game not having access to this, since it's for a player in an unescapable situation?

**Comment by Wuzzy2** [comment]
This shouldn't be in builtin. Since it works without privilege, it's a gameplay change.

Yes, there is a case for a subgame not needing it. Take Labyrinthus for example. Or the Inside The Box server. Or basically any game in which suicide is discouraged.

I have no opinion about keeping it in MTG or not. This is a subgame decision.

**Comment by jastevenson303** [comment]
Once more for the record: It should be `kill`, not `killme`.

There's a world of difference, there.

**Comment by jastevenson303** [comment]
https://github.com/jastevenson303/dcbl_default/blob/master/serveressentials.lua#L139

Here I have modified GunshipPenguin's `kill` command to assume the issuer is the recipient if no argument to the command was provided.  `kill`, in this case, is general.

```lua
minetest.unregister_chatcommand("killme")
minetest.register_chatcommand("kill", {
	params = "[player name]",
	description = "Set HP to 0.",
	privs = {interact = true},
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		if not player then
			return false, "Player not found."
		end
		if param == name or param == "" then
			local player = minetest.get_player_by_name(name)
			if not player then
				return false, "Player not found."
			end
			player:set_hp(0)
			return true, "Setting your HP to 0."
		elseif players[param] and minetest.check_player_privs(name, "kill") then
			minetest.get_player_by_name(param):set_hp(0)
			return true, "Setting player's HP to 0."
		end
	end
})
```

**Comment by paramat** [comment]
Thanks for input, i won't pursue this further.

**Comment by paramat** [comment]
> in the absolute least it should be a more generically named "commands" mod instead with the potential for expansion, rather than a whole mod devoted to one specific command.

Reopening as i agree with Ezhh this needs work.
The mod name is unpleasant.
The mod lacks README and license.
