### ISSUE TITLE
Change of the chest opening behaviour

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest_game#2045]
Currently when you open a chest you need to wait a bit for the animation. l'd like to change this behaviour because waiting for the animation is annoying and unrealistic (imo): Players right click them, wait until it opens and then view the inventory.

Instead I think it should work this way:
* right click on a closed chest: open it
* right click on an open chest: show formspec
* punch an open chest: close it

Players would click to open, 
then click to access.
In reality you can open chests fast and harshly or in the slow quiet way.
You need to click the chest two times to open, so the time delay is still there but it depends on the player's experience.
The animation can be kept of course. You could use the previous click time(s) to determine the animation's speed to make it look realistic.
If you want to close the chest automatically if nobody is there, you can simply use the get_staticdata function of the chest lid object.

This fixes #2031.

**Comment by sofar** [comment]
nah, let's not make it more complex.

**Comment by Ezhh** [comment]
Needing to click a chest twice to open it doesn't really appeal to me.

Also how would this work for chests that have a node above them?

**Comment by JurajVajda** [comment]
2 user actions to get 1 feedback - bad ux
Binding 2 different keys to do the same action - bad ux

**Comment by paramat** [comment]
The wait for the animation is only a very short time, and is intended so you see the animation.
The new system won't make accessing a chest any faster but it will now take 2 clicks instead of 1.
It's not often that a player will intend to leave a chest open to access later, usually when you exit the formspec you have finished with the chest and want it closed.
Having chests stay open when leaving formspec complicates chest code.
:-1:
