### ISSUE TITLE
Kelp can float

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2053]
Kelp on sand doesn't fall like it seemingly should; perhaps it could drop as an item if the block under it is removed. Also, it seems like kelp should self-destruct if the water above it is removed, but this may not be possible. Just a small issue.

P.S. I apologize if this has already been fixed. I looked over the code and saw no indication that it had been.

**Comment by Ezhh** [comment]
I'm not sure if the first part should be classed as a bug. To my thinking, the sand having something growing from it would anchor it and make it fall less easily. 

For the second part, ideally you shouldn't have kelp waving about in air, but it does take quite some effort to remove the water (it's renewable), meaning this seems only likely to happen when people cause it intentionally. Since removing water doesn't do anything to the actual kelp node, I'm not sure if there is a good way to change it.

**Comment by random-geek** [comment]
> To my thinking, the sand having something growing from it would anchor it and make it fall less easily.

To my thinking, no other plant can float and neither can sand, so I see no reason kelp on sand should be gravity-defying.
Just an opinion.

**Comment by Ezhh** [comment]
Just because sand by itself would usually fall doesn't mean it will fall when it has something growing in it. 

And another thing to think about: if kelp were to become detached from the seabed, it actually would float, not fall.

Also just an opinion.

**Comment by jastevenson303** [comment]
Then it would float to the top, Ezhh.

**Comment by paramat** [comment]
We forgot to try falling, perhaps we didn't expect it to work on this special drawtype.
Trying 'falling_node = 1' does work but creates a sand node entity out of nothing.
'attached_node = 1' causes the sand node to fall and the kelp item to be dropped, so could be done.

Removing if water is removed above is not practical, as water can flow away due to engine liquid code, it would be too intensive to search for and remove water plants every time a water node flows away.

**Comment by Ezhh** [comment]
@jastevenson303 No, it goes wherever it likes and twists about as the water takes it. I've swam in the sea enough times to know. Either way, my point was that it doesn't simply fall and land neatly on the seabed. We'd be trading one thing for another if we do that.

@paramat I expected it could work, but didn't like the idea. I still don't. I would like if we could fix the other point, but I also can't see a good way to do that without too many checks.

**Comment by paramat** [comment]
Falling is buggy anyway, and i'm neutral about 'attached_node = 1'.
The water checks thing is not remotely practical, it would completely destroy liquid processing performance.

**Comment by paramat** [comment]
So closing.
