### ISSUE TITLE
Add Bats as plantlike

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest_game#2067]
##### Issue type
 - Feature request

##### Summary

Had the idea, thought I'd throw it out there real quick: You put fireflies in as a plantlike, you could add bats that work the same way but spawn underground. Also you already will have the net for retrieving them to, they would add some life to the underground and make a good decoration for a mansion or anything else.

**Comment by Ezhh** [comment]
This is something I've been considering (actually for butterflies, instead of bats, but the general approach would be the same). 

I believe an animated texture could utilise the plantlike drawtype so that we create the impression of wings flapping. I'm not going to promise it will be MTG worthy, but playing around with it is at least on my to do list once fireflies are completely finished up.

**Comment by Ezhh** [comment]
Butterfly concept showing flapping wings:
![mt_butterfly](https://user-images.githubusercontent.com/7035183/36941116-60ca52ec-1f4b-11e8-88e4-d20c896858fa.gif)

**Comment by paramat** [comment]
The plantlike approach is excellent for insects but i feel that bats are in a different class of mobs that needs and deserves more complex behaviour and would not work just randomly flapping around in one place as insects often do.

**Comment by TekhnaeRaav** [comment]
This is a mod thing :+1:
