### ISSUE TITLE
Introduce cave gases

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2074]
Generates in caves underground (pregenerated or via abm), possibly behaves like a "liquid", source at ceiling, invisible, large pockets, three possible kinds:
+ dead air (aka suffocating gas) - player slowly suffocates
+ explosive air - explodes during contact with torch, lava, fire or during tool use (probabilistic)
+ corrosive air - tools degrade much quicker during mining

This offers a great challenge and danger to mining, as in real life, adds actual challenge.

**Comment by paramat** [comment]
This would require the ability for biomes to add custom 'air' nodes, which is somewhat intended in the engine #5725
If a liquid, a problem will be that any liquid underground can spread infinitely down through tunnels and spread into massive floods in caves, with the possibility of overloading the liquid processing code and becoming intensive. Underground we have to be careful with liquids.
I would prefer an airlike node that just stays where it is.
I'm neutral on the feature.

**Comment by paramat** [comment]
Engine PR https://github.com/minetest/minetest/pull/7241

**Comment by TumeniNodes** [comment]
Just to key in on this, I think it is a good idea.
I have also thought it would be interesting to have torches placed on, or maybe next to coal ore, (and possibly even mese ore) to cause an explosion.
code from tnt could be utilized to create this effect.
SO I would keep "explosive air" down to reaction to torch, if it is set for lava it is a candidate for lag due to the processes which will happen in areas generated with lava, and might be too much strain.
Explosive air should also be limited to generate only as a chance, and only in or around coal ore.

The gases idea could be good if could be that coal gases can cause an explosion (as mentioned above) and there could be a chance of coming across poisonous gases in caves with lava, which can be set to give the player time to escape to an area with better air.

The poisonous gases idea, leads way for mods related to breathing aparatus, and even possibly potions to combat the effects, etc.
These sort of ideas definitely add to more interesting gameplay (even without mobs)
It would be nice to have such interesting challenges built into the game itself.
But they need to be set as chances, not for every instance. That way it builds even more on the intensity.

**Comment by Ezhh** [comment]
Just some quick thoughts for if we start adding in dangerous environments: 

1 - if players have no way to notice a danger until after it hits, for example if the air looks normal and placing a torch then makes the surroundings (and yourself) explode, that's annoying and can make it feel like the game is "cheating". The player needs to be able to notice something isn't quite right.
2 - increased danger should generally come with increased reward. I'm keen on adding different air types, but it should be introduced along with new underground content that makes the danger worth facing.

**Comment by TMcSquared** [comment]
`cough` `cough` ny-`cough`-an c-`ough`-ats

But seriously, something of that caliber of rarity might be reason enough.

**Comment by Fixer-007** [comment]
>The player needs to be able to notice something isn't quite right.

Maybe generate some weird particles?

**Comment by alexdevteam** [comment]
Suffocating gas should lead to hallucination or making the player's vision slightly darker over time

And also, if there was exploding gas on caves with lava, wouldn't it self-explode?

**Comment by TMcSquared** [comment]
Wouldn't that happen IRL?

**Comment by FaceDeer** [comment]
As an interim measure, I've added explosive/suffocating "mine gas" in the [oil submodule of df_caverns](https://github.com/FaceDeer/dfcaverns/tree/master/oil). It looks a little chunky since I can't use the liquid drawtype with it (I think there's an issue filed elsewhere requesting the ability to make liquids "unswimmable") but it "flows" and is unbreathable and if it's adjacent to both torches and breathable air an explosion ensues.

**Comment by jastevenson303** [comment]
liquids are unswimmable when/with `walkable=1`

**Comment by paramat** [comment]
No core dev support for a year, and the engine feature is needed first, could reopen if/when it is and if any core dev support.
