### ISSUE TITLE
Add sprint mod

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#2094]
* https://github.com/octacian/sprint/
* https://github.com/rubenwardy/capturetheflag/tree/master/mods/sprint

**Comment by Ezhh** [comment]
Would this not interfere with every server / game where people have added something else that uses physics overrides?

**Comment by octacian** [comment]
That is a good point. Maybe something similar to the [player_monoids](https://forum.minetest.net/viewtopic.php?t=14895) mod should be implemented first, either here or in the engine.

To be completely honest, I think that the features provided by sprinting mods would be best implemented in the engine itself. Sprinting speeds could be configured server-side, and controlled using physics overrides just like other physics-related variables are already. Since this should usually be available to all players by default, it could be implemented under a new permission, such as `sprint`, leaving `fast` in place for super-fast-movement and super-fast-flying-movement. This would also take some possible load off of the server and decrease lag for the player as the actual sprinting could be handled by the client. This could be especially important for more advanced features that I'd like to see, some of which are already implemented in my mod and others that I am planning. Several of these are:

* Stopping sprint when the player bumps into an object
* Slowing sprint in water (implemented in my mob)
* Decreasing the amount that sprint is slowed in water if the player is touching a solid block at the bottom

A simple sprint API could be added for both the server and client, allowing mods to force or prevent the player from sprinting, and register callbacks to be called when the player starts, stops, and is sprinting. With this API, mods such as those that implement hunger could integrate with it.

**Comment by paramat** [comment]
For MTG i prefer this stays as optional mods. MTG has never had 'sprint' because the approach is that there is one speed set to a slow run: 4m/s, and there's no point in going slower than that, we have sneak for slow movement. This is a mistake MC made, resulting in MC players running everywhere and needing a special control usage to do so.

Aso, we already have 'fast' which is often used as a 'sprint'.
:-1:

**Comment by Ezhh** [comment]
@paramat Fast is a very poor sprint because it also allows all kinds of crazy unrealistic movement. I also have no clue what you mean by "special control usage"... plenty of mods have this working just fine in terms of controls.

With that said, I would only support this if the underlying issue with physics overrides can be addressed first.

**Comment by rubenwardy** [comment]
Fast has no cost to it. Sprint is a way of doing fast whilst consuming some form of energy. It makes fast movement practical and balanced.

Having sprint in MTG would encourage the engine to offer more efficient support for controls than polling, and it's a good demonstration of use of controls. It also requires a better way of resolving physics, which is something either the engine API or a MTG mod should provide

> special control usage

Sprint uses the same key as fast, no special controls there

**Comment by paramat** [comment]
I mean fast with a speed configured to be lower, but i am unaware of the special movement abilities because i rarely use it while on the ground, what are they?

By special controls i was referring to MC. Do some sprint mods allow toggling of sprint? If so i retract that argument.
>  Sprint is a way of doing fast whilst consuming some form of energy.

We don't have hunger so there's no cost, do you propose hunger to be added too?
> Having sprint in MTG would encourage the engine to offer more efficient support for controls than polling, and it's a good demonstration of use of controls. It also requires a better way of resolving physics, which is something either the engine API or a MTG mod should provide

This is a non-argument, these can and should be done anyway with or without sprint in one game.

**Comment by Ezhh** [comment]
Changing fast like that seems quite inconvenient for something that should be a basic feature and the cost of sprint doesn't need to be hunger. 

> Do some sprint mods allow toggling of sprint?

Controls are simple: hold E (or whatever other key you have set for this) while not flying to move faster. If you have the fast priv, it uses the priv, otherwise it uses sprint and consumes whatever resource is selected, be that hunger or stamina or something else.

**Comment by paramat** [comment]
Yes edited my comment, E is not uncomfortable for forwards.

I'm concerned about changing jump distance, we really need to make MTG mods disableable, for parkour worlds, or add a mod option.

I don't see any need or use for sprint in vanilla MTG and see it as a specialist movement feature. I prefer MTG stays a simple mod base, or rather, i can't see it being anything else as it seems no-one has enough time or interest (including myself) to develop it into a complete game and maintain it as a complex game, so i feel it's best to resist adding specialist features.

**Comment by rubenwardy** [comment]
Spenting is very common and I wouldn't regard it as specialist

**Comment by Ezhh** [comment]
> ... no-one has enough time or interest (including myself) to develop it into a complete game and maintain it as a complex game

Complete and complex are two different things.

And yes, this should be optional, but so long as it's a separate mod, the mod can just be removed.

**Comment by benrob0329** [comment]
Technically MT has sprinting, if you turn down the speed of ``fast`` it becomes a very nice sprinting mechanic (even if you need a mod for revoking fast on stamina drain/hunger drain).

Personally, I have heard complaints that most sprint mods use only stamina, which runs out quickly rather than increasing how much hunger is used over time.

**Comment by paramat** [comment]
Actually 'fast' is not good for sprint as it can't come at a cost, i also think it is best kept as a super-fast admin/creative speed which is what it is for.
Sprint is common in games yes but other games are complete games that have a reason for it, i can't see much reason in MTG.
> Stamina really has to be part of a game-wide consideration of hunger / health / stamina, not just thrown in in a single mod.

I partially retract this, but adding stamina inevitably raises some questions about other aspects of movement, stamina, hunger and health. I can see why stamina is used in a separate mod as a way to find a cost, but as part of a game it seems a little inconsistent. There may be a solution to this though.

**Comment by JurajVajda** [comment]
I would rather prioritize adding hunger first before adding sprint..after that sprint will make more sense

**Comment by Ezhh** [comment]
I would much prefer sprint does not depend on hunger.

**Comment by JurajVajda** [comment]
So how do you prevent sprint being infinite? Will it take the health bar down, will it have timer or just it will be infinite?

**Comment by jastevenson303** [comment]
Sprinting is to stamina as hunger is to satiation.  You may link them, but
they are often times not.

**Comment by Ezhh** [comment]
@JurajVajda Check how this works on rubenwardy's CTF server.

**Comment by JurajVajda** [comment]
It depends on stamina instead of hunger... that sounds reasonable..thanks

**Comment by tenplus1** [comment]
I dont like the idea of having too many status bars on screen if possible.

**Comment by LoneWolfHT** [comment]
>sprint icon
That would be interesting

**Comment by 4w** [comment]
> Sprinting is very common and I wouldn't regard it as specialist

I'd say a sprinting mechanic is so common that the engine should have an API for it so sprinting can be directly controlled/changed via mods.

**Comment by paramat** [comment]
I was wrong to say it's specialist. But 'being common' is not a valid reason to add it to MTEngine or MTG. Computer games are very varied so the featires they have are usually irrelevant to MT. Many of them have it because it is a necessary part of their gameplay and has a function. There are many engine and game features that are common but that would not be right for MT.

At the moment i don't see a good reason in MTG because it is a simple mod-base type game that lacks anything that needs sprint, there's nothing to run towards or away from, no time pressure to need speed. Our movement speed is already a slow run at 4m/s so is obviously designed to be a middle-ground between walk and run, to not need sprint. Maybe if MTG develops further there may then be a good reason for sprint.

I see more reason to support it in MTE as i expect many MT games may have a need for it.

**Comment by sorcerykid** [comment]
I really wish that sprinting could be implemented in the engine itself, including a formal API. Constantly checking key states in a globalstep callback is a hack, at best. This would be more suitable for CPP (which already handles other player movement like climbing and jumping) with appropriate settings available in Lua, possibly via physics override or other methods of the player object.

**Comment by paramat** [comment]
I disagree with this being in the MTG roadmap. It doesn't have clear support from other core devs.
I disagree it is a fundamental or necessary feature (i don't care what other games do or how many have sprinting, that's irrelevant, games are free to be different from other games).
It seems best left to optional mods, there are many to choose from already so people can choose one that suits their taste.
I disagree MTG has to be a complete or impressive game, that is far better done with a new game.
(sorry, and i don't mean this to sound harsh).

**Comment by paramat** [comment]
Closing due to #2710
