### ISSUE TITLE
Add wield3d

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#2097]
Wield3d is quite an important mod for multiplayer, whether co-op or PvP.

* How do existing mods perform?
* Will entity bugs break the practicality of this?
* What about seeing the wield in 3rd person mode?

**Comment by Fixer-007** [comment]
>How do existing mods perform?
There are at least two mods that provide this (from my memory):
* wieldview, included in "3D Armour" by stujones11: https://github.com/stujones11/minetest-3d_armor/
* wield3d by stujones11: https://github.com/stujones11/wield3d
From what I've seen they mostly do their job, without game breaking, but have some rough edges I will describe below:
** occasional 180deg tool reversal in hands of other players (not sure many even noticed this)
** not all is rendered in hands when in 3rd person modes

>Will entity bugs break the practicality of this?
I never had any problems with this on actual servers making it not practical.

>What about seeing the wield in 3rd person mode?
Works partially, I did test it on Hometown just now, items, tools show up, but blocks are not, it seems.

@stujones11

**Comment by stujones11** [comment]
The biggest problem with wield3d currently is the 180 degree reversal glitch with b3d model attachments, see https://github.com/minetest/minetest_game/issues/1447#issuecomment-265825919

While we can get around that problem by tweaking the animation key-frames, as I have explained later in that issue and elsewhere, I would prefer to find a better solution. However, this may turn out to be our only option if the problem lies with the rendering engine.

> How do existing mods perform?

Shouldn't be a problem in most cases, although the ability to specify attachment position/rotation would probably be helpful. wield3d does this by exposing a global table which is far form ideal.

> Will entity bugs break the practicality of this?

Historically, stray objects have been a problem for this mod but I think this is less of a problem with recent versions. https://github.com/minetest/minetest/pull/6786 would also probably be helpful in this regard.

 > What about seeing the wield in 3rd person mode?

Absolutely you should, however there is a MTE bug that causes the wield item to disappear when the attachment rotation changes, see https://github.com/stujones11/wield3d/issues/2

Ultimately I would love to see something like wield3d included in the base game though I am not sure the mod should be added as-is. IMO it would be best incorporated into the the player_api mod where you already have access to the individual player objects.

**Comment by Ezhh** [comment]
Just to add, I am massively in favour of seeing this added.

**Comment by stujones11** [comment]
> Works partially, I did test it on Hometown just now, items, tools show up, but blocks are not, it seems.

This sounds more like my wieldview mod where the wield item is actually part of the 3d_armor model. Consequentially, this does not involve the use of entities nor does it suffer from attachment glitches, however, it is very limited in terms of item shape as it only works with items that can be extruded from their inventory image. Cubic nodes can be optionally displayed as tiles but this is off by default as it looks pretty lame, IMO.

**Comment by sofar** [comment]
I think a good compromise would be to add a non-entity based wieldmod. Cube nodes can be represented with an extra mesh part where you map 1 tile to that wieldcube. Can't do stairs and slabs, but it'd still be a major improvement. An out-of-tree mod could then override that with an entity based one.

**Comment by stujones11** [comment]
> I think a good compromise would be to add a non-entity based wieldmod.

I have to disagree, the 'extrusion' method used by wieldview is very costly in terms of additional rendering unless you use a simple flat 'sprite-like' wield item, which is a poor compromise IMO.

We already have much more efficient item extrusion built into the engine so we might as well use it. Adding a single entity per-player should not cause any noticeable server lag, it's really no more costly than say hp gauges, for example.

Of course, whatever way the feature is implemented it would need to optional anyway.

**Comment by rubenwardy** [comment]
I think it's better to use an entity here, and fix any bugs the engine throws at us

**Comment by stujones11** [comment]
@rubenwardy This reminds me, If this were to be included as s a separate mod then it should probably be done in much the same way as your gauges mod re-work as that solves many of the per-player entity problems in a more elegant way than my current wield3d implementation.

**Comment by stujones11** [comment]
Regarding the wieldview extrusion, there is another method that is a lot more efficient but restricted to a fixed pixel resolution. In other words, it would not play well with hd texture packs.

Essentially it's just a grid of cubes uv mapped to individual pixels. It works quite well but far to restrictive. I just thought I would mention it for completeness :)

**Comment by paramat** [comment]
We have a PR for optimisation of engine extrusion, it removes internal faces.
Nice feature, i assume it will only insignificantly affect FPS and game performance?

**Comment by paramat** [comment]
Yes i'm not really worried because i can't really see how it could be intensive, but checking because i'm not very knowledgeable on how it is implemented.

However, a note on the 'most servers' argument: Even if most do use a mod for this already, many also don't, and the mod was added by choice which is different to adding a feature as standard in our simplest MT game.
For example, most servers add 'moretrees', which is an extremely overcomplex, slow and laggy mod that would never be added to MTG.

'Noticeable' is not a good way to judge lightweightness, noticeable is around 100ms which is a huge amount of time in code. But i think i know what you mean, it's insignificant even by code time standards.

**Comment by stujones11** [comment]
Okay, those are fair points, although I was not using to 'most servers' argument as a reason to add this mod, it was more as a reason why there will not be any performance hit in most cases :)

**Comment by Fixer-007** [comment]
Add this to roadmap https://github.com/minetest/minetest_game/projects/1

**Comment by raymoo** [comment]
Just want to say that for rendering, delays are noticeable at much less than 100ms delay since the delay happens every frame.

**Comment by stujones11** [comment]
FWIW, I have updated my wield3d mod borrowing some ideas from rubenwardy's re-work of the gauges mod (suggested here https://github.com/minetest/minetest_game/issues/2097#issuecomment-375922552) This should hopefully make the mod much more robust and efficient in a busy multi-player environment.

Using the player model I adapted for my 'SAM-Viewer' app (available here: [here](https://github.com/stujones11/minetest-models/tree/master/character/sam_viewer) appears to solve the 180 degree reversal issue, albeit not in a way I am completely satisfied with, it's the best I got right now. This can be used as a direct replacement for the current model (offset and scaling should be correct)

The only real remaining engine issue is the third-person visibility problem, however, there is what seems to be a working fix here: https://github.com/minetest/minetest/pull/8342

There may still be a small amount of latency/inertia, especially when moving very fast but this is the case for all attachments that are not made directly to the 'root' bone.

**Comment by paramat** [comment]
Closing due to #2710

**Comment by runsy** [comment]
Please, reopen. Not solved. I've created a new model from stracth and the ghost wield item issue appears.

**Comment by appgurueu** [comment]
> Please, reopen. Not solved. I've created a new model from stracth and the ghost wield item issue appears.

Consider using [my mod](https://github.com/appgurueu/visible_wielditem) instead and see if it fixes the issue. As for MTG, this is closed due to the reasons stated by paramat.

**Comment by runsy** [comment]
Your mo0d is cool but it does not resolve the issue. I will try to rework on my model as MTG model, but the bug is there, Blender export or Irlich.

Plase, a dev can reopen?

**Comment by rubenwardy** [comment]
Minetest Game is in feature freeze, adding a wield item is out of scope

**Comment by appgurueu** [comment]
> Your mo0d is cool but it does not resolve the issue. I will try to rework on my model as MTG model, but the bug is there, Blender export or Irlich.
> 
> Plase, a dev can reopen?

That's more like a bug report then, and adding such a mod inside MTG isn't going to fix that. I have reported that bug already BTW (assuming that's what you mean by "ghost wielditem"): #11991
