### ISSUE TITLE
Fix removed blocks/items/mobs

### ISSUE THREAD

**Issue by stas730** [minetest/minetest_game#2102]
There were some removed blocks/items/mobs in Minetest Game. They should be removed from the world instead of being Unknown Node/Unknown Item/Unknown Object.

**Comment by Ezhh** [comment]
Can you confirm what was removed?

Is it possible you disabled a mod that is not part of minetest_game, and that caused the unknowns?

**Comment by Ezhh** [comment]
minetest_game is only one specific game. If minetest_game has removed something and you have a problem as a result (for example, if it's to do with certain cats or certain rainbows), you need to let us know so that we can fix it. 

Unless you tell us which nodes the problem is with, we can't help.

**Comment by Fixer-007** [comment]
Nyan cat was removed quite recently

**Comment by GreenXenith** [comment]
I don't think this would be a good idea.

If a mod on a server somehow gets disabled (either by bug or accident), your server restarts with unknown nodes, everything is lost because Minetest would remove them automatically.

People need unknowns for modding too. When I am testing aliases I certainly don't want those completely purposeful unknowns to disappear.

They aren't hard to remove. If you have a whole lot, a quick alias from what they used to be to air can do you some good.

**Comment by SmallJoker** [comment]
I agree with @GreenXenith. Removing is overall a bad idea, as the server owner might want to use a replacement mod after these unknown nodes like [MooGNU](https://github.com/Thomas--S/moognu/blob/master/init.lua#L85) which takes care of the unknown nyan cat nodes.
It's sometimes also not known whether there was important data saved in those nodes (full inventories?) - these would be lost if we removed those. A custom mod to remove garbage (i.e. only decorative nodes or objects) already exists: https://forum.minetest.net/viewtopic.php?id=2777
Nowadays it's possible to reduce the server lag to when mapblocks are loaded using LBMs, which can be [created quite easily](http://dev.minetest.net/lbm).

**Comment by paramat** [comment]
Probably an engine issue but as above :-1: whereever it is implemented.
