### ISSUE TITLE
Remove coral air-death ABM

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2169]
* Coral is only placed by mapgen underwater, so in places unlikely to be drained of water. If these places are drained of water players would very likely be removing the coral too.
* Coral already dies when dug, reducing the need for an ABM.
* Kelp does not die if drained of water and many other plants survive in highly unrealistic situations, like removing dirt from under a tree or removing the lower parts of a tree trunk. This lack of strict realism is to keep MTG simpler and avoid excessive numbers of ABMs. The coral death ABM was added with a good intention of being strictly realistic but is a level of realism and complexity inconsistent with the rest of MTG.
* We need to try very hard to remove as many ABMs as possible as they are very intensive and are unoptimised. We have 14 running in MTG, some as often as every 2s.

Related issue #1561 
Corals are up for a rework soon so this could be part of that.

**Comment by Ezhh** [comment]
I've never liked the implementation of corals at all (as you know, because I've talked your ears off about it). I agree it doesn't make much sense to hold to strict realism for coral death like this, at least not when the price is an ABM. We could just as well argue we should add ABMs so trees with a missing trunk node fall over and so on... and if we're not going to go that route I think coral death ABM can go.

**Comment by paramat** [comment]
Ok. Sorry i assigned you, should have just tagged you instead. I'm more than happy to do this PR, and probably will.

**Comment by paramat** [comment]
PR #2172
