### ISSUE TITLE
Flowers Spread Excessively Fast

### ISSUE THREAD

**Issue by ChimneySwift** [minetest/minetest_game#2177]
Hometown recently upgraded to 0.4.17.1 and we've been noticing the flowers spread significantly faster than before. This area at spawn had a small cluster of 4-5 flowers before the upgrade:

![Hometown Spawn](https://media.discordapp.net/attachments/369123125021114369/468196967151960075/unknown.png?width=1248&height=676)

This growth is unlikely to be artificial:
![Town](https://media.discordapp.net/attachments/369123125021114369/468195273903046656/unknown.png?width=1248&height=676)

This all happened within about 4 days.

**Comment by paramat** [comment]
Caused by #2016 

"Flora spreads until it reaches a maximum density, the density was out of date (unchanged since mgv6-only days) and far too low, this PR raises it to match maximum mapgen density of flora."

"Typical maximum density for one flower type is therefore -0.02 + 0.04 = 0.02.
With 8 flower types: 0.02 * 8 = 0.16 flowers per node (1 flower per 6 nodes).
Over 9 ^ 2 node area: 0.16 * 9 ^ 2 = 12.96 roughly 13 flowers instead of 3."

"Maximum mapgen flower density is 13 per 9x9 area"

However your first screenshot seems to show a higher density than 13 per 9x9 (1 per 6 nodes). No idea how that happened.

This does uncover an issue though, in my calcualtion of maximum mapgen flower density i assumed all 8 flower types at maximum density at a particular location. This is of course very rare, it may be better to set maximum mapgen flower density to that of 4 flower types at maximum density, which will be 6.5 flowers per 9x9 area.

I can make this change to lower the maximum density reached, however there are further related issues (see next comment).

**Comment by paramat** [comment]
The inherent problem with the flora spread ABM is that it causes 'flora group' spread until a certain density is reached. However, mapgen intentionally places flora in varying densities, the ABM therefore works against this and tries to create a uniform density, whether flora spread is wanted or not (usually it isn't, but it is if using a flora node as a resource).

If the ABM maximum density is low then farming flora as a resource, for example flowers for dye, requires a very large area, and there have been many complaints that flora spreads too slowly and stops at a low density.
If the ABM maximum density is higher, as it was recently made, then we get complaints of too high density in places where just a few scattered plants are wanted.
Additionally, whatever maximum density is chosen the desired density variation created by mapgen will eventually be ruined and become uniform and boring.

Also, the flora spread ABM is our most intensive ABM.

I have long complained about these issues, and proposed we change to using seeds to spread flora, so that they essentially work like tree saplings. But this may be too disruptive for certain worlds or mods, and the idea was also unpopular with other core devs.

I made mushrooms spread using spores, but again this was unfortunately changed (a mistake i feel) and another intensive ABM added. Now we have the same issue with mushrooms too.

In this situation there is no solution, only a balance between undesirable behaviours.
It's yet another case of MTG being unfixable because a good idea can't be used due to it being different from what has been done before, therefore possibly breaking the gameplay of certain worlds or breaking certain mods.

**Comment by paanrama** [comment]
It is more work, but one alternative is keep the old behavior and add a new behavior using seeds (and maybe in future a third behavior using timers if this can eventually replace the actual ABM) under a configuration, so initially anybody can get what they want changing one initial parameter. Then you can define that the seeds are the default in 0.5 branch (and the ABM is the default on 0.4 branch).

**Comment by JurajVajda** [comment]
Another solution what i found very helpful would be, instead of having excessive amount of seeds/saplings for every plant/grass/decoration plant is bonemeal. Just using it on (dry) grass would randomly grow plants/decorations based on that biome. It reduces amount of items, logic, textures... to maintain and it would be still challenging to get all kinds of flowers since you have to find the right biome to grow them with bobemeal. This way we don't need ABM, LBM nor timers what would extremely improve the performance. If wanted as an extra feature bonemeal could grow farming/tress faster...you know the behavior already.

**Comment by rubenwardy** [comment]
How about keeping the old behaviour as low density, but then making them spread easier on to wet soil? So you can farm them by placing them in wet soil

**Comment by paramat** [comment]
Sorry i dislike the idea of bonemeal, it's very MC, and the placing of bonemeal causing plants to instantly appear is a tasteless method in my opinion. We also have no bonemeal or fertiliser yet.

Rubenwardy, some interesting ideas.

Anyway, for those who need to apply a quick fix @ChimneySwift 
Change the 7 back to a 3 here:
https://github.com/minetest/minetest_game/blob/ee72bc722c4068adea7cb90457f80616bb0fcd7f/mods/flowers/init.lua#L147

**Comment by paramat** [comment]
Yes this density is too high i agree, i will at least halve it. Farming considerations are best done another way.

'Dirt with snow' was re-added to the soil group in https://github.com/minetest/minetest_game/commit/a6aa68d5b4ed0abb8dd27ca62c8de670313a2e1a then a commit was added to only allow flora to spread to an identical surface node https://github.com/minetest/minetest_game/commit/495fa32873202c667c589ae691f5e67186762521#diff-52c5bc63b60652919a9dfd687bb92bf9
The 2nd commit was probably not backported to 0.4.17, not sure about the 1st.

**Comment by paramat** [comment]
So as another quick fix your server could remove dirt_with_snow from the soil group.

**Comment by paramat** [comment]
PR #2178
