### ISSUE TITLE
Stairs and slabs dont get wood group assigned

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2248]
Since the full wooden nodes has group `wood = 1`, shouldn't their stair and slab counterparts have that too? Perhaps its the same problem for stairs and slabs of all types.

**Comment by paramat** [comment]
Looks like the groups for slabs/stairs were not updated to match changes to the full cube groups.
However it depends on what these missing groups are used for, that needs checking.

**Comment by tenplus1** [comment]
Group:wood is typically used for recipes requiring a full wooden node, if stairs had them assigned then it would be possible to cheat with recipes and use slabs instead giving 3x as much.

**Comment by paramat** [comment]
Exactly.

**Comment by tacotexmex** [comment]
Ah, I see. I discovered it as I wanted to collect all nodes made mainly out of wood, so that’s indeed something completely different.

**Comment by paramat** [comment]
It's difficult to decide because groups are used for various purposes.

**Comment by Ezhh** [comment]
The group is used for recipes because we have multiple types of wood. Some examples just within MTG:
- Boat recipe.
- Cart rails recipe.
- Wooden hoe recipe.
- Mapping kit recipe.

There's probably some others as well.

If you add nodes to this group that cost a fraction of the price of a wood node, you invalidate the recipes... which are the whole point of the group. It simply can't be done.

To add to the considerations, it would also change the behaviour of xpanes so they connect to stairs and slabs, which would be weird.

This was a good question to ask, but :-1: from me.

**Comment by paramat** [comment]
I agree.
