### ISSUE TITLE
Next steps for mapgen: underground biomes, dehardcodisation

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2339]
Addresses part of #1944 and prepares for the rest of that and #1168 #2048 

Now 5.0.0 is released and there are many new engine mapgen features to use, i propose some next steps that i can code if there is agreement:
* Underground biomes. DONE
Replace the "underground" biome with an underground layer of each primary surface biome, all extending down to world base. This will complete the 'biome columns' and enable horizontal distribution of new stone types, ores, dungeon types, cave liquids and underground decorations.
* Dehardcodisation. DONE
MTG will then have to use the new 'biome-defined dungeon and cave liquid nodes' features. This is desired anyway as the classic hardcoded dungeon type and cave liquid type distributions are really just a Mapgen V6 thing that is unfortunately still used for the newer mapgens.
So i propose a complete 'dehardcodisation' of MTG's use of engine mapgen code, everything will be defined and distributed by biome.
* Dungeon nodes defined by biome definitions. DONE
This will happen together with my engine intention https://github.com/minetest/minetest/issues/8251 to enable a variety of dungeon structures for biome-defined dungeons, instead of currently where all biome-defined dungeons have the same structure.
So, for example, sandstone dungeons will then come in a variety of structures instead of all being low and wide as currently.
* Cave liquids defined by biome definitions. DONE
Currently all mapgens use another yucky hardcoded distribution for the mid-sized liquid caves. Half of these caves are flooded, and 66% of those are lava, otherwise water. I propose keeping these 3 cave types but defining by biome and maybe tuning the rarity of each.

**Comment by benrob0329** [comment]
Suggestion: Rather than random floods in caves, actual underground lakes (maybe even oceans with islands on them, because why not).

I am very much for this, making MTG's underground more interesting would give exploration much more value and cause the dread of having to go mining for another 3 hours become anticipation for what crazy underground terrain I'll find next.

**Comment by Linuxdirk** [comment]
> Underground biomes.

If I understand this correctly it would allow underground biomes depending on overworld biome. This would be one of the greatest improvements!

The rest: yes, all power to the biome definitions.

**Comment by paramat** [comment]
>  it would allow underground biomes depending on overworld biome.

Yes.

**Comment by misterskullz** [comment]
I would suggest trying to have a bit of horizontal blend between biomes.  There is blending at the surface which looks great and vertical blending between biome layers but if you use a different base stone in each biome you will get these perfect columns of "this is biome 0 stone, this is biome 1 stone".

Crycal clear smooth lakes as an option "auto expand water sources XZ by lake_size nodes" would be great. 

Decoration schematic placement is troublesome because you don't have unlimited blue sky overhead and you either force place or have things chopped off.  A decoration "minimum air above / below for placement" would be awesome.  If you wanted to get REALLY crazy you could have decorations placed on the side of nodes, not just the tops or bottoms. 

Dungeons as is seem to be kind of a misfit.  If you want to do anything serious with them you have to go all out with a underground structures mod. I would either remove them entirely OR abstract the room, hallway concept out to a connected graph. It would be awesome to be able to define decoration for a hallway, a small room, large room, door schematic, etc. Currently dungeons are just frustratingly hinting at what could be and seem to be the only "man made" structure in the game.

**Comment by paramat** [comment]
We could have fewer biomes underground, but i can't see a reason why. If we use the surface biomes underground this creates more variety, and means that surface biomes become a marker for what's below. So i think it's best to stay with the 'world height biome columns' approach.

**Comment by paramat** [comment]
@Ezhh please could you consider the suggestions above when you have time?

**Comment by Ezhh** [comment]
@paramat You already know, and have seen (via HW) a large part of my vision for how the underground should work. The only possible difference here is that you recommend a single underground layer, whereas HW has several, (but HW may over time change this, since it's possible to set decorations by height anyway). It will all come down to which content actually needs biomes in order to be controlled, and whether we eventually want differing stone types by depth.

For those who are curious about how stone types mix underground when using such an approach, this is an early HW screenshot from when I we started looking at how biome edges appear:

![hw_stone_mix](https://user-images.githubusercontent.com/7035183/55560877-13bc7f80-56e9-11e9-944b-247e348bab28.png)

As far as I'm concerned, the amount of blending looks pretty good.

I do however want to add that I only consider this worthwhile if we are committed to adding new stone types and/or other biome-specific underground content. MTG has been largely stagnant in many ways, and this is something that could make a huge difference, not only to MTG but to the potential mods have to expand on MTG.

**Comment by paramat** [comment]
>  if we are committed to adding new stone types and/or other biome-specific underground content.

We are =) Dev is just slow as we're so busy keeping the engine alive.

Ok i'll go ahead, at the moment i can't see a reason to have multiple underground layers of biomes, but that can change in future if needed.

**Comment by paramat** [comment]
Actually my intention will be like how HW is now, the 'ocean' layer will extend to y = -256 so itself is the shallow underground layer.
Like HW i propose adding "_under" to biome names to avoid the length of adding "_underground".

An issue with cave liquids:

If defined per biome, when underground it will not be so easy to find water *and* lava caves in one region, i'm not sure if this will be a problem. Additionally, if we want 3 liquid cave types (as currently): non-flooded, water, lava, the desired resource could be even more difficult to find as it will be found in 1 in 3 biomes.

One way around this would be the player knowing which biomes have which cave type, and digging down at the border of a 'water cave' biome and a 'lava cave' biome.

I'd prefer to not use the engine's hardcoded liquid choosing, but we could continue to.

**Comment by paramat** [comment]
![newBiomes9_liq](https://user-images.githubusercontent.com/3686677/56325620-bd305600-616a-11e9-9ffe-56eac2e3addd.png)

^ Proposed distribution of lava and water caves by biome.
Red = lava, blue = water.

12 biomes, 6 of each.
Trying to create a 'chessboard' type pattern such that both resources are always fairly close.
Assuming that lava is a slightly more precious resource than water (because water is already available at the surface), i have looked at the spawn mod biomes and tried to maximise the number of these that have lava:
```
-- Table of suitable biomes

local biome_ids = {
	minetest.get_biome_id("taiga"),
	minetest.get_biome_id("coniferous_forest"),
	minetest.get_biome_id("deciduous_forest"),
	minetest.get_biome_id("grassland"),
	minetest.get_biome_id("savanna"),
}
```
Of course, we will have to inform players which biome has which cave liquid.

**Comment by sofar** [comment]
Given that lava is rare at the surface, shouldn't water be rare down below?

As in, I think it should be rare in every biome. I'm not saying we shouldn't have caves with giant dark seas (that would be cool), I'm just saying that no biome should have overwhelmingly water filled caves.

**Comment by Ezhh** [comment]
I think I'm fairly neutral regarding the liquids being biome specific. sofar makes a good point, but I'm not sure how we'd pull that off since we can define just one underground liquid per biome (or use the default of both being present).

**Comment by paramat** [comment]
The current engine-hardcoded behaviour is:
Half of the mid-size caves are flooded, randomly chosen per cave.
Of those, 66% have lava, the rest water, determined by 3D noise with spread 150 nodes.

The issue is, current behaviour is that both water and lava are available within a distance of roughly 150-300 nodes.
When deep underground, both resources are valuable, as surface water is distant. So i don't want to make water rare underground, mods and games may be reliant on it. 
Since cave liquid is defined per biome, making more biomes lava could result in underground water being 1000s of nodes away.

Ezhh is correct, a biome can only have 1 cave liquid, not a mix of both.

**Comment by paramat** [comment]
I'll make a PR with the above distribution now.

**Comment by paramat** [comment]
New approach https://github.com/minetest/minetest_game/pull/2358#issuecomment-485039362

**Comment by paramat** [comment]
All done.
