### ISSUE TITLE
player_api.player_attached is undocumented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2343]
It seems that setting `player_api.player_attached[player_name]` to `true`/`false` after attaching/detaching a player is important, but it is not documented in `game_api.txt`. :-(

---

Besides, why is the documentation of `player_api` not included in the mod itself?

**Comment by misterskullz** [comment]
We could toss in a "do_attached" and "do_attached_to" style function which would take an entity in and call set_attach, then update the boolean. This plus adding a "if you attach outside of player_api you are responsible for setting the flag" warning. 

I think leaving the documentation in game_api.txt is reasonable because that is what folks will usually read.  A "see game_api.txt for docs" note might be helpful.

**Comment by SmallJoker** [comment]
I'd prefer to deprecate this table and use `player:get_attach()` to check whether the player is actually attached to something. Does anyone have an idea why this table was added after all? For performance reasons (Lua -> C++ calls)?

**Comment by DS-Minetest** [comment]
Performance might be a reason because [it's used on globalstep](https://github.com/minetest/minetest_game/blob/0ea6065a09f1fee014c7f2a9a36605d57986a209/mods/player_api/api.lua#L104).

Another reason might be that attachment should also be possible with still having player animations.

**Comment by LoneWolfHT** [comment]
I just used this today to prevent players from walking on the horse they're riding (IIRC if I set the sit anim it'll be overridden when the player uses WASD?)

**Comment by sfan5** [comment]
> Does anyone have an idea why this table was added after all? For performance reasons (Lua -> C++ calls)?

Beds for example use this to disable animation while the player is made immovable (using physics overrides). The player isn't actually attached while sleeping in bed, so `get_attach()` wouldn't work here.
