### ISSUE TITLE
Layered snow?

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest_game#2390]
I really like how the mod [minetest-mod-snow](https://github.com/Splizard/minetest-mod-snow/) (created by @Splizard) allows snow to be layered and then turns into a snow block. I think it would be a nice, simple addition to Minetest and it could be a part of adding weather to Minetest in the future.
![screenshot_20190611_163448](https://user-images.githubusercontent.com/49789044/59286545-d7b51600-8c67-11e9-944a-dc05d088ca00.png)
![screenshot_20190611_163453](https://user-images.githubusercontent.com/49789044/59286546-d7b51600-8c67-11e9-8177-06fa1f9c18e0.png)

I tried implementing it into Minetest already. It was a small addition to the code and worked just like the mod does.

Why it should be added:
· Realistic
· Fun
· Simple/small addition (doesn't require a huge change to the code)
· Will work well with weather

**Comment by SmallJoker** [comment]
It used to be like that until weather was removed somewhen after 0.4.7.

**Comment by DS-Minetest** [comment]
Stacking won't work nicely if a full snow block falls onto any snow layer. It will simply replace instead of stacking.

**Comment by An0n3m0us** [comment]
Why would that happen? Anyway, that sounds alright.

**Comment by DS-Minetest** [comment]
Near [here is](https://github.com/minetest/minetest/blob/4c11574e9deeb583f00e8b890f21d87f0d81d816/builtin/game/falling.lua#L75) the relevant code.
Hm, as minetest_game snow is currently not walkable, stacking wouldn't even work if a snow layer falls onto another one.

**Comment by An0n3m0us** [comment]
![test](https://user-images.githubusercontent.com/49789044/59356859-a6991c00-8d21-11e9-9ec8-b20b51f3f753.gif)

I added the code to `minetest_game`. Works perfectly, like I said before.

**Comment by Niwla23** [comment]
cool

**Comment by sfan5** [comment]
Not sure about other coredevs, but I definitely support this.

In general it would be nicer to quickly discuss about-to-be-closed issues before doing so. Lack of activity does not imply that the feature is not supported.

**Comment by paramat** [comment]
sfan5, please could you add the 'supported by core dev' label if you support a request / feature request? It really helps issue management =)

sfan5 i used to do what you suggested.
I used to make a big effort to get old unsupported issues visibility: I bumped them, added labels, regularly left messages on IRC asking for core devs to go through the labelled issues, then i would sort through then a second time and close after a month if still no support.
Nothing i did seemed to have any effect, the issues still seemed to be ignored, core devs did not seem to sort through the labelled issues.
So i stopped making such a big effort, i could no longer justify spending so much time on what is low priority. 
So understandably i feel a little fed up, i cannot be blamed for this, i have tried everything already, what can i do?

The responsibility and problem here is with the other core devs, they need to consider a feature request within a year of it being opened, and add the label if they support, this is not much to ask.
If an issue is closed after a year and a core dev only then considers it (as here), that is the fault of that core dev for neglecting issues.

If a core dev simply has no time for considering feature requests (which is understandable), then keeping an issue open makes no difference, it will just get buried in 1000s of issues with ever-decreasing chance of being considered again, and that core dev will not have time to consider it in future either.

Feature requests are the highest volume (rougly 50%) and lowest priority issues.
If not even a single core dev can consider a feature request a fairly good idea over a whole year, then it is not much of an idea.
If we assume that 'core devs just missed it' and keep it open then all unsupported feature requests would stay open forever, and we would be up to 1500+ by now in the engine. The more issues there are the more likely they will be buried and forgotten.
So we can only assume they have been considered within that year.

I disagree that a feature request actually has to be disapproved to be closed, because we need an actual positive reason to add a feature, neutrality is not enough.
> Lack of activity does not imply disapproval.

But it proves lack of approval, which is a good reason to close it.

We have been too 'soft', making the mistake of thinking that can only be good, it actually it harms everyone, including users and people who open issues. The more issues there are the less feature requests get considered, the more chance the good ones get buried in the neutral ones.

Consider this deveopment rule as an example of good classic MT development strictness, this is the level of strictness we should be aiming for:
"If a pull request or an issue does not get a response from its author in one month (when requiring more details), it is closed."

**Comment by paramat** [comment]
:-1: for the request, reasons in the PR.

**Comment by sfan5** [comment]
> So understandably i feel a little fed up, i cannot be blamed for this, i have tried everything already, what can i do?

Note that I am not blaming you for this.

> I disagree that a feature request actually has to be disapproved to be closed, because we need an actual positive reason to add a feature, neutrality is not enough.

> But it proves lack of approval, which is a good reason to close it.

Well no, it doesn't if coredevs might not even have looked at the request. But you already explained why that's a problem, so let's not get hung up on this point.

> Nothing i did seemed to have any effect, the issues still seemed to be ignored, core devs did not seem to sort through the labelled issues.

I don't suggest you make a big effort if you believe it isn't productive.
But I think sending a reminder about old issues on IRC once in a while would nice.

**Comment by sfan5** [comment]
> -1 for the request, reasons in the PR.

Reading the PR comments I get the impression that you're opposed to neutral on the feature but disapprove the concrete implementation due to complexity and unsolved issues.
Is this accurate?

**Comment by paramat** [comment]
Sorry that my last comment was a little long and ranty.
Here is what i will do now, which is not much effort for me: I will bump the issue by adding the 'no core dev support long term' and 'possible close' labels, wait 2+ weeks then close. The bumping and the labels will allow other core devs to find these issues and consider them.

**Comment by An0n3m0us** [comment]
> Reading the PR comments I get the impression that you're opposed to neutral on the feature but disapprove the concrete implementation due to complexity and unsolved issues.

I don't know what Paramat thinks about the PR, but I'm stuck because of the snow levels causing 'detailed' nodes. I can't tell if it would be a good or bad addition to the game:
https://github.com/minetest/minetest_game/pull/2392#issuecomment-568332648

HybridDog gave a good suggestion:
https://github.com/minetest/minetest_game/pull/2392#issuecomment-568779343

There were a few other issues too:
https://github.com/minetest/minetest_game/pull/2392#issuecomment-568127875

**Comment by TumeniNodes** [comment]
So why can there not be a limit set to the height the snow can go?
Once at this height, snow fall simply does not accumulate (prob easier said than done, and I may not have described what I mean correctly)

_If_ this could be implemented without problems... the same could be done with sand and gravel on_blast... and could create rather cool and realistic looking craters (at least in my mind)

**Comment by paramat** [comment]
PR #2392

**Comment by paramat** [comment]
PR not supported.
