### ISSUE TITLE
PR #2419 may have caused an issue in creative mode.

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2420]
Since updating to the latest commit, I can no longer break stone, etc. by hand when in creative mode... and my altered range setting for selecting nodes is back to default.

**Comment by TumeniNodes** [comment]
https://github.com/minetest/minetest_game/pull/2421

**Comment by DS-Minetest** [comment]
#2419 is a PR, the commit is https://github.com/minetest/minetest_game/commit/9fe877ef990c0e0036d6f3bae33f89308a436921.

The hand is registered twice:
https://github.com/minetest/minetest_game/blob/64a923f7fb92b18a2fb2e727a45c69df744559b8/mods/creative/init.lua#L43
https://github.com/minetest/minetest_game/blob/e19f42d6481b0ba4d7397702ed866f861c5fda12/mods/default/tools.lua#L4

This can probably be fixed by not registering it in default if `minetest.settings:get_bool("creative_mode")`.
However, there might be nicer ways.

**Comment by TumeniNodes** [comment]
yes, this was merely the simplest means to hack/fix the problem until a solid solution is found.
It voids 'oddly_breakable_by_hand'

**Comment by paramat** [comment]
Sorry, i did wonder if my commit might create a problem

**Comment by TumeniNodes** [comment]
it works for me right now

**Comment by paramat** [comment]
Confirmed bug.

**Comment by paramat** [comment]
#2421 merged.
