### ISSUE TITLE
3D Ladder Model.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2423]
I have made a model for wooden/steel ladders. I think the current ladder looks like too flat and much like minecraft one. So, I decided to make own volumous ladder for Minetest unlike that.

![image](http://www.imageup.ru/img281/3433914/screenshot_20190723_200145.jpg)

Download Links:
https://ufile.io/23jko4qs  (.b3d)
https://ufile.io/pfb6rlao  (.blend)
https://ufile.io/pbxnbz94  (nodes.lua)

**Comment by DS-Minetest** [comment]
Related: #2418

@Andrey2470T Have you thought of making this to a mod? Overriding the ladder nodes to uses meshes is easy.

**Comment by Andrey2470T** [comment]
I don`t want to make this as a mod. I want it to be added to MTG. Also, minetest_game is not so easy it can`t even have so simple models. For example, the boat model is much harder that that I suggested.

**Comment by paramat** [comment]
The pixels are unequal sizes, vertically squashed on the uprights, chopped at rung ends, and not equal in size to pixels on other nodes. The rungs now contain pixels from the 'uprights' sections of existing textures.
I realise this is to make the UV wrapping work with existing textures, but it looks very messy. This is the problem with changing a non-model node into a model and changing the proportions.
Better would be to use nodeboxes instead and keep the proportions identical seen from the front, but then of course the rungs would be as thick as the uprights, and extra side textures would be needed, breaking texture packs.

So :-1: due to the visual problems.
I also disapprove of using a model for ladders at all, as signlike is reasonable, much faster to render (ladders occur in large quantities), and this approach leads to using nodeboxes/models for every non-cubic node.
I prefer MTG uses as few models as possible as working with models is beyond the abilities of most modders (beyond my ability too).

**Comment by Linuxdirk** [comment]
> Better would be to use nodeboxes instead and keep the proportions identical seen from the front

I did this exact thing in my redefinition mod (no plans on releasing, though). Looks perfect with default textures and a nodebox.

This is the whole code (pretty sure this could be optimized).

```lua
local ladders = {
    {'ladder_wood', 'default_ladder_wood.png', 'default_wood.png'},
    {'ladder_steel', 'default_ladder_steel.png', 'default_steel_block.png'}
}


for l,def in pairs(ladders) do
    minetest.override_item('default:'..def[1], {
        tiles = { def[2], def[2], def[3], def[3], def[3], def[3] },
        drawtype = 'nodebox',
        paramtype = 'light',
        node_box = {
            type = 'fixed',
            fixed = {
                {-0.375, -0.5, -0.5, -0.25, -0.375, 0.5}, -- strut_1
                {0.25, -0.5, -0.5, 0.375, -0.375, 0.5}, -- strut_2
                {-0.4375, -0.5, 0.3125, 0.4375, -0.375, 0.4375}, -- rung_1
                {-0.4375, -0.5, 0.0625, 0.4375, -0.375, 0.1875}, -- rung_2
                {-0.4375, -0.5, -0.1875, 0.4375, -0.375, -0.0625}, -- rung_3
                {-0.4375, -0.5, -0.4375, 0.4375, -0.375, -0.3125} -- rung_4
            }
        },
        selection_box = {
            type = 'wallmounted',
            wall_top = {-0.4375, 0.375, -0.5, 0.4375, 0.5, 0.5},
            wall_side = {-0.5, -0.5, -0.4375, -0.375, 0.5, 0.4375},
            wall_bottom = {-0.4375, -0.5, -0.5, 0.4375, -0.375, 0.5}
        }
    })
end
```

Could be optimized by using only the ladder texture and cropping the parts needed for the sides. But to me this looks nice enough with the default textures.
