### ISSUE TITLE
Separate nodes for connected and non-connected glass, connected glass not chosen by client

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2434]
This was discussed in https://github.com/minetest/minetest/issues/8290 and https://github.com/minetest/minetest_game/issues/2326
Opening a new issue to clarify.

My suggestion:
For each glass node (normal glass, obsidian glass):
The existing glass node is changed to 'glasslike' drawtype (never connected).
Add a new node that is a 'glasslike framed' (always connected) version.

The structure of glass becomes intentional and chosen by the builder, as it should have been from the beginning.
Any one player will now experience both types of glass, according to what is most suitable for each build usage, instead of only ever experiencing 1 type of glass.
Keep in mind that an area of obsidian glass becomes invisible when connected, so the structures are radically different and justify separate nodes.

Obviously, some builders will want to change the nodes used in existing builds to the framed version, according to the intended structure. So an optional mod would be provided to make converting glass nodes quick and easy: Punch the node to convert, or, set 2 corner points and convert all nodes in the volume.
A little pain for the larger gain of going forwards correctly in the future.

The engine feature of client-chosen connected glass was, i think, a big mistake, but understandable as it was probably intended to allow existing builds to have their non-connected glass become connected glass. So a clientside-option drawtype was created and unfortunately MTG glass used this for all glass nodes.

Relevent comments from previous threads:
https://github.com/minetest/minetest/issues/8290#issuecomment-468973478
https://github.com/minetest/minetest/issues/8290#issuecomment-469896514
https://github.com/minetest/minetest/issues/8290#issuecomment-470489535
https://github.com/minetest/minetest_game/issues/2326#issuecomment-470488225
https://github.com/minetest/minetest_game/issues/2326#issuecomment-475178531
https://github.com/minetest/minetest_game/issues/2326#issuecomment-516136382

@Ezhh

**Comment by DS-Minetest** [comment]
>A little pain for the larger gain of going forwards correctly in the future.

The pain is not so little. Compatibility to old buldings is lost. Building with glass is much more complicated, even though there's nearly no visible difference between connected and not connected glass, the builder has to decide between the one glass or the other, which can be very difficult.

The gain isn't large either. Builders will either (1) use the first glass node they get via crafting, (2) use what they think is the superior glass node (probably connected glass) or (3) use the version _they_ prefer. Why shouldn't the people who look at the building decide how the glass should look like? The optional connected glasslike type setting might be comparable to texturepacks.

Whether the glass should be connected should not need to be considered by builders.

If a server wants to allow builders to specify whether the glass of their building should be connected, they can use a mod.

:-1:

**Comment by paramat** [comment]
> Compatibility to old buldings is lost.

Can you explain further?
>  the builder has to decide between the one glass or the other, which can be very difficult.

That's not remotely difficult, this could be claimed for any node.
> The gain isn't large either. Builders will either (1) use the first glass node they get via crafting, (2) use what they think is the superior glass node (probably connected glass) or (3) use the version they prefer.

I can't see the problem with this? You've just stated that builders have more choice and control over the appearence of a build, which is good.
Option 1 is laziness, we're not responsible for poor results caused by lazy builders.
> Why shouldn't the people who look at the building decide how the glass should look like? The optional connected glasslike type setting might be comparable to texturepacks.

I suspected the texture pack argument would be made. It's not the same, as texture packs only alter the appearence of each individual node. Connected glass alters an area of glass on a large scale (potentially very large scale), and in the case of obsidian glass or any glass without 'shine', is the difference between a large invisible wall and per-node frames.
The player can still, through the use of a texture pack choose what the glass looks like per-node.
> Whether the glass should be connected should not need to be considered by builders.

Why?
> If a server wants to allow builders to specify whether the glass of their building should be connected, they can use a mod.

Optional mods are irrelevant because the intention is to put right a mistake in MTG. Most servers and singleplayers will not use a mod and so the problems of the current implementation will continue.

**Comment by DS-Minetest** [comment]
> > Compatibility to old buldings is lost.
> 
> Can you explain further?

Yes, I can.
Buildings from old worlds would look different with new mtg

> > the builder has to decide between the one glass or the other, which can be very difficult.
> 
> That's not remotely difficult, this could be claimed for any node. Should we make MTG use only 1 node because choosing nodes is too difficult? =)

The difficulty is that there's only a very little difference between connected and not connected glass.

Imagine you could chose between a red and a blue bonbon. They both taste the same. Mixing both would taste awful. Which one do you chose?

> > The gain isn't large either. Builders will either (1) use the first glass node they get via crafting, (2) use what they think is the superior glass node (probably connected glass) or (3) use the version _they_ prefer.
> 
> I can't see the problem with this? You've stated that builders have more choice and control over the appearence of a build, which is good.

Normally, if players should have more control over the appearance, mods are used. If we would want to give players all the freedom accessible in basic mtg, we could as well add nodes for each change in textures. Eg. add about 5 old sorts of cobble, about 2 old stone brick nodes and co.

What I wanted to say in the original comment you quoted is, that builders won't be able to gain any profit from the different glass nodes. There are not many buildings that would clearly look better with one of the styles.

> Option 1 is laziness, we're not responsible for poor results caused by lazy builders.

This is not only because of laziness, some players might simply not know that there's a weird new second glass node.

> > Why shouldn't the people who look at the building decide how the glass should look like? The optional connected glasslike type setting might be comparable to texturepacks.
> 
> I suspected the texture pack argument would be made. It's not the same, as texture packs only alter the appearence of each individual node. Connected glass alters an area of glass on a large scale (potentially very large scale), and in the case of obsidian glass or any glass without 'shine', is the difference between a large invisible wall and per-node frames.
> The player will still be able to, through the use of a texture pack choose what the glass looks like per-node.

I don't really understand how the change of the look of a single node differs greatly to one of an area of nodes.

The obsidian glass being invisible is acceptable imo. There are beings who bump against windows.
If someone has problems with this, they can add shine via a texturepack.

> > Whether the glass should be connected should not need to be considered by builders.
> 
> Why?

Choosing the glass is difficult and the effect on the building's look is not good for the building but only for the personal taste of the builder currently looking at it, in the best case. Look at the arguments above.

> > If a server wants to allow builders to specify whether the glass of their building should be connected, they can use a mod.
> 
> Optional mods are irrelevant because the intention is to put right a mistake in MTG. Most servers and singleplayers will not use a mod and so the problems of the current implementation will continue.

If you consider this a mistake, you could as well consider it a mistake that nodes' textures were simply changed without leaving a copy with the old texture.

**Comment by TumeniNodes** [comment]
In my own opinion, I would much rather see two separate glass types.
When the option 'connected glass' is one which provides your entire world with one or the other, I consider it a bit restrictive, and I have never really liked that option in the first place.

Having both available provides maximum options, and diversity in big builds.
I feel the option was added at the time because it was cool and sort of an exciting new discovery, so it was added in hast.
Hindsight, it is restrictive and actually doesn't make as much sense anymore.

>If you consider this a mistake, you could as well consider it a mistake that nodes' textures were simply changed without leaving a copy with the old texture.

Copies of old ver. TPs can easily be offered.
I made a copy of the MTG TP for 4.16 i think? when desert cobble was being changed, knowing people would be looking for it... (I have to add the rest of the textures from all the mods now that I think of it) https://github.com/TumeniNodes/original-Minetest_Game_0.4.16-default-textures

**Comment by paramat** [comment]
@sfan5 @SmallJoker you both commented in #2326 but you both seemed confused, understandably as that issue was confusing. Here is the clarified suggestion, please could you consider and comment?
@Ezhh it seems you might be able to support this?

**Comment by paramat** [comment]
Closing due to #2710
