### ISSUE TITLE
Any missing fundamental ores? Silver?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2459]
Note to avoid repeating the argument: We have discussed mithril several times before and it probably will not be accepted, i disapprove of that ore as has at least one other core dev. See the other issues for discussion of that. This issue is not about replacing the moreores mod.
//////////////////////////////

As MTG is a sort of modding base, a world with resources for mods to use, and because it already has a reasonably large variety of ores, i suggest that we try to complete a set of fundamental ores for mods to use.
Ores seems to be one thing that MTG can do fairly completely.
What ores do many mods use in crafting that MTG is missing?

The first i think of is silver, which is also in the 'moreores' mod. Is silver widely used by mods?

I can add silver ore quite easily to mapgen, at a suitable depth.
I disagree it needs a non-decorational use in MTG immediately, although adding a use later will be good. It is justified enough by the mods that will use it.
Also, we wil not add another set of tools for silver, it's a silly material for tools anyway.

Because adding silver will not act as, and is not intended to be, a replacement for the 'moreores' mod, i'm not sure what to do about any aliases with moreores silver items, or how many of those items should be aliased.
EDIT: I think, alias the ore node only.

**Comment by TumeniNodes** [comment]
I know that related to ores, I've always wanted to see an iron block and ingot (all the other ores have these) I created them myself a while ago.
A tool set could be added for Iron as well.

Silver makes sense to me. It can be used for currency/treasure, found in loot chests or something (as gold should be too, rather than for tools, same for diamond)

We could open a discussion to make changes such as those as well?
(which would also open discussion to add a basic currency system, and a reason to have it, such as buying materials to make tools?)

Anyway, I like the idea of adding silver

**Comment by paramat** [comment]
Well, we tend to not like the idea of adding yet more redundant tool tiers, we already feel there are too many and some are redundant. That;s best left to optional mods.

Iron is interesting, but requires a way to smelt it that doesn't result in steel, so probably requires an alloy furnace first (already requested), or maybe the requirement of an air-blasted furnace for smelting steel. So anyway, iron not yet.

**Comment by Wuzzy2** [comment]
Materials, ranked:

Diamond: Crafts the best tools.
Mese: Fairly balanced. Useful for the second-best tools and useful as light source. Exciting.
Steel: Massively overpowered, you need steel for everything. The most important ore in the game IMO. Fairly easy to get and steel tools are pretty strong already, they can already mine diamond. Steel has the most uses of all ingots/ores, the other ores have much fewer uses in crafting.
Bronze: Bronze tools, which are, IRONically, worse than steel tools, but more difficult to craft. Also binoculars but that's an one-time craft because they don't take damage
Copper: Only for crafting bronze. No other direct use by anything.
Tin: Only for crafting bronze, and you only need tiny amounts of it. Pretty much a throw-away ore. Boring.
Gold: Gold is always exciting to mine … But in reality … It's mostly garbage. Only useful for keys, which are useless in singleplayer and not often needed in multiplayer.
Silver: ??????? Even more garbage than gold? No concrete use has been suggested.

Looks like silver will become the most useless ore in the game. The current ores and ingot system is not balanced at all and crafting is heavily biased towards iron. The only really useful ores in the game are coal, iron, mese (for shiny lamps) and diamond. You can mostly ignore copper, tin, bronze and gold, and (soon) silver, too.

**Comment by paramat** [comment]
The usefulness of ores or resources is not defined by the uses within MTG, please read the first post =)

**Comment by Wuzzy2** [comment]
Well, don't you think that MTG needs more balancing? What's the point of a modding base if the base game itself is poorly balanced? Mods cannot fix a rotten core.

**Comment by DS-Minetest** [comment]
Well, iron is very common on earth and many things are built out of. The problem is that iron is so easy to process and doesn't occur in large masses.

If there are not enough uses for other ores, add them, directly into mtg. More content means more fun. What about a candy biome and a silver spoon with that you can eat dessert sand (aka sugar)?

**Comment by paramat** [comment]
Yes i agree things need balancing, but that is offtopic and unrelated to adding new ores, which we assume will be added in a balanced way.

**Comment by TumeniNodes** [comment]
I thought about this a bit the other day and I figure that adding silver only makes sense, so I'd say go for it. 
 Though perhaps it should be More Ores mod which uses an alias to override the ore in MTG?
MTG should take precedence. If a 3rd party mod (even one already in existence) wishes to handle any part of MTG differently, it should use override features.

 MTG as a base to build off for other games/mods means that it should probably only provide the very basic resources which an environment/or planet would provide, and the tools to obtain those resources (which it already has with hand tools, tnt, and carts)

Warning, OT banter incoming:
 Perhaps some time in the future MTG should be considered to be renamed as MTB (Minetest Base, or Basics)

**Comment by C1ffisme** [comment]
I remember either going through Wikipedia's list of applications for Silver either on the Minecraft Forum or this GitHub repository. For either game, I really don't see a lot of applications for Silver.

- Decoration? Jewelry? We already have _two_ shiny grey metals, one without many uses.
- Electronics? The game has no electronics at the moment.
- Being a catalyst in an obscure chemical reaction? Ah yes, while we're looking for uses for one new material, lets add a few more.

Unless you can add enough uses to justify Tin, (maybe canning food? Is food rot worth adding? IDK) I think the only use for Silver (decoration) can be covered by Tin, Iron and Gold.

Sure it could be useful in mods, but so could Uranium, Platinum, Chromium, Mercury, Oil, Lead, heck, some of these materials would probably have far _more_ uses even in the vanilla game. And there's no reason to stop at the underground either, why not go ahead and add half of the plants in the real world?

Really the only reason I can fathom to add Silver to the Vanilla game is a sense of completeness, and while that might be a nice reason to add one semi-useless ore, we already have three.

**Comment by paramat** [comment]
Good points. I agree silver is low priority.
I think best to wait for issues suggesting ores instead of leaving an open question like this. Closing.
