### ISSUE TITLE
Same translation used for different items

### ISSUE THREAD

**Issue by h4ml3t** [minetest/minetest_game#2489]
In English you can use the same word for two different things, e.g.:
"glass" can be used for "a glass of water" or "a glass slab".

In Italian you can't use the same word, i.e.:
"a glass of water" = "un bicchiere d'acqua" (glass == bicchiere)
"a glass slab" = "una lastra di vetro" (glass == vetro)

This means that the translated word "vetro" (the glass material) will be used also for "a glass of water", which instead must be "bicchiere".

**Comment by sfan5** [comment]
This is of theoretical concern currently, something to be aware of.
There no reported cases where 1) a string is reused like this and 2) some language requires different translations.

**Comment by Wuzzy2** [comment]
Yeah, as a translator, you should test your translations in-game or just play the game whenever such cases come up. Then, the context should become obvious.

For example, the string “Glass” always means the block, while “Glass Bottle” is always the glass bottle. There is no double meaning for any identical string as far I am aware. This would be a real problem.

So yes, this is of theoretical concern. As there is no real bug report included, I think this is close-worthy.

**Comment by h4ml3t** [comment]
Keep in mind that  this "bug" report is due to this:
http://irc.minetest.net/minetest-dev/2019-09-18#i_5593261
http://irc.minetest.net/minetest-dev/2019-09-18#i_5593264

So, of course this is not yet a bug but maybe in the future it could become one.
As sfan5 said "This is of theoretical concern currently, something to be aware of.".

IMHO I would close this only if there is another proper place where to keep this note "sticky", better having a "note to self" that prevents issues rather than let it slip into oblivion and having to deal with real bugs later.

**Comment by Wuzzy2** [comment]
Basically, this is just one of many problems caused by Minetest not using the Gettext file format for mod translations … :P

Gettext supports adding comments to strings that the translator then can see. This feature is great to explain particular ambigious strings (such as “Glass”).

Theoretically, comments could be added to the “.tr” files as well, but it all must be added to by hand and cannot be written in the source code.

Note that when you actually need to use the exact same string in English twice, but with different meaning, you just use a different context in `minetest.get_translator`. So it's not impossible to deal with.

**Comment by paramat** [comment]
> celeron55 	it's a common problem in all software due to how gettext works

As it is a general problem, and there are no actual cases in MTG, i do not think an issue is justified.
