### ISSUE TITLE
Lava is no longer waving

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest_game#2501]
Result of the "Restrict waving liquid shader to normal water" change.
Is that on purpose or an oversight?

@paramat

**Comment by lhofhansl** [comment]
It's very much confirmed :)

**Comment by paramat** [comment]
Heh, i mean perhaps it was an accidental change.
Anyway, see #2346 "Now the true edge of lava is clear": Intentional to avoid the problem of flowing lava that has waved below the surface of a node and become invisible but is actually still there and able to cause damage.
Also of course lava looks wrong waving like water, it's too viscous to do so.

**Comment by lhofhansl** [comment]
So it was by design? waving = 3 is missing from the lave_source definition.
While, yes, lava is more viscous, right now it does not move at all anymore, which looks lame :)

**Comment by paramat** [comment]
Yes, waving was removed from lava intentionally.
See https://github.com/minetest/minetest/issues/5694
