### ISSUE TITLE
Adding new dicernable features each release

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2511]
I think that Minetest should add new features each release so players have some new thing to explore each update it will also help keep players hooked for the next update

So for future updates I think there should be at least 3 non-bugfix additions to Minetest_game

Example 5.0.0 added a whole new biome containing 3 new blocks, it added more underwater variety, marram grass, cactus seedling, insects, ect.

**Comment by paramat** [comment]
There probably are new features in MTG every release, and 'discernable' varies from person to person and depends on what they consider significant. So deciding what is significant enough is impossible and just leads to pointless argument.

Even though new game features every release is desirable, this is not something that can be enforced, because MTG development is synced to MTEngine and a MTG release must be made every time an engine release is made, whether there are new features in MTG or not.

Very often, in fact almost always, features are intended but do not happen due to lack of core dev time, they are not something that can be forced, neither are we intentionally neglecting MTG.

At some point in the future, if efforts are primarily made in new games and MTG is simply maintained and fixed, new features may not occur and certainly shouldn't be enforced.
Hard rules like this can only harm development, cause pointless arguments and waste time. Besides, we already intend and try to add new features to every MTG release, so stating this is desirable is redundant.

Your intention is good and i share your desire for new features in MTG, but closing for the above reasons.
