### ISSUE TITLE
Character model: Server side API

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [minetest/minetest_game#2522]
I think that an huge improvement would be adding an API for uploading character skins, so players can select for each server their skin model and submit it, and the server will dispatch it to other clients
I personally think this would be a very important change, since, actually, there's no reason for choosing minetest over cracked java minecraft, except optimization
This isn't meant as a critic, I personally respect your work and recognize your efforts into producing a proper alternative

**Comment by LoneWolfHT** [comment]
There are a million reasons why someone would choose MT over MC I know a lot of Minecraft players that play Minetest more.

On the topic of skins: I think I prefer the current method of server owners adding a 'custom skins' mod and allowing players to submit the skin they want.

With your method: How would skins be moderated? Minetest's playerbase is packed with trolls that would like nothing better than to walk around with an inappropriate skin

**Comment by SmallJoker** [comment]
There's yet no skins mod in minetest_game. Related #1965.
If you'd like that there's a central place in Minetest to upload skins, see https://github.com/minetest/contentdb/issues/143.

**Comment by paramat** [comment]
Yeah, there are many reasons why some people prefer MT over MC, although of course it is not for everyone.

Your feature is more of an engine request due to the complexity required.
I am not convinced it is worth the complexity when the current method of submitting skins to servers through other channels works well enough. They all have to be manually moderated, checked and sometimes edited anyway.

**Comment by paramat** [comment]
@TanyaEleventhGoddess 
This is an engine issue so please open here instead https://github.com/minetest/minetest/issues
Closing only because this is in the wrong place.
