### ISSUE TITLE
Describe 'wool' nodes as 'fibre block' (or something), not 'wool'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2574]
This is to partially clean up the 'wool from cotton' mess in MTG.
In MTG, wool nodes are made from cotton, so are not wool. But other games and mods may use the wool mod and produce the wool nodes from sheep.
Obviously we cannot now change the node names of wool nodes, but using the word 'fabric block' in the wool node descriptions makes sense for both cotton and sheep sources.
This is also more descriptive, as a wool nodes isa  woven material.

**Comment by An0n3m0us** [comment]
> Obviously we cannot now change the node names of wool nodes

How about using LBMs?

**Comment by paramat** [comment]
Nuuuu =) changing node names would be far to much trouble to be worth it.

**Comment by Wuzzy2** [comment]
I agree the itemstring should not be touched unless absolutely neccessary. Otherwise your pretty face is going to alias hell.

**Comment by An0n3m0us** [comment]
@Wuzzy2
But then the description of the blocks will not correspond with the mod name and the itemstrings.
We would end up having a wool mod containing cotton blocks or something xD

And if one was to create an actual wool mod; how would players tell the difference?

The problem is that it should've been corrected in the first place; but that cannot be helped now.

**Comment by HybridDog** [comment]
> But other games and mods may use the wool mod and produce the wool nodes from sheep.

I think those mods should add their own Sheep's Wool nodes with custom properties (e.g. a more coarse-looking texture). To me it does not make much sense to get the same "wool" node from cotton and sheep. For the craft recipes, we could add a fabric group because e.g. clothes can consist of both cotton and sheep's wool.

Fyi: This issue is no problem in some languages, e.g. the German word for "cotton" is "Baumwolle"; it is a determinative compound and literally means "tree wool".

**Comment by runsy** [comment]
I have wool from sheep in my Petz mod. I do not care about creating real wool nodes.
The problem I see is that cotton blocks are unrealistic, maybe cotton bobins, or cotton fabric. But this is impossible cos compatibility issues. :-O

**Comment by paramat** [comment]
Suggestion is actually disapproved by 3 core devs in the PR https://github.com/minetest/minetest_game/pull/2576#issuecomment-581073526
