### ISSUE TITLE
Papyrus tops

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2601]
Since in real life papyrus looks like this: ![hi](https://q7i2y6d5.stackpathcdn.com/wp-content/uploads/2011/11/papyrus1.jpg)

I think at least the fuzzy top should be added.
![Screenshot_2020-02-17-15-02-08-1](https://user-images.githubusercontent.com/33675971/74691961-ee6a2000-5199-11ea-9317-45b6f5291f3c.png)

![papyrus_top](https://user-images.githubusercontent.com/33675971/74692063-5f113c80-519a-11ea-963e-27d96bedb1a4.png)

**Comment by paramat** [comment]
This has occurred to me too.
However, i expect this is too disruptive to change now, considering papyrus farming machines in worlds etc.
Also ... all the existing papyrus that will not change, and the growing code needing to cope with both situations.
Although they look 'wrong', i like the classic appearence.
I am thinking it is probably best to leave them as they are.

**Comment by runsy** [comment]
I love the new papyrus. It's like being in old Egypt! :-)

**Comment by Moth-Tolias** [comment]
I like this graphical change as well.

**Comment by LoneWolfHT** [comment]
I like the look of it

**Comment by Gerold55** [comment]
I love it... even if it was just an addon mod to minetest... I know a lot and a lot of people would use it

**Comment by sfan5** [comment]
I wondered why similar issues don't come up more often.

It would be possible to change the `plantlike` rendering code to allow different a texture for the (bottom or) top-most node of the plant. Not sure in how many situations this will be useful though.

**Comment by Extex101** [comment]
@sfan5 that would cool if we could do that for plantlike rooted. Give kelp a top and bottom.

P.S. Hi @Gerold55 long time no see!

**Comment by Gerold55** [comment]
Hey yeah it's been a while...

**Comment by paramat** [comment]
To be clear, i think this could 'look' good, but it is important to think through all the issues.
Papyrus has been this way for many years, people build automated machines for farming papyrus that assume no special top node, a change could break many worlds, so we have to be careful.
I do not currently disapprove, just unsure it is worth doing. I should have used the word 'possibly' instead of 'probably' in the first post.

I think the texture would need to be improved, as you can see it does not resemble the photograph, needs to be taller and more spherical.
-1 for changes to plantlike drawtypes for a special 'top', i cannot see enough need currently and this can be done in MTG. Changes to drawtypes need a lot of justification.
Kelp looks fine as it is.

**Comment by Extex101** [comment]
Servers that have machines that farm papyrus break it from the bottom. So that won't be a problem

**Comment by Gerold55** [comment]
Yes and it would only change the bottom mostly no need to change the block
name. The top piece when broken would be a regular papyrus...

**Comment by Extex101** [comment]
Yeah just have it drop normal papyrus

**Comment by sfan5** [comment]
> -1 for changes to plantlike drawtypes for a special 'top', i cannot see enough need currently and this can be done in MTG. Changes to drawtypes need a lot of justification.

You are saying "this can be done in MTG", yet you argue that we can't change the top node because people might rely on it. Yes, drawtypes should not just be changed because it's convenient but this would solve exactly this issue.

> people build automated machines for farming papyrus that assume no special top node, a change could break many worlds, so we have to be careful.

I agree that care should be taken not to break worlds.
However I don't think we should cater to automatic farming or similar things and try to ensure such contraptions never ever break. Changes are fine as long as automated farming is not made entirely impossible.

**Comment by Abdou-31** [comment]
Why not follow the developers method in these case: making a new papyrus node which is more realistic and mark the old one deprecated, so players are invited to not use it anymore ? (may be you can add a visual effect to depracted nodes).

**Comment by An0n3m0us** [comment]
:+1:  Looks awesome! Can't wait for a PR

I think the new top bit shouldn't count as papyrus; instead be just a design, where it doesn't drop anything. Of course, it should be removed after one has dug the papyrus.

**Comment by LoneWolfHT** [comment]
I'm willing to do a PR if nobody else wants to

**Comment by Gerold55** [comment]
Look forward to seeing it...

**Comment by TumeniNodes** [comment]
This adds a nice visual, I like it.
And papyrus should really have more varieties of uses in-game (but that is a topic elsewhere)
https://egypt.mrdonn.org/papyrus.html

![Screenshot from 2020-02-24 01-42-08](https://user-images.githubusercontent.com/18484258/75133146-9d7d8e80-56a7-11ea-95d5-93097200fafb.png)

https://extension.msstate.edu/sites/default/files/news/2018/sg20180514_king_tut.JPG

**Comment by paramat** [comment]
> Servers that have machines that farm papyrus break it from the bottom. So that won't be a problem

Thanks for the information, so i have no objection to this done using an additional node added to the top. The texture needs to be improved and be more of a 'spherical puff', and an updated stem texture would be ok to remove the ridges.
> making a new papyrus node which is more realistic and mark the old one deprecated,

-1, unnecessary, too complex and too disruptive.

**Comment by paramat** [comment]
Closing due to #2710
