### ISSUE TITLE
Ores Rarity

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest_game#2664]
Some ores are very rare 
-diamonds
-mese block
-mese ore
It is not easy today to make large mesecons circuit in survival...
Is it possible to can set in the world generation panel ores global rarity ?

**Comment by SmallJoker** [comment]
Rarer ores were sort of requested in #1168, and added in #2107.

**Comment by paramat** [comment]
> It is not easy today to make large mesecons circuit in survival...

Ore densities have not actually decreased, the ore regions have just become deeper due to #2107
So the area with normal rarity is still present, but it is just deeper.
Each ore has an upper region of low density, and a lower region of normal density. You are probably misunderstanding the upper region as meaning ores have become less dense.
> Is it possible to can set in the world generation panel ores global rarity ?

:-1: Not fundamental enugh to add settings, it would also be very complex as there would need to be a lot of settings.
If you want to change ore rarity you can do this using a mod that clears the ore registrations then re-registers them with your desired changes.
If mesecons requires too much mese then the mod should change its crafting recipes, MTG does not change to compensate for poorly balanced mods.

The new depths are:
(The y values shown are: Top of upper low density region. Top of lower normal density region)

Ore. Highest. Density increase
Coal 64 -128
Iron -64 -128
Tin -128 -256
Copper -128 -256
Gold -256 -512
Mese crystal -512 -1024
Diamond -1024 -2048
Mese block -2048 -4096

**Comment by LoneWolfHT** [comment]
It isn't too hard to dig deep down if you have the right strategy.
Mods that allow teleportation or fast travel along the y axis help a lot too

**Comment by AFCMS** [comment]
On Minecraft, Diamonds and Redstones can be found much less deep that in Minetest.
I think it is a big difference between the two.

**Comment by SmallJoker** [comment]
@AFCMS I believe there aren't deep tunnels and caverns in the underground. There are quite holes in MInetest's underground which ease finding ores. Most servers and players use transportation mods (lifts, teleporters, carts) to get down really fast.

Without mods I can understand it might be frustrating to not find as many ores, but this ore placement is a compromise that was done under consideration of often used mining practices.

**Comment by paramat** [comment]
> On Minecraft, Diamonds and Redstones can be found much less deep that in Minetest.
I think it is a big difference between the two.

What Minecraft does is irrelevant =)

We used to have many complaints that mining was too easy, and it was far too easy, especially once we added tunnels that travel down a long distance, so a change was made for non-mgv6 mapgens. Mgv6 still has the old depths.

For the mesecons issue you should contact the mod maintainer and ask them to consider making the crafting recipes drop more conductors.

**Comment by paramat** [comment]
Huh i just realised something =D A Minecraft world has an underground only 64 nodes deep, so the ores are inevitably much shallower. So it is meaningless to compare ore depths to MT.

**Comment by AFCMS** [comment]
It would be cool to have possibility to play the two game styles

- Minetest : fast travel, teleport, etc (with ores deep)

- Minecraft : no fast travel (with ores not deep)

**Comment by paramat** [comment]
Closing due to #2710
