### ISSUE TITLE
Wool is too difficult to obtain

### ISSUE THREAD

**Issue by koi-ghoti** [minetest/minetest_game#2679]
When one begins a Minetest game, they must bear the burden of having to do things at night for an inordinate amount of time. The journey to find cotton seeds, which may only be found in a jungle, may be long and burdensome. I suspect that most players would prefer being able to start building comfortably in a more reasonable time frame.

**Comment by sfan5** [comment]
see #2551

**Comment by paramat** [comment]
And see #2617 . If merged, that will add wild cotton plants to savanna biome, so that cotton seeds are not limited to the rainforest biome (it is not a jungle biome).
If merged, that will make cotton as easy to find as it can be, while still being realistic, in which case this issue can be closed.

Some people find MTG too easy and complain about the lack of challenge. Some people like the challenge of having to explore, searching for particular biomes for particular resources. So it will be impossible to satisfy everyone.

**Comment by sfan5** [comment]
Cotton seeds can also be found in dungeon chests by the way. Though those are probably too rare to be considered a good source of cotton.
