### ISSUE TITLE
Cart icon looks strange

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2719]
The cart item icon looks weirdly stretched, especially the left side.

Version: 5.3.0

**Comment by sfan5** [comment]
#2666

**Comment by Wuzzy2** [comment]
Unfortunately, this still happens in e193f9fda3aff548bf0b6cd7890462eff82345dc to me.

**Comment by paramat** [comment]
![screenshot_20200718_205736](https://user-images.githubusercontent.com/3686677/87860937-6f8c3580-c939-11ea-8d46-6f6cb1f3e7a0.png)

#2666 was a bugfix, the inventory image now shows top, front and side as it should.
The front as shown in inventory is `carts_cart_front.png`:

![carts_cart_front256](https://user-images.githubusercontent.com/3686677/87861048-66e82f00-c93a-11ea-8e57-bea7f8048d6a.png)

But see my screenshot, the cart front in-game does not match `carts_cart_front.png` because the model's UV mapped texture is different.
So, `carts_cart_front.png` needs changing to match the UV mapped texture.

**Comment by paramat** [comment]
Resolved by merged PR.

**Comment by Wuzzy2** [comment]
The cart icon still looks strange in 6a9cbcad827c9e04eee53321844b170dfa63e388.

**Comment by sfan5** [comment]
Screenshot? It looks correct to me.

**Comment by Wuzzy2** [comment]
Oh, I see now the cart object textures were changed as well. My bad. Now the inventory image more or less matches the object. Nvm.
