### ISSUE TITLE
Chests can be rotated sideways by screwdriver

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest_game#2723]
**Engine Version:**
Minetest-5.3.0 a2199bf

Apparently it is possible to rotate chests onto their side using the screwdriver tool. As a result, when the chest is right-clicked, the formspec is perpetually stuck on the screen. The only way to escape is to force-quit Minetest (although if you press ESC fast enough, you may be able to access the game menu).

I cannot think of any reason why non Y-axial rotations are even needed for chests. Perhaps this hints at a much more serious concern: Why does the screwdriver assume that `paramtype2 = "facedir"` nodes can be rotated around any axis? I would think the default behavior should have been `screwdriver.rotate_simple`, unless otherwise specified. But I guess that is too late now.

I suggest going through all `paramtype2 = "facedir"` nodes in MTG and assess which ones should actually be using simple rotations, with `default:chest` and `default:chest_locked` being the top priority obviously

**Comment by An0n3m0us** [comment]
> As a result, when the chest is right-clicked, the formspec is perpetually stuck on the screen.

This doesn't occur for me on `5.4.0-dev`.

**Comment by sorcerykid** [comment]
Ah, good catch. I think I upgraded the engine but copied over the Minetest Game mods from 5.0.0. So there were likely changes that resolved that bug. But  your are able to rotate the chests sideways, correct?

**Comment by An0n3m0us** [comment]
> But your are able to rotate the chests sideways, correct?

Yeah. It can be rotated in all of the axes.

**Comment by paramat** [comment]
> Apparently it is possible to rotate chests onto their side using the screwdriver tool.

Although non-Y rotations are not what you would usually expect for a chest, there is no harm in allowing this for the rare occasion it might be wanted for whatever crazy or decorative reason (for example a ruined building where a chest has been knocked onto its side to create a 'messed up' look).
I do not agree to restricting rotation for nodes unless there is actual harm caused. So :-1: for doing this for chests.
> I suggest going through all paramtype2 = "facedir" nodes in MTG and assess which ones should actually be using simple rotations

All that matters is if there is actual harm, which i doubt there is for any node. In which case it is not worth the effort and extra code complexity.
> Why does the screwdriver assume that paramtype2 = "facedir" nodes can be rotated around any axis?

Seems an odd statement, why would it not?
"facedir" allows all possible rotations, so this assumption is obviously correct. Defaulting to Y-axis rotations only would be wrong because the large majority on nodes require all possible rotations. Defaults are usually set to the majority usage to keep code simpler.

**Comment by sorcerykid** [comment]
> I do not agree to restricting rotation for nodes unless there is actual harm caused. So i disapprove doing this for chests 👎

Doors are restricted to Y-axis rotations for no obvious reason, even though trapdoors aren't. For consistency with everything else in the game, therefore, doors should be rotatable around X, Y, and Z axes. I can think of several type of builds where a door lying face down on the ground would be useful.

**Comment by LoneWolfHT** [comment]
Doors are made up of two nodes, I don't think allowing non-Y rotations would be an easy task

**Comment by sorcerykid** [comment]
Closing because this is not critical enough to be deemed necessary maintenance. Also I have a Chests Redux mod that restricts rotation, so I may simply publish that as an alternative.
