### ISSUE TITLE
Lava should melt ice

### ISSUE THREAD

**Issue by niansa** [minetest/minetest_game#2736]

**Comment by paramat** [comment]
Duplicate.
Melt to water or destroyed completely?

Whether lava should melt or flood (destroy) ice was discussed in #1005 see https://github.com/minetest/minetest_game/issues/1005#issuecomment-259122325
It was decided that ice cools lava to make obsidian, PR #1383 . This is because if lava melted ice to water, that water would then turn lava into obsidian anyway.
So essentially ice acts just like water in the lavacooling ABM.
