### ISSUE TITLE
Sounds files need volume balance

### ISSUE THREAD

**Issue by johalun** [minetest/minetest_game#2749]
Hey

One thing I noticed while playing is that some sounds are very loud compared to others. The first one that is very prominent is footsteps. Googling this show I'm not the only one. Also when watching Minetest Youtube videos, this really stands out. The other one (that I found so far) is doors opening/closing. 

In general I think maybe sounds files need to be balanced a bit. I was also thinking about options for controlling volume for difference categories of sounds but that wouldn't really help if sounds in the same category are not balanced.

For now, I ended up deleting the footstep sound files just because it got kind of annoying. No complaints or disrespect to the sound themselves, they are fine, just the volume in comparison to other sounds in the game is a problem.

I'm not a sound guy so not sure the best solution would be. Editing the sound files directly or change the playback volume in the code if there's support for it?

**Comment by johalun** [comment]
Ok so I dug through the lua code a bit and found that each sound is registered with a gain. I change footsteps to have 50% of their original gain and doors I set to 30% of the previous value. Feels more balanced now.

**Comment by paramat** [comment]
Yes this is not surprising. We recently changed a lot of sounds, and to get the PR merged were not perfectionist about rebalancing the levels, so some may be unsuitable.
I should probably rebalance the new sounds, none are very bad but they can be improved.
When i balanced sounds i intentionally make the footsteps a little subtle, because they can get tiresome due to the repetition.

**Comment by SmallJoker** [comment]
@johalun Also feel free to open a PR after you're satisfied with your changes - so that the balancing work is only done once ;)

**Comment by paramat** [comment]
@johalun i need to know what version of MTG you are referring to.
Only the development version after 29 August contains commit https://github.com/minetest/minetest_game/commit/befed5525a33f1d563e2a1b8a33fcb3775fcb006 with the recently added new sounds.
This is to clarify if you are reacting to the recently added new sounds.

It would also be good to know which specific sounds you find too loud. Footstep sounds are not all identical in loudness, some are already quiet.
> Also when watching Minetest Youtube videos, this really stands out.

But you do not know if you are reacting to sounds from mods, only sounds in unmodded MTG are relevant.

Related to that, is your opinion based on using unmodded MTG? Be careful to ignore any mod sounds.

I certainly disagree with reducing any of the older footstep sounds to 50%, as that is extreme and they are already well balanced, but the recently added new ones might need a lower level.
However, you might be reacting to the recently added new footstep sounds (some of which are fairly loud) and did this as a rough first experiment without considering each sound individually.

Ignoring the recently added new sounds:
We have had very few complaints about sound levels since i balanced them 4 years ago. This suggests the balance is already a good compromise of people's differing tastes. Due to that and for consistency, i would like to do the balancing of the recently added new sounds myself.

**Comment by johalun** [comment]
I'm using 5.1.1+repack-1build1 on Ubuntu 20.04. AFAIK, no mods other than MTG that has footstep sounds.
The sounds files are `default_*_footstep.*.ogg`

**Comment by jamesalexanderstevenson** [comment]
The code in TNT mod has gain > 1.0; which is a crazy thing.

**Comment by TumeniNodes** [comment]
> The code in TNT mod has gain > 1.0; which is a crazy thing.

 This gain setting was chosen for a good reason.
Look back at the PR for more detail. https://github.com/minetest/minetest_game/pull/2449

**Comment by paramat** [comment]
Thanks, 5.1.1 is well before the new sounds, so has well balanced levels in my opinion, especially footsteps, i intentionally made them quiet relative to everything else.
Sound levels are rather subjective, and this issue proves that, so it will be impossible to satisfy everyone, it is like textures, someone will always complain =)
We could check door levels, but otherwise i suggest a close unless someone can specify an extreme problem.

**Comment by johalun** [comment]
I didn't realize ubuntu default apt install is that old. I'm running newer version now and I don't feel that footsteps are too loud so all good there! 

It's not complaining, it's contributing valid opinions to an open source project. But yeah, I get what you mean. However, when opening/closing a door is twice as loud (subjective guess here) as mining stone with a pick axe, then something is off :) A few nodes away it's not so bad but when using pressure plates to open the door it opens when you're right next too it and then it's quite loud.

**Comment by paramat** [comment]
Ok good to know. I will check doors, they may need tweaking.

**Comment by TumeniNodes** [comment]
Doors _are_ rather loud as a whole.
I've felt the same about it since I first discovered MTG.
They could probably use some reduction.

I think the larger issue with this, is for people who like to play at times when others may be sleeping...  ; )

**Comment by 0-afflatus** [comment]
They really are ...
It's a five minute job to fix

**Comment by TumeniNodes** [comment]
if I had the 5 minutes, I'd do it.
As is, lately I only get about 5-10 min just to cruise through some MT stuff and comment.
Pulling up code and pulling in all the latest merges, etc... turns into about a couple hours with testing

**Comment by 0-afflatus** [comment]
@TumeniNodes I'm not suggesting you do it. Paramat has already self-assigned this.
Yes testing is very time-consuming.
I am a sound engineer / musician, so I'd be happy to do it if that was an issue. However, I've been out of the loop for a long while, and while it would be good practice to get myself organised in order to submit a PR, there may be more useful things I could do.

**Comment by paramat** [comment]
It takes more than 5 mins to do this well =) This is what i intend:

Place various nodes that play the older well balanced sounds (the newer sounds are not yet fine-adjusted).
Listen on headphones.
Trigger those sounds while fine-adjusting volume to a comfortable andn balanced level.
For each door: Open/close from 1 node away (max volume) and fine adjust the sound gain.

Will do this within a few days.

**Comment by johalun** [comment]
@paramat Thanks! Highly appreciate it :)

**Comment by TumeniNodes** [comment]
> @TumeniNodes I'm not suggesting you do it.

 I didn't assume you did, I was simply commenting I'd have done it if I had the time.

**Comment by paramat** [comment]
PR #2767 
Doors/trapdoors/fencegates really were far too loud.

**Comment by paramat** [comment]
During testing i discovered that several door/trapdoor/fencegate sounds are indeed far too loud when the player is close.

I will start work on a better solution than #2767 , the better solution is explained here https://github.com/minetest/minetest_game/pull/2767#issuecomment-719931068

**Comment by paramat** [comment]
WIP PR #2768

**Comment by paramat** [comment]
johalun,
I decided to check and balance all MTG sounds, resulting in PR #2774 , and discovered many unbalanced sounds, including some footstep sounds. Sorry that i was too confident in my sound balancing of a few years ago.

**Comment by paramat** [comment]
#2768 merged, but that did not close this issue. I forgot to remove the incorrect 'closes #xxxx' comment in that PR.
This issue will be resolved when #2774 is also merged.

**Comment by paramat** [comment]
Please fix this high priority issue and merge #2774
