### ISSUE TITLE
New stone dig sounds sound worse

### ISSUE THREAD

**Issue by Desour** [minetest/minetest_game#2755]
It sounds very different, not stony and not good.

The new gravel dig sounds are also not that nice.

Edit: #2605 is probably the PR that introduced these sounds.

**Comment by paramat** [comment]
The core devs decided they were better. I prefer the older gravel dig sound but was outvoted.

As MTG is feature frozen, there needs to be a very good reason to change sounds, everyone will have differing tastes so we cannot take personal tastes too seriously otherwise we will have never-ending issues and PRs.
So, as these sounds are acceptable, i am not convinced it is worth changing them again.

:-1: i think this should be closed unless multiple core devs consider the sounds a big problem.

**Comment by paramat** [comment]
Hmm actually, if any of the new sounds were considered a big problem core devs would have already objected to them in that PR.
So this is just a personal taste issue and therefore cannot be considered for obvious reasons.
MTG is also feature frozen, we do not accept new sounds or textures unless there is an actual significant problem, which there is not.
We have to be strict otherwise we will not move on and precious core dev time will be diverted from the engine.

**Comment by KaylebJay** [comment]
I tested the new stone sounds and they are indeed worse than before (IMO). The new gravel dig sound is quite good though, from my perspective.
