### ISSUE TITLE
Placing nodes in the air using butterflies

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest_game#2786]
You can use a butterfly (i guess fireflies too, but i didn't test) to place nodes in the air.
If you destroy the node afterwards, the butterfly is gone.

One should not use the words 'realism' and 'minetest' in the same sentence, but this just feels wrong.

![screenshot_20201130_090930](https://user-images.githubusercontent.com/32773707/100584309-394dc200-32ec-11eb-8a64-07c29a297772.png)

![screenshot_20201130_090941](https://user-images.githubusercontent.com/32773707/100584327-3f43a300-32ec-11eb-9e43-de984e04403e.png)

**Comment by randomMesh** [comment]
Proposed fix (if approved, i'll post a pull request):

```diff
diff --git a/mods/butterflies/init.lua b/mods/butterflies/init.lua
index 49240ee..f2f97c4 100644
--- a/mods/butterflies/init.lua
+++ b/mods/butterflies/init.lua
@@ -31,7 +31,7 @@ for i in ipairs (butter_list) do
                waving = 1,
                paramtype = "light",
                sunlight_propagates = true,
-               buildable_to = true,
+               buildable_to = false,
                walkable = false,
                groups = {catchable = 1},
                selection_box = {
@@ -57,6 +57,9 @@ for i in ipairs (butter_list) do
                                minetest.set_node(pos, {name = "butterflies:hidden_butterfly_"..name})
                        end
                        minetest.get_node_timer(pos):start(30)
+               end,
+               on_rightclick = function(...)
+                       return false
                end
        })
```

**Comment by NathanSalapat** [comment]
I agree that this seems odd, however the problem with this solution is you can't punch the butterflies or fireflies to break them, which means you would have to build a net and catch them if you wanted to build anything in a space where they are.

**Comment by randomMesh** [comment]
> with this solution is you can't punch the butterflies or fireflies to break them

You're right, didn't think of that. I changed the code to take care of this:
```diff
diff --git a/mods/butterflies/init.lua b/mods/butterflies/init.lua
index 49240ee..3b57e1f 100644
--- a/mods/butterflies/init.lua
+++ b/mods/butterflies/init.lua
@@ -31,7 +31,7 @@ for i in ipairs (butter_list) do
                waving = 1,
                paramtype = "light",
                sunlight_propagates = true,
-               buildable_to = true,
+               buildable_to = false,
                walkable = false,
                groups = {catchable = 1},
                selection_box = {
@@ -57,6 +57,12 @@ for i in ipairs (butter_list) do
                                minetest.set_node(pos, {name = "butterflies:hidden_butterfly_"..name})
                        end
                        minetest.get_node_timer(pos):start(30)
+               end,
+               on_rightclick = function(...)
+                       return false
+               end,
+               on_punch = function(pos, ...)
+                       minetest.remove_node(pos)
                end
        })
```

**Comment by paramat** [comment]
Thanks for your work on this.
MTG is feature-frozen but bugfixes are still done.

**Comment by randomMesh** [comment]
> MTG is feature-frozen but bugfixes are still done.

I wasn't sure if this a bug or a missing feature. Anyway, i created a pull request.

**Comment by appgurueu** [comment]
This unfortunately turns out to be nontrivial, despite appearing quite trivial at first glance:

1. Using `buildable_to = false` the issue can be partially resolved: The butterfly won't be replaced anymore, it will just be "built to"
2. By setting `on_rightclick`, simple rightclicking can be disabled. Nodes can still be placed next to the butterfly using shift + rightlick though.
3. This can be mitigated using `register_on_placenode`. But even that has it's [issues](https://github.com/minetest/minetest/issues/11967).

Making the butterfly not pointable is hardly an option, as that would stop the net from the `fireflies` mod from working. This could again be worked around using raycasts or the like, but would provide very bad user experience.

An entity for butterflies could fix many of these problems, but would also introduce new ones. In particular, backwards compatibility dictates that the nodes be kept. Perhaps a node + entity combination could be used?
