### ISSUE TITLE
Marram grass missing groups

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2842]
Marram grass is missing the grass and flora groups
Suggestion:
marram_grass and flora

**Comment by sfan5** [comment]
The usage of "type-specific" groups seems inconsistent: fern and junglegrass don't have them, others do
Agree it should have `flora` though.

**Comment by Wuzzy2** [comment]
It makes sense give each “grass size variant” its own group because it gets annyoing if you want to check whether a node is e.g. marram grass, “normal grass”, dry grass, fern. Currently, you must check all sizes manually, which is awkward.

Suggested groups: `marram_grass`, `fern`, `normal_grass` (for all 5 sizes of `default:grass_X`, but not other grass types), `dry_grass`.
And the `grass` group is the overall group for all grass types (grass, dry grass, marram grass).

**Comment by Extex101** [comment]
Grass and dry grass already have the `dry_grass` and `grass` groups so it's just a matter of adding new groups to marram grass and fern (as well as flora to marram gras as stated earlier)
