### ISSUE TITLE
recipes tab shows not_in_creative_inventory grouped items

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest_game#2843]
what the title says https://github.com/minetest/minetest_game/blob/master/mods/mtg_craftguide/init.lua#L120 is to blame for it, adding on `and def.groups.not_in_creative_inventory ~= 1` to the end of it is the simple fix however that isnt exactly the best code format

**Comment by sfan5** [comment]
I don't see the issue here, if a craft is defined for an item why shouldn't the craft guide show it?

Which items do you see appearing in the craft guide which you think shouldn't be there?

**Comment by wsor4035** [comment]
install mesecons, click on the recipe tab, it will show all the variations of the wire node which have no craft, and should not be shown 
![image](https://user-images.githubusercontent.com/24964441/109897453-ba588480-7c60-11eb-95c6-70487625305f.png)

**Comment by rubenwardy** [comment]
Yeah, on thinking about this, the problem is that they have no recipes

**Comment by wsor4035** [comment]
add the janky fix in the first message and the problem is fixed

**Comment by wsor4035** [comment]
to clarify, you cannot see the items in all(as it should be), but you can see them in the recipe tab

**Comment by sfan5** [comment]
It shouldn't be showing items that have no recipes IMO, that'd solve this without relying on pre-set groups.

**Comment by ronoaldo** [comment]
Maybe this part needs to change then?

https://github.com/minetest/minetest_game/blob/2c9733ac4593e85cf27a44ad498f52b97499594e/mods/mtg_craftguide/init.lua#L160,L164

```lua
	for name, def in pairs(minetest.registered_items) do
		if recipes_cache[name] or usages_cache[name] then
			table.insert(init_items, name)
		end
	end
```

I guess (but not tested yet) that by removing the `or usages_cache[name]` condition, it will not show items that has no recipe and only usages. I'm not sure if there is an use case for showing items that cannot be crafted. I do see some use cases where showing the item that is not in creative because it can serve as a "guide" to how to obtain the item that way.

**Comment by wsor4035** [comment]
> It shouldn't be showing items that have no recipes IMO, that'd solve this without relying on pre-set groups.

yeah, i agree with this, my fix fixes the issue in the image for the wrong reason. however i still think that the crafting guide should not shows items with the not_in_creative_inventory group even if they have a craft recipe. since its odd to not have them in one tab(all), but to have them in another(recipes).

**Comment by pauloue** [comment]
Many items that cannot be crafted can be found in the wild or created by means other than crafting. It's useful to show usages for these items. For example, a player might collect some gravel and wonder what they can use it for, so they search for it in the craft guide and find that they can craft gun powder with coal and gravel. Another example: a key cannot be crafted, but can be smelted into gold.

Items with `not_in_creative_inventory` are shown because they may have useful recipes. For example `default:book_written` is not show in the creative inventory, but it has a recipe to copy the contents into a new book.

I think the solution is to add `not_in_craft_guide` to the mesecons items.

**Comment by wsor4035** [comment]
hmm, maybe i do agree with you on allowing `not_in_creative_inventory` items to show, since they do have the option to hide if they want. however i disagree with

> I think the solution is to add `not_in_craft_guide` to the mesecons items.  
  
i disagree with you here and agree with sfan5

> It shouldn't be showing items that have no recipes IMO, that'd solve this without relying on pre-set groups.

**Comment by sfan5** [comment]
@pauloue makes a good point: If items with zero craft are dropped then people are not able to see their usages.

For Mesecons specifically it looks like a recipe is registered for every possible wire state (why isn't it a group?).
There are no automatic means to detect this so setting them as `not_in_craft_guide` is the only solution here.

**Comment by louisroyer** [comment]
> For Mesecons specifically it looks like a recipe is registered for every possible wire state (why isn't it a group?).

I checked and it is not the case: recipes are registered only once. Most recipes are using `group:mesecon_conductor_craftable` (and other recipes only use `mesecons:wire_00000000_off`).

**Comment by pauloue** [comment]
I think a good solution would be to add `not_in_craft_guide` to all but one of the mesecons wires. That way there will only be one wire in the item list, but you don't loose any usages since the wires all have the same usages.

**Comment by louisroyer** [comment]
> I think a good solution would be to add `not_in_craft_guide` to all but one of the mesecons wires. That way there will only be one wire in the item list, but you don't loose any usages since the wires all have the same usages.

This is exactly the solution I had implemented in https://github.com/minetest-mods/mesecons/pull/555.
