### ISSUE TITLE
More Strong Base Game

### ISSUE THREAD

**Issue by MrDraxs** [minetest/minetest_game#3036]
i know that you guys said that you have officially moved to maintenance only mode but the facts are that people are layz, if you guys dont modifiy the base game to have (a good story, good mechanics, mobs, npcs, bosses) basicaly if you guys dont make the base game more interesting most of the people will open the game see that they can't even sprint will not open a search the mods close the game and never open ever again, the more strong base game is needed to attract more people "maybe even big streamers and etc" to the community so more mods are created and the community thrive and grow allot.
I'm not asking you guys to create a clone of minecraft, but i do recommend that you guys make something like dawncraft(modpack).
(what i would like to play is a minecraft mixed with titanfall2 parkour far-cry close kill actions (it wouldn't kill but take a good part of the enemy life) and dark-souls like combat. this are my preferences and recommendations you guys can make any type of base game you like)
i really want to see this game thrive instead of being forgotten, please reconsider your guys approach on maintenance only mode.

**Comment by appgurueu** [comment]
> basicaly if you guys dont make the base game more interesting most of the people will open the game see that they can't even sprint will not open a search the mods close the game and never open ever again

That's why there is a proposal to [ship the engine without games](https://github.com/minetest/minetest/issues/9509#issuecomment-1531191733), forcing the users to choose a game.

> i really want to see this game thrive instead of being forgotten, please reconsider your guys approach on maintenance only mode.

There are multiple issues with this:

* MTG has significant technical debt (e.g. poorly modularized with a massive `default` mod, much code duplication, an overall legacy codebase).
* We (the MTG maintainers) and the core devs seem to have too little development resources for such an effort.
* We can't afford to risk breaking backwards compatibility since MTG is a widely used modding base.
* There is a lack of direction. Being a modding base, MTG is supposed to be bland; mod it to your liking! If we chose to change this, we'd still need direction; the bikeshedding would be worse than what there already is.

That said, I'd be open to discussing turning MTG into a proper game. That should probably be a fork (with better branding) though, and we'd have to get a couple experienced modders on board to be able to sustain development efforts.
