### ISSUE TITLE
Invalid position "crash" in TNT mod

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest_game#3120]
I've seen some error like (and similar) to this:

```
2024-03-19 07:06:00: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): Invalid position (expected table got nil). 
2024-03-19 07:06:00: ERROR[Main]: stack traceback: 2024-03-19 07:06:00: ERROR[Main]: [C]: in function 'get_meta' 
2024-03-19 07:06:00: ERROR[Main]: .../../games/minetest_game_28/mods/tnt/init.lua:410: in function 'boom' 
```

I fixed it like this:
```
diff --git a/mods/tnt/init.lua b/mods/tnt/init.lua
index 622b6c9..ab438a5 100644
--- a/mods/tnt/init.lua
+++ b/mods/tnt/init.lua
@@ -159,6 +159,7 @@ local function entity_physics(pos, radius, drops)
 	local objs = minetest.get_objects_inside_radius(pos, radius)
 	for _, obj in pairs(objs) do
 		local obj_pos = obj:get_pos()
+		if obj_pos then
 		local dist = math.max(1, vector.distance(pos, obj_pos))
 
 		local damage = (4 / dist) * radius
@@ -200,6 +201,7 @@ local function entity_physics(pos, radius, drops)
 				end
 			end
 		end
+		end
 	end
 end
 
```

**Comment by SmallJoker** [comment]
`minetest.get_objects_inside_radius` should never return invalidated objects. This appears to be an engine issue. Related code:

https://github.com/minetest/minetest/blob/6c0b8229ecc8da7109ca471db8480a345abdf426/src/script/lua_api/l_env.cpp#L766-L767

**Comment by appgurueu** [comment]
> `minetest.get_objects_inside_radius` should never return invalidated objects. This appears to be an engine issue.

The problem is that this is a pre-generated list however. Due to side effects the object refs in that list can still be invalidated while we are iterating the list.

For example, suppose one object is attached to another, and the logic is such that when the "parent" is removed, the "child" is removed as well (there are a few mods with logic like this).

If the parent is then damaged - and killed - first, this will result in the "child" being an invalidated object during the traversal.

I believe we should provide an abstraction for modders to loop over non-invalidated objects inside radius. Due to the aformentioned reason, this will need a new iterator-based API.

**Comment by lhofhansl** [comment]
Shall I do a trivial PR with this?

**Comment by appgurueu** [comment]
> Shall I do a trivial PR with this?

Sure, go ahead.
