### ISSUE TITLE
Damage for the hoe and the screwdriver

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest_game#3143]
### Problem

The hoe and the screwdriver don't deal damage to NPCs like other tools.

### Solutions

The hoe and the screwdriver should deal damage to NPCs like other tools.

### Alternatives

I don't have any.

### Additional context

Since those 2 tools have the left click assigned to a specific action I can understand if it won't be possible to set them to deal damage to NPCs when they're aimed and within the tool range. If so, you can just tell it and close the feature request right now.

**Comment by appgurueu** [comment]
Probably a somewhat controversial feature I imagine, especially when it comes to the screwdriver. We probably have to reject this due to the permanent feature freeze MTG is in (unless there is a way to frame this as a bug fix?).

(I see no reason why this shouldn't be possible to implement, however.)

**Comment by tenplus1** [comment]
@PavanLuca - If it helps I've tweaked Farming Redo so that registered Hoe's damage player and mobs.
