### ISSUE TITLE
minetest_game is it still fun enough ?

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#432]
Interesting remarks yesterday (celeron55 and rubenwardy) : http://irc.minetest.ru/minetest-dev/2015-02-18#i_4160244

- Is that the game should, as a technical showcase, further exploit the engine can do actually ? (i.e. showing off mesh nodes, particles, entities, GUI elements, etc.)

- Should we provide more blocks / items, refine the gameplay and make the inventories more practical ?

Aiming reference, VoXus : https://forum.minetest.net/viewtopic.php?f=50&t=10895

**Comment by nerzhul** [comment]
i think minetest_game must have more functionalities for regular players. mods are very good, but users which wants to know about minetest, regular users, test the game with default minetest_game from package manager... and the modding comes before, when they have tested the game and they want more, but they need to be interested in their first approach.

Minecraft exposes more functions by default, enjoying players, and users who wants more can mod, but many users doesn't mod by default.

**Comment by rubenwardy** [comment]
Not necessarily minetest_game, but including other subgames.

Relevant:
* [Gaining our own identity, as a gaming experience.](https://forum.minetest.net/viewtopic.php?f=3&t=10885)
* [Advantages and Disadvantages of merging Mesecons](https://forum.minetest.net/viewtopic.php?p=158606)

**Comment by C1ffisme** [comment]
I agree that moreblocks and plantlife should be added, but moreblocks shouldn't consume the memory with so many node types. About mesecons : I agree that a simpler version would be nice. I think that maybe a drawtype for wires should be added if it is added. I had an idea though, we could stick some mods into the mods folder, and then when people are wondering what the "Customize" button does, they find they can add more nodes and fun to the game, but they can choose if their worlds are laggy or not.

**Comment by rubenwardy** [comment]
Mods bundled by default is a good idea, in my opinion.

**Comment by Calinou** [comment]
Please include default walking speed. This changes a lot to how you feel a subgame.

**Comment by C1ffisme** [comment]
What about merging moreores? We could alias the gold and copper, and the tin would make bronze more logical. (See my talk at #178 for other reasons to add tin.) If not too laggy, we could try and add 3d_armor, although a purpose for armor is yet to be found.

**Comment by Wuzzy2** [comment]
The biggest problem with minetest_game is that is does not have a real project goal.
What are you aiming for? A pure sandbox?
An actual game (minetest_game is FAR away from that)?
Just a technical demo?
A “base for modding”?

Etc.

IMO minetest_game does not do really well in all these categories. For a sandbox, it's too small. For a game, it lacks challenges and goals. Minetest_game is, in fact, not a game at all. For a technical demo, it is too outdated, because it fails to demonstrate Minetest's latest and greatest features. Other subgames have long overtaken minetest_game here.
For a base for modding, it carries along a lot of cruft, and there is a poor seperation of core mods (look how overloaded the default mod is: Player model, GUI definition, random and large collection of items, core functions, etc.).

**Comment by Calinou** [comment]
> although a purpose for armor is yet to be found.

PvP. Also, mobs.

**Comment by rubenwardy** [comment]
Armour could be used for falling damage and lava damage too.

**Comment by C1ffisme** [comment]
True, true. Speaking of PVP, why not add bows? We don't have any real range weapons in minetest other than maybe lava. And lava dosen't spread far enough, not to mention it is destructive.

**Comment by Calinou** [comment]
The throwing mod could be added, provided it is made safe enough for use (ie. can't crash server or remove immortal entities with it).

**Comment by C1ffisme** [comment]
@Calinou Yeah. And no fire arrows, those cause some SERIOUS lag. We should probably add some normal, build, dig and TNT arrows. (TNT arrows becuase it would be like having a rocket launcher! AWESOME!!!!)

**Comment by MT-Modder** [comment]
It could also have an api for adding new bows and arrows.

**Comment by C1ffisme** [comment]
We have beds now! Yay!

**Comment by C1ffisme** [comment]
This is also related : #426 and see my list of things to add...

**Comment by paramat** [comment]
The answer is it desn't need to be.
I feel celeron55's remark misses the point, MTgame has never been particularly exciting and that is not a problem. The MTgame team do have an objective for it, which is to be a simple and minimal basis for adding modules to, and to not force anything complex or specialised on anyone, so it will inherently feel rather lacking. Ths is why extra content is, and should be, added in a very restrained way.

As it is now it can be fun enough for some, if all you want to do is build stuff and not worry about survival, hostile mobs etc. It's a bit like LEGO, the only limit is your own imagination. New players are not stupid and will quickly find the forum with all the exciting content in the mods, the slightly boring nature of MTgame is an encouragement to download mods. If they are stupid then it's no loss to us (in fact a benefit) if they get bored and go elsewhere =)

Plantlife should not be added, as awesome and beautiful as it is, it is too complex, specialised and has too many species for MTgame, even if it's performance was increased it's complexity would still make basic mapgen too slow. It is a mapgen mod, basic mapgen should be done in the engine or in the biome API because those are both very fast.

**Comment by rubenwardy** [comment]
The only limit is what the engine's API supplies, what mods exist and whether or not it will crash.

**Comment by C1ffisme** [comment]
You know, thinking about it, it's really about the balance of the game.

**These things are throwing off minetest's balance:**
1. Mods.
Get a mod like homedecor, and it limits creativity. In minecraft there is no real furniture, so you have to think of ways to build it. You start to think about what you should build.
2. No competition.
No, I'm not talking about other clones, I'm talking about gameplay. When you play the game, you are completely alone. You can reach your goals without much trouble. If you put weights on the mining key and the forwards key and watched out for lava, you could get diamonds in just a few minutes. In minecraft you have to watch out for zombies, gravel, mob spawners, you keep active in the game.
3. No goals.
See, survival minetest is boring because as soon as you reach diamond, you've pretty much won the game. In minecraft, every survival world you play, you are trying to defeat the ender dragon. It takes skill and you work towards the goal. You basically create a story about yourself. Maybe minetest needs some kind of hidden treasure, underground ores that are really hard to get, etc.
Even on multiplayer minecraft, you want to become the biggest and best known player on the server.
4. Not enough teirs or technology. And no reason to explore.
In minecraft, you need to get around the world to collect resources from different biomes. In minetest, it's just the same 2 biomes over and over again. No rare mushroom biomes or anything. In minecraft you are encouraged to use your resources to build railways, portals, boats, and many more methods of transportation. Just imagine being able to manipulate your world. Having bases everywhere...

Basically, we need to add a few more things to minetest_game:
* Exploration (More biomes, underground dungeons with treasure, etc.)
* A goal or 2 (Either a final boss or superior technology or the best possible ores, etc.)
* Fighting (Humans like to argue and complain. Adding mobs would help. We just need to tweak the engine...)
* Enough Content (Sometimes you just need to make sure people DONT download mods.)

**Comment by 0-afflatus** [comment]
1. Agreed. moreblocks > homedecor for the sort of game I like. However, the default game needs to cater for broader tastes, this is one reason for keeping the default game simple and encouraging people to add mods.
2. Fair comment, so add mobs. For me the only reason for not adding mobs by default is the lack of maturity of any of the available mobs mods. Mobs Redo is probably closest IMO.
3. You forgot about nyancats, but this is a useful observation nonetheless. Hidden treasure / quest items with a story angle, plus some kind of player ranking system may help towards creating goals. I think it is important to keep it open-ended, so I don't like the idea of a "final boss".
4. The new biomes support will give plenty of reason to explore. I'd like to see a more structured tech tree with bottlenecks created by crafting recipes involving rare resources or other difficult to craft items.

I feel your perceptions are over-coloured by Minecraft. I have found your thoughts very useful in building my sub-game, but I think minetest_game should be kept relatively simple. Some people just like playing virtual lego.

**Comment by C1ffisme** [comment]
@0-afflatus I'm glad you agree. About number 3, I think a solution might arise if we add one of the achievement mods that has sprung up in the Mod Forums. Then we could add some goals that people might enjoy.

Okay, I admit I've been playing a lot of Minecraft recently. Maybe I think we just need to get my attention more.

About virtual lego, maybe VAEs will solve the problem of no vehicles. I hope.
