### ISSUE TITLE
Rename Minetest (the subgame)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#437]
I suggest to rename Minetest (the subgame). I am only talking about the “human-readable” name which is openly advertised, not what is internally used for some repository name or folder name etc.

I discussion, two names are used commonly used for this subgame, and both are bad:
* “minetest_game” (too technical)
* “Minetest” (identical to the name of Minetest (the engine))

IMO this subgame needs a “human-readable” name which is can not be confused with the name of the engine (“Minetest”).

This issue comes directly from the forums:
https://forum.minetest.net/viewtopic.php?f=3&t=10854
I post it here because few disagreed with that Minetest (the subgame) needs to be renamed.

As of the moment in which I wrote this, suggested names were:
* “Official subgame”
* “Mineland”
* “minetest_demo”
* “game_demo”
* “Minetest Sandbox”
* “Minetest Vanilla”
* “Minetest VanillaBox”
* “VanillaBox”
* “Vanilla Minetest”
* “Common base game”
* “Minetest Game”

First: Would you agree that this subgame needs to be renamed?
Second: Post ideas for names here. :)

**Comment by MT-Modder** [comment]
I think it should be changed as well, just calling it "Minetest" can be confusing to new players.

:+1: For Minetest Vanilla. It fits and it helps new players, those who know the term "vanilla" of course, understand it's just a basic representation of the engine and not an immersive game with goals.

**Comment by Wuzzy2** [comment]
Finally, for the first time, I post my name ideas:
* “Meseland” (Because it has mese in it, and landscapes)
* “Mesetest” (Because is has mese in it, alludes to “Minetest”, also the whole subgame feels more like a test instead of a full gaming experience. :D)
* “Mesemine” (Because mining is a mining task, and mese is the most unique ore you can find)
* “Mesetint” (this is based on a folder name of Minetest the subgame of a very old 0.3 release)
* “Testmine” (Get it? Minetest is the engine and Testmine the subgame. Haha!)

**Comment by MT-Modder** [comment]
Of those suggestions I prefer "Mesetest" for the reasons stated above and it differs the least from current name. If some form of mesecons is added it would make that title fit even better.

**Comment by kilbith** [comment]
No, minetest_game is good enough.  No ambiguity.

**Comment by Wuzzy2** [comment]
The problem is, “minetest_game” is only colloqial. The current official name is “Minetest” (that's what game.conf says). Not even the folder name is “minetest_game”, the actual folder name is “minetest”.

I guess the name “minetest_game” soley comes from the name of the repository.

Or do you maybe want to suggest that Minetest (the subgame) is now to be *officially* called “minetest_game”?

**Comment by MT-Modder** [comment]
@kilbith The name in the game.conf should at least be changed to "Minetest Game", instead of just "Minetest".

**Comment by dsohler** [comment]
*Minetest Game* for the default game that comes with *Minetest Engine* … And the combination of those two things is simply *Minetest*.

**Comment by Rochambeau** [comment]
LibreMiner
LibreBlox
VanillaBlox

**Comment by ShadowNinja** [comment]
`Minetest Vanilla` or a perpetuation of that sounds good.  I wouldn't want to make a major change to the name.

**Comment by MT-Modder** [comment]
I agree with @ShadowNinja. The name shouldn't stray too far.

**Comment by rubenwardy** [comment]
I would like Minetest Game. Vanilla implies that it is unmodded, which is not necessarily true. See my comments in the forum thread.

**Comment by rubenwardy** [comment]
Actually I think the menu used to display "minetest_game" in subgame game select due to a bug that made it use the first subgame in the list's foldername rather than game.conf name.

**Comment by BlockMen** [comment]
@rubenwardy you mean this one? :P
https://forum.minetest.net/viewtopic.php?p=166442#p166442

I think Vanilla would be the best choise if we rename it to anything at all

**Comment by rubenwardy** [comment]
```
I agree with Minetest XYZ.

It's "subgame" anyway, and the world creater should reflect this. You could
see it as game modes. You play Minecraft for creative and survival. I don't
like Minetest vanilla as it implies that it is unmodded, which isn't
necessarily true. Minetest Game is satisfactory, but I think there should
be 3 or more bundled by default called Minetest XYZ, with the XYZ
explaining what the subgame aims to do easily, with none implying they're
the default game.

Like Minetest Builder, Minetest Survival, Minetest Engineer. You'd need
descriptions too.
Builder isn't creative, but won't have hardcore hunger and mobs like
survival would have.
```

https://forum.minetest.net/viewtopic.php?p=171365#p171365

**Comment by BlockMen** [comment]
@Novatux @sfan5 @PilzAdam @ShadowNinja :
I would like to get this topic done, so this should be decided within the next week.
My vote is "Minetest Vanilla".

**Comment by Heybye44** [comment]
How about <code>Minetest the Game</code> or <code>MeseMines</code> or <code>MineMese</code>
<br>
I like <code>Minetest Vanilla</code> from what other people have said.

**Comment by Wuzzy2** [comment]
I vote (if this is a vote now) for “Minetest Vanilla”.

**Comment by thatgraemeguy** [comment]
I vote for "Minetest Vanilla".

**Comment by PilzAdam** [comment]
@BlockMen I would prefer "minetest_game" or "Minetest Game", but I abstain from voting.

**Comment by MT-Modder** [comment]
I vote for either "Minetest Vanilla" or "Minetest Game". The latter seems best as it doesn't really change the name just the in-menu name.

**Comment by rubenwardy** [comment]
I vote for Minetest Game.

Vanilla means original and uncustomised. I think this is wrong for both of those - there shouldn't be an original game, and it's a base and isn't necessarily unmodded / uncustomised.

**Comment by tenplus1** [comment]
+1 for Minetest Game

**Comment by dsohler** [comment]
**[tl;dr]** If this is a vote, I vote for “Minetest Game”

_________

**Against any of the “very creative” names**: This game isn’t affiliated with Roblox nor is it’s main content wrapped around Mese. And it should be identifiable as “Minetest” so it should either contain the word “Minetest” or at least end with “…test”.

**Against anything with “vanilla”**: The term “Vanilla” isn’t known or used outside “the scene of IT aficionados” (games, coders, Linux users, fans, nerds, geeks … us). And it is technically wrong when it comes to the subgame being shipped with Minetest and being available under the name “minetest_game”.

**Against names containing “demo”**: Since it’s technically correct that you could call “minetest_game” a “demo” the term usually is associated with some kind of free and very very very limited software showing a little part of software you need to buy.

**Against “game” names**: “minetest_game” isn’t actually a game since there are no objectives or goals.

_________

**For any of the “creative names”**: New name, new chance? And it sound’s less like something that justs exists because of testing purposes

**For anything with “vanilla”**: for people who know the difference it will be pretty clear what to expect when they hear “vanilla”.

**For names containing “demo”**: Even if the term itself may be associated with crippled payware being free to try it is actually a pretty accurate term describing a reference implementation.

**For “game” names**: It’s simple and easy to distinguish from other Minetest components and thare are other gmaes in the wild that are not games when applying the definition “has objectives and/or goals”.

_________

***My opinion***: *I still prefer “Minetest Game” since it’s already called like that even if it might be an accident or just wasn’t considered showing a proper name when coding the client GUI.*

Another thing that will be possible very easy: We could name other Minetest components accordingly: “Minetest API”, “Minetest Engine”, “Minetest Mod(ification)s”, “Minetest X Mod(ification)” (where “X is the mod’s name”), “Minetest X” (where “X” is the subgame’s name).

**Comment by Novatux** [comment]
I would vote either for "Minetest game" or "Minetest vanilla"; with a preference for the latter because it implies the existence of mods :)

**Comment by C1ffisme** [comment]
:+1:  for Minetest Game.

@dsohler :+1:

**Comment by Jordach** [comment]
I think the best solution to this naming problem is "Minetest Base" or
"Minetest Basic"

Why these? It shows that the game itself can be modified and or improved
with mods and modpacks. This shows that the user can experiment with
modding without breaking the game.

**Comment by paramat** [comment]
What Jordach wrote, i was thinking 'basic game' or something that describes a basis or foundation for adding modules to, to make it clear to players that although it may seem lacking they should add modules.

**Comment by rubenwardy** [comment]
I'm sure Krock (@SmallJoker) would be willing to give up the "Minetest Base" name. If not, Minetest Foundation could be a synonym. But still, depends on what people vote.

**Comment by SmallJoker** [comment]
Alright, I did not expect a change of minetest_game's name.
To prevent from confused people, I would rename `base_game` to something else.

**Comment by Wuzzy2** [comment]
@BlockMen: Now that the “next week” is over, have we come to a decision yet? :P

**Comment by C1ffisme** [comment]
How about Minetest Baseplate?
Or just Minetest Simplicity.

It needs to be something that demonstrates that the game is simple, but can be modded.

BTW : If we have a Minetest Baseplate, we should make another game called Minetest Fun or Minetest Explore or something for people who don't snatch up mods everytime they need fun.

**Comment by Wayward1** [comment]
Personally, I'd go with "Default" or "Base", because both are short, descriptive, and self explanatory. However, of the two main choices, I like Minetest Game the best.

**Comment by BlockMen** [comment]
It stays Minetest Game, since we had kinda a standoff and sfan5 voted for "Minetest Game".

See also: http://irc.minetest.ru/minetest-dev/2015-03-29#i_4205087

**Comment by MT-Modder** [comment]
I still think game.conf should be changed to reflect this instead of just "Minetest".

**Comment by rubenwardy** [comment]
I voted for Minetest Game, not minetest_game.

**Comment by jogag** [comment]
I also vote for "Minetest Game".
"Minetest Vanilla" means "no mods", and the user can install mods!
"Minetest Basic" - yes, it's basic, but the user can install huge modpacks which add thousands of items!
"Mesetest", "Testmine" and similar are too focusing on mese. But minetest is not only mese!!!
Also the technical name is "minetest_game", so don't make big changes!

**Comment by FreeLikeGNU** [comment]
Minetest: The Motion Picture *in 3D!*
Seriously,  I think for a game the name "minetest" is somewhat unfortunate.  It can easily be perceived as a lack of confidence or invokes memories of test-taking.  What we really have here is more like Game Craft.  That is what makes this game so special, the ability to craft your own game.

**Comment by Heybye44** [comment]
@Francisco "Game Craft" sounds a bit too much like Minecraft.






—

**Comment by FreeLikeGNU** [comment]
@Heybye44 don't forget witchcraft, aircraft, arts'n'crafts, hovercraft oh and WorldCraft.  But I see where you are coming from.  Minetest and Minecraft evolved concurrently and are said to stem from the ideas in Infiniminer.
Minetest is free open source software and does not require java.  Minetest has proven that it is quite portable regardless, with pc, osx, android ports made well already. I can leave home after being on a minetest server from my laptop, sit at a bus stop and continue where I left off on that same server with my phone!  

 Lua is the modding script language that also sets it apart from MC and IM.  Mining and crafting are big parts of the game but there are many others.    I think because of its shared lineage and communities, it is not inappropriate to have a name that resembles its conterparts only because its easy to think "oh this is a game like minecraft (to the casual eye)".  Unfortunately there are those that think Minecraft is the only game with this concept and should remain unchallenged by competing projects and find the similarity disturbing.

**Comment by Heybye44** [comment]
More random suggestions:

TailorMake
TailorMade
Up2U
Make
MakeReal
TailorMadeVoxels
LuaCubes
Modiverse
Plus
InControl
YourWorld
