### ISSUE TITLE
Small improve of the Flowers minetest_game mod

### ISSUE THREAD

**Issue by Ombridride** [minetest/minetest_game#469]
Small improve of the Flowers minetest_game mod, the code is more smaller and do the same thing.

If you want it, take it (the most important changes are from Davedevils who makes a very well optimisation work) : 
https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/minetestforfun_game/mods/flowers/init.lua

**Comment by C1ffisme** [comment]
If you have code, then make a pull request. (Unless you have a specific reason for not making a pull request, which you should describe in the issue, rather than telling a commenter afterwards.)

**Comment by LeMagnesium** [comment]
@C1ffisme , @Ombridride didn't create a pull-request because he wanted to know if people where interested, but it's possible in a pull-request. I think he should have created a pull-request with the isolated changed code too. Maybe he had not time to apply his (@davedevils in fact) changes over the actual flowers mod.

**Comment by C1ffisme** [comment]
Ah, okay.

**Comment by Ombridride** [comment]
A minor bug with dye was fixed, this code in now ready for a Pull Request, i close this issue ticket
