### ISSUE TITLE
Exploitable grass drop chance of seed

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest_game#472]
I don't know if it was meant to be, anyway this looks like an exploit to me. Grass has a low chance to drop seed and an higher chance to drop itself, but this means that i can simply dig and replant the same grass until i get the seed, which will likely happen after some seconds, avoiding also a useless grass stack.
Let's be clear, this doesn't bother me, it's also useful if I want to get some cotton or wheat soon, but it looked strange so i ask myself if it's expected to happen.

**Comment by PilzAdam** [comment]
It is expected.

**Comment by thatgraemeguy** [comment]
It is normal the way its currently implemented. It should be possible to use metadata to differentiate naturally grown grass from grass that was dug and manually planted, so that only natural grass has a chance of dropping seed.

Then again, this is hardly a massive loophole in the bigger scheme of things.

**Comment by Echoes91** [comment]
It would be simpler to define two different decorations with the different drops, using the same texture and setting fill ratios instead of drop chances, anyway i got the answer and I'm happy for it :)
