### ISSUE TITLE
[Feature-request] Bucket filling based on node def

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#478]
Currently, you can fill the empty bucket if you point the water or lava nodes only.

The bucket could be filled in punching any node that have a param like `sourcing = 1`. That way it would work with other liquids or the Home Decor's water well for examples.

**Comment by sfan5** [comment]
It would make more sense to add(isn't there one?) a bucket API for this, buckets need to registered for the fluid too.

**Comment by LeMagnesium** [comment]
@sfan5 There is already a bucket API, which is used in some mods (I cant' recall them at the moment).  Furthermore, the empty bucket actually checks if the punched node is a source which was registered by looking in a table instead of looking for a group, and if it is, then it replaces the actual empty bucket with the bucket full of the removed source.
The bucket already fills depending on the node def, but you have to register the bucket.
However, there could be something like a loop on the node table with `minetest.after(0.1,function())` which would register a bucket for every node with the `sourcing` group. I don't know if it could work.
