### ISSUE TITLE
Apple drop

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#553]
Apples have a tendency to hang around in the air even after the tree has been chopped, if you add the following line to the node registry for default:apple then it'll drop:

```
drop = "default:apple",

**Comment by PilzAdam** [comment]
To make apples drop we added the `leafdecay_drop` a while ago, so this should already work. Are you sure that it is not working correctly (have you waited long enough)?

Also adding your line does not help, since leafdecay checks whether the drop name is different from the node name (for saplings), which is not the case for apples, even when adding this line.

**Comment by tenplus1** [comment]
Having simple leafdecay_drop does nothing but leave the fruit hanging in the air, for some reason it only works when drop = "default:apple" has been added to the node definition...

**Comment by PilzAdam** [comment]
@tenplus1 It has to be in the leafdecay and the leafdecay_drop group (like apples currently are).

**Comment by tenplus1** [comment]
Installed latest build and it works ok now with just those two flags...  Dunno what stopped it working before !?!?
