### ISSUE TITLE
Stairs and slabs texture problem

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#570]
Before (Nodebox):
![screenshot_20150715_162816](https://cloud.githubusercontent.com/assets/8843475/8693016/a0ece0ee-2b0e-11e5-823a-ed329926daeb.png)
After (Meshnode):
![screenshot_20150715_162827](https://cloud.githubusercontent.com/assets/8843475/8693017/a10ff9f8-2b0e-11e5-91ba-c65963bd6df1.png)

I can't use multiple texture.

Cause:#551(perhaps)

**Comment by paramat** [comment]
Probably due to the recent change to meshnode. kilbith, gravgun please can uv mapping be updated?

**Comment by kilbith** [comment]
@paramat Please highlight correctly my nick, I didn't noticed this issue yet... And no, there were no several fixes (only one for the shadow – the rest was purely optimization).

Otherwise yes it's deliberate : 
- There's only one blender material for this model meaning that the tile is applied on every face.
- I can split each face in their own material (it adds weight) but _that_ stairs model is meant for the elements not using multiple tiling (wood, stone, etc.) -> the most frequent case.

So if modders want multiple tiling, they should use a nodebox instead for achieve their specific goal.

**Comment by paramat** [comment]
Thanks and sorry for my slight frustration. Yes the basic stair must support multiple textures as before, if you can enable multiple textures that would be much appreciated. Would this cause any problems and make returning to the nodebox definition the better option?

**Comment by Rui914** [comment]
#571
If you use this, you can use the Nodebox.

For example,
```
stairs.register_stair_and_slab("test", "test:test",
		{cracky=3},
		{"default_stone.png","default_dirt.png"},
		"Test Stair",
		"Test Slab",
		default.node_sound_stone_defaults(),
		{
			drawtype = "nodebox",
			node_box = {
				type = "fixed",
				fixed = {
					{-0.5, -0.5, -0.5, 0.5, 0, 0.5},
					{-0.5, 0, 0, 0.5, 0.5, 0.5},
				},
			},
		}
)
```
How is this?

**Comment by kilbith** [comment]
The simplest solution is to add a function's param in the stairs API so that modders can choose between nodebox and mesh. The model could remains light and simple.

**Comment by Rui914** [comment]
What about if plurality of texture, then use of Nodebox?

**Comment by kilbith** [comment]
I will fix that for the mesh first.

**Comment by Rui914** [comment]
#571
I've updated the commit.
How about this?

**Comment by kilbith** [comment]
Yes, it's a different strategy.

Mesh model fixed : https://github.com/minetest/minetest_game/pull/576

**Comment by kilbith** [comment]
https://github.com/minetest/minetest_game/commit/26866e4c212a8e92789d03d143842c7d2859d6ee Can be closed.
