### ISSUE TITLE
Mushrooms are spawned underwater

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#589]
This [piece of code](https://github.com/minetest/minetest_game/blob/master/mods/flowers/mapgen.lua#L23-L33) has been a lazy way to spawn the mushrooms on the dirt patches inside caves. But this also spawns the mushrooms underwater. The fix is to use a Lua fonction to properly spawn them underground as @PilzAdam suggested.

![screenshot_20150724_165001](https://cloud.githubusercontent.com/assets/7883281/8877196/74530a14-3224-11e5-808c-a66a78d838ac.png)

Also on a side note : I don't notice a performance drop when using `spawn_by`. The mushrooms ought go to their appropriate places (next to the trees).

**Comment by PilzAdam** [comment]
Marked as high priority so we don't get releases with different mapgen.

Also a custom regrowing system would be nice (since the flowers mod always needs light currently).

**Comment by paramat** [comment]
Will fix very soon.

**Comment by paramat** [comment]
For mushroom regrowing, i would prefer a spore system so they can be intentionally farmed. I do not like the current flower spreading system as it is slow and uncontrolled: with enough time all flowers will be everywhere and at uniform density. I suggested a seed system instead for flowers but this was not popular with other devs.

**Comment by paramat** [comment]
kilbith the mapgen performance drop by using 'spawnby' would have to be huge to be easily noticeable in-game, it's not huge it's small but significant. I was just saying it should be used cautiously.
My main point was that mushrooms only in a 1 node radius of trees will not be good.

Lua is very slow and best avoided, i'm still thinking on how to spawn mushrooms underground if there is enough dev support for this (i'm fairly neutral so won't vote either way) until then my previous code was a way to occasionally spawn mushrooms underground 'efficiently, simply and fast', you can call that 'lazy' if you want =).

The underwater mushroom you found must have been a rare one near an overgenerated underwater cave, decorations will not replace water so that air pocket must have been there before. You can see in your screenshot some other air pockets around and a possibly a nearby cave.

**Comment by paramat** [comment]
I checked the code and decorations do not replace water, what is happening is that mgv6 is creating air pockets on the seabed dirt, normally these would quickly fill with water but decoration code is seeing the air pocket and is placing a mushroom.
This makes placing mushrooms on cave dirt very difficult as there is seemingly no way to distinguish between dirt on a cave floor and seabed dirt under a temporary air pocket.

I like the idea of making mushrooms farmable, as this would create an easy to grow food source underground, as they don't require light. In a while i will go ahead and implement this using the seed (spores) method.

**Comment by tenplus1** [comment]
if the spawn_by function allowed for multiple entries e.g.

spawn by = {"default:tree", "default:stone"},

then maybe mushrooms could spawn above ground next to tree's and in caves beside stone...

**Comment by C1ffisme** [comment]
Or re-register it so that when it spawns below water level, it must spawn by air.
