### ISSUE TITLE
Acacia tree/wood : wrong naming convention

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#603]
Currently :
```
default:acacia_tree
default:acacia_wood
```
Should be :
```
default:acaciatree
default:acaciawood
```

Like the other trees/woods.

**Comment by paramat** [comment]
default:jungletree
default:junglewood
default:jungleleaves
default:junglesapling

default:pinetree
default:pinewood
default:pine_needles
default:pine_sapling

default:acacia_tree
default:acacia_wood
default:acacia_leaves
default:acacia_sapling

Hmm i made a mess of pine names, mixing split and unsplit words, too late to change that now.
A while back Shadowninja insisted that these words are better split, and i agree, although both forms are used in language the split form is visually clearer and more in line with Minetest naming convention of not combining words. So i decided to go with the correct form instead of being consistent with c55's old node names.
Input from other devs?

**Comment by kilbith** [comment]
Not too late, there are aliases and those nodes are not released yet.

**Comment by paramat** [comment]
Ah yes, maybe then we could split 'pinetree' and 'pinewood'.

**Comment by paramat** [comment]
See #616

**Comment by paramat** [comment]
I now think it's best to just correct pinetree and pinewood, new PR coming.
