### ISSUE TITLE
Simplification of fire drawtype

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#655]
![screenshot_20150826_232131](https://cloud.githubusercontent.com/assets/3686677/9565541/96f1d54a-4ecc-11e5-88a3-7cccd39baaad.png)

Working on the fire mod i noticed a huge drop in FPS when viewing a forest fire, by far the largest FPS drop i have ever seen in MInetest. The fire drawtype has up to 10 textures displayed, most of the time 6 are displayed: 4 edges and the 2 in a central X shape. Perhaps it is the number of textures used combined with them being animated which is causing the FPS drop?

FIre is usually viewed more from the side than from the top, with 6 textures the effect is extremely dense, i feel the central 2 are not really needed.

There are 4 textures placed against the base of a node, seems overkill for the purpose, perhaps these could be simplified to just 1 that is level and placed a small distance under the node? This texture could be a different texture designed for the purpose, having flames spreading outwards from the centre.

**Comment by est31** [comment]
Perhaps we should have opaque fire, just like opaque leaves.

**Comment by est31** [comment]
This is an engine bug.

**Comment by paramat** [comment]
Hm perhaps a 'simple fire' setting in conf that selects plantlike.

**Comment by paramat** [comment]
Testing again i don't get such a large drop in FPS as i did before, however i do find the firelike drawtype too dense and overkill, so might open an engine PR to simplify it by removing the 2 central textures.

**Comment by Amaz1** [comment]
>Testing again i don't get such a large drop in FPS as i did before, however i do find the firelike drawtype too dense and overkill, so might open an engine PR to simplify it by removing the 2 central textures.

If you do this, would you be able to make it a setting please? I like firelike as it is now...

**Comment by est31** [comment]
Might be a good idea, I would change it in my local installation as well.

**Comment by paramat** [comment]
There's not much difference when removing the central 2, it still has a reasonable density especially when viewed from the side. Currently it's so dense it looks like a random mess and therefore out of character, Minetest's visual style is simple geometric structures.

Working on it last night i realised it has a problem, there are 10 drawtype textures within a limit of 6. The lower 6 flames have priority so some of the top 4 flames are often missing depending on which of the 4 lower side flames are used. Removing the central lower 2 allows up to 2 independant textures for use as top flame textures, these will always appear as the burning underside of the node above.

So it was over-engineered and buggy, i managed to reduce textures from 10 to 5, and further simplified the code, now the code is more than twice as lightweight while also being more effective at doing what firelike was meant to do.

**Comment by est31** [comment]
What load did you precisely remove? Note that with your changes to fire, there aren't any forest fires anymore, because fire just almost doesn't spread anymore, so no low FPS to be worried about. Also, this is an engine discussion, can you open an engine issue, so that we can discuss this there instead?

Fire is dense, and it is a random mess. That's what fire is, period. If you view fire from angles like 45°, you do notice the missing faces. actually the best idea would be to have a particle spawner here, which spawns "fire" particles. Then, if it still looks acceptable, we can remove those two textures.

**Comment by est31** [comment]
Minetest *is* messy, e.g. in the mapgen. Here we neither have "simple" shapes, but rather have an elaborate landscape, with lots of features.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/pull/3171

**Comment by est31** [comment]
Honestly I can't notice an FPS drop caused by fire:
![screenshot_20150912_050150](https://cloud.githubusercontent.com/assets/8872119/9829610/8aae4dce-590b-11e5-81ff-6742d48eca2a.png)
![screenshot_20150912_050202](https://cloud.githubusercontent.com/assets/8872119/9829611/8cbf57c0-590b-11e5-8375-0c83e70c146c.png)

**Comment by paramat** [comment]
With a large forest fire, much larger than above, i noticed a 10 FPS drop.

**Comment by paramat** [comment]
Closing for reasons given in the PR https://github.com/minetest/minetest/pull/3171
