### ISSUE TITLE
Waterlilies are inappropriately walkable

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#677]
For some odd reason, `walkable = false` has been silently removed by @paramat to the original PR.

We are not supposed to walk over the waterlilies, these are thin vegetal pads and unless if you willfully defy the laws of physics, you normally sink into water by trying to move over them.

Also, it complicates swimming and access to the land coasts.

**Comment by paramat** [comment]
I changed a few things. For walkability i wasn't sure so i chose what was more fun instead of strict realism, also i was thinking of Minecraft and how much fun it seemed to jump on the pads. It seemed weird being able to pass right through a pad. If the pads are very dense we can jump over them instead of swimming or using a boat, but they're rarely that dense.
Devs your opinions?

**Comment by paramat** [comment]
Ok will change this.

**Comment by paramat** [comment]
Fixed and added a missing group too.

**Comment by kilbith** [comment]
Thanks you.
