### ISSUE TITLE
The organic cycle of Cobblestone

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#699]
An ABM should turn (tardily) the cobble to mossy cobble for a life-like transformation.

As for the fusspots who are instinctively worried by the name "ABM", it's nothing worse than e.g. the dirt to dirt_with_grass, or the saplings to trees ones.

**Comment by tenplus1** [comment]
I like the idea of turning cobble into mossycobble when near water (I use this in Ethereal already), although changing cobble in players' builds without the water would annoy more than impress.

**Comment by PilzAdam** [comment]
Yes, cobble  near water should turn into mossy cobble. For simplicity (and performance) the water should be a direct neighbor.

**Comment by paramat** [comment]
Seems good (on direct neighbours only, scanning for "group:water"), as long as the ABM has a very high chance value (very low chance), assume a huge cobble structure, every node will be scanning it's neighbours.

**Comment by kilbith** [comment]
I'd prefer something like that (it's just matter of humidity after all) : 

``` Lua
minetest.register_abm({
    nodenames = {"default:cobble"},
    neighbors ={"group:water"],
    interval = 100, chance = 20,
    action = function(pos, _, _, _)
        minetest.set_node(pos, {name="default:mossycobble"})
    end
})
```

And don't tell me that's too heavy... (it's wrong).

**Comment by PilzAdam** [comment]
Someone should benchmark if @kilbith really isn't too heavy.

**Comment by paramat** [comment]
Sorry but it is way too heavy, it's a scan of 1330 nodes instead of 26.
The chance value is way too low and the interval too long, within the active block range of a player, 32 nodes, there may be a cobble construction with 100s to 1000s of cobble nodes, each scanning 1330 nodes.
Moss growth should be very slow and gradual so we can use a much higher chance value, it's also best to use a lower interval because many small lua lags are better than fewer large ones.
Keeping moss close to water, within 1-2 nodes is visually more effective than a spread that might cover an entire wall.

**Comment by kilbith** [comment]
@paramat ~~It's a scan of 125 nodes (5^3 = 125) per cobble~~. Some cheap servers extensively use [one of my ABM](https://github.com/kilbith/xdecor/blob/master/hive.lua#L46-L62) that scans with a radius of 8 (= 4913 nodes), without impact on lag. Have you ran any benchmark for underpin your apriorism ? Perhaps 2 of radius is a good compromise.

EDIT: my bad, I miscalculated : it scans 5 nodes of radius in all 6 dirs. 11^3 = 1331 nodes.

**Comment by paramat** [comment]
Ah so you were actually suggesting a radius of 2, that's reasonable i'm fine with that.
Apparently ABMs are more complex than they need be, and moss is low priority and should be slow spreading, so i feel we can keep the ABM lightweight.
A small dungeon room and a dungeon corridor each have roughly 100+ nodes, there are on average 10 of each in a dungeon, so 2000+ nodes within 32 nodes of a player. So i was thinking a chance of roughly 200 so that each interval there are 10 nodes checked? Using an interval of 29s, prime numbers are best to keep ABMs out of phase as much as possible.

**Comment by paramat** [comment]
Just saw the dirt to grass ABM has a chance of 200 so this seems a reasonable value.

**Comment by PilzAdam** [comment]
The problem with doing any kind of scan is that you have a lot of core -> Lua switches.

I'd suggest to use 2 ABMs that both run on cobble: one that has `neighbor="group:water"` and turns cobble into mossy cobble, and one that has `neighbor="mossy_cobble"` and scans for water nearby, before turning the cobble into mossy cobble. This would reduce the the number of nodes that the ABM runs on which needs to do checks in Lua. Thus this reduces the number of core -> Lua switches drastically.

**Comment by kilbith** [comment]
Sorry but I don't see the point of water neighborhood as necessary condition. The moss just needs some humidity (e.g. inside of dirt), not a soaking of water to grow. I suggest to have the same tardy ABM than the [dirt](https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L312-L330) and let the cobble naturally getting older and turn mossy everywhere (at least in dark areas).

**Comment by PilzAdam** [comment]
@kilbith there needs to be a way for players to protect their cobble buildings from turning into mossy cobble. Not placing water near it makes (enough) sense and is easily understandable by players.

**Comment by tenplus1** [comment]
Agreed, mossy cobble annoys players after making a creation, so only changing cobble beside water would be a better idea:

```
minetest.register_abm({
	nodenames = {"default:cobble"},
	neighbors={"group:water"},
	interval = 30,
	chance = 10,
	action = function(pos, node)
		minetest.set_node(pos, {name = "default:mossycobble"})
	end
})

**Comment by C1ffisme** [comment]
This sounds like an OK idea.

But one of the things about making mossy cobblestone walls is to use noise, not make an entire wall of mossy cobble (which looks ugly). There are some servers that have mossy stone, and underwater cliffs look completely green.

I think the moss spread should have a limit, like only moss-ifying if there aren't say, 3 or 4 nodes (These are just arbitrary numbers. Don't actually use them.) of mossy cobble around.

Considering the mossy cobblestone node just looks like cobble with green cracks, this might make it look at least slightly better.

**Comment by C1ffisme** [comment]
![screenshot_20151017_173323](https://cloud.githubusercontent.com/assets/9893266/10561584/31f65b3a-74f5-11e5-9889-78a31cb11041.png)
Compare these two walls.

**Comment by paramat** [comment]
C1ffisme your suggestions are too complex, this needs to be lightweight. I think a solid expanse of moss looks okay. As moss would apppear very slowly it would be noisy for a very long time anyway.

**Comment by C1ffisme** [comment]
Actually, all you would need to do is have an ```if``` with a ```minetest.find_nodes_in_area(pos1,pos2,"default:mossycobble")``` and then if (Insert Tested for good results number here) nodes are in that area, then don't convert the cobble.

**Comment by paramat** [comment]
That's another scan which means double the processing. Moss in dungeons is fairly continuous, varying on a scale of 5 nodes.

**Comment by kilbith** [comment]
Yes, 2 is a good compromise.

**Comment by paramat** [comment]
See #713

**Comment by kilbith** [comment]
https://github.com/minetest/minetest_game/commit/2729777b943413323550d7891ea6df8861376598 (not fully satisfied though)

**Comment by sorcerykid** [comment]
> @kilbith there needs to be a way for players to protect their cobble buildings from turning into mossy cobble. Not placing water near it makes (enough) sense and is easily understandable by players.

What about maps created prior to this "feature", in which such cobble structures have already been completed? To whimsically change the default behavior of cobble (one of the most commonly used building materials in Minetest) is in my view very poor judgment.

Proof in concept is the JT2 server, which required nearly two days of work repairing parks, roadways and buildings that were griefed by this ABM. Tens of thousands of nodes had to be replaced since a significant portion of the city is constructed on a giant lake.

It's quite concerning, honestly, that this feature was implemented solely because it seemed like would be a really cool idea without considering its impact on existing builds.
