### ISSUE TITLE
Should snowblock be a falling node?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#702]
I think yes, any reasons why not?

**Comment by nerzhul** [comment]
:+1:

**Comment by PilzAdam** [comment]
Then add snow brick so we can build snow castles.

**Comment by LazyJ** [comment]
Falling snowblocks would be a problem for dome-shaped igloos, snowmen constructed of spheres made of snowblocks, snowy overhangs of roofs, structures made from snowblocks instead of white wool or where ever a non-fabric looking, default white block may be used to build or sculpt with. With the large snow biomes in the default game, wintry builds are more possible than they were before.

**Comment by rubenwardy** [comment]
Compressed snow block, maybe.

**Comment by kilbith** [comment]
:-1: You will melt lot of snow buildings as LazyJ pointed out.

**Comment by paramat** [comment]
Good points, snowblock can be considered fairly compacted and stable then, players will want to use it for snowmen and igloos etc.
