### ISSUE TITLE
Saplings no longer grow in caves and underground structures.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest_game#724]
Hi, recently the behavior of growing trees has changed. Now they need a torch or something to be placed beside them so they can grow.

This completely breaks gameplay on my server and others as this breaks several machines people make.

Please change the behavior back to what it was, when saplings would grow into trees without strong light, as in caves and underground buildings and structures.

**Comment by Megaf** [comment]
And also, the game is not about realism! It's all bout freedom, isn't it?

**Comment by kilbith** [comment]
You must realize that this change has been widely accepted, so you'll likely revert that on your own only.

**Comment by Megaf** [comment]
four people accented that. On my server alone there's more people that don't accept that.

**Comment by kilbith** [comment]
> On my server alone there's more people that don't accept that.

... who cares ?

**Comment by Megaf** [comment]
Here are some examples where we need saplings to grow underground.

![screenshot_20151111_115202](https://cloud.githubusercontent.com/assets/6201512/11090524/788c18ea-886a-11e5-9649-378ea08a8980.png)
![screenshot_20151111_115223](https://cloud.githubusercontent.com/assets/6201512/11090527/78989ba6-886a-11e5-96b9-8a133875082b.png)
![screenshot_20151111_115243](https://cloud.githubusercontent.com/assets/6201512/11090526/789877e8-886a-11e5-8ef7-9e7e9d7c6f64.png)
![screenshot_20151111_115305](https://cloud.githubusercontent.com/assets/6201512/11090528/78b34280-886a-11e5-9b8b-889af411000f.png)
![screenshot_20151111_115317](https://cloud.githubusercontent.com/assets/6201512/11090529/78b711da-886a-11e5-9e9a-70fe637c20bb.png)

**Comment by PilzAdam** [comment]
AFAIK mese lamps spend enough light to grow trees.

**Comment by falsechicken** [comment]
That freedom part you mentioned means you can just change it yourself @Megaf ...

**Comment by crazyR14** [comment]
#725  i do believe forking just for the sake of 1 line change is ridiculous thing todo. Ive created a pull request for a solution that i thought would make both sides of this situation happy. but looks like i was wrong. it unlikely to get merged. but @Megaf if you want to pursue it feel free you have my full support.

**Comment by rubenwardy** [comment]
It's not really forking, just a user modification.

**Comment by crazyR14** [comment]
i was responding to @falsechicken lol.

**Comment by rubenwardy** [comment]
I know.

**Comment by falsechicken** [comment]
But wouldn’t this user modification require maintaining? Aka merging upstream changes with your modification every time the base is updated? I would figure "forking" (In the sense that you want anything different) would be the easiest way to do this. Unless there is some "user modification" system I am missing xD. 

Unless you want to modify that one line manually every time you update. Which can work fine. But being used to Git I would rather use it. Not to mention any future changes your server's community doesn’t agree with.

**Comment by paramat** [comment]
Everything else in Minetest needs light 13 to grow, so this is a long-overdue change for consistency and obviously makes a lot of sense. It adds more challenge to growing trees underground and creates more use for mese. It's annoying i know but players have had it far too easy with growing underground trees.
Meselamps are a part of Minetest Came now, only a meselamp placed beside the sapling has enough light (diagonally beside won't work though).

Sorry for the inconvenience but in most situations it can be easily fixed by placing a meselamp. In a non-creative world i suggest making the required number of meselamps freely available to players to make the transition easier.
Your machines look like there is nowhere to place the meselamp close enough. I know it would be annoying but you could rebuild the machines to be spaced further apart, making room for the growlamp.

You could add your own growlamp node to the server which is easier to craft than a meselamp.

Alternatively you could just edit the value on the server MTGame or write a mod that over-rides or defines it's own ABM.

**Comment by paramat** [comment]
:-1: for reverting, but see my comments in the PR.

**Comment by paramat** [comment]
See #729

**Comment by paramat** [comment]
729 now merged.

**Comment by Megaf** [comment]
Thanks @paramat @Ryan-Nolan ! :+1:
