### ISSUE TITLE
ALL recipes for colored wools are with magenta wool image

### ISSUE THREAD

**Issue by amadin** [minetest/minetest_game#750]
In craft guide recipes for colored wools are with magenta wool image, but it must be with white wool image. I fixed it by changing 
recipe = {'group:dye,'..craft_color_group, 'group:wool'}, 
to 
recipe = {'group:dye,'..craft_color_group, 'wool:white'},

0.4.13

**Comment by sofar** [comment]
This would change the recipe so that wool can not be re-dyed. Is that intentional?

I'm suspicious of this being a bug in whatever displays the crafting recipe to you - it should not replace "group:wool" with a magenta block, but display a while wool block. I realize that there's no way currently to unmap "group:wool" programmatically to "wool:white" and so the most likely solution would be for unified_inventory (which I assume you're using) to hardcode group translation into defaults.

**Comment by amadin** [comment]
I can't turn of craft guide in unified inventory, i use separate craft guide mod.

**Comment by sofar** [comment]
That's indeed what I am suggesting. It may help if you tell us which crafting recipe tool you are using, and possibly post a screenshot. Is it unified_inventory? Or something else?

**Comment by kilbith** [comment]
The mod you use is bad.

A maintainer for closing this, please.
