### ISSUE TITLE
Mushroom spread may need tuning

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#754]
SInce the new code picks a random nearby node for mushroom spread:

```
interval = 11,
	chance = 50,
	action = function(pos, node)
		if minetest.get_node_light(pos, nil) == 15 then
			minetest.remove_node(pos)
		end
		local random = {
			x = pos.x + math.random(-2,2),
			y = pos.y + math.random(-1,1),
			z = pos.z + math.random(-2,2)
		}
```

.. that node will often be unsuitable being either above or below ground, this lowers the speed of mushroom spread, so 'chance' may need tuning. 'interval' should remain below 16 as that ensures that no mushroom is missed by the ABM when a player walks past, a prime number 'interval' helps to spread the load of ABMs by keeping them out-of-sync as much as possible, either 11 or 13 is fine.

**Comment by kilbith** [comment]
Unrelated : can you please surround your code between ``` (atop and below) for readability ?

**Comment by paramat** [comment]
Thanks i was wondering how to do that.

**Comment by sofar** [comment]
Agreed. Glad to see someone else is appreciative of prime numbers in ABMs.

Since this code was somewhat drastically changed, I had built a small mushroom farm to look at the growth rate, and it didn't look exorbitant or too sparse to me either, but I haven't done any numerical comparison or looked at actual gameplay.

I think getting some numbers would be the way to determine the outcome of this bug, and it should include a description of the expectation when a player is sitting idle next to a mushroom farm - how fast do we want mushrooms to "fill out" a section of a certain size?

**Comment by paramat** [comment]
If you've checked growth rate that's fine i can close this. We can always tune it later if needed.
