### ISSUE TITLE
Remove normalmap textures

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#764]
Currently in order to update a normalmap for a new texture, a particular program must be compiled and a complex method followed to get a good result, Gimp isn't capable. This is too much to ask, the huge normalmaps also make an irritating mess in the texture pack.
The feature is there for modders to use, but i feel MTGame should not bother with it, because it has changed textures from something simple into something complex and time consuming, this goes against the Minetest philosophy of textures as simple pixel art.
A texture pack of default textures plus normalmaps can be maintained by RBA or whoever for those who want to use them, by default MTGame will use the fallback of auto-generated normalmaps.
I will submit a PR.

**Comment by Calinou** [comment]
:+1:

They are barely useful, since the game doesn't enable normal maps by default.

**Comment by RealBadAngel** [comment]
Just because you dont have any knowledge on how to create useful normalmap by yourself you want the work to be removed? It indicates just you are not capable of making decisions regarding GFX, you lack skills, knowledge and taste (well, we can have different ones, as players can). You should stick to mapgen stuff where you are good at. Otherwise you're making yourself looking as fanatic amateur.

**Comment by paramat** [comment]
The issue is that the creation of normalmaps is well beyond most modder's abilities. The intention of Minetest is that most things are easy to create as either pixel art or nodeboxes. Your instructions to sofar in IRC show it's a complex process, although i am probably capable of doing it it's just too much to bother with every time we update a texture. If Gimp was capable of good results the situation would be a little different.

**Comment by RealBadAngel** [comment]
Gimp is not a proffesional tool to create such files. You would like to get artisitc effect without any effort and skills? Sorry man, you are totally wrong. First you have to know what you are doing, then you need skills for that, and most important you need correct tools.

**Comment by LazyJ** [comment]
What about changing Minetest's code *(engine or game, whichever points to where the "textures" directory is)* so that normalmaps could be separated out into their own sub-directory?

For texture packs, the normalmap files would be in "path/minetest/textures/textuepack_name/normalmaps".

For mods, the normalmap files would have to be moved from the mod's included "normalmaps" directory into the "path/minetest/textures/mod_name/normalmaps". With this idea, normalmaps would be separated into a directory that players can delete if they don't want to use normalmaps while players who do want to use normalmaps can have them. This would also mean that the normalmaps for minetest_game mods would have to be downloaded and installed separately just like adding another texture pack. If players are savvy enough to download and install multiple texture packs, then adding normalmap texture packs shouldn't be any more difficult for them.

I believe texture packs are the way the graphic artists in the Minetest community can contribute. Those gifted with coding skills *(modders)* create the toys, while those with graphic art skills make the toys look good. Just as modders are more adept with programs like Vim, Geany, Eclipse, and Code::Blocks, graphic artists are more adept with programs like Inkscape, GIMP, Blender, and AwesomeBump. *(AwesomeBump has [pre-compiled](https://github.com/kmkolasinski/AwesomeBump/releases) packages for both Linux and Windows.)*

Both mod code and graphics are sorely lacking good "how-tos" in Minetest. I know rubenwardy has been working on a project, ["Minetest Modding Book"](http://rubenwardy.com/minetest_modding_book/index.html) to cover the "how-to" part of mod codding basics; perhaps RealBadAngel could help the textures section with some normalmap basics?

**Comment by tenplus1** [comment]
+1

**Comment by paramat** [comment]
The feature is there for modders to use, but i feel MTGame should not bother with it, because it has changed textures from something simple into something complex and time consuming, this goes against the Minetest philosophy of textures as pixel art.
A texture pack of default textures plus normalmaps can be maintained by RBA or whoever for those who want to use them, by default MTGame will use the fallback of auto-generated normalmaps.

**Comment by PilzAdam** [comment]
I agree that normalmaps should be removed from this repo, and offered as an external texture pack.

**Comment by HybridDog** [comment]
>it has changed textures from something simple into something complex and time consuming

You could use 16x16 normalmaps, in my opinion they look good, especially the moreblocks stone tile.
https://github.com/HybridDog/HybridTP

**Comment by paramat** [comment]
Okay will merge soon.
