### ISSUE TITLE
Introducing 2 new nodes used in decorations

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#795]
Cc: @paramat 
Cci: @sofar

What I would like to see as decorations for completing some areas...
- Cobwebs in the top-corners of dungeons. The player could be "stuck" by crossing it as in liquids.
  - Appropriate [nodedef](https://github.com/kilbith/xdecor/blob/master/nodes.lua#L111-L126).
  - Texture (by Gambit) : ![xdecor_cobweb](https://cloud.githubusercontent.com/assets/7883281/12466022/a17570d2-bfd1-11e5-9224-8822725e6103.png)

![screenshot_20160120_234656](https://cloud.githubusercontent.com/assets/7883281/12465962/43e93e3a-bfd1-11e5-9f2e-b32663c35a55.png)
- Vines falling from jungle leaves.
  - Texture (by Gambit) : ![xdecor_ivy](https://cloud.githubusercontent.com/assets/7883281/12466078/20478b3e-bfd2-11e5-896a-ff11476524f3.png)

![17934408-6161-11e5-8d82-ba66c6f272d3](https://cloud.githubusercontent.com/assets/7883281/12466050/e06b2e76-bfd1-11e5-9079-1f6fb06897ae.png)

**Comment by MoNTE48** [comment]
Vines falling use bad texture. Not for jungle tree. Big contrast. But, +0.5

Cobwebs in the top-corners of dungeons, yes, good idea! +100500 :)

**Comment by sofar** [comment]
Both the Vine and Cobweb textures are decent, I think they'd fit well in the current texture pack.

I like the alternative physics component to both these nodes. They can replace or serve as alternate ladders, or traps.

**Comment by sofar** [comment]
@kilbith I would start with adding the nodes and textures as a separate PR. I have some concerns about mapgen for vines, as I think it's not something that can be nicely done in the schematic without looking artificial. Perhaps we need to randomly place some vines on all jungle tree sides that are exposed in a registered_on_generated() method, but I'm pretty sure that that isn't preferable.

The dungeons are generated by C++ afaic, so I'll leave it to @paramat to consider how to decorate caves. I'm unsure whether decorations run after dungeon generation. If that's the case, it may be relatively easy (e.g. place "air, air, air, cobweb" on a "default:mossycobblestone" when Y < 0 through the decoration system)

If we'd modify the schematics to hang these, they can't be random, and it would make the jungle tree schematic larger (from 5x5xH to 7x7xH, doubling the size), as vines would logically be on the outer side of the jungle tree. Unless we want to put it on the trunk instead (only).

Also of concern is the current license. You'll need to relicense the nodedefs explicitly. WTFPL for the textures is OK, though, perhaps just relicense those to CC-BY-SA (that's reasonable and not in conflict). Since I suspect you wrote the nodedefs yourself, it's probably trivial.

**Comment by kilbith** [comment]
@sofar Thanks for your answer. The nodedef is pretty trivial, don't bother me with a relicensing and do whatever with this. Also note that a copyright owner can share everything whatever the license is.

**Comment by tenplus1** [comment]
+1 for both, will remove from Ethereal mod when added to game.

**Comment by sofar** [comment]
@kilbith the copyright holder you can relicense, but all you have to do is write a line in a PR that gives us the new license you are sharing it with minetest_game under.

If I look at nodes.lua in xdecor, the lines with the cobweb nodedef were contributed by ```jp```, so if I take them myself, or if you don't ask ```jp``` if he is OK with relicensing, we've committed a copyright violation, even if it is ridiculously trivial code.

I still can't just "take" the code.

**Comment by kilbith** [comment]
"jp" is me. And no I won't bother relicensing a dumb nodedef, this is ridiculous. There's no violation if you have an explicit authorization from the author, this is why we can backport some GPL stuff in the engine proposed by the forkers themselves.

**Comment by sofar** [comment]
@kilbith it doesn't matter how you feel about it, but it matters a ton for minetest_game that merging is done without copyright violation. If you do not feel like submitting this as a PR yourself with proper relicensing grant, you're effectively making it harder for us to merge it, not easier.

Maybe in some point of time in the future you regret your contributions and then you'd have a perfectly legal argument to go after the minetest community for violating your copyright. And a lawsuit is never ridiculous. It can however be extremely costly.

So please, let's not make a big stink about something that's easy to do for you, but hard for everyone else.

**Comment by tenplus1** [comment]
...and this is what stops development of new features. (loves his WTFPL license)

**Comment by paramat** [comment]
I'm fine with both being in Game for use, but not added to jungletree schematics because they double the volume of the schematics, beng 7x7 instead of 5x5. Also, the trunks already have vines wrapped around them.
Maybe later we might find a way to add the cobwebs to default mapgen, not sure where, the decoration code won't work in dungeons though.

**Comment by kilbith** [comment]
OK, you won, license [changed](https://github.com/kilbith/xdecor/commit/da0fb30b4133259ccbc4743bcfb9d7afd5d1190e) to be friend with MTG.

**Comment by C1ffisme** [comment]
:+1: 

This could be a good way to get string early in-game, if you needed it.
And the vines could be pretty useful for decor/parkour.

**Comment by Dragonop** [comment]
@paramat Can't you just make vines and cobwebs a decoration (like flowers) and make them spawn in cobble and in jungle leaves?

**Comment by paramat** [comment]
No the decoration code only works at ground level, not in trees or in dungeons.

**Comment by sofar** [comment]
@paramat that's unfortunate, and I think a severe limitation that should be addressed - Having cave decorations, dungeon decorations seems like an entirely reasonable thing to do.

1st pass - terrain and base material, ores
2nd pass - dungeons
3nd pass - caves
4th pass - decorator?

**Comment by Dragonop** [comment]
@paramat Then I guess this is a good chance to work on decorations for caves, dungeons, trees and air.

**Comment by paramat** [comment]
It's this way because it's meant to be simple and fast and was only designed for ground-level flora etc.

**Comment by paramat** [comment]
Not sure about either of these. Vines have no way of being placed in the world, due to the per-node randomness of jungletree schematics they can't hang from the leaves (and i oppose that anyway).
Cobwebs, we have no spiders.
I think these can be left to a 'morenodes' type mod.
:-1:

**Comment by Fixer-007** [comment]
I like vines, they add nice feel to jungles and in decor, can be added via abm to appear and grow on jungletrees :}

**Comment by C1ffisme** [comment]
@paramat Maybe they were spider webs from long ago, when the Minetest world had some kind of life? I dunno. It adds a bit of depth and backstory to the game, though.

I would imagine vine placement would work similarly to ladders, but rotate themselves automatically if they are placed so that they are facing upwards or downwards, rather than sideways.

Also, I think the mod you are thinking of is `moreblocks`.

**Comment by HybridDog** [comment]
Cobwebs should not appear in dungeons which aren't connected to the upper world because spiders make them to catch flies. Moss growing in dungeons makes more sense because it gets light from the glowing mese, doesn't it?

**Comment by paramat** [comment]
Dev opinions? I disagree with both and feel they are best in mods.
Cobwebs would be weird 1000's of nodes underground and i feel the y make dungeons look worse.
I don't agree with adding vines to trees, there are problems with doing this due to leaf and branch randomisation. Again i don't feel it looks better, possibly worse.
:-1:

**Comment by sfan5** [comment]
I'd like both vines & cobwebs :+1:

**Comment by Fixer-007** [comment]
Me too, both are very cool for decor, especially on buildings (as addition to mossy cobblestone).

**Comment by paramat** [comment]
Well they could be added and not used in mapgen (for now).

**Comment by sofar** [comment]
I'm perfectly fine with adding both these nodes, but adding them without mapgen placement or some form of generation in-game makes no sense to me.

We don't need to place cobwebs 1000 nodes deep underground. We can do a very rarely running ABM that places them on or under stone nodes that are above -10 (or so), that are in full darkness at mid day (using the light bank data), and have something to entice players into dark caves.

The same with vines. There are a few spots in the jungle tree `mts` where we could insert a vine `master` and we could have some code trigger downward generation of more vine nodes, or just place air, once the block has been generated (again an ABM would do fine).

In any case, the only way to explore the options is if people make a nice PR that accomplishes both (1) a good nodedef and supporting code, and (2) provide a reasonable in-game way of obtaining.

**Comment by Ferk** [comment]
Cobwebs might be hard to place in appropriate locations with an ABM.

what about adding a very simple form of mob? something like a very tiny spider entity that might very rarely pop up from stone and crawl in the ground to collide with a wall and then if there's a not too high ceiling, fly up to place a cobweb before disappearing.

Seeing small animals like this would also add some ambient to the game and looks like an organic way to place cobwebs. But dunno if it would be too much for MTG.

**Comment by sofar** [comment]
@ferk yeah, that's a really easy solution, let's just add mobs to solve this problem.

> But dunno if it would be too much for MTG.

Take a guess...

**Comment by Ferk** [comment]
Lol, I didn't mean it as an easier solution. Just as a more worthwhile one, imho.
I would be personally more motivated writing something like that than an overcomplex ABM. And adding lightweight fauna is in the goals anyway.
But yeah, just brainstorming.

**Comment by Fixer-007** [comment]
* cobwebs spawn in dungeons at mapgen time
* vines spawn in trees at mapgen time and spread down via abm

problem?

**Comment by paramat** [comment]
Ther could perhaps be a few cobwebs added under certain nodes (stone, cobbel, branches) near surface level by ABM.
I really don't want vines on every tree and added to the schematic, a few master nodes could be added by ABM and later extend down by ABM, Jungletrees are already very densely packed and overlapping so there's not much need or space for vines. I feel people are thinking too much about MC, vines are not an urgent necessity.

**Comment by paramat** [comment]
Once i add underground decorations then a few cobwebs could possibly be added under certain nodes near surface level. I see these as very low priority though, there are many other types of decoration that should be worked on first.
I'd rather not add vines to jungletrees, the trees are already so closely packed there isn't much room for them and it wouldn't make much difference to the overgrown feel. Growing them by ABM means that the vines will not be generated at mapgen time but drop-down when you approach a tree, not good. It's also another ABM load. Decorations need to be done by biome API decoration code for speed.
Too much priority is being put on these nodes because of MC, but i'm not opposed to adding them for manually-placed decoration use.

**Comment by C1ffisme** [comment]
@paramat 
> It's also a little weird adding an animal-construction when we have no mobs, or when we have mobs but they're disabled. When we add mobs we may not want to add spiders, then we'll have webs but no spiders which would be weird.Maybe they were spider webs from long ago, when the Minetest world had some kind of life? I dunno. It adds a bit of depth and backstory to the game, though.

> Maybe they were spider webs from long ago, when the Minetest world had some kind of life? I dunno. It adds a bit of depth and backstory to the game, though.

I'm just saying, plot holes in a voxel game are where the player gets to fill in the gaps with their own made-up lore. And besides that, there is every chance that we would add spiders as much as we wouldn't.

> Too much priority is being put on these nodes because of MC, but i'm not opposed to adding them for manually-placed decoration use. But as a part of default mapgen i'm not keen.

They would have to appear in the mapgen somewhere for people to use them, unless we want to make bizzare crafting recipes.

**Comment by paramat** [comment]
:-1: for both for reasons given.

**Comment by paramat** [comment]
Issue is 1.5 years old, it's clear no MTG dev is interested in coding this, so if soemone wants it they have to code it and open a PR.
I will close this in 1 month, there's no point in having an issue sit around for years being discussed but no-one coding anyhting. We want to avoid the 850-issue fate of MT engine.

Note that although these nodes could be added for decoration i will not add them to mapgen, for reasons given.

Nodes added to mapgen need some sort of cause, the only possible cause of cobwebs is spiders which we do not have. it would be as bad as beehives without bees or bird's nests without birds. New players will expect spiders if they see cobwebs. So cobwebs can be added to mapgen when spider moobs are added and enabled.

**Comment by Fixer-007** [comment]
One way is to find good vines and cobweb mods and just integrate it into MTG.
