### ISSUE TITLE
Is 'game_api.txt' supposed to be using markdown?

### ISSUE THREAD

**Issue by red-001** [minetest/minetest_game#798]
It seems to alternate between using markdown and not. If it's supposed to use it then the formatting should be fixed and the file renamed to `game_api.md`. Renaming the file would mean Github could display it as HTML.

**Comment by rubenwardy** [comment]
Yes, it should be.

It should be the same as [https://github.com/minetest/minetest/blob/master/doc/lua_api.txt](lua_api.txt).
lua_api.txt is in markdown, but hasn't been renamed for some reason. I don't know why. At a guess:

1. To not break links - line numbers change all the time, I don't think this is a big problem.
2. For windows compatibility - this is still a problem with .txt files as they end with \n rather than \r\n, which Windows doesn't like.

**Comment by red-001** [comment]
Windows doesn't like a lot of Unix things and I don't think this is a big deal. Anyone smart enough and with enough knowledge of programming/scripting to make a minetest mod would probably be able to figure out something might be a text file even if it doesn't end in `.txt` after all `.lua` files usually are. I think line endings would be *less* of a problem if this is done as people can always look at it on Github. Stable release could even have the markdown files complied to html.

**Comment by red-001** [comment]
I will make a PR to fix this soon.

**Comment by red-001** [comment]
#799

**Comment by est31** [comment]
@rubenwardy  see the commit msg of https://github.com/minetest/minetest/commit/800d912b6f93b4e9e6efdc89b9e7a720807f2b1a
