### ISSUE TITLE
Hunger

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#853]
There is a PR minetest/minetest#3388 in the engine for adding hunger, but some people think it would fit better in minetest_game, so maybe it is worth opening an issue here too. The benefit of a canonical hunger mechanic (whether in minetest or minetest_game) over a hunger mod would be for food modders of minetest_game and derivatives to feel more compelled to add satiation mechanics to their food, so that hunger mods do not have to add in support for every food mod out there that doesn't care or doesn't want to put a soft dependency on a hunger mod (of which there are at least two).

The gameplay benefits would include providing a greater challenge, which has been discussed before.

**Comment by sofar** [comment]
https://github.com/minetest/minetest_game/pull/855

**Comment by nerzhul** [comment]
@raymoo maybe modders should discuss about a common API together ?

**Comment by sofar** [comment]
I think the biggest hurdle is a lack of persistent per-player metadata storage.

That seems like something that should be fixed in core (e.g. player:get_meta() or similar, and move storage to sqlite instead of unmaintainable text files).

Once there is a generic player metadata storage, it'll be far easier for mods and games to choose mechanics and design API's around these type of data bits.

**Comment by C1ffisme** [comment]
We could add serialized data for players, just like LuaEntities.

**Comment by sofar** [comment]
>We could add serialized data for players, just like LuaEntities

player: get_meta()

Yes, I wrote this somewhere else as well.

**Comment by 0-afflatus** [comment]
Let's lobby for the engine change.
This conversation brings up the issue of how to attach arbitrary attributes to players. That needs a highly generic solution, so it could be used for other mods too.

**Comment by paramat** [comment]
Seems engine work is needed, let's discuss in an engine issue first before discussing how to implement this in MTGame.

**Comment by rubenwardy** [comment]
We now have persistent per-player storage. Hunger is essential to a survival game

**Comment by paramat** [comment]
But should of course be optional. Hopefully by allowing MTG mods to be switched off in mod menu.

**Comment by TekhnaeRaav** [comment]
Wouldn't it be better to have hunger as a check box near the "Enable Damage" and "Creative" check boxes.

**Comment by rubenwardy** [comment]
> Wouldn't it be better to have hunger as a check box near the "Enable Damage" and "Creative" check boxes.

Yes, but it would still be a subgame feature

**Comment by alexdevteam** [comment]
I've always seen discussion about "hunger" in minecraft-related games, however, I haven't seen a "thirst" mechanic yet. Maybe it would support the hunger mechanic, and it would also be a little bit original.

**Comment by C1ffisme** [comment]
@alexdevteam Most of what's required to satisfy thirst is available within a few seconds of gameplay. The easiest way of cleaning water is smelting it, so as long as you can get water somehow, you don't have to worry about thirst.

Meanwhile, food is a bit less frequent. Sure, apples are ridiculously common in the game right now, but in Minecraft, you need to start planting seeds or killing animals quickly before you starve.

**Comment by raymoo** [comment]
>I've always seen discussion about "hunger" in minecraft-related games, however, I haven't seen a "thirst" mechanic yet.

TerraFirmaCraft (a survival-oriented Minecraft total conversion mod) has a thirst mechanic which varies in depletion rate depending on environment and player activity, along with its other health stats. So unfortunately it wouldn't be completely original, but it could make MTG's survival elements stronger than vanilla Minecraft's.

>Most of what's required to satisfy thirst is available within a few seconds of gameplay. The easiest way of cleaning water is smelting it, **so as long as you can get water somehow**, you don't have to worry about thirst.

(Emphasis added by me) Thirst would be a good way to make dry biomes like desert or savannah be harder to survive in.

**Comment by paanrama** [comment]
>Most of what's required to satisfy thirst is available within a few seconds of gameplay.
Some months ago I was playing with thirst and hunger, and I can say that in MTG there is too little water in good places (only river water, snow and ice are edible, as the more abundant water is ocean salty water). To get a good balance of thirst and hunger can be very difficult for the begining of a game because the player can't make something to put the water into so it must stay near a edible water source until he can make a water container.

**Comment by C1ffisme** [comment]
@paanrama Depends on your standards for water. Boiling water will get rid of most of the bacteria.

> Thirst would be a good way to make dry biomes like desert or savannah be harder to survive in.

Even then, once you have a source of water, the gameplay aspect of thirst just becomes more micromanage-y than hunger. (Plus, I've found water nearby deserts and savannahs before. Biomes aren't that big.)

See, at least Minecraft's hunger system has some advantages to it:
- Making food in a furnace can earn you XP points.
- The need to eat food that keeps you full while battling mobs encourages the player to progress to better forms of food.
- Different kinds of food or food items may have additional uses in potions.
- Different kinds of food can be traded in large quantities, encouraging the player to create large farms to make a profit from.

Meanwhile, an MTG Thirst system would have:
- No XP benefits, at least not yet since XP does not exist or have a use in the game.
- No trade benefits, since trade does not yet exist.
- No potions, since potions and potion effects have not yet been implemented.

Granted, progression might be possible if done creatively, ("Cleaner" forms of water could heal more thirst and slow down the pace that the thirst bar decreases at.) but even then, I think the most pressing reason for me is that food is more relatable to the average player living in a first-world country compared to water, which is plentiful to people who live in those countries.

**Comment by Ezhh** [comment]
> ...the gameplay aspect of thirst just becomes more micromanage-y than hunger

This is the exact reason I find hunger annoying after the initial struggle to get enough food. Only with thirst you get to this stage even quicker... so adding it would require very careful consideration. I personally think thirst isn't a good mechanic for MTG.

**Comment by raymoo** [comment]
Food could be made more involved / difficult to obtain, so that more of the player's time is taken up by food acquisition / processing. At the same time, food production mechanics could be given more depth so that it's not some boring chore that you have to do periodically. This is assuming we want a survival-focused game.

**Comment by Ezhh** [comment]
MTG needs to be not only survival (this really being one of the big problems with MTG - it needs to be everything), so any hunger mechanic must be optional. With that said, as long as it's optional, I'm in favour. I would however like to see something better than I have in any hunger-adding mods so far (but I'm also really not sure how best to do it).

**Comment by raymoo** [comment]
I like TFC's food system

**Comment by raymoo** [comment]
About not being just survival, it would be easy to add a configurable multiplier to hunger drain, so you can make it as easy or difficult to maintain satiation as you want.

Also I take back what I said about thirst making it more difficult to survive in dry biomes. Currently in MTG you could just carry around two buckets of water for infinite thirst quenching.

**Comment by Ezhh** [comment]
> ... configurable multiplier to hunger drain ...

This doesn't really do anything to increase difficulty. It just increases how often you need to repeat the same really easy tasks.

**Comment by raymoo** [comment]
@Ezhh I am not saying adding hunger to current MTG will instantly make survival more interesting. It would need to be in addition to new food mechanics that allow increasing food production with some kind of effort other than time investment linearly proportional to food produced. One example is that if there are automation mechanics, then a high hunger rate means you would get a lot of value (free time) from automating food production, or from buying food from somebody who automated it.

As for why you would want mild hunger instead of no hunger, one reason could be to balance food on multiplayer PvP servers (no spam clicking apples in combat). I do sort of think that the current state of hunger mods on most servers has no real meaning as far as survival gameplay goes. My original point (which I forgot to state) is that MTG doesn't have to be "only survival" just because hunger is active. It can still be other things at the same time. My other point for this post is that increased hunger can mean something other than a proportionally increased player time investment. Also I wasn't arguing against being able to turn hunger off.

**Comment by HybridDog** [comment]
To be honest, I almost never use food in minetest. Food items like Apple and Bread are useless from the gameplay perspective. If I have low health and need more I simply kill myself and teleport home after respawning.
Hunger mods are just annoying to me. When I get hungry and gradually lose life, I kill myself to get full hp and hunger bar, so as difference between having hunger and not having it I need to interrupt what I do every few minutes to kill me (or fill the hunger bar in another way). Killing myself is easier than growing and eating food.
Maybe something with long-time effects can be added to food?

**Comment by Fixer-007** [comment]
>To be honest, I almost never use food in minetest. Food items like Apple and Bread are useless from the gameplay perspective. If I have low health and need more I simply kill myself and teleport home after respawning.

To avoid kill trick, I guess you should respawn "weak", with just 2-3 hearts, and then you gradually eat your way up, you can eat N items per day to increase your health back to maximum (very very slowly to avoid cheaters, maybe ingame week). Then you just eat X items per day to maintain your HP or it will go back to "weak" mode.

**Comment by HybridDog** [comment]
I like this idea. 
I think that instead of eating items each day in minetest time for maintaining HP, players should need to eat food every real day (or every 8 real hours), so that they can build and mine for hours (real time) without constantly eating food, while food still contributes to gameplay.
However, I don't know how this works together with very slow hp recovery. Maybe the hp could regenerate within a minute after respawning if the player ate food, but when he/she is hungry, the hp do not regenerate, and eating food still directly contributes to the hp.

**Comment by benrob0329** [comment]
In reality, you can survive 3 weeks (ish) without food, however you will get weaker and more frail the longer you go without food.

**Comment by Extex101** [comment]
Yeah so the lower your hunger, the slower you heal, break and move. But as timegoes on toy slowly lose health maybe with a poison type effect

**Comment by paramat** [comment]
Closed due to #2710
