### ISSUE TITLE
Needed fair mechanic which would let player unstuck

### ISSUE THREAD

**Issue by xeranas** [minetest/minetest_game#857]
Since minetest_game includes many blocks which are unbreakable by bare hands there are situations when player stuck in hole and cannot escape (e.g. no pickaxe in inventory).

It would be good to have build-in solution rather than depend from mods who gives whole pack of "cheats" commands.

My suggestions:
1. If you pushing long enought "unbreakable by bare hands" block you start losing health. Probably would require loot of work to intruduce it, but it would add some spice to game.
2. Include into minetest_game "seppuku / killme" (or whaever name) command which would let kill himself. Better not instantly let say after 15-30 seconds (or configurable in case of pvp servers).
3. ??? 

There are teleport and sethome/home but these commands feels like cheats (and does not fit into minetest proposed logic. You can't break stone by bare hands but you can perform teleportations like pro?).

**Comment by C1ffisme** [comment]
I understand you. And yes, this is a problem in some cases.

I think option 2 is good, or if we add stamina, we can just AFK until we are killed by starvation. Which works unless you are stuck at spawn, right between some cliffs. In which case you will probably have some extra dirt to get out.

Home and Sethome are slightly cheaty, but they are useful on servers that are more for building than surviving.

**Comment by 0-afflatus** [comment]
I don't see the difference between teleporting out (/home or /spawn) and /killme. Yes it's cheat-like, but IMO better for the game. It depends how hard you want survival to be.

**Comment by RHRhino** [comment]
Minecraft allows to destroy nearly all blocks very very slowly with your bare hands, which is important if you fall into a pit or ravine without tools very early in the game. It allows you to dig out of it, but the blocks disappear instead of getting collected into your inventory. The advantage of this is that you can escape such "stuck situations", but the disadvantage is that new players might be confused why blocks disappear, when they try to dig stuff with their bare hands instead of the right tool. I think we should consider to add this behaviour, if nobody has a better idea, but I'm definitely against adding /killme or similar chat commands.

**Comment by tenplus1** [comment]
Typing /spawn would be the easier option incase you get stuck, and knowing that you'd have to go back to the beginning would make you better prepared the next time around :)

**Comment by rugk** [comment]
I also [proposed](https://forum.minetest.net/viewtopic.php?f=3&t=14059&p=207768) a `/killme` command.

**Comment by paramat** [comment]
I prefer a death command.

**Comment by tobyplowy** [comment]
@RHRhino +1 I agree!

**Comment by paramat** [comment]
See #1483

**Comment by paramat** [comment]
#1483 merged.
