### ISSUE TITLE
Suggestion: Tweak straw

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#884]
* Add crafting recipe: 9 dry grass → 1 straw (this would make dry grass a bit more useful other than using it as a low-grade fuel source. Only 1 straw instead of 3 like for wheat because there is a lot of dry grass in savannas)
* Remove the “reverse” crafting recipe to turn straw into wheat (otherwise players could easily turn dry grass into wheat)
* Make straw furnace fuel (burntime: 4. Intentionally low because straw burns very quickly)

**Comment by PilzAdam** [comment]
These suggestions sound good.

**Comment by C1ffisme** [comment]
9 Grass -> 1 Straw isn't a very good balance, as it could take whole hours just to find enough dry grass to make a thatch roof.

(P.S. Yes, I see that we are keeping the wheat recipe, but wheat is pretty expensive by itself, since it takes so long to grow.)

**Comment by MT-Modder** [comment]
:+1: More uses! I didn't even know dry grass was fuel.

I think burntime should be adjusted otherwise it's just a waste as a fuel:

1 dry grass = 2 sec
9 dry grass = 18 sec
1 straw = 4 sec ???

IMO we should look at coal block burntime relative to coal lump burntime and apply the same here:

1 coal lump = 40 sec
1 coal block = 370 sec

That's a 1.11... increase per lump

So straw would be about 28 sec

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Time to apply this now that straw reduces fall damage.

**Comment by paramat** [comment]
There are problems with the first 2 suggestions, see discussion in #1143

**Comment by paramat** [comment]
So closing.
